import os
from src.utils import write_response

import requests

headers = {
    "Host": "b.i.instagram.com",
    "Accept-Language": "en-US",
    # 'Content-Length': '31910',
    "Content-Type": "application/x-www-form-urlencoded",
    "Priority": "u=3, i",
    "User-Agent": "Instagram 410.1.0.63.71 Android (31/12; 420dpi; 1080x2274; Google/google; sdk_gphone64_arm64; emulator64_arm64; ranchu; en_US; 846519343)",
    "X-Bloks-Version-Id": "b7737193b91c3a2f4050bdfc9d9ae0f578a93b4181fd43efe549daacba5c7db9",
    "X-Client-Doc-Id": "356548512614739681018024088968",
    "X-Fb-Client-Ip": "True",
    "X-Fb-Friendly-Name": "IGBloksAppRootQuery-com.bloks.www.bloks.caa.reg.create.account.async",
    "X-Fb-Request-Analytics-Tags": '{"network_tags":{"product":"567067343352427","request_category":"graphql","purpose":"fetch","retry_attempt":"0"}}',
    "X-Fb-Server-Cluster": "True",
    "X-Ig-Android-Id": "android-f35f126bc4795e76",
    "X-Ig-App-Id": "567067343352427",
    "X-Ig-Attest-Params": '{"attestation":[{"version":2,"type":"keystore","errors":[-1013],"challenge_nonce":"LUV3jahbCM8BkTPN94eymHtYEFfg5wzq","signed_nonce":"","key_hash":""},{"version":3,"type":"play_integrity","errors":[-9],"challenge_nonce":"BJenaqsyuNRb_A0gZDUct8iLlM1ow9Yd","integrity_token":""}]}',
    "X-Ig-Capabilities": "3brTv10=",
    "X-Ig-Device-Id": "c734a1c7-d663-4fad-af07-817b064e424b",
    "X-Ig-Is-Foldable": "true",
    "X-Ig-Timezone-Offset": "7200",
    "X-Ig-Validate-Null-In-Legacy-Dict": "true",
    "X-Root-Field-Name": "bloks_action",
    "X-Tigon-Is-Retry": "False",
    "X-Zero-Eh": "IG0e09d776530888418ab70f3822fbb4e1",
    # 'Accept-Encoding': 'gzip, deflate, br',
    "X-Fb-Conn-Uuid-Client": "95b2bb513e6c590b7147b9e4bcf849d8",
    "X-Fb-Http-Engine": "Tigon/MNS/TCP",
    "X-Graphql-Client-Library": "pando",
    "X-Graphql-Request-Purpose": "fetch",
}

data = {
    "method": "post",
    "pretty": "false",
    "format": "json",
    "server_timestamps": "true",
    "locale": "user",
    "purpose": "fetch",
    "fb_api_req_friendly_name": "IGBloksAppRootQuery-com.bloks.www.bloks.caa.reg.create.account.async",
    "client_doc_id": "356548512614739681018024088968",
    "enable_canonical_naming": "true",
    "enable_canonical_variable_overrides": "true",
    "enable_canonical_naming_ambiguous_type_prefixing": "true",
    "variables": '{"params":{"params":"{\\"params\\":\\"{\\\\\\"client_input_params\\\\\\":{\\\\\\"ck_error\\\\\\":\\\\\\"\\\\\\",\\\\\\"aac\\\\\\":\\\\\\"{\\\\\\\\\\\\\\"aac_init_timestamp\\\\\\\\\\\\\\":1769034606,\\\\\\\\\\\\\\"aacjid\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"d2c8ed10-f952-4a12-aa09-e83671b1bf71\\\\\\\\\\\\\\"}\\\\\\",\\\\\\"device_id\\\\\\":\\\\\\"android-f35f126bc4795e76\\\\\\",\\\\\\"waterfall_id\\\\\\":\\\\\\"d6031628-57e9-4414-93ad-9911cf738e0b\\\\\\",\\\\\\"zero_balance_state\\\\\\":\\\\\\"\\\\\\",\\\\\\"network_bssid\\\\\\":null,\\\\\\"failed_birthday_year_count\\\\\\":\\\\\\"\\\\\\",\\\\\\"headers_last_infra_flow_id\\\\\\":\\\\\\"\\\\\\",\\\\\\"ig_partially_created_account_nonce_expiry\\\\\\":0,\\\\\\"machine_id\\\\\\":\\\\\\"aXFTbgABAAHw1cpzzsgkxOLUNm6H\\\\\\",\\\\\\"should_ignore_existing_login\\\\\\":0,\\\\\\"reached_from_tos_screen\\\\\\":1,\\\\\\"ig_partially_created_account_nonce\\\\\\":\\\\\\"\\\\\\",\\\\\\"ck_nonce\\\\\\":\\\\\\"\\\\\\",\\\\\\"force_sessionless_nux_experience\\\\\\":0,\\\\\\"lois_settings\\\\\\":{\\\\\\"lois_token\\\\\\":\\\\\\"\\\\\\"},\\\\\\"ig_partially_created_account_user_id\\\\\\":0,\\\\\\"ck_id\\\\\\":\\\\\\"\\\\\\",\\\\\\"no_contact_perm_email_oauth_token\\\\\\":\\\\\\"\\\\\\",\\\\\\"encrypted_msisdn\\\\\\":\\\\\\"\\\\\\"},\\\\\\"server_params\\\\\\":{\\\\\\"event_request_id\\\\\\":\\\\\\"9765106e-c2a5-481c-9861-156f6eea4a7f\\\\\\",\\\\\\"is_from_logged_out\\\\\\":0,\\\\\\"layered_homepage_experiment_group\\\\\\":\\\\\\"ld_no_language_selector\\\\\\",\\\\\\"device_id\\\\\\":\\\\\\"android-f35f126bc4795e76\\\\\\",\\\\\\"reg_context\\\\\\":\\\\\\"AVjfEWediHFklSccnYXQ9vdz1gIaKnmhyuOcHjUWIJH6159OfOzROjN6R_jS4K0dftoH-tWHbJtjxhhBAFHiRvvJ_fE8FZWAd3KHufEeHD_W9qoHUk8fY36Jyz9729FNho__StB4YYbCq6R4vVqMqDsZhoeVboul87Q1szae2xwPF18lHj_cM3Gvze5LxU62Q-j05QEjQm7dccGUoZtSxHEqcjXmZUpDhPW7rZc81Yn-1UfWksNTaUJJyLcPsdYrB66x8deTe-ata7_NbWG3M3TI9peVHaiAM7ffZIxvQitijgVdKZKigqhKvIuQbG4NoIu5LvSRs9e1FuYJRRSq5Bs2kxArh6UKS_4t6fc73YRiJFA_XFoLhJAghEAyqgAdxk90DR59tDzRcwq4L94_iMORqF-AC81j-QLtEVuAHJ8qe2W9QOYfspeVB1iEI1eAwYrpDT1ICu1SO9mjhvA7JoGCbW45mYpWD7aMzOgHkr6qCt1WrMOChUucmzb96m5oP7n_oUGrzvVsIwH6MIr4lsuw9gYUguMHqbMQaTEBx2olJfoO5ah5cNvN5pmvENyRjQDYR4DYERm4lR7p3HdNLORanoLTztqGZu8jdMlqPBfP7jdcWjjmwEpfo5-OcaIc_BmmUw2QafSFxDSzWgKuj4lp22CZpTJGpfA7ZjfYSrsjfZFDNMIP_U0QtL0LMX_WUlVno7mCJkrNLxsUWFX9ZXuUgD2Fho5u5lHBYXlqgQCG8pSpXeqiZSbMWN0U47chDcqq1xbu-J52gmqrECmaNwVfLiFIOCoK_ihRct4-zwCdq0IQD8J7g6JUGOlbo5AQ0TLzRMEyQ4xUkPI7OKOYzqWBnsz8iCd3eOB2ZPtzqVHST2LFIY-CWUnA0mk-ou69pVC0Yu7EDrPttg4WBrLsSY_VNoaWNJZIw-TIavYfCRHldI_bjivMU0pp4Pf2odaoonAQgIesnES6zPXJY5XFNtxBkErnb9bwUj_giEAPH7RoqHxRQSKmudTU67y_BZVdFkA6LZAnGPiEsIBoqfkAr22AmRZdYMNdXTRQEa523cSWJBXpttsK_nFxfkqDO5BA2BkI4Ia64P4A8qcGAtuJ1bk-1KZFrvGV4VDzcWmaK0vU7K764BRk6SKzMvCv0qZrqyI89AqAdXjwPiiL49Zt65c2vgLxGSUq9D4JlCYDyBo0PN3O0G_ft6Olj0JB1jd8g8nEqSCW9C9UVJ4eIqvTX1NJ7uacoCEJLdKr1tPNmEgGGr8HEATxbRuEQbPJbONAMAn9FwHEGamuohlk48y82UyETJS36-rVeLcamTYSb8wvgH2LCvETEngBmafyx-f2EOquubIGBkEZyiIXceNAP2PjLW5AYaBNgApxA2cgFI7kpVk5MvEFnErz8arbhZ379di3vlZ_z-1EdvmQxFf-do4H1hmy72gWEyvHCe71ZgrWkV-Nomzqms2Rr8Z--65AeSg22FTE3jd7MKSYlZmZoOC7IFiXfMkToAiIfGbhjfMoaq-0oNWZOApf3320GRdt0jAn4HZI6rBnM2Zyuddvrk_ikVMBmNZkc4SZzUhpHrUu07ND1egc27MsJYD_ebXQcCWYDWY87DQG53uZZOQsL7qTz_-HjV_VtxiLh5Jwj2VEWzT7qwwqBP-A0J3y41LLljZlR0ZZenE3C5csRuSwmRVekVskHVQGCUGw5edAZqrFzBs9Eopv-Ai5ri6SDLKsSA0B954Rj_WjDI7lJqXAuNw8wmKEBw0yXIbRCmBVqaCfGkbogplGw1kuk25VBCgCMF9ONJ15Mnks9gceTkzVKGbTF0_ELxbOxdns_FeObyJvV8IxduAAKNBGCeVn9GhnXcco_T2y2j0V6Uxt7t8snvlzcR97soT3_aJ6Gv_Om0F5HQMiHtOdORpLttPFni8fkaRLOpNh-KEXbDFwB0RUoJCTKy4kPlWblSAwqUMV0hdR7BNKFFixLxFHagNTHT4G05rzLnrk4acT6UxOXJmtG025CYhxvCIpZgcMuhHgMpQFMcTe9moXk2QtV-kJj1U-KQF2tLqsn8wMmEA7DIAKRyyemZIz9ehwBLU7bLuGhTZhsHeAT4teokHeFkZ2jO4rhupX4zA2QM1er1udZ5GEzdcVBm6O99xwbLo7emuxirSHBCbvqaNAr1BkbmgfDRJ6z8cE8fqT9Tg7Dz2YetKI-VnUBwIuA80G0bmxyfiMx-f_KHWKepvzq6bJHINVkIXZNJcVP7MKqua9u9xoIdDrKPszavRPz2QZdGAnk9w9ruUBLSpW7zsHh6c_MsHqp-UklX6Ew4ViXB1faSSJ5cs_g8PSd8gz4zNyQDvG1PHCbqBuilqmib-I3RD6esufdJWsjXZHD0VVY_XKxH23yu3iSDPHHwwmR2fC2Uzg3B9VcPmGDR0fh_JYNJ24_o1kk76-_wFfA_8y1qm6IcRpq-Uf8DsUp1oIdP_lu1nvcYWNUSq1x9BUIvBBh6pxlbt42E235SN9lXr1F0Z7YQR5nHRdERdf9WmYAx40SLl6rAufvW_ibqN88EfuhUjRVxrCQteyKSvNJ1ib7QiAvExit5MppEBVxovwQ8Rdufs-USLAGEsiejfZFmrdM_co4eRkxjqogwtsmE8nh4AqfDGrEWtenvnTatWB4VC_rf7EWSv7KBhFV_bCZjlTb2rM2tI3rRsnnQZiVR4tHX8aPyhT14w83cdL2LwZsLROY_D9eBLPNYKg9rZMJnYvNWlUw4RfjcUOoLrv9Z0XL9Gi4GNvanosBTI1OwhlaA9oZIEj-_g0EUiJXS3bXlIzOJ2rvCLknidxi7SAFf1MbZgHqHP9NS8m0P5au0uldlsg2bLPRMTGapy5E_c6PkLD2BT4SubXgxoZXcu15Kng3hQgsAa6aEpsWDIBfbktrpDUTxEaZqGsft-6EiuWHzvfwMv064YUsyafPxla3RbX8JUzuH6PB5ZsOxIh4B1tUrOInxAgAxIzJGxk0P8u5oo0j3Wy9xpfoEY5ciIzB4rtEnGUDMF2vYgjJ70J1MRxSXaFshS4svfBJ0kprKrV4Dp28bVWJkRMIqgWVCDqtKRCI3S5ESWvsGdReYUV2LDLe7TrF-otlMWBZHF4V0NkNEvu0ANlg1Kw431arYFqIvceUQwgC7pTAObN7YMDzEI8IFerQSduhviSdICg2UNeb0wSm870x9wHU55XGIAR8wheccHXmjw-hJ7dTtTUefHJYZC09HwPDBOJ84fxWOZvTu4bZBYOdVR9M3onawZaO915zj20SZNWuH-pi3Q_QiFZhHSJPOem94sXz8ZzI4dkDt2Su8BejHMm-i-L21tidlACPjCEvEMoDI5_zGsqbVU9inqXvqvQABbB6lbT_abR9jV3gj1dso8dp0XP9JPe07XAWLeNwd1irzq-KvUAaNcjkPWhDcMfY4wYCnQ40PYQZPZg-QtpufDc7E6P6EjqaBiZ7msZtqDyBTry9pVKpUUSaoxvUvJIUtWT9TFxibJ1bxy44LATz-zqGaTvMWzryhBBiidK8w281Ioi7Vew1VykcSHDe0Y3TpLzzzZboTOjOieSxqCwVuTFuA0_ijgeq71_35hERpcbCwkFWC-bTbrHuNuiCXIARuaQyxhz2pHvpjNiKF-z_aAoUX6JzNvU8F4jjxi_AQ7jiRDnSf6IIqknyFYa0A1JiC5lPW668XBZPAK_ExJYAbHjaP6qv-OvDwgZq3IZJRj4ytevY95ARObcDFa4uIpISfxfyfbRpkjURuuBjh0tlGrGWkso9wT27NWBPJuzvARL4inH5JinhJJZNbkCpnIGjdzFG7Si02iLsPtLTOdJz_JKcjb-UA37m6WianVxxtRbsKB9abVUAJJi-vVHIl1pGRYditqRXPEboF_NrWnaQpX_MrLfHvp-zCk5y0gcitufDPbFVrdL70ZfC90ChV6WE8uC8VqBqr0aJ1B5XtDVYR_I2ywtC7K0MVKxSu9P2qmQVQpD-XAntZn8N4LPs9yVBwVEovnVPHgfXglexVWXI3H-PNiUTiKU4frbQnLwkSiJJy9067DEYAvhMvXJoGCC2_f0DVjo22W1cvDesw39y5o7sGqV_EOmypY1gS9ychirquFscrdGbkkhk670Ujm-VRe9L9DTiaAhfet7J41cINtFNXwt17FA06PGv6mlykZkK1RpGdKJSpi2q03XkXt8VAUT4V50QbQDlHBrvU6Zrrym2exRet63MSNjP6gKwqj0fV3J3XudONcoPnsH5YtiyLFNL054gBU_ITDby9erWlVMdk8K8tjrHI9qpwNUFwS3MjOIAZNNRJuS828icA9Zlc3OdoI245A7mYIDzwbK9EsQKuxmbmiQmOPralsB1BQjE7KLzHDj-WvUZBA8fnnzZlBldwUa6tL_tx0BgCYJigKmzBtjun_IkGgl0sV692SkGZRRpzU5UfBC3Zb_8NIRgrzIPHdZaVLzL4v51j53bN571sXJnyzB_LyAvBteYb-a1MKF9YCZX-Txao_XpdGWqf_XNx2nZWtZMkHyscGSjveITB7XDl3Nu4tNiADuNxT458INm1zorkXl0vkvzWMc72X1Z0IHqTs_GBB917MaP0zDqS2ThHpc9JXAN4Th1Mc4UFQKm13qYO8ClsTqoeUb6_5vr_rgCTnUoc4C7CzDMCnjLOuQjV8GURVe2H-7c_upv8gpfwDd5fNVEvbZYudCFW9vvbxQQl5FmQfElmMGtpXTA7kUJyQbIMeL5YVy5C07dhuYe2oQyXLdPT86HxplRVA8tZ9g95MPd9cyq_h00vYKC6aiNyRxwQ7eeMJkY2zzPcwVwgKZFIB3hGb3KPFkqLBsv_N4jd9-vToIPEu66NwaXZnKgRu_pRcWTyqVgFuam_HhwEGZFzZ6SnunUmPKYOtZqgspMSiis5Q9pFVvr1Tw9jMxNp8nWMiwwaIYO3CMa9JXMIEDbm5EOKRPW1JU8FZEBGG4-ZfFFiZfAGqYeUhyU5lOs2bSuQHt_PG66JwQyXs9ddFCAnbdS9xi4BMqbaQpvuFXhrlJPap4p_3tDgAdFSoR7RqFESiayApCcK4YChl5PnSvEU_2jRvU5ROFgH-UXffDBWVhpr-hLaEMVi_lBD7-t0Ko1kMg587bzG1yhvA4tTrw2pK4R_UUZbKubc0PyxJtW-zsb26ac0K3pI-K54mmSPKppnPdVQcNFWUXjD_6aKp5KNWfsZvmsPMo9zWTWH_b-Nz6zgxkI_Zz_1zB4RXkarhvAr01abPrLmYvyE7k55rlc5pXa6f3jb91m4o5QMcwnQPzZIyx8fRHOfY41bpPH_v5JWBxx9bS5lN6wqLHsYXqsWxDcOXG62i7dlDrRxA681kdpK3ctafzztMzq4johYQtR1RIMgrn56XLe-flSnFWiF6IjZ9TXkHV0ZJbcES8zc_Cp_XjMRAxf8QwtFPpD4CNfKM-J164dsDHtuTbPowyQmOzRO7CLDsvYQusHiwiAChHFFNlR-Sj8pvfBGE0eo7XLlD3_zV6IJ2crg6oFWE0rzHdEqF-89GQf7E7JvC1XkmYscr56qWSOXVtPP4TNeQdxIZwgYgkRDonewV4hX18eqWTx7l-OZSwAzWMNjiyHWf96AhONufK-5F-qcKjCAR2EiLIJ31XrTYSKlrxpMtXhdCC3p_tZ2ZTQU3lA52EDQQ_bii3QoazGq5zbED3CLTNyQLqDzKneQovBr17yDHhPMyQyaGS_sfNQYmmkP_Dxf4gyTn-NHRXRJ6-luLB-scrMRjCoIztx0ZWKUei0aFfEiG-qBeBJST4mzJ3PmJn7scnsHueDMrT9c8uLO6_9QpAPZOjGf3sxV5pt3NsnHPjbM6rtPpS-0PkWVryGrjbBp48H0bEazwm1N8cMfFqw5j6RHLwvJwf4wyITuhhl5GxM_jzgkPy0BPsVGsv5BlDpyp-oqNAxmaos9v3L54eg8pvEPrgf_u4_a71iKwspFxOkrOfMIUUkX-t7OTpE-rP6UQmipk8HYHEXAdC5tR3mY43qF1iq_UO4qzNYu3o3WIw-0TZvt1645Pl0oV-iIHUtF6lChRF8LrdkKYB2xYmdB0zUHkufQZSllGV-7VTDW_SIp9fhPikeokULTYHOjJOQXVnc0W08EhBIQWbab4e0OAOaBLAAO4yzIKSLAse8kqPuLSQwNMvTnJzzz71tJVZDrRBAzemLXo9BYRI2APiKDyhXGEC9CHaygiWK2W3Y9KK1lwrg78AD9dJrCMHcbr34o_aeRs_OsutnIIJfxvCBKVO40kHTc6soErAa4HCGNd2RdRAbouscnZiHMM3cGAoMXW4PPwRX_SOO746WbqYl9yQbG6lv7gelSOOZ-mmEqUA_IojTebe5h6Y0o0vivgACpjN0fLL4zUZqodx-Ke69AaHllYen4hTFrId-p3p8vwZ9wjWyzu13G89VnhtY6eh3kN94Bk3gerwcJ4MSoFEFkBQuYPqNd9UPN7TupllKB6z7x5-qbyqDsNSKSCZJf2yw5X7A71NRqOXJVZKL0TM1XY9kS99X2YzyzoTTrht4tydd4oSXU67-P_T-KYK2C8e-TrNG10Lc90Sln7_uyXaIqGPq_89jlGqDW0ADfgiJ4hZbCj9A4xOK9ROQWIN5HGP-CmzVlA5goTFzB0S_3OXskjU5As4EUms8sjby76dfhECIwhov4x_Ks338Mdkt9PnGnq9z1FauL432SuPG5kmo8888tnWSAkSaVL8a_wbmejGnOyLxu8M2TsMlk6Y3LHD9lfCQNdEpw8XW-f2bSoteoPnPdB74MsNf-Lo3ItlGlivET03T9DVQ5Yx53EGg3ewfAUYegd13DUkTrdMk0Kg5IozCgYVs-3IAbB1Kx03vDgntIIjE2J_Hs7oKt8Qqff--nTmvULOep8LAWFkrshGCbcitxe2Tdsy1G8Jtp7qsk6Ovc7T4sm9BT1Ono8Tp5dOaYexFtBXAs2fQ3Yfnx9OqXsbDfc2qXs4Gql9iXGoFMsYK2hZFuMTINdaGKIaE8fWedBFPbc9SmOfrSPSN1ZLiNFK4kVLNQMZ0VE01O-vkBQn5CteLALTPDWhZf_K2fHIwXMsMTS8fhRrg7moU1y5Rrfv4WRe8rcfyyLXSBmiOFzPXAVcMhrhJo0znBrYxznzL5PpByHin9QsxRrYL6xZjYe3kbiTeimTW3ynbrjtbyfcGqQZ4VP0oDT8MLXlyDhPVdEvYEiDRhPGccHcAxJWh_LstfduSqdxBgPx7gFHg-1lKYXexK2FXWc_ZR0KTlVuh4lRzkTNFkhwkZ13cpVuNEWYUZENCnPmxenYd5wYejGp4EBN9FG8UeNP8qqzydnYFLnygbs5ttjIrGc40NwxzGiJf2GfGCnODw6Yoo2LlzImc_HmgXBZGPwiVsGa5v-SLW4YITUN7KYqDRqPz1ktYfYJP9KV4u4IC5h3MhzIKhev3blEA5MQafJKXyohf_4BjiBmKFDCaH_IL3NXaeBNxvCkYNL9tZutq93fkX-8fvJFta8bTc4mq9lGU08fWh_NCbcXR_byFFYA8WrF1Nz0DtnM5a78GUpPZN-ZLQ-zE01YsCwADlyuZhP1qLg4ZDNgB8mfDW2-HIDHVvW7M852pcyA8ucrXWkhCcwfCtrlVZrVdIFkPlpwKVthhqbghMouLhzevSRGGWmupjC2kz0d7aawYvfRK35dB2Z6kvJWKukVQ3Uz2ROTCKctdUflezhqYVSy3cWY2RlbpXmoq3YBDA7Jyg9ZTJpCVaLx7Q9GGqOzVyKj2jygVYRk3YBhLpFqhtLA_z8vQMJNU0zNPTLm_0iF0W9YVdKOkXdlosLeqviGUJ2zMTjp2HR547U36bHsedXyqlsLmPJ2a-iBQCbyEq4e59Vgte9o25kqIdVsJ0BXwvwqsECKMwZOTHGmdLtzcH_TdO2Tj9LonO3h5did2hNOS6U5YQQXLwUgtdeoPVd9BYXi7FWmDhFgBmev_w8kaKgEyLkeVNarxscO2J_3GnFL8VGPu8mpCNKuq6WUExfOdJBhpiGJFi7P46dXA8eA70Ln51Xro7SuV3Ro3ZeFj13Xjq2C21z4PKozIQKPHfLYR73hnDomfk67sFHKeD0ZHnCuLzm_dRy0Ea_JvlHWqOT6wdy44AX0jopz8zjFBha9vNiOGC3A2zbIvePtGFWPUzCcBlB6OeWYimd_bOr8X9HkpozftCPrFUTZ_jiY04OEmDqLmwOXE9FgxZWJm0XZHU2CmrJEXQXdjS8I8XEYe2H16po2QjMpPGDdUEaPDM9te-x-2cAM6Mt0-s04VzxQgrp_vtdnxZ19wwzkDq-HL8idO-8W-8n3wzdn-JRrRH6w-gKsIEHfTdfUGd4zhW6TB74ARGABBRZP0ZHEwZdZRlymKhu4vN-HESyuST6BK6yt-gYvu0fa2cTx6Y4HlxdxBJaq3Q6YtLwAIUFWANASwOUXGQvmHxJDOTY2OIz0KX_xzCFR7nNVswRgo8aXSPegyJWuzJEhZ3boJmY7O8PtjEb_u8-r1Br0Q7p6oKibm0zraRiTe-1H9oJDtyp-IEQ0ELGASWFDSOP3RrmNXmNcGXcKju370ozoszhvCK66QMfdIcqqfQ_raQaoKofhkeivqi-FIauP_PcAmr6JmgYV8QV_K_EYiUn0DAvkICJJ0UnMNOpXauz_B9aIKj_8fxoaWPId4koG4g3rA3lO1mkJdhyLVPxeAWtDEnSJhCHGyHqCps8evXGRy6VYgCbE-ZSAHuX_jf6yDa0xuDt55JRBUFCd0cFbCgjszRamm71rpBsDHuz8Oh5-cUuMO7RRa3vvhcAaHLmPDNr9Ba4BS3hh4D06Yp6EBApwI8xBh2SGlTXg6YGd1fEQCj9yaPYJto2IpUJdTQECtnGSlL2R_6Rcx3zZLLPDPuda6XdZxK-mbtZtcK0TdDsI-5iu6YzkU1IAz3AlW9LvTbd1hCvtm4DnCElvG2BFqkUYyrlH4dxrmhSTYHsNhNSNvStAD5Qo5MPJbPRFH-56RytsuPbl4b5HSObrjma0gtd3wDxiXaY68PvEpUvnOLa9Vkxfj8OBbN_rkKo7jhXF7K7Gr8CHuiVIjTQpZZ9CL8TQCROn9Fq40R1L43HmIbLKVALH9b0OlhSUtSQJSq0WofbnhHnRQ0yVXKRCs7Iao9uoF3UTwzMoGZjSq9Zf4SgZe4YxCT-4Iua9A5fpefgzKebrR-AxW4DFMXABGx6VbZgNO-rzm_yT2XwP1iocqBwcfWcde8Tiv2B4xJjWckcP0eKZq8UKgjHzGB5WLlAybWOQgyE6JbKuxbNSttBACV_XWUX53P5ef7uZ-QwN8AKdBH3G--uBZrcxjolVmvCUWw9Qk059K3fcHdunBUsvFijq1P3yKknW5CrKnp_YPz76VEqvfCDYY9T12O7MNGiVmIHlZvX9O88w-vtrKLIGXexoUYMreQ38BX3q_pWhApvf3or9G91azZcCeaWAhsIyN6MXBv38BVENt0YEearesqlSyGY49sonE7Y-Dm5gXh-0GkuS02l29DVdIPYcF2xlUDR06pzffLwH9QVy2-p6CaVFbDAfHv-cNyAZTcSdGUhkqulxPAoXQvx6tHutgec2zAXs8NvCiG3o775xYhuq_iTZ2ioes7GeMnAUW7P9a2wIOz4iBenLHjYu-uqTvXuS6FjomL8JP1JRsiAXV-UFmxs9c2pX40PBIxTJgbCdsz7BCnAEo4t7jBBGCLr4BcxSuFUFe6_3n86rvgQYXUJ_6AA1lsbd3fr33EVQcvcP-T5ONvzPkkbWxnXwmpMaudr8Ga5NnuFDD7UmXi01I4IoV5r5DXV8et5VOB4fDJiitVJ5fB7Mwl0mmA|regm\\\\\\",\\\\\\"waterfall_id\\\\\\":\\\\\\"d6031628-57e9-4414-93ad-9911cf738e0b\\\\\\",\\\\\\"INTERNAL__latency_qpl_instance_id\\\\\\":1.32085942500023E14,\\\\\\"flow_info\\\\\\":\\\\\\"{\\\\\\\\\\\\\\"flow_name\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"new_to_family_ig_default\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"flow_type\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"ntf\\\\\\\\\\\\\\"}\\\\\\",\\\\\\"is_platform_login\\\\\\":0,\\\\\\"should_ignore_suma_check\\\\\\":0,\\\\\\"INTERNAL__latency_qpl_marker_id\\\\\\":36707139,\\\\\\"bloks_controller_source\\\\\\":\\\\\\"bk_caa_reg_tos_screen\\\\\\",\\\\\\"reg_info\\\\\\":\\\\\\"{\\\\\\\\\\\\\\"first_name\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"last_name\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"full_name\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"Eugene\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"contactpoint\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"e70375344\\\\\\\\\\\\\\\\u0040gmail.com\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"ar_contactpoint\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"contactpoint_type\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"email\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"is_using_unified_cp\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"unified_cp_screen_variant\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"control\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"is_cp_auto_confirmed\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"is_cp_auto_confirmable\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"is_cp_claimed\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"confirmation_code\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"HLhN6nli\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"birthday\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"22-01-1993\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"birthday_derived_from_age\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"age_range\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"o18\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"did_use_age\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"os_shared_age_range\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"gender\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"use_custom_gender\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"custom_gender\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"encrypted_password\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"#PWD_INSTAGRAM:4:1769035008:AZ5ExDXjM1ZLdM2rMGUAAVPBP\\\\\\\\\\\\\\\\/IsjHJHTphEA\\\\\\\\\\\\\\\\/Iam7dV4U+CpYwbFzkSnyJ5xrOgk0pnBnN5Qd8FN2qviVQTSHUAIkcg2J2Zc0xFq7\\\\\\\\\\\\\\\\/lE+e4pDSze1c9WOk8rW2YpfIskC7yxjUw3dEYE2BGqJeNLzNYNs435LEIE4ar8t7iTwTS2oWb2UkZ\\\\\\\\\\\\\\\\/nWma7wCS0GwR+\\\\\\\\\\\\\\\\/S5HZtpcSvM6ZUxBKwu75OmUM\\\\\\\\\\\\\\\\/3wrCnWSQ0ZcJpbdTmbvE+sE+Yh+\\\\\\\\\\\\\\\\/ROr\\\\\\\\\\\\\\\\/Unte8z5rn9nGKU5Jx8pi6I7wpH0YlZJPAIVi7qqk\\\\\\\\\\\\\\\\/N18aLUGIwYCY8xTO49ogv+nRCoOSIu72A\\\\\\\\\\\\\\\\/IXdAc+A\\\\\\\\\\\\\\\\/druvNvDluMsgyLJAyyeo4L+QW\\\\\\\\\\\\\\\\/OrY5HOVRkeflqunwyNZMkPTfDOWgGtgA0LCvnFrEso=\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"username\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"just.traces\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"username_prefill\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"e70375344\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"fb_conf_source\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"device_id\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"android-f35f126bc4795e76\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"ig4a_qe_device_id\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"c734a1c7-d663-4fad-af07-817b064e424b\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"family_device_id\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"dd5b9513-0be3-4263-9106-459e51268b46\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"user_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"safetynet_token\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"ZTcwMzc1MzQ0QGdtYWlsLmNvbXwxNzY5MDM0OTM5fBWut2xb6bRZ8ZphWFhqT9knoNB2hgkyHg==\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"skip_slow_rel_check\\\\\\\\\\\\\\":true,\\\\\\\\\\\\\\"safetynet_response\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"API_ERROR: class com.google.android.gms.common.api.ApiException:7: \\\\\\\\\\\\\\",\\\\\\\\\\\\\\"machine_id\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"h1NxaVnaYULGGzgpCn_hPfVP\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"profile_photo\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"profile_photo_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"profile_photo_upload_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"avatar\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"email_oauth_token_no_contact_perm\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"email_oauth_token\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"email_oauth_tokens\\\\\\\\\\\\\\":[],\\\\\\\\\\\\\\"sign_in_with_google_email\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"should_skip_two_step_conf\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"openid_tokens_for_testing\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"encrypted_msisdn\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"encrypted_msisdn_for_safetynet\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"cached_headers_safetynet_info\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"should_skip_headers_safetynet\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"headers_last_infra_flow_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"headers_last_infra_flow_id_safetynet\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"headers_flow_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"was_headers_prefill_available\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"sso_enabled\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"existing_accounts\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"used_ig_birthday\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"create_new_to_app_account\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"skip_session_info\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"ck_error\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"ck_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"ck_nonce\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"should_save_password\\\\\\\\\\\\\\":true,\\\\\\\\\\\\\\"fb_access_token\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"is_msplit_reg\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"is_spectra_reg\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"dema_account_consent_given\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"spectra_reg_token\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"spectra_reg_guardian_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"spectra_reg_guardian_logged_in_context\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"user_id_of_msplit_creator\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"msplit_creator_nonce\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"dma_data_combination_consent_given\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"xapp_accounts\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"fb_device_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"fb_machine_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"ig_device_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"ig_machine_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"should_skip_nta_upsell\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"big_blue_token\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"caa_reg_flow_source\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"login_home_native_integration_point\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"ig_authorization_token\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"full_sheet_flow\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"crypted_user_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"is_caa_perf_enabled\\\\\\\\\\\\\\":true,\\\\\\\\\\\\\\"is_preform\\\\\\\\\\\\\\":true,\\\\\\\\\\\\\\"should_show_rel_error\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"ignore_suma_check\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"dismissed_login_upsell_with_cna\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"ignore_existing_login\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"ignore_existing_login_from_suma\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"ignore_existing_login_after_errors\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"suggested_first_name\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"suggested_last_name\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"suggested_full_name\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"frl_authorization_token\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"post_form_errors\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"skip_step_without_errors\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"existing_account_exact_match_checked\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"existing_account_fuzzy_match_checked\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"email_oauth_exists\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"confirmation_code_send_error\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"is_too_young\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"source_account_type\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"whatsapp_installed_on_client\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"confirmation_medium\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"source_credentials_type\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"source_cuid\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"source_account_reg_info\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"soap_creation_source\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"source_account_type_to_reg_info\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"registration_flow_id\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"2bfd5926-c03f-48eb-8e17-a98ed947592c\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"should_skip_youth_tos\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"is_youth_regulation_flow_complete\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"is_on_cold_start\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"email_prefilled\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"cp_confirmed_by_auto_conf\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"in_sowa_experiment\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"youth_regulation_config\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"conf_allow_back_nav_after_change_cp\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"conf_bouncing_cliff_screen_type\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"conf_show_bouncing_cliff\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"eligible_to_flash_call_in_ig4a\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"eligible_to_mo_sms_in_ig4a\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"mo_sms_ent_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"flash_call_permissions_status\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"attestation_result\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"request_data_and_challenge_nonce_string\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"confirmed_cp_and_code\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"notification_callback_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"reg_suma_state\\\\\\\\\\\\\\":0,\\\\\\\\\\\\\\"is_msplit_neutral_choice\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"msg_previous_cp\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"ntp_import_source_info\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"youth_consent_decision_time\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"should_show_spi_before_conf\\\\\\\\\\\\\\":true,\\\\\\\\\\\\\\"google_oauth_account\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"is_reg_request_from_ig_suma\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"is_toa_reg\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"is_threads_public\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"spc_import_flow\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"caa_play_integrity_attestation_result\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"client_known_key_hash\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"flash_call_provider\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"spc_birthday_input\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"failed_birthday_year_count\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"user_presented_medium_source\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"user_opted_out_of_ntp\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"is_from_registration_reminder\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"show_youth_reg_in_ig_spc\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"fb_suma_is_high_confidence\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"screen_visited\\\\\\\\\\\\\\":[\\\\\\\\\\\\\\"CAA_REG_CONTACT_POINT_PHONE\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"CAA_REG_CONTACT_POINT_EMAIL\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"CAA_REG_CONFIRMATION_SCREEN\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"CAA_REG_PASSWORD\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"bloks.caa.reg.birthday\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"CAA_REG_IG_NAME_SCREEN\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"CAA_REG_IG_USERNAME\\\\\\\\\\\\\\"],\\\\\\\\\\\\\\"fb_email_login_upsell_skip_suma_post_tos\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"fb_suma_is_from_email_login_upsell\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"fb_suma_is_from_phone_login_upsell\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"should_prefill_cp_in_ar\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"ig_partially_created_account_user_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"ig_partially_created_account_nonce\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"ig_partially_created_account_nonce_expiry\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"force_sessionless_nux_experience\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"has_seen_suma_landing_page_pre_conf\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"has_seen_suma_candidate_page_pre_conf\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"suma_on_conf_threshold\\\\\\\\\\\\\\":-1,\\\\\\\\\\\\\\"move_suma_to_cp_variant\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"control\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"pp_to_nux_eligible\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"should_show_error_msg\\\\\\\\\\\\\\":true,\\\\\\\\\\\\\\"th_profile_photo_token\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"attempted_silent_auth_in_fb\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"attempted_silent_auth_in_ig\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"cp_suma_results_map\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"source_username\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"next_uri\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"should_use_next_uri\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"linking_entry_point\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"fb_encrypted_partial_new_account_properties\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"starter_pack_name\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"starter_pack_creator_user_ids\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"wa_data_bundle\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"bloks_controller_source\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"airwave_registration_code\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"is_sessionless_nux\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"login_contactpoint\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"login_contactpoint_type\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"is_nta_shortened\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"should_show_bday_after_name_suggestions\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"should_override_back_nav\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"ig_footer_variant\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"control\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"device_network_info\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"is_from_web_lite_reg_controller\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"login_form_siwg_email\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"account_setup_waterfall_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"is_wanted_suma_user\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"device_zero_balance_state\\\\\\\\\\\\\\":null}\\\\\\",\\\\\\"family_device_id\\\\\\":\\\\\\"dd5b9513-0be3-4263-9106-459e51268b46\\\\\\",\\\\\\"offline_experiment_group\\\\\\":\\\\\\"caa_iteration_v3_perf_ig_4\\\\\\",\\\\\\"access_flow_version\\\\\\":\\\\\\"pre_mt_behavior\\\\\\",\\\\\\"app_id\\\\\\":0,\\\\\\"is_from_logged_in_switcher\\\\\\":0,\\\\\\"current_step\\\\\\":9,\\\\\\"qe_device_id\\\\\\":\\\\\\"c734a1c7-d663-4fad-af07-817b064e424b\\\\\\"}}\\"}","bloks_versioning_id":"b7737193b91c3a2f4050bdfc9d9ae0f578a93b4181fd43efe549daacba5c7db9","infra_params":{"device_id":"c734a1c7-d663-4fad-af07-817b064e424b"},"app_id":"com.bloks.www.bloks.caa.reg.create.account.async"},"bk_context":{"is_flipper_enabled":false,"theme_params":[],"debug_tooling_metadata_token":null}}',
}

response = requests.post(
    "https://b.i.instagram.com/graphql_www",
    headers=headers,
    data=data,
    verify=False,
)

write_response(response, os.path.dirname(__file__))

import json
from src import RegistrationData
from src.flow import utils


def get_agreement_body(data: RegistrationData) -> dict:
    reg_info = {
        "first_name": None,
        "last_name": None,
        "full_name": "Eugene",
        "contactpoint": "e70375344@gmail.com",
        "ar_contactpoint": None,
        "contactpoint_type": "email",
        "is_using_unified_cp": False,
        "unified_cp_screen_variant": "control",
        "is_cp_auto_confirmed": False,
        "is_cp_auto_confirmable": False,
        "is_cp_claimed": False,
        "confirmation_code": data.confirmation_code,
        "birthday": data.birth_date,
        "birthday_derived_from_age": None,
        "age_range": "o18",
        "did_use_age": False,
        "os_shared_age_range": None,
        "gender": None,
        "use_custom_gender": False,
        "custom_gender": None,
        "encrypted_password": data.encrypted_password,
        "username": data.username,
        "username_prefill": data.username_prefill,
        "fb_conf_source": None,
        "device_id": data.android_id,
        "ig4a_qe_device_id": data.device_id,
        "family_device_id": data.family_device_id,
        "user_id": None,
        "safetynet_token": "ZTcwMzc1MzQ0QGdtYWlsLmNvbXwxNzY5MDM0OTM5fBWut2xb6bRZ8ZphWFhqT9knoNB2hgkyHg==",
        "skip_slow_rel_check": True,
        "safetynet_response": "API_ERROR: class com.google.android.gms.common.api.ApiException:7: ",
        "machine_id": data.machine_id,
        "profile_photo": None,
        "profile_photo_id": None,
        "profile_photo_upload_id": None,
        "avatar": None,
        "email_oauth_token_no_contact_perm": None,
        "email_oauth_token": None,
        "email_oauth_tokens": [],
        "sign_in_with_google_email": None,
        "should_skip_two_step_conf": None,
        "openid_tokens_for_testing": None,
        "encrypted_msisdn": None,
        "encrypted_msisdn_for_safetynet": None,
        "cached_headers_safetynet_info": None,
        "should_skip_headers_safetynet": None,
        "headers_last_infra_flow_id": None,
        "headers_last_infra_flow_id_safetynet": None,
        "headers_flow_id": None,
        "was_headers_prefill_available": None,
        "sso_enabled": None,
        "existing_accounts": None,
        "used_ig_birthday": None,
        "create_new_to_app_account": None,
        "skip_session_info": None,
        "ck_error": None,
        "ck_id": None,
        "ck_nonce": None,
        "should_save_password": True,
        "fb_access_token": None,
        "is_msplit_reg": None,
        "is_spectra_reg": None,
        "dema_account_consent_given": None,
        "spectra_reg_token": None,
        "spectra_reg_guardian_id": None,
        "spectra_reg_guardian_logged_in_context": None,
        "user_id_of_msplit_creator": None,
        "msplit_creator_nonce": None,
        "dma_data_combination_consent_given": None,
        "xapp_accounts": None,
        "fb_device_id": None,
        "fb_machine_id": None,
        "ig_device_id": None,
        "ig_machine_id": None,
        "should_skip_nta_upsell": None,
        "big_blue_token": None,
        "caa_reg_flow_source": "login_home_native_integration_point",
        "ig_authorization_token": None,
        "full_sheet_flow": False,
        "crypted_user_id": None,
        "is_caa_perf_enabled": True,
        "is_preform": True,
        "should_show_rel_error": False,
        "ignore_suma_check": False,
        "dismissed_login_upsell_with_cna": False,
        "ignore_existing_login": False,
        "ignore_existing_login_from_suma": False,
        "ignore_existing_login_after_errors": False,
        "suggested_first_name": None,
        "suggested_last_name": None,
        "suggested_full_name": None,
        "frl_authorization_token": None,
        "post_form_errors": None,
        "skip_step_without_errors": False,
        "existing_account_exact_match_checked": False,
        "existing_account_fuzzy_match_checked": False,
        "email_oauth_exists": False,
        "confirmation_code_send_error": None,
        "is_too_young": False,
        "source_account_type": None,
        "whatsapp_installed_on_client": False,
        "confirmation_medium": None,
        "source_credentials_type": None,
        "source_cuid": None,
        "source_account_reg_info": None,
        "soap_creation_source": None,
        "source_account_type_to_reg_info": None,
        "registration_flow_id": data.registration_flow_id,
        "should_skip_youth_tos": False,
        "is_youth_regulation_flow_complete": False,
        "is_on_cold_start": False,
        "email_prefilled": False,
        "cp_confirmed_by_auto_conf": False,
        "in_sowa_experiment": False,
        "youth_regulation_config": None,
        "conf_allow_back_nav_after_change_cp": None,
        "conf_bouncing_cliff_screen_type": None,
        "conf_show_bouncing_cliff": None,
        "eligible_to_flash_call_in_ig4a": False,
        "eligible_to_mo_sms_in_ig4a": False,
        "mo_sms_ent_id": None,
        "flash_call_permissions_status": None,
        "attestation_result": None,
        "request_data_and_challenge_nonce_string": None,
        "confirmed_cp_and_code": None,
        "notification_callback_id": None,
        "reg_suma_state": 0,
        "is_msplit_neutral_choice": False,
        "msg_previous_cp": None,
        "ntp_import_source_info": None,
        "youth_consent_decision_time": None,
        "should_show_spi_before_conf": True,
        "google_oauth_account": None,
        "is_reg_request_from_ig_suma": False,
        "is_toa_reg": False,
        "is_threads_public": False,
        "spc_import_flow": False,
        "caa_play_integrity_attestation_result": None,
        "client_known_key_hash": None,
        "flash_call_provider": None,
        "spc_birthday_input": False,
        "failed_birthday_year_count": None,
        "user_presented_medium_source": None,
        "user_opted_out_of_ntp": None,
        "is_from_registration_reminder": False,
        "show_youth_reg_in_ig_spc": False,
        "fb_suma_is_high_confidence": None,
        "screen_visited": [
            "CAA_REG_CONTACT_POINT_PHONE",
            "CAA_REG_CONTACT_POINT_EMAIL",
            "CAA_REG_CONFIRMATION_SCREEN",
            "CAA_REG_PASSWORD",
            "bloks.caa.reg.birthday",
            "CAA_REG_IG_NAME_SCREEN",
            "CAA_REG_IG_USERNAME",
        ],
        "fb_email_login_upsell_skip_suma_post_tos": False,
        "fb_suma_is_from_email_login_upsell": False,
        "fb_suma_is_from_phone_login_upsell": False,
        "should_prefill_cp_in_ar": None,
        "ig_partially_created_account_user_id": None,
        "ig_partially_created_account_nonce": None,
        "ig_partially_created_account_nonce_expiry": None,
        "force_sessionless_nux_experience": False,
        "has_seen_suma_landing_page_pre_conf": False,
        "has_seen_suma_candidate_page_pre_conf": False,
        "suma_on_conf_threshold": -1,
        "move_suma_to_cp_variant": "control",
        "pp_to_nux_eligible": False,
        "should_show_error_msg": True,
        "th_profile_photo_token": None,
        "attempted_silent_auth_in_fb": False,
        "attempted_silent_auth_in_ig": False,
        "cp_suma_results_map": None,
        "source_username": None,
        "next_uri": None,
        "should_use_next_uri": None,
        "linking_entry_point": None,
        "fb_encrypted_partial_new_account_properties": None,
        "starter_pack_name": None,
        "starter_pack_creator_user_ids": None,
        "wa_data_bundle": None,
        "bloks_controller_source": None,
        "airwave_registration_code": None,
        "is_sessionless_nux": None,
        "login_contactpoint": None,
        "login_contactpoint_type": None,
        "is_nta_shortened": False,
        "should_show_bday_after_name_suggestions": None,
        "should_override_back_nav": False,
        "ig_footer_variant": "control",
        "device_network_info": None,
        "is_from_web_lite_reg_controller": None,
        "login_form_siwg_email": None,
        "account_setup_waterfall_id": None,
        "is_wanted_suma_user": False,
        "device_zero_balance_state": None,
    }
    params = {
        "client_input_params": {
            "ck_error": "",
            "aac": '{"aac_init_timestamp":'
            + utils.get_pigeon_raw_client_time().split(".")[0]
            + ',"aacjid":"'
            + data.aacjid
            + '"}',
            "device_id": data.android_id,
            "waterfall_id": data.waterfall_id,
            "zero_balance_state": "",
            "network_bssid": None,
            "failed_birthday_year_count": "",
            "headers_last_infra_flow_id": "",
            "ig_partially_created_account_nonce_expiry": 0,
            "machine_id": "aXFTbgABAAHw1cpzzsgkxOLUNm6H",
            "should_ignore_existing_login": 0,
            "reached_from_tos_screen": 1,
            "ig_partially_created_account_nonce": "",
            "ck_nonce": "",
            "force_sessionless_nux_experience": 0,
            "lois_settings": {"lois_token": ""},
            "ig_partially_created_account_user_id": 0,
            "ck_id": "",
            "no_contact_perm_email_oauth_token": "",
            "encrypted_msisdn": "",
        },
        "server_params": {
            "event_request_id": "9765106e-c2a5-481c-9861-156f6eea4a7f",  # check from username request
            "is_from_logged_out": 0,
            "layered_homepage_experiment_group": "ld_no_language_selector",
            "device_id": data.android_id,
            # below check from username request
            "reg_context": "AVjfEWediHFklSccnYXQ9vdz1gIaKnmhyuOcHjUWIJH6159OfOzROjN6R_jS4K0dftoH-tWHbJtjxhhBAFHiRvvJ_fE8FZWAd3KHufEeHD_W9qoHUk8fY36Jyz9729FNho__StB4YYbCq6R4vVqMqDsZhoeVboul87Q1szae2xwPF18lHj_cM3Gvze5LxU62Q-j05QEjQm7dccGUoZtSxHEqcjXmZUpDhPW7rZc81Yn-1UfWksNTaUJJyLcPsdYrB66x8deTe-ata7_NbWG3M3TI9peVHaiAM7ffZIxvQitijgVdKZKigqhKvIuQbG4NoIu5LvSRs9e1FuYJRRSq5Bs2kxArh6UKS_4t6fc73YRiJFA_XFoLhJAghEAyqgAdxk90DR59tDzRcwq4L94_iMORqF-AC81j-QLtEVuAHJ8qe2W9QOYfspeVB1iEI1eAwYrpDT1ICu1SO9mjhvA7JoGCbW45mYpWD7aMzOgHkr6qCt1WrMOChUucmzb96m5oP7n_oUGrzvVsIwH6MIr4lsuw9gYUguMHqbMQaTEBx2olJfoO5ah5cNvN5pmvENyRjQDYR4DYERm4lR7p3HdNLORanoLTztqGZu8jdMlqPBfP7jdcWjjmwEpfo5-OcaIc_BmmUw2QafSFxDSzWgKuj4lp22CZpTJGpfA7ZjfYSrsjfZFDNMIP_U0QtL0LMX_WUlVno7mCJkrNLxsUWFX9ZXuUgD2Fho5u5lHBYXlqgQCG8pSpXeqiZSbMWN0U47chDcqq1xbu-J52gmqrECmaNwVfLiFIOCoK_ihRct4-zwCdq0IQD8J7g6JUGOlbo5AQ0TLzRMEyQ4xUkPI7OKOYzqWBnsz8iCd3eOB2ZPtzqVHST2LFIY-CWUnA0mk-ou69pVC0Yu7EDrPttg4WBrLsSY_VNoaWNJZIw-TIavYfCRHldI_bjivMU0pp4Pf2odaoonAQgIesnES6zPXJY5XFNtxBkErnb9bwUj_giEAPH7RoqHxRQSKmudTU67y_BZVdFkA6LZAnGPiEsIBoqfkAr22AmRZdYMNdXTRQEa523cSWJBXpttsK_nFxfkqDO5BA2BkI4Ia64P4A8qcGAtuJ1bk-1KZFrvGV4VDzcWmaK0vU7K764BRk6SKzMvCv0qZrqyI89AqAdXjwPiiL49Zt65c2vgLxGSUq9D4JlCYDyBo0PN3O0G_ft6Olj0JB1jd8g8nEqSCW9C9UVJ4eIqvTX1NJ7uacoCEJLdKr1tPNmEgGGr8HEATxbRuEQbPJbONAMAn9FwHEGamuohlk48y82UyETJS36-rVeLcamTYSb8wvgH2LCvETEngBmafyx-f2EOquubIGBkEZyiIXceNAP2PjLW5AYaBNgApxA2cgFI7kpVk5MvEFnErz8arbhZ379di3vlZ_z-1EdvmQxFf-do4H1hmy72gWEyvHCe71ZgrWkV-Nomzqms2Rr8Z--65AeSg22FTE3jd7MKSYlZmZoOC7IFiXfMkToAiIfGbhjfMoaq-0oNWZOApf3320GRdt0jAn4HZI6rBnM2Zyuddvrk_ikVMBmNZkc4SZzUhpHrUu07ND1egc27MsJYD_ebXQcCWYDWY87DQG53uZZOQsL7qTz_-HjV_VtxiLh5Jwj2VEWzT7qwwqBP-A0J3y41LLljZlR0ZZenE3C5csRuSwmRVekVskHVQGCUGw5edAZqrFzBs9Eopv-Ai5ri6SDLKsSA0B954Rj_WjDI7lJqXAuNw8wmKEBw0yXIbRCmBVqaCfGkbogplGw1kuk25VBCgCMF9ONJ15Mnks9gceTkzVKGbTF0_ELxbOxdns_FeObyJvV8IxduAAKNBGCeVn9GhnXcco_T2y2j0V6Uxt7t8snvlzcR97soT3_aJ6Gv_Om0F5HQMiHtOdORpLttPFni8fkaRLOpNh-KEXbDFwB0RUoJCTKy4kPlWblSAwqUMV0hdR7BNKFFixLxFHagNTHT4G05rzLnrk4acT6UxOXJmtG025CYhxvCIpZgcMuhHgMpQFMcTe9moXk2QtV-kJj1U-KQF2tLqsn8wMmEA7DIAKRyyemZIz9ehwBLU7bLuGhTZhsHeAT4teokHeFkZ2jO4rhupX4zA2QM1er1udZ5GEzdcVBm6O99xwbLo7emuxirSHBCbvqaNAr1BkbmgfDRJ6z8cE8fqT9Tg7Dz2YetKI-VnUBwIuA80G0bmxyfiMx-f_KHWKepvzq6bJHINVkIXZNJcVP7MKqua9u9xoIdDrKPszavRPz2QZdGAnk9w9ruUBLSpW7zsHh6c_MsHqp-UklX6Ew4ViXB1faSSJ5cs_g8PSd8gz4zNyQDvG1PHCbqBuilqmib-I3RD6esufdJWsjXZHD0VVY_XKxH23yu3iSDPHHwwmR2fC2Uzg3B9VcPmGDR0fh_JYNJ24_o1kk76-_wFfA_8y1qm6IcRpq-Uf8DsUp1oIdP_lu1nvcYWNUSq1x9BUIvBBh6pxlbt42E235SN9lXr1F0Z7YQR5nHRdERdf9WmYAx40SLl6rAufvW_ibqN88EfuhUjRVxrCQteyKSvNJ1ib7QiAvExit5MppEBVxovwQ8Rdufs-USLAGEsiejfZFmrdM_co4eRkxjqogwtsmE8nh4AqfDGrEWtenvnTatWB4VC_rf7EWSv7KBhFV_bCZjlTb2rM2tI3rRsnnQZiVR4tHX8aPyhT14w83cdL2LwZsLROY_D9eBLPNYKg9rZMJnYvNWlUw4RfjcUOoLrv9Z0XL9Gi4GNvanosBTI1OwhlaA9oZIEj-_g0EUiJXS3bXlIzOJ2rvCLknidxi7SAFf1MbZgHqHP9NS8m0P5au0uldlsg2bLPRMTGapy5E_c6PkLD2BT4SubXgxoZXcu15Kng3hQgsAa6aEpsWDIBfbktrpDUTxEaZqGsft-6EiuWHzvfwMv064YUsyafPxla3RbX8JUzuH6PB5ZsOxIh4B1tUrOInxAgAxIzJGxk0P8u5oo0j3Wy9xpfoEY5ciIzB4rtEnGUDMF2vYgjJ70J1MRxSXaFshS4svfBJ0kprKrV4Dp28bVWJkRMIqgWVCDqtKRCI3S5ESWvsGdReYUV2LDLe7TrF-otlMWBZHF4V0NkNEvu0ANlg1Kw431arYFqIvceUQwgC7pTAObN7YMDzEI8IFerQSduhviSdICg2UNeb0wSm870x9wHU55XGIAR8wheccHXmjw-hJ7dTtTUefHJYZC09HwPDBOJ84fxWOZvTu4bZBYOdVR9M3onawZaO915zj20SZNWuH-pi3Q_QiFZhHSJPOem94sXz8ZzI4dkDt2Su8BejHMm-i-L21tidlACPjCEvEMoDI5_zGsqbVU9inqXvqvQABbB6lbT_abR9jV3gj1dso8dp0XP9JPe07XAWLeNwd1irzq-KvUAaNcjkPWhDcMfY4wYCnQ40PYQZPZg-QtpufDc7E6P6EjqaBiZ7msZtqDyBTry9pVKpUUSaoxvUvJIUtWT9TFxibJ1bxy44LATz-zqGaTvMWzryhBBiidK8w281Ioi7Vew1VykcSHDe0Y3TpLzzzZboTOjOieSxqCwVuTFuA0_ijgeq71_35hERpcbCwkFWC-bTbrHuNuiCXIARuaQyxhz2pHvpjNiKF-z_aAoUX6JzNvU8F4jjxi_AQ7jiRDnSf6IIqknyFYa0A1JiC5lPW668XBZPAK_ExJYAbHjaP6qv-OvDwgZq3IZJRj4ytevY95ARObcDFa4uIpISfxfyfbRpkjURuuBjh0tlGrGWkso9wT27NWBPJuzvARL4inH5JinhJJZNbkCpnIGjdzFG7Si02iLsPtLTOdJz_JKcjb-UA37m6WianVxxtRbsKB9abVUAJJi-vVHIl1pGRYditqRXPEboF_NrWnaQpX_MrLfHvp-zCk5y0gcitufDPbFVrdL70ZfC90ChV6WE8uC8VqBqr0aJ1B5XtDVYR_I2ywtC7K0MVKxSu9P2qmQVQpD-XAntZn8N4LPs9yVBwVEovnVPHgfXglexVWXI3H-PNiUTiKU4frbQnLwkSiJJy9067DEYAvhMvXJoGCC2_f0DVjo22W1cvDesw39y5o7sGqV_EOmypY1gS9ychirquFscrdGbkkhk670Ujm-VRe9L9DTiaAhfet7J41cINtFNXwt17FA06PGv6mlykZkK1RpGdKJSpi2q03XkXt8VAUT4V50QbQDlHBrvU6Zrrym2exRet63MSNjP6gKwqj0fV3J3XudONcoPnsH5YtiyLFNL054gBU_ITDby9erWlVMdk8K8tjrHI9qpwNUFwS3MjOIAZNNRJuS828icA9Zlc3OdoI245A7mYIDzwbK9EsQKuxmbmiQmOPralsB1BQjE7KLzHDj-WvUZBA8fnnzZlBldwUa6tL_tx0BgCYJigKmzBtjun_IkGgl0sV692SkGZRRpzU5UfBC3Zb_8NIRgrzIPHdZaVLzL4v51j53bN571sXJnyzB_LyAvBteYb-a1MKF9YCZX-Txao_XpdGWqf_XNx2nZWtZMkHyscGSjveITB7XDl3Nu4tNiADuNxT458INm1zorkXl0vkvzWMc72X1Z0IHqTs_GBB917MaP0zDqS2ThHpc9JXAN4Th1Mc4UFQKm13qYO8ClsTqoeUb6_5vr_rgCTnUoc4C7CzDMCnjLOuQjV8GURVe2H-7c_upv8gpfwDd5fNVEvbZYudCFW9vvbxQQl5FmQfElmMGtpXTA7kUJyQbIMeL5YVy5C07dhuYe2oQyXLdPT86HxplRVA8tZ9g95MPd9cyq_h00vYKC6aiNyRxwQ7eeMJkY2zzPcwVwgKZFIB3hGb3KPFkqLBsv_N4jd9-vToIPEu66NwaXZnKgRu_pRcWTyqVgFuam_HhwEGZFzZ6SnunUmPKYOtZqgspMSiis5Q9pFVvr1Tw9jMxNp8nWMiwwaIYO3CMa9JXMIEDbm5EOKRPW1JU8FZEBGG4-ZfFFiZfAGqYeUhyU5lOs2bSuQHt_PG66JwQyXs9ddFCAnbdS9xi4BMqbaQpvuFXhrlJPap4p_3tDgAdFSoR7RqFESiayApCcK4YChl5PnSvEU_2jRvU5ROFgH-UXffDBWVhpr-hLaEMVi_lBD7-t0Ko1kMg587bzG1yhvA4tTrw2pK4R_UUZbKubc0PyxJtW-zsb26ac0K3pI-K54mmSPKppnPdVQcNFWUXjD_6aKp5KNWfsZvmsPMo9zWTWH_b-Nz6zgxkI_Zz_1zB4RXkarhvAr01abPrLmYvyE7k55rlc5pXa6f3jb91m4o5QMcwnQPzZIyx8fRHOfY41bpPH_v5JWBxx9bS5lN6wqLHsYXqsWxDcOXG62i7dlDrRxA681kdpK3ctafzztMzq4johYQtR1RIMgrn56XLe-flSnFWiF6IjZ9TXkHV0ZJbcES8zc_Cp_XjMRAxf8QwtFPpD4CNfKM-J164dsDHtuTbPowyQmOzRO7CLDsvYQusHiwiAChHFFNlR-Sj8pvfBGE0eo7XLlD3_zV6IJ2crg6oFWE0rzHdEqF-89GQf7E7JvC1XkmYscr56qWSOXVtPP4TNeQdxIZwgYgkRDonewV4hX18eqWTx7l-OZSwAzWMNjiyHWf96AhONufK-5F-qcKjCAR2EiLIJ31XrTYSKlrxpMtXhdCC3p_tZ2ZTQU3lA52EDQQ_bii3QoazGq5zbED3CLTNyQLqDzKneQovBr17yDHhPMyQyaGS_sfNQYmmkP_Dxf4gyTn-NHRXRJ6-luLB-scrMRjCoIztx0ZWKUei0aFfEiG-qBeBJST4mzJ3PmJn7scnsHueDMrT9c8uLO6_9QpAPZOjGf3sxV5pt3NsnHPjbM6rtPpS-0PkWVryGrjbBp48H0bEazwm1N8cMfFqw5j6RHLwvJwf4wyITuhhl5GxM_jzgkPy0BPsVGsv5BlDpyp-oqNAxmaos9v3L54eg8pvEPrgf_u4_a71iKwspFxOkrOfMIUUkX-t7OTpE-rP6UQmipk8HYHEXAdC5tR3mY43qF1iq_UO4qzNYu3o3WIw-0TZvt1645Pl0oV-iIHUtF6lChRF8LrdkKYB2xYmdB0zUHkufQZSllGV-7VTDW_SIp9fhPikeokULTYHOjJOQXVnc0W08EhBIQWbab4e0OAOaBLAAO4yzIKSLAse8kqPuLSQwNMvTnJzzz71tJVZDrRBAzemLXo9BYRI2APiKDyhXGEC9CHaygiWK2W3Y9KK1lwrg78AD9dJrCMHcbr34o_aeRs_OsutnIIJfxvCBKVO40kHTc6soErAa4HCGNd2RdRAbouscnZiHMM3cGAoMXW4PPwRX_SOO746WbqYl9yQbG6lv7gelSOOZ-mmEqUA_IojTebe5h6Y0o0vivgACpjN0fLL4zUZqodx-Ke69AaHllYen4hTFrId-p3p8vwZ9wjWyzu13G89VnhtY6eh3kN94Bk3gerwcJ4MSoFEFkBQuYPqNd9UPN7TupllKB6z7x5-qbyqDsNSKSCZJf2yw5X7A71NRqOXJVZKL0TM1XY9kS99X2YzyzoTTrht4tydd4oSXU67-P_T-KYK2C8e-TrNG10Lc90Sln7_uyXaIqGPq_89jlGqDW0ADfgiJ4hZbCj9A4xOK9ROQWIN5HGP-CmzVlA5goTFzB0S_3OXskjU5As4EUms8sjby76dfhECIwhov4x_Ks338Mdkt9PnGnq9z1FauL432SuPG5kmo8888tnWSAkSaVL8a_wbmejGnOyLxu8M2TsMlk6Y3LHD9lfCQNdEpw8XW-f2bSoteoPnPdB74MsNf-Lo3ItlGlivET03T9DVQ5Yx53EGg3ewfAUYegd13DUkTrdMk0Kg5IozCgYVs-3IAbB1Kx03vDgntIIjE2J_Hs7oKt8Qqff--nTmvULOep8LAWFkrshGCbcitxe2Tdsy1G8Jtp7qsk6Ovc7T4sm9BT1Ono8Tp5dOaYexFtBXAs2fQ3Yfnx9OqXsbDfc2qXs4Gql9iXGoFMsYK2hZFuMTINdaGKIaE8fWedBFPbc9SmOfrSPSN1ZLiNFK4kVLNQMZ0VE01O-vkBQn5CteLALTPDWhZf_K2fHIwXMsMTS8fhRrg7moU1y5Rrfv4WRe8rcfyyLXSBmiOFzPXAVcMhrhJo0znBrYxznzL5PpByHin9QsxRrYL6xZjYe3kbiTeimTW3ynbrjtbyfcGqQZ4VP0oDT8MLXlyDhPVdEvYEiDRhPGccHcAxJWh_LstfduSqdxBgPx7gFHg-1lKYXexK2FXWc_ZR0KTlVuh4lRzkTNFkhwkZ13cpVuNEWYUZENCnPmxenYd5wYejGp4EBN9FG8UeNP8qqzydnYFLnygbs5ttjIrGc40NwxzGiJf2GfGCnODw6Yoo2LlzImc_HmgXBZGPwiVsGa5v-SLW4YITUN7KYqDRqPz1ktYfYJP9KV4u4IC5h3MhzIKhev3blEA5MQafJKXyohf_4BjiBmKFDCaH_IL3NXaeBNxvCkYNL9tZutq93fkX-8fvJFta8bTc4mq9lGU08fWh_NCbcXR_byFFYA8WrF1Nz0DtnM5a78GUpPZN-ZLQ-zE01YsCwADlyuZhP1qLg4ZDNgB8mfDW2-HIDHVvW7M852pcyA8ucrXWkhCcwfCtrlVZrVdIFkPlpwKVthhqbghMouLhzevSRGGWmupjC2kz0d7aawYvfRK35dB2Z6kvJWKukVQ3Uz2ROTCKctdUflezhqYVSy3cWY2RlbpXmoq3YBDA7Jyg9ZTJpCVaLx7Q9GGqOzVyKj2jygVYRk3YBhLpFqhtLA_z8vQMJNU0zNPTLm_0iF0W9YVdKOkXdlosLeqviGUJ2zMTjp2HR547U36bHsedXyqlsLmPJ2a-iBQCbyEq4e59Vgte9o25kqIdVsJ0BXwvwqsECKMwZOTHGmdLtzcH_TdO2Tj9LonO3h5did2hNOS6U5YQQXLwUgtdeoPVd9BYXi7FWmDhFgBmev_w8kaKgEyLkeVNarxscO2J_3GnFL8VGPu8mpCNKuq6WUExfOdJBhpiGJFi7P46dXA8eA70Ln51Xro7SuV3Ro3ZeFj13Xjq2C21z4PKozIQKPHfLYR73hnDomfk67sFHKeD0ZHnCuLzm_dRy0Ea_JvlHWqOT6wdy44AX0jopz8zjFBha9vNiOGC3A2zbIvePtGFWPUzCcBlB6OeWYimd_bOr8X9HkpozftCPrFUTZ_jiY04OEmDqLmwOXE9FgxZWJm0XZHU2CmrJEXQXdjS8I8XEYe2H16po2QjMpPGDdUEaPDM9te-x-2cAM6Mt0-s04VzxQgrp_vtdnxZ19wwzkDq-HL8idO-8W-8n3wzdn-JRrRH6w-gKsIEHfTdfUGd4zhW6TB74ARGABBRZP0ZHEwZdZRlymKhu4vN-HESyuST6BK6yt-gYvu0fa2cTx6Y4HlxdxBJaq3Q6YtLwAIUFWANASwOUXGQvmHxJDOTY2OIz0KX_xzCFR7nNVswRgo8aXSPegyJWuzJEhZ3boJmY7O8PtjEb_u8-r1Br0Q7p6oKibm0zraRiTe-1H9oJDtyp-IEQ0ELGASWFDSOP3RrmNXmNcGXcKju370ozoszhvCK66QMfdIcqqfQ_raQaoKofhkeivqi-FIauP_PcAmr6JmgYV8QV_K_EYiUn0DAvkICJJ0UnMNOpXauz_B9aIKj_8fxoaWPId4koG4g3rA3lO1mkJdhyLVPxeAWtDEnSJhCHGyHqCps8evXGRy6VYgCbE-ZSAHuX_jf6yDa0xuDt55JRBUFCd0cFbCgjszRamm71rpBsDHuz8Oh5-cUuMO7RRa3vvhcAaHLmPDNr9Ba4BS3hh4D06Yp6EBApwI8xBh2SGlTXg6YGd1fEQCj9yaPYJto2IpUJdTQECtnGSlL2R_6Rcx3zZLLPDPuda6XdZxK-mbtZtcK0TdDsI-5iu6YzkU1IAz3AlW9LvTbd1hCvtm4DnCElvG2BFqkUYyrlH4dxrmhSTYHsNhNSNvStAD5Qo5MPJbPRFH-56RytsuPbl4b5HSObrjma0gtd3wDxiXaY68PvEpUvnOLa9Vkxfj8OBbN_rkKo7jhXF7K7Gr8CHuiVIjTQpZZ9CL8TQCROn9Fq40R1L43HmIbLKVALH9b0OlhSUtSQJSq0WofbnhHnRQ0yVXKRCs7Iao9uoF3UTwzMoGZjSq9Zf4SgZe4YxCT-4Iua9A5fpefgzKebrR-AxW4DFMXABGx6VbZgNO-rzm_yT2XwP1iocqBwcfWcde8Tiv2B4xJjWckcP0eKZq8UKgjHzGB5WLlAybWOQgyE6JbKuxbNSttBACV_XWUX53P5ef7uZ-QwN8AKdBH3G--uBZrcxjolVmvCUWw9Qk059K3fcHdunBUsvFijq1P3yKknW5CrKnp_YPz76VEqvfCDYY9T12O7MNGiVmIHlZvX9O88w-vtrKLIGXexoUYMreQ38BX3q_pWhApvf3or9G91azZcCeaWAhsIyN6MXBv38BVENt0YEearesqlSyGY49sonE7Y-Dm5gXh-0GkuS02l29DVdIPYcF2xlUDR06pzffLwH9QVy2-p6CaVFbDAfHv-cNyAZTcSdGUhkqulxPAoXQvx6tHutgec2zAXs8NvCiG3o775xYhuq_iTZ2ioes7GeMnAUW7P9a2wIOz4iBenLHjYu-uqTvXuS6FjomL8JP1JRsiAXV-UFmxs9c2pX40PBIxTJgbCdsz7BCnAEo4t7jBBGCLr4BcxSuFUFe6_3n86rvgQYXUJ_6AA1lsbd3fr33EVQcvcP-T5ONvzPkkbWxnXwmpMaudr8Ga5NnuFDD7UmXi01I4IoV5r5DXV8et5VOB4fDJiitVJ5fB7Mwl0mmA|regm",
            "waterfall_id": data.waterfall_id,
            "INTERNAL__latency_qpl_instance_id": 132085942500023.0,  # check from username request
            "flow_info": '{"flow_name":"new_to_family_ig_default","flow_type":"ntf"}',
            "is_platform_login": 0,
            "should_ignore_suma_check": 0,
            "INTERNAL__latency_qpl_marker_id": 36707139,  # check from username request
            "bloks_controller_source": "bk_caa_reg_tos_screen",
            "reg_info": json.dumps(reg_info),
            "family_device_id": data.family_device_id,
            "offline_experiment_group": "caa_iteration_v3_perf_ig_4",
            "access_flow_version": "pre_mt_behavior",
            "app_id": 0,
            "is_from_logged_in_switcher": 0,
            "current_step": 9,
            "qe_device_id": data.device_id,
        },
    }

    return {
        "method": "post",
        "pretty": "false",
        "format": "json",
        "server_timestamps": "true",
        "locale": "user",
        "purpose": "fetch",
        "fb_api_req_friendly_name": "IGBloksAppRootQuery-com.bloks.www.bloks.caa.reg.create.account.async",
        "client_doc_id": "356548512614739681018024088968",
        "enable_canonical_naming": "true",
        "enable_canonical_variable_overrides": "true",
        "enable_canonical_naming_ambiguous_type_prefixing": "true",
        "variables": json.dumps(
            {"params": {"params": json.dumps({"params": json.dumps(params)})}}
        ),
    }


def get_agreement_headers(data: RegistrationData) -> dict:
    return {
        "Host": "b.i.instagram.com",
        "Accept-Language": "en-US",
        # 'Content-Length': '31910',
        "Content-Type": "application/x-www-form-urlencoded",
        "Priority": "u=3, i",
        "User-Agent": data.user_agent,
        "X-Bloks-Version-Id": data.bloks_version,
        "X-Client-Doc-Id": "356548512614739681018024088968",
        "X-Fb-Client-Ip": "True",
        "X-Fb-Friendly-Name": "IGBloksAppRootQuery-com.bloks.www.bloks.caa.reg.create.account.async",
        "X-Fb-Request-Analytics-Tags": '{"network_tags":{"product":"'
        + data.app_id
        + '","request_category":"graphql","purpose":"fetch","retry_attempt":"0"}}',
        "X-Fb-Server-Cluster": "True",
        "X-Ig-Android-Id": data.android_id,
        "X-Ig-App-Id": data.app_id,
        "X-Ig-Attest-Params": '{"attestation":[{"version":2,"type":"keystore","errors":[-1013],"challenge_nonce":"LUV3jahbCM8BkTPN94eymHtYEFfg5wzq","signed_nonce":"","key_hash":""},{"version":3,"type":"play_integrity","errors":[-9],"challenge_nonce":"BJenaqsyuNRb_A0gZDUct8iLlM1ow9Yd","integrity_token":""}]}',
        "X-Ig-Capabilities": "3brTv10=",
        "X-Ig-Device-Id": data.device_id,
        "X-Ig-Is-Foldable": "true",
        "X-Ig-Timezone-Offset": "7200",
        "X-Ig-Validate-Null-In-Legacy-Dict": "true",
        "X-Root-Field-Name": "bloks_action",
        "X-Tigon-Is-Retry": "False",
        "X-Zero-Eh": "IG0e09d776530888418ab70f3822fbb4e1",
        # 'Accept-Encoding': 'gzip, deflate, br',
        "X-Fb-Conn-Uuid-Client": "95b2bb513e6c590b7147b9e4bcf849d8",
        "X-Fb-Http-Engine": "Tigon/MNS/TCP",
        "X-Graphql-Client-Library": "pando",
        "X-Graphql-Request-Purpose": "fetch",
    }
