import os
from src.utils import write_response
import requests
import json
from src import RegistrationData
from src.flow import utils


headers = {
    "Host": "b.i.instagram.com",
    "Accept-Language": "en-US",
    # 'Content-Length': '30274',
    "Content-Type": "application/x-www-form-urlencoded",
    "Priority": "u=3, i",
    "User-Agent": "Instagram 410.1.0.63.71 Android (31/12; 420dpi; 1080x2274; Google/google; sdk_gphone64_arm64; emulator64_arm64; ranchu; en_US; 846519343)",
    "X-Bloks-Version-Id": "b7737193b91c3a2f4050bdfc9d9ae0f578a93b4181fd43efe549daacba5c7db9",
    "X-Client-Doc-Id": "356548512614739681018024088968",
    "X-Fb-Client-Ip": "True",
    "X-Fb-Friendly-Name": "IGBloksAppRootQuery-com.bloks.www.bloks.caa.reg.birthday.async",
    "X-Fb-Request-Analytics-Tags": '{"network_tags":{"product":"567067343352427","request_category":"graphql","purpose":"fetch","retry_attempt":"0"}}',
    "X-Fb-Server-Cluster": "True",
    "X-Ig-Android-Id": "android-f35f126bc4795e76",
    "X-Ig-App-Id": "567067343352427",
    "X-Ig-Capabilities": "3brTv10=",
    "X-Ig-Device-Id": "c734a1c7-d663-4fad-af07-817b064e424b",
    "X-Ig-Is-Foldable": "true",
    "X-Ig-Timezone-Offset": "7200",
    "X-Ig-Validate-Null-In-Legacy-Dict": "true",
    "X-Root-Field-Name": "bloks_action",
    "X-Tigon-Is-Retry": "False",
    "X-Zero-Eh": "IG0e09d776530888418ab70f3822fbb4e1",
    # 'Accept-Encoding': 'gzip, deflate, br',
    "X-Fb-Conn-Uuid-Client": "95b2bb513e6c590b7147b9e4bcf849d8",
    "X-Fb-Http-Engine": "Tigon/MNS/TCP",
    "X-Graphql-Client-Library": "pando",
    "X-Graphql-Request-Purpose": "fetch",
}

data = {
    "method": "post",
    "pretty": "false",
    "format": "json",
    "server_timestamps": "true",
    "locale": "user",
    "purpose": "fetch",
    "fb_api_req_friendly_name": "IGBloksAppRootQuery-com.bloks.www.bloks.caa.reg.birthday.async",
    "client_doc_id": "356548512614739681018024088968",
    "enable_canonical_naming": "true",
    "enable_canonical_variable_overrides": "true",
    "enable_canonical_naming_ambiguous_type_prefixing": "true",
    "variables": '{"params":{"params":"{\\"params\\":\\"{\\\\\\"client_input_params\\\\\\":{\\\\\\"client_timezone\\\\\\":\\\\\\"Europe/Kiev\\\\\\",\\\\\\"aac\\\\\\":\\\\\\"{\\\\\\\\\\\\\\"aac_init_timestamp\\\\\\\\\\\\\\":1769034606,\\\\\\\\\\\\\\"aacjid\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"d2c8ed10-f952-4a12-aa09-e83671b1bf71\\\\\\\\\\\\\\"}\\\\\\",\\\\\\"birthday_or_current_date_string\\\\\\":\\\\\\"22-01-1993\\\\\\",\\\\\\"os_age_range\\\\\\":\\\\\\"\\\\\\",\\\\\\"birthday_timestamp\\\\\\":727655810,\\\\\\"lois_settings\\\\\\":{\\\\\\"lois_token\\\\\\":\\\\\\"\\\\\\"},\\\\\\"zero_balance_state\\\\\\":\\\\\\"\\\\\\",\\\\\\"network_bssid\\\\\\":null,\\\\\\"should_skip_youth_tos\\\\\\":0,\\\\\\"is_youth_regulation_flow_complete\\\\\\":0},\\\\\\"server_params\\\\\\":{\\\\\\"is_from_logged_out\\\\\\":0,\\\\\\"layered_homepage_experiment_group\\\\\\":\\\\\\"ld_no_language_selector\\\\\\",\\\\\\"device_id\\\\\\":\\\\\\"android-f35f126bc4795e76\\\\\\",\\\\\\"reg_context\\\\\\":\\\\\\"AVitCNVb6u6KaI0w_ThwbgIQlEfF4gCl-nk1FRnFhOHOo8HHbhNMVLYr36eF0uZWAR5FnEPOUcMWEmkxp3-V7SFuje51DMyWIezyRUEULtYfyLGRfaSsX1DAMhhVCkffJ4kz3b3EtJFcBVpEjtSUDoT6XgfrEIA51qJwa0pS7Wb6jddUpnksVP_S663qfgEeImbZOPWdTflweZgVxf95_w8xdPom04N_oAC3wiSA1Iqlvgfyl994dcKG63QytMAZJChWFW3jDpZXukzxH018M4XUE8yxGpDymAzNp362mWdG9gtBkcBJQ6H9aQLISpv32QsBnXUh5eEbWIh08JRlUXVHgbNaIP50YNck9zC-7CxQFMVrpo-A9acXvzNglblSkEjHiNPsYJz7oyl1qEVouBGvB0eW0eYbAsJDASe3vwrJxcaokr96L667_28fOVBz3fFJPEAW08DMrIZnaGMF6vvaZoS50GkupkzHsMjsiYfawl74FrQjZOf3OPJhCe5z6IcHKmohaJsIOR4FMfK3X-LjvY9mY_JTSTcYE7PpcZQmwCG88_K07Gdrv9wON-kySDQwogGdckbJUOa6qlbyKzp-OTNgasr51yX37ErnvLrImYedptypgVd_PsDvCieVN49C0edn_Lsk59z0bmBqwOKy2wU_Dxls64ABtSjRJXPhP7SIb2vR47A4JVHVzgrcvkp2psJs_yI2AO4QAgcwp0J-AOfT8JLAMb1Rqpn4Ehip5L_ZfiURk3jiHUFmcrJ8QmpF0yeKZxIjEMYANKFuDi5BnNtHFeCI2LpmqlnBMABHql_y-i8wzQR1C_kXS5hiu2lTt7RkPEG_P-QYNExBD-8ajAdrAqtMoEQl2_EsitaVF7Err-bsFuFvfvZ_ZUClv0R5WeLtlipOlZRKBoxozlcRSubn2hGTPK_YWcPnmIY65AWHqJZi-YE3yKVM0Ke5sh1MYBYBGGyahdk4BWTJO6pf61ePvVtg8Cy1bAELmCxbIVbeZzjG1ENzybJ3JsuOzmrE0zH1WrM5wTyO9ekwa1tsAWXRXEcaPEeu_TZxK9t4YTW5aEkizCPNai2pAC75YA9paRbsaVLe5p8plnU78N4SZmVWnIwUeqo0_KYD9fSTx3UhZzUEEuZu_x9R5fqJ5h4DOwGcx541NdirnnfiTORUsSYNvZb1SnINJnGUQxzkoNCBqPqiynTjDmLzAV29sQuyPzo_PbTH2xS-T-4JEH7LpxUQzR3Rk1r0Hl0VnVuWjjqQ6hsPU9rpNITHXD-gz6XzBhlMJb3D4wS3wQWs6jr9-JoEU4XMOLzy7jc-fwDjIzn4ZHd4ePK8gukI6AcQplOeligHiY1DiEP1_dH5TtMO6xboeS1dI85Oqk8qooIrj2tC0SipWlorW-ZjFK1Hb0D1f9uIc8sBdvjDTbAyWsn5LMMrQwbeeDhBUdeiMQ0xkVaSFMzqsIiljQdWmhXDX_LVvR7ttAn8-PbTK2eAib1d3TIiuFVMY2BQZIHlFQ7xsVGlHiSPKf600so7S4XKinpm8mPuzOU4XIlBb4ozU5CHmWHbOj78x5L9qwLiQTjwxjNH1x9Phq6sq4aZcnvdv2UcvAReyEzz0rhmxrwTRDe298LFlO94TcAZMaezkNILVEtt4FUOKu6Q_a-QgkPwu4ZKqleY_ZIMDG1ihmYpo3MgeuTOqByQKHPE0gCtOm2b12iAUgC4_e-yUvgzxbM9YJdKJuFlZ91O0eMoLHScpxXszjErYDVMUPqBkgCvYmyC3Rdqddc9vrRHGfy-_yTLYy01Y5nSPuk0yp9UlU8vKRunRbWbPuV5zJETbQeX1ZsqOzRuAKnemL3D7SLtHFx_ZdmRlVnjaIHinQHSF3yYgROL9W_t57Un-4LJSAONtpYaNZV5gGnpBHuJAUXM1C6QGBfFuruRkJjnLaMQxKCyRgXyd6C1Ue3QrUhSFJqIp0-hVep6jeWs66dtNS16EHawWINvPM54Nz9Tequ7sYrr7JjLB9fWU_7dc_jvoyFz6Z2KmKI09hBPyum-ipAU7L-JZdA4ZRp3cuD-bY-8LVwU0H2MVYnI5fIBL9tmEOO56k7MhHPMo2NfQM_gdFfVlPjvbz3hoe2BimYX4jTfc66QNmKcRBJhdQqB6ovfPB0zeSMQnLxxmX3M1Oc8mTIeXROa75lPQEt0Lso5YoyaZwh9TNa6h2cGRVwXwdC9lLmZZJeG3IN8wOOmozxBH7Vh0pk0gaKlx0ywaODi8y-pV1I_j3xPM9alUyJIK28lgLzp1b-iJs-R8LRaW7iVLbCdlKahsi1P0VYWlSLWBfDJdmMF90jbuYfqEGFhusCqYTn7IFtVY2GvrtQURDALwTt1Qc-sveezWvXNAujemtCfTzwFRjTF0GAh0eGQpuEPvsiHreM3eD4IfJE8CXext_Zr5R8OEPHwstyqyfRA-QUEJSpVtn0HgSvRe075bg0m3nwvY9gHJhhWTRhaCJR9p1rV2xNlyHKm3urWSHZ9OoOmmlwqp46DCRHPx5tVAZbaYV-gno8MRpH-K9s1VVMLIMdSFNi_s_-wlk0pVv1_o-r13haCyJk4OHrcN0x4HLl8_uFQyFbD7GrSy9IvfF2aprrePkNGk_ki7Nmu80499mXWGdaPLJz0PBLgbHI0CDMIqGUQPyajRljySubyO0IK9R6LpQwNznmuMR9iziDp8N2XV0JjmZJGOgEMXI867lifOk7bFaB6iJrEKtbQkyxLB2EyIZ2XoAwJjtCAxFEUB9WTvCCND7fr8YBBql8WykVW2Fyo1bkFhdDgSUBQZG-eC-6yCiP-DrrkhyGmMNT1dn4gjKH_3-UVgwrvFuKK2BfFh4iSgN3pts1Qzj8CtHBzs6by8TIuToOIemM30II7o-Q5UwagEJ7szI59O6Y0vz2k_p0cwKVF6TBU4vA7HERB1zOiSbo8UQwUNpXN26mE9KrvkRDJ1jecSDQ0awVzLdjy_9Ck13GICtIbgUvu6SOLWOTQRnSOFjGgO3CZiI4DVxBMVYKJgqIshM4RhfuMTPudv5pmu9MPta1XnHUE8gnOjcL8HWzYMcN9EUEACEUlcnKRT8W-OmdT7AQzNmGQ06_6QhDez9fyInQeZzRMTBhFcteg3VkdS1HHamednh5-2vTdPu1jkmUIe3AhXe4d54FiUykonqAcAkrJmnocj22Unhmn-fXapqkHZurViXik4DTbMra6juN886zM4W905_VCUNzD5TtYfSDEkUkER6WXz50A06FHIWbxyC7Qs-4iQc3nXnqTzF8HGGVMjP4ntoHI3squy94kq-8FO_Ctl5V9zedb8xU6p1ksIS6u-d0pDZ_JF8Z2EEvNu4QzVZCiTti15CY55FNMeL85wQJaM84ZO85UnEt64lR1ObUpVKsdcGijJMsKg7RGdkUXd8MIAyYdzvqcPBFNjHbV9qThLGd0HGxus3NOLoXEyqyBYp_E4fLJ0prSUzTD747xbGWw-GvaLAZx-VjXbd1hnyDSG1uhQHd1ejfLWN43ZTPk6tD3cwInvC2dRW1Cp-9eXlvF-RCPg3sXf0wRmoOpevZmOa0ig-sT4ANEjbFweLsQgf66gHqb4-SmAuh1HNa2OIxKwtumkzXDdrCa59sh1bhzZ39vSzw6IHaMlaj646CktGJ-F1s2c45hpbQfNG5NTCcSBZUfFtXH3ECtOtk65x5Xm5vZdqOW0Kv5JvKjSwIIUyr2qqPrQlTK2cWkLJEUAS1VcCZvyt16pj0LtJNJi5vnPt00Yl2hTgRqnfGGAmsgkjgeZVv5-eV2u-pCoojEpbvmKONvqRzI73B1ogMPxSsDX7Yx03_4hxh-K2j2OVbi0uz1nYU8Yx06EZk6XugjuiPt1UOqw40qlyXxvc9drBansyLJMfQi3Uq_oBrWkNyeT501qq_XOwAPKwdzjg7kOJfx7WwatjfP2xNmvzbw_u__SsIrECdl5o12hi2-QTT-w2RTKzAZrmfd7GN0euVRq5bKCQIeJDp55yH69QApmm9WQKEYNcOZ0SQa785ZpRPyfRas3zbqB1hbZOpMpzsGtDB94bVVrdL25gNyAkQOTakVPYKCb3SBO9bkRbebTRhmzj4qY1mp5PbADoe9nwrOFOB7dwcLlK-H619p_Tj7mebTTdeiNXCxhMVlCSL3N5gtYUV76udX6YZw6fuJhUvN7D2aHBewaJj56XFH1Tynnp4VdyxI4U6bToDEcKajTSWGAd9VMBHie0eE8lrsFZbUbv2uSqpUpdgK65Aoa_3uW6yS_Ixoiv8k2WuyiHRdfieSBNykYykuAqX2vIXmmbmSIONC2eFGDYx5V3nGV-iiev191AgW4-4Leb1n2JCzQgB8II-rKSHIhSQI4YGR5j7p74_h2cbu96VJvSoRAkH6Onv582NwkhNS47ztCV7pICPLmaEF9muC54mXxaT3j_3TAfYQGnn_V8l3pKTOkS2QjxPYLjo9I3ZaK6gUsxVDYaGUp6ylNHBM2mpghrY3B-GOLSFJhMEiDaSK7H282cxIHiOrJGEbSsrraGhJwqV-eo50KN051ab1qOY5cj8t6CMAsxeS2Gw2P146inNF6koz1TFO4ja5EbwSWT9QbkgKvhJ-w8Sh6uIJzwRgAjfGk-IBASqVTL1-zmsTt0LelfAKVDLJj3KU-2fcLMEBaKJ8zIBcJ05eoqN8xeVqbzfYMC5QXoNEwsZy36sXZWaDXIC7Gc0ORgGGCbG0ADTzoM3r38aGStnQ5YxHm0Bp0Vc7wGndtty9zixDCzIqN-peUUqxLspJHhY-fWppmqdhsMGbW7YIxDs6GleYW7t-vV5_pE5yOtSerapCHtjHbPrI00GiipkenOIvKmBPsBT3168LdEKwyTGPmpQL_88Wdxb_ArdoCtP5JEZW7Ooe4pZq20eCvz3LE2fjVYzEwWYiTUmSjIqu0_nMeV60z4pN29CTMWMQYmvdnRg_IK9obBwENEfH1ly0L1Hua9UIYLsJLSCaYzeyBmV-VeGaJjSyrL_WAtb3uniR5IvX--OtyckkaAmbBxmFFNvrTcbZLj19K23dCiA9i7AVNbxxdXc4KZa9SmN29tgz1e5MIdPzxogJMgPCvvU0MHgKgPrm4Y86NXDjCH2cYsZnYxw_NRCbu43S3jZT6PFdsV10XMDIyBinGmX0e_jZ-af-1Aj_I_Uwlj-POVDsxQvPTyPry2ZodfUk5UorHOumNOULQt589RdFIL3Oa3WtBotwevsWBX0ZUAKxDxUI0v1j0fbyNjfjqVuFDoJ8zVLv_5VYlL1i_l0ij969AdKYPXbHu_XQhFcyqkCM4pKp9l5CcFcKQwgU2xpJll8A6w2-Czc2hWlXqaQPP4WocQHIS05da9usby75Dc2JIrlLh7othFqN32wBMgIWkQvCxtUuzQ07QTjye6IWydE9KzpJAGlqloAfDej8ntfybb1QvL8Bd0CdTPOTyygWxZqYVrdDoCY28RGeRuMoe90iy-0Qn4mtO6J1XbgCbZ8Vmgt-zrxFYuyov8AyMweA1ek3RqqVdyEcNkrDY_f5IbOHkw5Yv3f2tQsd-k595lICxVD9xihZTPW9XDCLh6GU0YV9PgRjaKPK3CwK0C1Nf8aFRjXEXS220ocJgopDEBEPP8YRBz2qqd9Z9epB9jiNPmcJ6srT0CaP3tN5hZXkmLsFjk-4AqHyqWslfgbI-uTLuqIlV-9B9OrRMwNfvz3uEwDKM0aO1ttXB1_YHQA6ZJY5AN1Wk_J6hw98FL8pxV19TioKwOjsIzFjeIYKLIEwuwXyc5OBssqKCat1OWQVQ8x4A0sTkvnfVcFe8HwS81clrHisrvq-_AlUq_aHihRLS_yXtqpNkWQ0fHzMbA2G6AzF8KSDIny1A9B-CnxQPLUGicXUADhWtnd8Y3ifSvWDWCp0F8u-PDM_8oLqw2qCgAORKJLyQI8cIiyuIHk6L7ivwtGrLQfkYAqBTRMNXtz_gmm8-9RxhntjmHbgdH6CZZyl4TQuXb6SVWS1d0ITo_pfYha-LrX4pn5zpIF3KCGOUeieHF9KCC4KcmEc9Z0t65udd-OeaqWGt1Oc6_zY-NpuXC9QmASIwIF20sOMZwEQvb-R2OBA9sf1QrOIteQGo47vIANPfBNOUWyPIV2B6rcjGHQGzlBcSzenQ7JFLKw7gc873jLpLao4-LluAMN0T50w0txRoj4YyghYAfrfmSi-FooP9AYIN_OMvkDclmaALmrWbCwATTS0bG1-PvzO7uETjr21gur4d8f_AdY9mQ36dek0B34dw8Yw2Iuay4AX6N0RpnUNzqFwJyPPkwC7oiIAMku_0VCYGBiKcpTkygaMkTZdRa2OdaQtW_r2cevL3dEJ8dL9uf3qL0zoqTn7lhtmTBzAUL64So_9akMnYQ4_tqI62qvWUtgsTA4bvEgnFLKqUqd5G_XpdTdGEfsH4ez6HgaLMzPHdiumYl3IozNB28czs_BBYfqMfnjn46vJVtWt2Mjyl_LR3nbFXFgtSndJ2Duu_0kROcG7AQ7zSezu-P9Ip0PE8JlkE2NWrFcnvcq1HgsDMSQYOhVlgzS8HPuT7kRkKpUSfT_Ve1HPCDXq4JUFu993ZbVrAP4h9iihseDVBIflH9yBgxXEkVySoOoW00PNRjCsP6LHgke0KzZ0flVeK8m_XOnp4U0PwiAH1qwP75IZVtk-F3nWg7u8rznkQWywMNP1NBSGmQpwOgZKarOMSxJ3XPrqdutGMBLJ4iCrgNv7QDttP6rGBKM63byLaryJ1eCV2ub_GeFMuRExl4KLF42Re7dIrVDzvUN9EjSdLz-F0mpCwaz8KmFj5anj5ATsGkLC8xUcS3W_BWW-_rvixQsT1oxhX6iSb6jPxVc7yMZCUfzoCX2pbD4EjD1VHz-g6NshTLwn8vhf-9kgiizuwVx69Aelz9Ui9IOYmbOK1HcRGDwBoL4y-n4TL4pIvr1lBJ-eXNvM_gZ0LMsoreb7tlmCro05svYqwV8llliVyQ2QlEpLQO8XczEM2AXyyH7Bk_hUoj_8LmZ_E919QKgn-FNGTyOYQEfhUwTIqHxRkoiMjKxtjV_8NX0Ru8asYykNKNl9uGBHpfyY0Q8XvuRu5thvS99LURttMn4bLUT8nERwn_9E-9rsi06Hl0Umozx0XJa35BulCat1jmsmIvGqN7l_WQwb2xT6aG1vBYsV0Bst9MGmiYQtr0_B6fSN8jzANzCBvgsoMcKdRmXUSbSAm3mhTbgVd6FpFvjzyyIJU4cIV4LMZNPIFOHLFWejPLpfpGPnSN3X7iqO9mfXWqbkuCRUmIJ6yRtWQNLwZApLWawD7zKJTnSjtGr0l44REHWA-ggdZAtyQvIxk1xFUNzaYIY_bInrhzJBMh5nAMCtl9LYntJPJqeNVLEDemW6I6gIP2WhR2o9VdxFceCY4agVeyPj_ABjjQJUd2sKN5BxDSTErDEsDnKqXoE8nNUrxhDpptJylyed6nOF5TW0Kx44s0C6HS9Hf6OB5OKhOqqwyxf_qBZKAisI2tA39w87ebcdDdFaKPNDMNmfc4L_DlZmY7ZQV8BOkvs-rvYFE2jGqzfz8WGFiUtRPgGoCNzlJ7O6zs_jG6iz_5Bb2E3raUyRoerTa-WJv27MFylFy3BZEcYwlFLTbhyYC3FzWCV1Bu4vkIxMVwrspReDodAo8Re7bBqcj1kR8KcojIU3wrTN_JJjfVJ-W8hYUW2EGpXalusC9I9uhwSm9oIqJ5WCBXCBhS5GRxwcu0PZOTkO5rCJlsXrZ0m9-ESRVOBS6hsPX4cNu6O1V5-zXaH_5cXTEOqPlj6QhsEYzxOu7MMj57jno7H5RrMxekewHpV65h6-O61coQ8E75Vm7nFeYKuwKIlQEujYN8nZDcpuadgJA7F0xuj-mJ2yPfc5gNaFV6qk1fZX87fec8vLcVuZZ72T8FrdU4AbXs-KhtQavhpiZa6SkRMgj6eiPtg2anDHA-Ok11gHgoT4Ef7KJsXngvlSsiS6Ff2XxOlVQL9_lec0yanTq-fWRQfCs6n15-BwGPyIjL4EuUyboDcSl3YzOUCAqcW5uYgn338Yz2rJucGpgmtqM9fve4d_3GAtaN9tnFV4vdKVgSn6gIeZiqlwQe4yzXszGwmGq10rMa0IkO5bhGmtN5FcQahRkgCuERHIu3F5P9x0B3vcAiuMjuYweC6OpN41DfVo0N1uF06junDZRvjf4zY0wpl6FFbkI-LrgT4xl4P3Ky2JWQSkRbkBGiEiRfE0sTNteL5wAoswSeKyYc8Pb4qlVfdEo3pHEJDbpaowXSF46DpFKVvGdOCBLMF5YrYXixlrrZxJBgxU49IRc1hOgmF4CT-lTSnvlbdhYzsx_le98n9vuZ5rbiPwsi1c7N5-IDcWzdOVZj3mQvuQHmnPaN_wXnHPmbT1WHTtgILqaYZvBRd4GmCIEsUH3GkyIZVAxN_lp4czoS0OQubj2qhuYw_pVhm6gjg6-Qd8KD1B8jwz8vgLVyFC1S99KeG2xwQxjm-3HUSx3gy-4Py6pZELBB2MshewyYGJy2haVLopL8YOArplb6Sgbzbw73huh9cnLX51gs4hZ9uS4NtwKFJikUCWRzjBwC2MSJazEHoPJRWBPBGPCjsfuhlNcNAyuLR0GwvRSwePVLx9SsKqNYqQLc51Ci7aohl9q6qXOI8vsf3n3QC8LUV2wRjYi_Ph2YQn0Obwuq0Oe1YAd85C85Cud7XLtP33gX2A6B0wKhEUsvzBSeHhmFqDWYBjc0VnB_Rp0ue0sBGWMMrkxqnEZX2ETdLVOgLPtFeiNbGFb2R6zTzk3HB05-Y8ZXRIgJbVCUyJKZJ-DXoJCE0WIlXnfsqwQgfNyEz4j6HZ5r1JcNMXneiYMJ9teh2qWYH_NEBUrocb9_W4rITejOh62VnZPXOyCDOPCR6WOwe7rupN6tMTU3MXSjsZkY-whIiQPbZmVvkJrf_ZV-Ny0a8SyuHCu1vD96hmC4Ecutfa0A0OOJTB-610Yp0mr5R-LN1h3NVpV09tGEUR_nmUAv3ECrwJ65GN5Z4MnwmjGU37i_-kH-0ZIfZUYfqJd05_HhH41_T5EwgEUX3lCMM9W5XL56yOi8hjwDKqNJc_mRixwv0_ggAsHqyTsHfd-ZpeIxpsa7QITFwZPh0i7kYYyd-_iTrZoRr_KIQ__dpNW09ecWRzWicBOr2quWXawINRyhyWJRDkDOwAbfb_V7Gr19mDrdN_nChgu6CQFN_e0t4D5GwFS82fKUQNfREAolKI2D4ZxSCS4H_pS-ga0BOi_prdI62vzxGGyo0Imw-mbG24D3aoFSsG3av3RQOdPWrn_V58AZCI9ZVLOlL9Faq1wZ49z5-Ub7ebzWo6xT7tcYBLJJw7HAwP4hRvCfai0Go0M50qNaUwlAEN9ajgk1c-6SV1ck4LZdY8zhIXERuclHWchl9qehk22g_kXb45xV8rQkS7mnSHPKv4K4IfcAYXpawvpTstzx0Vk_3Y1doiZRFtZmngfQmue2uIeA1YJetI3HkiyMzJECfMBe0cKdd5x2-iB6CDLnhBiVhbjG-z13l-8GASF2u7J94ExX3GrIJHs8JRzAIQDq1ASE8iKCvD9f7dDnkCmMQtOIHhbsjAWxNeryLJqZkbSZ7l-PrVQPFau_ta7WnOMCstmBlPrQ0YcJMed8ume4QofRBZ|regm\\\\\\",\\\\\\"waterfall_id\\\\\\":\\\\\\"d6031628-57e9-4414-93ad-9911cf738e0b\\\\\\",\\\\\\"INTERNAL__latency_qpl_instance_id\\\\\\":1.31635346000265E14,\\\\\\"flow_info\\\\\\":\\\\\\"{\\\\\\\\\\\\\\"flow_name\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"new_to_family_ig_default\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"flow_type\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"ntf\\\\\\\\\\\\\\"}\\\\\\",\\\\\\"is_platform_login\\\\\\":0,\\\\\\"INTERNAL__latency_qpl_marker_id\\\\\\":36707139,\\\\\\"reg_info\\\\\\":\\\\\\"{\\\\\\\\\\\\\\"first_name\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"last_name\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"full_name\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"contactpoint\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"e70375344\\\\\\\\\\\\\\\\u0040gmail.com\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"ar_contactpoint\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"contactpoint_type\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"email\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"is_using_unified_cp\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"unified_cp_screen_variant\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"control\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"is_cp_auto_confirmed\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"is_cp_auto_confirmable\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"is_cp_claimed\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"confirmation_code\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"HLhN6nli\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"birthday\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"birthday_derived_from_age\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"age_range\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"did_use_age\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"os_shared_age_range\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"gender\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"use_custom_gender\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"custom_gender\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"encrypted_password\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"#PWD_INSTAGRAM:4:1769035008:AZ5ExDXjM1ZLdM2rMGUAAVPBP\\\\\\\\\\\\\\\\/IsjHJHTphEA\\\\\\\\\\\\\\\\/Iam7dV4U+CpYwbFzkSnyJ5xrOgk0pnBnN5Qd8FN2qviVQTSHUAIkcg2J2Zc0xFq7\\\\\\\\\\\\\\\\/lE+e4pDSze1c9WOk8rW2YpfIskC7yxjUw3dEYE2BGqJeNLzNYNs435LEIE4ar8t7iTwTS2oWb2UkZ\\\\\\\\\\\\\\\\/nWma7wCS0GwR+\\\\\\\\\\\\\\\\/S5HZtpcSvM6ZUxBKwu75OmUM\\\\\\\\\\\\\\\\/3wrCnWSQ0ZcJpbdTmbvE+sE+Yh+\\\\\\\\\\\\\\\\/ROr\\\\\\\\\\\\\\\\/Unte8z5rn9nGKU5Jx8pi6I7wpH0YlZJPAIVi7qqk\\\\\\\\\\\\\\\\/N18aLUGIwYCY8xTO49ogv+nRCoOSIu72A\\\\\\\\\\\\\\\\/IXdAc+A\\\\\\\\\\\\\\\\/druvNvDluMsgyLJAyyeo4L+QW\\\\\\\\\\\\\\\\/OrY5HOVRkeflqunwyNZMkPTfDOWgGtgA0LCvnFrEso=\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"username\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"username_prefill\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"fb_conf_source\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"device_id\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"android-f35f126bc4795e76\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"ig4a_qe_device_id\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"c734a1c7-d663-4fad-af07-817b064e424b\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"family_device_id\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"dd5b9513-0be3-4263-9106-459e51268b46\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"user_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"safetynet_token\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"ZTcwMzc1MzQ0QGdtYWlsLmNvbXwxNzY5MDM0OTM5fBWut2xb6bRZ8ZphWFhqT9knoNB2hgkyHg==\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"skip_slow_rel_check\\\\\\\\\\\\\\":true,\\\\\\\\\\\\\\"safetynet_response\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"API_ERROR: class com.google.android.gms.common.api.ApiException:7: \\\\\\\\\\\\\\",\\\\\\\\\\\\\\"machine_id\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"h1NxaVnaYULGGzgpCn_hPfVP\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"profile_photo\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"profile_photo_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"profile_photo_upload_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"avatar\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"email_oauth_token_no_contact_perm\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"email_oauth_token\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"email_oauth_tokens\\\\\\\\\\\\\\":[],\\\\\\\\\\\\\\"sign_in_with_google_email\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"should_skip_two_step_conf\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"openid_tokens_for_testing\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"encrypted_msisdn\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"encrypted_msisdn_for_safetynet\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"cached_headers_safetynet_info\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"should_skip_headers_safetynet\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"headers_last_infra_flow_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"headers_last_infra_flow_id_safetynet\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"headers_flow_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"was_headers_prefill_available\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"sso_enabled\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"existing_accounts\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"used_ig_birthday\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"create_new_to_app_account\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"skip_session_info\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"ck_error\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"ck_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"ck_nonce\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"should_save_password\\\\\\\\\\\\\\":true,\\\\\\\\\\\\\\"fb_access_token\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"is_msplit_reg\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"is_spectra_reg\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"dema_account_consent_given\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"spectra_reg_token\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"spectra_reg_guardian_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"spectra_reg_guardian_logged_in_context\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"user_id_of_msplit_creator\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"msplit_creator_nonce\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"dma_data_combination_consent_given\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"xapp_accounts\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"fb_device_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"fb_machine_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"ig_device_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"ig_machine_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"should_skip_nta_upsell\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"big_blue_token\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"caa_reg_flow_source\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"login_home_native_integration_point\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"ig_authorization_token\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"full_sheet_flow\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"crypted_user_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"is_caa_perf_enabled\\\\\\\\\\\\\\":true,\\\\\\\\\\\\\\"is_preform\\\\\\\\\\\\\\":true,\\\\\\\\\\\\\\"should_show_rel_error\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"ignore_suma_check\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"dismissed_login_upsell_with_cna\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"ignore_existing_login\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"ignore_existing_login_from_suma\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"ignore_existing_login_after_errors\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"suggested_first_name\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"suggested_last_name\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"suggested_full_name\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"frl_authorization_token\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"post_form_errors\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"skip_step_without_errors\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"existing_account_exact_match_checked\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"existing_account_fuzzy_match_checked\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"email_oauth_exists\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"confirmation_code_send_error\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"is_too_young\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"source_account_type\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"whatsapp_installed_on_client\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"confirmation_medium\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"source_credentials_type\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"source_cuid\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"source_account_reg_info\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"soap_creation_source\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"source_account_type_to_reg_info\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"registration_flow_id\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"2bfd5926-c03f-48eb-8e17-a98ed947592c\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"should_skip_youth_tos\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"is_youth_regulation_flow_complete\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"is_on_cold_start\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"email_prefilled\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"cp_confirmed_by_auto_conf\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"in_sowa_experiment\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"youth_regulation_config\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"conf_allow_back_nav_after_change_cp\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"conf_bouncing_cliff_screen_type\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"conf_show_bouncing_cliff\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"eligible_to_flash_call_in_ig4a\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"eligible_to_mo_sms_in_ig4a\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"mo_sms_ent_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"flash_call_permissions_status\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"attestation_result\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"request_data_and_challenge_nonce_string\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"confirmed_cp_and_code\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"notification_callback_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"reg_suma_state\\\\\\\\\\\\\\":0,\\\\\\\\\\\\\\"is_msplit_neutral_choice\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"msg_previous_cp\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"ntp_import_source_info\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"youth_consent_decision_time\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"should_show_spi_before_conf\\\\\\\\\\\\\\":true,\\\\\\\\\\\\\\"google_oauth_account\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"is_reg_request_from_ig_suma\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"is_toa_reg\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"is_threads_public\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"spc_import_flow\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"caa_play_integrity_attestation_result\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"client_known_key_hash\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"flash_call_provider\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"spc_birthday_input\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"failed_birthday_year_count\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"user_presented_medium_source\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"user_opted_out_of_ntp\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"is_from_registration_reminder\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"show_youth_reg_in_ig_spc\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"fb_suma_is_high_confidence\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"screen_visited\\\\\\\\\\\\\\":[\\\\\\\\\\\\\\"CAA_REG_CONTACT_POINT_PHONE\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"CAA_REG_CONTACT_POINT_EMAIL\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"CAA_REG_CONFIRMATION_SCREEN\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"CAA_REG_PASSWORD\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"bloks.caa.reg.birthday\\\\\\\\\\\\\\"],\\\\\\\\\\\\\\"fb_email_login_upsell_skip_suma_post_tos\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"fb_suma_is_from_email_login_upsell\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"fb_suma_is_from_phone_login_upsell\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"should_prefill_cp_in_ar\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"ig_partially_created_account_user_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"ig_partially_created_account_nonce\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"ig_partially_created_account_nonce_expiry\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"force_sessionless_nux_experience\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"has_seen_suma_landing_page_pre_conf\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"has_seen_suma_candidate_page_pre_conf\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"suma_on_conf_threshold\\\\\\\\\\\\\\":-1,\\\\\\\\\\\\\\"move_suma_to_cp_variant\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"control\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"pp_to_nux_eligible\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"should_show_error_msg\\\\\\\\\\\\\\":true,\\\\\\\\\\\\\\"th_profile_photo_token\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"attempted_silent_auth_in_fb\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"attempted_silent_auth_in_ig\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"cp_suma_results_map\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"source_username\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"next_uri\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"should_use_next_uri\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"linking_entry_point\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"fb_encrypted_partial_new_account_properties\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"starter_pack_name\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"starter_pack_creator_user_ids\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"wa_data_bundle\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"bloks_controller_source\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"airwave_registration_code\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"is_sessionless_nux\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"login_contactpoint\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"login_contactpoint_type\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"is_nta_shortened\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"should_show_bday_after_name_suggestions\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"should_override_back_nav\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"ig_footer_variant\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"control\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"device_network_info\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"is_from_web_lite_reg_controller\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"login_form_siwg_email\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"account_setup_waterfall_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"is_wanted_suma_user\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"device_zero_balance_state\\\\\\\\\\\\\\":null}\\\\\\",\\\\\\"family_device_id\\\\\\":\\\\\\"dd5b9513-0be3-4263-9106-459e51268b46\\\\\\",\\\\\\"offline_experiment_group\\\\\\":\\\\\\"caa_iteration_v3_perf_ig_4\\\\\\",\\\\\\"access_flow_version\\\\\\":\\\\\\"pre_mt_behavior\\\\\\",\\\\\\"is_from_logged_in_switcher\\\\\\":0,\\\\\\"current_step\\\\\\":6,\\\\\\"qe_device_id\\\\\\":\\\\\\"c734a1c7-d663-4fad-af07-817b064e424b\\\\\\"}}\\"}","bloks_versioning_id":"b7737193b91c3a2f4050bdfc9d9ae0f578a93b4181fd43efe549daacba5c7db9","infra_params":{"device_id":"c734a1c7-d663-4fad-af07-817b064e424b"},"app_id":"com.bloks.www.bloks.caa.reg.birthday.async"},"bk_context":{"is_flipper_enabled":false,"theme_params":[],"debug_tooling_metadata_token":null}}',
}

response = requests.post(
    "https://b.i.instagram.com/graphql_www",
    headers=headers,
    data=data,
    verify=False,
)

write_response(response, os.path.dirname(__file__))


def get_birth_body(data: RegistrationData):
    reg_info = {
        "first_name": None,
        "last_name": None,
        "full_name": None,
        "contactpoint": data.email,
        "ar_contactpoint": None,
        "contactpoint_type": "email",
        "is_using_unified_cp": False,
        "unified_cp_screen_variant": "control",
        "is_cp_auto_confirmed": False,
        "is_cp_auto_confirmable": False,
        "is_cp_claimed": False,
        "confirmation_code": "HLhN6nli",
        "birthday": None,
        "birthday_derived_from_age": None,
        "age_range": None,
        "did_use_age": False,
        "os_shared_age_range": None,
        "gender": None,
        "use_custom_gender": False,
        "custom_gender": None,
        "encrypted_password": data.encrypted_password,
        "username": None,
        "username_prefill": None,
        "fb_conf_source": None,
        "device_id": data.android_id,
        "ig4a_qe_device_id": data.device_id,
        "family_device_id": data.family_device_id,
        "user_id": None,
        "safetynet_token": "ZTcwMzc1MzQ0QGdtYWlsLmNvbXwxNzY5MDM0OTM5fBWut2xb6bRZ8ZphWFhqT9knoNB2hgkyHg==",  ### check for this safetynet token on mobile
        "skip_slow_rel_check": True,
        "safetynet_response": "API_ERROR: class com.google.android.gms.common.api.ApiException:7: ",
        "machine_id": "h1NxaVnaYULGGzgpCn_hPfVP",
        "profile_photo": None,
        "profile_photo_id": None,
        "profile_photo_upload_id": None,
        "avatar": None,
        "email_oauth_token_no_contact_perm": None,
        "email_oauth_token": None,
        "email_oauth_tokens": [],
        "sign_in_with_google_email": None,
        "should_skip_two_step_conf": None,
        "openid_tokens_for_testing": None,
        "encrypted_msisdn": None,
        "encrypted_msisdn_for_safetynet": None,
        "cached_headers_safetynet_info": None,
        "should_skip_headers_safetynet": None,
        "headers_last_infra_flow_id": None,
        "headers_last_infra_flow_id_safetynet": None,
        "headers_flow_id": None,
        "was_headers_prefill_available": None,
        "sso_enabled": None,
        "existing_accounts": None,
        "used_ig_birthday": None,
        "create_new_to_app_account": None,
        "skip_session_info": None,
        "ck_error": None,
        "ck_id": None,
        "ck_nonce": None,
        "should_save_password": True,
        "fb_access_token": None,
        "is_msplit_reg": None,
        "is_spectra_reg": None,
        "dema_account_consent_given": None,
        "spectra_reg_token": None,
        "spectra_reg_guardian_id": None,
        "spectra_reg_guardian_logged_in_context": None,
        "user_id_of_msplit_creator": None,
        "msplit_creator_nonce": None,
        "dma_data_combination_consent_given": None,
        "xapp_accounts": None,
        "fb_device_id": None,
        "fb_machine_id": None,
        "ig_device_id": None,
        "ig_machine_id": None,
        "should_skip_nta_upsell": None,
        "big_blue_token": None,
        "caa_reg_flow_source": "login_home_native_integration_point",
        "ig_authorization_token": None,
        "full_sheet_flow": False,
        "crypted_user_id": None,
        "is_caa_perf_enabled": True,
        "is_preform": True,
        "should_show_rel_error": False,
        "ignore_suma_check": False,
        "dismissed_login_upsell_with_cna": False,
        "ignore_existing_login": False,
        "ignore_existing_login_from_suma": False,
        "ignore_existing_login_after_errors": False,
        "suggested_first_name": None,
        "suggested_last_name": None,
        "suggested_full_name": None,
        "frl_authorization_token": None,
        "post_form_errors": None,
        "skip_step_without_errors": False,
        "existing_account_exact_match_checked": False,
        "existing_account_fuzzy_match_checked": False,
        "email_oauth_exists": False,
        "confirmation_code_send_error": None,
        "is_too_young": False,
        "source_account_type": None,
        "whatsapp_installed_on_client": False,
        "confirmation_medium": None,
        "source_credentials_type": None,
        "source_cuid": None,
        "source_account_reg_info": None,
        "soap_creation_source": None,
        "source_account_type_to_reg_info": None,
        "registration_flow_id": data.registration_flow_id,
        "should_skip_youth_tos": False,
        "is_youth_regulation_flow_complete": False,
        "is_on_cold_start": False,
        "email_prefilled": False,
        "cp_confirmed_by_auto_conf": False,
        "in_sowa_experiment": False,
        "youth_regulation_config": None,
        "conf_allow_back_nav_after_change_cp": None,
        "conf_bouncing_cliff_screen_type": None,
        "conf_show_bouncing_cliff": None,
        "eligible_to_flash_call_in_ig4a": False,
        "eligible_to_mo_sms_in_ig4a": False,
        "mo_sms_ent_id": None,
        "flash_call_permissions_status": None,
        "attestation_result": None,
        "request_data_and_challenge_nonce_string": None,
        "confirmed_cp_and_code": None,
        "notification_callback_id": None,
        "reg_suma_state": 0,
        "is_msplit_neutral_choice": False,
        "msg_previous_cp": None,
        "ntp_import_source_info": None,
        "youth_consent_decision_time": None,
        "should_show_spi_before_conf": True,
        "google_oauth_account": None,
        "is_reg_request_from_ig_suma": False,
        "is_toa_reg": False,
        "is_threads_public": False,
        "spc_import_flow": False,
        "caa_play_integrity_attestation_result": None,
        "client_known_key_hash": None,
        "flash_call_provider": None,
        "spc_birthday_input": False,
        "failed_birthday_year_count": None,
        "user_presented_medium_source": None,
        "user_opted_out_of_ntp": None,
        "is_from_registration_reminder": False,
        "show_youth_reg_in_ig_spc": False,
        "fb_suma_is_high_confidence": None,
        "screen_visited": [
            "CAA_REG_CONTACT_POINT_PHONE",
            "CAA_REG_CONTACT_POINT_EMAIL",
            "CAA_REG_CONFIRMATION_SCREEN",
            "CAA_REG_PASSWORD",
            "bloks.caa.reg.birthday",
        ],
        "fb_email_login_upsell_skip_suma_post_tos": False,
        "fb_suma_is_from_email_login_upsell": False,
        "fb_suma_is_from_phone_login_upsell": False,
        "should_prefill_cp_in_ar": None,
        "ig_partially_created_account_user_id": None,
        "ig_partially_created_account_nonce": None,
        "ig_partially_created_account_nonce_expiry": None,
        "force_sessionless_nux_experience": False,
        "has_seen_suma_landing_page_pre_conf": False,
        "has_seen_suma_candidate_page_pre_conf": False,
        "suma_on_conf_threshold": -1,
        "move_suma_to_cp_variant": "control",
        "pp_to_nux_eligible": False,
        "should_show_error_msg": True,
        "th_profile_photo_token": None,
        "attempted_silent_auth_in_fb": False,
        "attempted_silent_auth_in_ig": False,
        "cp_suma_results_map": None,
        "source_username": None,
        "next_uri": None,
        "should_use_next_uri": None,
        "linking_entry_point": None,
        "fb_encrypted_partial_new_account_properties": None,
        "starter_pack_name": None,
        "starter_pack_creator_user_ids": None,
        "wa_data_bundle": None,
        "bloks_controller_source": None,
        "airwave_registration_code": None,
        "is_sessionless_nux": None,
        "login_contactpoint": None,
        "login_contactpoint_type": None,
        "is_nta_shortened": False,
        "should_show_bday_after_name_suggestions": None,
        "should_override_back_nav": False,
        "ig_footer_variant": "control",
        "device_network_info": None,
        "is_from_web_lite_reg_controller": None,
        "login_form_siwg_email": None,
        "account_setup_waterfall_id": None,
        "is_wanted_suma_user": False,
        "device_zero_balance_state": None,
    }
    variables = {
        "client_input_params": {
            "client_timezone": "Europe/Kiev",
            "aac": '{"aac_init_timestamp":'
            + utils.get_pigeon_raw_client_time().spit(".")[0]
            + ',"aacjid":"'
            + data.aacjid
            + '"}',
            "birthday_or_current_date_string": data.birth_date,
            "os_age_range": "",
            "birthday_timestamp": 727655810,
            "lois_settings": {"lois_token": ""},
            "zero_balance_state": "",
            "network_bssid": None,
            "should_skip_youth_tos": 0,
            "is_youth_regulation_flow_complete": 0,
        },
        "server_params": {
            "is_from_logged_out": 0,
            "layered_homepage_experiment_group": "ld_no_language_selector",
            "device_id": data.android_id,
            # from password_creation_request
            "reg_context": "AVitCNVb6u6KaI0w_ThwbgIQlEfF4gCl-nk1FRnFhOHOo8HHbhNMVLYr36eF0uZWAR5FnEPOUcMWEmkxp3-V7SFuje51DMyWIezyRUEULtYfyLGRfaSsX1DAMhhVCkffJ4kz3b3EtJFcBVpEjtSUDoT6XgfrEIA51qJwa0pS7Wb6jddUpnksVP_S663qfgEeImbZOPWdTflweZgVxf95_w8xdPom04N_oAC3wiSA1Iqlvgfyl994dcKG63QytMAZJChWFW3jDpZXukzxH018M4XUE8yxGpDymAzNp362mWdG9gtBkcBJQ6H9aQLISpv32QsBnXUh5eEbWIh08JRlUXVHgbNaIP50YNck9zC-7CxQFMVrpo-A9acXvzNglblSkEjHiNPsYJz7oyl1qEVouBGvB0eW0eYbAsJDASe3vwrJxcaokr96L667_28fOVBz3fFJPEAW08DMrIZnaGMF6vvaZoS50GkupkzHsMjsiYfawl74FrQjZOf3OPJhCe5z6IcHKmohaJsIOR4FMfK3X-LjvY9mY_JTSTcYE7PpcZQmwCG88_K07Gdrv9wON-kySDQwogGdckbJUOa6qlbyKzp-OTNgasr51yX37ErnvLrImYedptypgVd_PsDvCieVN49C0edn_Lsk59z0bmBqwOKy2wU_Dxls64ABtSjRJXPhP7SIb2vR47A4JVHVzgrcvkp2psJs_yI2AO4QAgcwp0J-AOfT8JLAMb1Rqpn4Ehip5L_ZfiURk3jiHUFmcrJ8QmpF0yeKZxIjEMYANKFuDi5BnNtHFeCI2LpmqlnBMABHql_y-i8wzQR1C_kXS5hiu2lTt7RkPEG_P-QYNExBD-8ajAdrAqtMoEQl2_EsitaVF7Err-bsFuFvfvZ_ZUClv0R5WeLtlipOlZRKBoxozlcRSubn2hGTPK_YWcPnmIY65AWHqJZi-YE3yKVM0Ke5sh1MYBYBGGyahdk4BWTJO6pf61ePvVtg8Cy1bAELmCxbIVbeZzjG1ENzybJ3JsuOzmrE0zH1WrM5wTyO9ekwa1tsAWXRXEcaPEeu_TZxK9t4YTW5aEkizCPNai2pAC75YA9paRbsaVLe5p8plnU78N4SZmVWnIwUeqo0_KYD9fSTx3UhZzUEEuZu_x9R5fqJ5h4DOwGcx541NdirnnfiTORUsSYNvZb1SnINJnGUQxzkoNCBqPqiynTjDmLzAV29sQuyPzo_PbTH2xS-T-4JEH7LpxUQzR3Rk1r0Hl0VnVuWjjqQ6hsPU9rpNITHXD-gz6XzBhlMJb3D4wS3wQWs6jr9-JoEU4XMOLzy7jc-fwDjIzn4ZHd4ePK8gukI6AcQplOeligHiY1DiEP1_dH5TtMO6xboeS1dI85Oqk8qooIrj2tC0SipWlorW-ZjFK1Hb0D1f9uIc8sBdvjDTbAyWsn5LMMrQwbeeDhBUdeiMQ0xkVaSFMzqsIiljQdWmhXDX_LVvR7ttAn8-PbTK2eAib1d3TIiuFVMY2BQZIHlFQ7xsVGlHiSPKf600so7S4XKinpm8mPuzOU4XIlBb4ozU5CHmWHbOj78x5L9qwLiQTjwxjNH1x9Phq6sq4aZcnvdv2UcvAReyEzz0rhmxrwTRDe298LFlO94TcAZMaezkNILVEtt4FUOKu6Q_a-QgkPwu4ZKqleY_ZIMDG1ihmYpo3MgeuTOqByQKHPE0gCtOm2b12iAUgC4_e-yUvgzxbM9YJdKJuFlZ91O0eMoLHScpxXszjErYDVMUPqBkgCvYmyC3Rdqddc9vrRHGfy-_yTLYy01Y5nSPuk0yp9UlU8vKRunRbWbPuV5zJETbQeX1ZsqOzRuAKnemL3D7SLtHFx_ZdmRlVnjaIHinQHSF3yYgROL9W_t57Un-4LJSAONtpYaNZV5gGnpBHuJAUXM1C6QGBfFuruRkJjnLaMQxKCyRgXyd6C1Ue3QrUhSFJqIp0-hVep6jeWs66dtNS16EHawWINvPM54Nz9Tequ7sYrr7JjLB9fWU_7dc_jvoyFz6Z2KmKI09hBPyum-ipAU7L-JZdA4ZRp3cuD-bY-8LVwU0H2MVYnI5fIBL9tmEOO56k7MhHPMo2NfQM_gdFfVlPjvbz3hoe2BimYX4jTfc66QNmKcRBJhdQqB6ovfPB0zeSMQnLxxmX3M1Oc8mTIeXROa75lPQEt0Lso5YoyaZwh9TNa6h2cGRVwXwdC9lLmZZJeG3IN8wOOmozxBH7Vh0pk0gaKlx0ywaODi8y-pV1I_j3xPM9alUyJIK28lgLzp1b-iJs-R8LRaW7iVLbCdlKahsi1P0VYWlSLWBfDJdmMF90jbuYfqEGFhusCqYTn7IFtVY2GvrtQURDALwTt1Qc-sveezWvXNAujemtCfTzwFRjTF0GAh0eGQpuEPvsiHreM3eD4IfJE8CXext_Zr5R8OEPHwstyqyfRA-QUEJSpVtn0HgSvRe075bg0m3nwvY9gHJhhWTRhaCJR9p1rV2xNlyHKm3urWSHZ9OoOmmlwqp46DCRHPx5tVAZbaYV-gno8MRpH-K9s1VVMLIMdSFNi_s_-wlk0pVv1_o-r13haCyJk4OHrcN0x4HLl8_uFQyFbD7GrSy9IvfF2aprrePkNGk_ki7Nmu80499mXWGdaPLJz0PBLgbHI0CDMIqGUQPyajRljySubyO0IK9R6LpQwNznmuMR9iziDp8N2XV0JjmZJGOgEMXI867lifOk7bFaB6iJrEKtbQkyxLB2EyIZ2XoAwJjtCAxFEUB9WTvCCND7fr8YBBql8WykVW2Fyo1bkFhdDgSUBQZG-eC-6yCiP-DrrkhyGmMNT1dn4gjKH_3-UVgwrvFuKK2BfFh4iSgN3pts1Qzj8CtHBzs6by8TIuToOIemM30II7o-Q5UwagEJ7szI59O6Y0vz2k_p0cwKVF6TBU4vA7HERB1zOiSbo8UQwUNpXN26mE9KrvkRDJ1jecSDQ0awVzLdjy_9Ck13GICtIbgUvu6SOLWOTQRnSOFjGgO3CZiI4DVxBMVYKJgqIshM4RhfuMTPudv5pmu9MPta1XnHUE8gnOjcL8HWzYMcN9EUEACEUlcnKRT8W-OmdT7AQzNmGQ06_6QhDez9fyInQeZzRMTBhFcteg3VkdS1HHamednh5-2vTdPu1jkmUIe3AhXe4d54FiUykonqAcAkrJmnocj22Unhmn-fXapqkHZurViXik4DTbMra6juN886zM4W905_VCUNzD5TtYfSDEkUkER6WXz50A06FHIWbxyC7Qs-4iQc3nXnqTzF8HGGVMjP4ntoHI3squy94kq-8FO_Ctl5V9zedb8xU6p1ksIS6u-d0pDZ_JF8Z2EEvNu4QzVZCiTti15CY55FNMeL85wQJaM84ZO85UnEt64lR1ObUpVKsdcGijJMsKg7RGdkUXd8MIAyYdzvqcPBFNjHbV9qThLGd0HGxus3NOLoXEyqyBYp_E4fLJ0prSUzTD747xbGWw-GvaLAZx-VjXbd1hnyDSG1uhQHd1ejfLWN43ZTPk6tD3cwInvC2dRW1Cp-9eXlvF-RCPg3sXf0wRmoOpevZmOa0ig-sT4ANEjbFweLsQgf66gHqb4-SmAuh1HNa2OIxKwtumkzXDdrCa59sh1bhzZ39vSzw6IHaMlaj646CktGJ-F1s2c45hpbQfNG5NTCcSBZUfFtXH3ECtOtk65x5Xm5vZdqOW0Kv5JvKjSwIIUyr2qqPrQlTK2cWkLJEUAS1VcCZvyt16pj0LtJNJi5vnPt00Yl2hTgRqnfGGAmsgkjgeZVv5-eV2u-pCoojEpbvmKONvqRzI73B1ogMPxSsDX7Yx03_4hxh-K2j2OVbi0uz1nYU8Yx06EZk6XugjuiPt1UOqw40qlyXxvc9drBansyLJMfQi3Uq_oBrWkNyeT501qq_XOwAPKwdzjg7kOJfx7WwatjfP2xNmvzbw_u__SsIrECdl5o12hi2-QTT-w2RTKzAZrmfd7GN0euVRq5bKCQIeJDp55yH69QApmm9WQKEYNcOZ0SQa785ZpRPyfRas3zbqB1hbZOpMpzsGtDB94bVVrdL25gNyAkQOTakVPYKCb3SBO9bkRbebTRhmzj4qY1mp5PbADoe9nwrOFOB7dwcLlK-H619p_Tj7mebTTdeiNXCxhMVlCSL3N5gtYUV76udX6YZw6fuJhUvN7D2aHBewaJj56XFH1Tynnp4VdyxI4U6bToDEcKajTSWGAd9VMBHie0eE8lrsFZbUbv2uSqpUpdgK65Aoa_3uW6yS_Ixoiv8k2WuyiHRdfieSBNykYykuAqX2vIXmmbmSIONC2eFGDYx5V3nGV-iiev191AgW4-4Leb1n2JCzQgB8II-rKSHIhSQI4YGR5j7p74_h2cbu96VJvSoRAkH6Onv582NwkhNS47ztCV7pICPLmaEF9muC54mXxaT3j_3TAfYQGnn_V8l3pKTOkS2QjxPYLjo9I3ZaK6gUsxVDYaGUp6ylNHBM2mpghrY3B-GOLSFJhMEiDaSK7H282cxIHiOrJGEbSsrraGhJwqV-eo50KN051ab1qOY5cj8t6CMAsxeS2Gw2P146inNF6koz1TFO4ja5EbwSWT9QbkgKvhJ-w8Sh6uIJzwRgAjfGk-IBASqVTL1-zmsTt0LelfAKVDLJj3KU-2fcLMEBaKJ8zIBcJ05eoqN8xeVqbzfYMC5QXoNEwsZy36sXZWaDXIC7Gc0ORgGGCbG0ADTzoM3r38aGStnQ5YxHm0Bp0Vc7wGndtty9zixDCzIqN-peUUqxLspJHhY-fWppmqdhsMGbW7YIxDs6GleYW7t-vV5_pE5yOtSerapCHtjHbPrI00GiipkenOIvKmBPsBT3168LdEKwyTGPmpQL_88Wdxb_ArdoCtP5JEZW7Ooe4pZq20eCvz3LE2fjVYzEwWYiTUmSjIqu0_nMeV60z4pN29CTMWMQYmvdnRg_IK9obBwENEfH1ly0L1Hua9UIYLsJLSCaYzeyBmV-VeGaJjSyrL_WAtb3uniR5IvX--OtyckkaAmbBxmFFNvrTcbZLj19K23dCiA9i7AVNbxxdXc4KZa9SmN29tgz1e5MIdPzxogJMgPCvvU0MHgKgPrm4Y86NXDjCH2cYsZnYxw_NRCbu43S3jZT6PFdsV10XMDIyBinGmX0e_jZ-af-1Aj_I_Uwlj-POVDsxQvPTyPry2ZodfUk5UorHOumNOULQt589RdFIL3Oa3WtBotwevsWBX0ZUAKxDxUI0v1j0fbyNjfjqVuFDoJ8zVLv_5VYlL1i_l0ij969AdKYPXbHu_XQhFcyqkCM4pKp9l5CcFcKQwgU2xpJll8A6w2-Czc2hWlXqaQPP4WocQHIS05da9usby75Dc2JIrlLh7othFqN32wBMgIWkQvCxtUuzQ07QTjye6IWydE9KzpJAGlqloAfDej8ntfybb1QvL8Bd0CdTPOTyygWxZqYVrdDoCY28RGeRuMoe90iy-0Qn4mtO6J1XbgCbZ8Vmgt-zrxFYuyov8AyMweA1ek3RqqVdyEcNkrDY_f5IbOHkw5Yv3f2tQsd-k595lICxVD9xihZTPW9XDCLh6GU0YV9PgRjaKPK3CwK0C1Nf8aFRjXEXS220ocJgopDEBEPP8YRBz2qqd9Z9epB9jiNPmcJ6srT0CaP3tN5hZXkmLsFjk-4AqHyqWslfgbI-uTLuqIlV-9B9OrRMwNfvz3uEwDKM0aO1ttXB1_YHQA6ZJY5AN1Wk_J6hw98FL8pxV19TioKwOjsIzFjeIYKLIEwuwXyc5OBssqKCat1OWQVQ8x4A0sTkvnfVcFe8HwS81clrHisrvq-_AlUq_aHihRLS_yXtqpNkWQ0fHzMbA2G6AzF8KSDIny1A9B-CnxQPLUGicXUADhWtnd8Y3ifSvWDWCp0F8u-PDM_8oLqw2qCgAORKJLyQI8cIiyuIHk6L7ivwtGrLQfkYAqBTRMNXtz_gmm8-9RxhntjmHbgdH6CZZyl4TQuXb6SVWS1d0ITo_pfYha-LrX4pn5zpIF3KCGOUeieHF9KCC4KcmEc9Z0t65udd-OeaqWGt1Oc6_zY-NpuXC9QmASIwIF20sOMZwEQvb-R2OBA9sf1QrOIteQGo47vIANPfBNOUWyPIV2B6rcjGHQGzlBcSzenQ7JFLKw7gc873jLpLao4-LluAMN0T50w0txRoj4YyghYAfrfmSi-FooP9AYIN_OMvkDclmaALmrWbCwATTS0bG1-PvzO7uETjr21gur4d8f_AdY9mQ36dek0B34dw8Yw2Iuay4AX6N0RpnUNzqFwJyPPkwC7oiIAMku_0VCYGBiKcpTkygaMkTZdRa2OdaQtW_r2cevL3dEJ8dL9uf3qL0zoqTn7lhtmTBzAUL64So_9akMnYQ4_tqI62qvWUtgsTA4bvEgnFLKqUqd5G_XpdTdGEfsH4ez6HgaLMzPHdiumYl3IozNB28czs_BBYfqMfnjn46vJVtWt2Mjyl_LR3nbFXFgtSndJ2Duu_0kROcG7AQ7zSezu-P9Ip0PE8JlkE2NWrFcnvcq1HgsDMSQYOhVlgzS8HPuT7kRkKpUSfT_Ve1HPCDXq4JUFu993ZbVrAP4h9iihseDVBIflH9yBgxXEkVySoOoW00PNRjCsP6LHgke0KzZ0flVeK8m_XOnp4U0PwiAH1qwP75IZVtk-F3nWg7u8rznkQWywMNP1NBSGmQpwOgZKarOMSxJ3XPrqdutGMBLJ4iCrgNv7QDttP6rGBKM63byLaryJ1eCV2ub_GeFMuRExl4KLF42Re7dIrVDzvUN9EjSdLz-F0mpCwaz8KmFj5anj5ATsGkLC8xUcS3W_BWW-_rvixQsT1oxhX6iSb6jPxVc7yMZCUfzoCX2pbD4EjD1VHz-g6NshTLwn8vhf-9kgiizuwVx69Aelz9Ui9IOYmbOK1HcRGDwBoL4y-n4TL4pIvr1lBJ-eXNvM_gZ0LMsoreb7tlmCro05svYqwV8llliVyQ2QlEpLQO8XczEM2AXyyH7Bk_hUoj_8LmZ_E919QKgn-FNGTyOYQEfhUwTIqHxRkoiMjKxtjV_8NX0Ru8asYykNKNl9uGBHpfyY0Q8XvuRu5thvS99LURttMn4bLUT8nERwn_9E-9rsi06Hl0Umozx0XJa35BulCat1jmsmIvGqN7l_WQwb2xT6aG1vBYsV0Bst9MGmiYQtr0_B6fSN8jzANzCBvgsoMcKdRmXUSbSAm3mhTbgVd6FpFvjzyyIJU4cIV4LMZNPIFOHLFWejPLpfpGPnSN3X7iqO9mfXWqbkuCRUmIJ6yRtWQNLwZApLWawD7zKJTnSjtGr0l44REHWA-ggdZAtyQvIxk1xFUNzaYIY_bInrhzJBMh5nAMCtl9LYntJPJqeNVLEDemW6I6gIP2WhR2o9VdxFceCY4agVeyPj_ABjjQJUd2sKN5BxDSTErDEsDnKqXoE8nNUrxhDpptJylyed6nOF5TW0Kx44s0C6HS9Hf6OB5OKhOqqwyxf_qBZKAisI2tA39w87ebcdDdFaKPNDMNmfc4L_DlZmY7ZQV8BOkvs-rvYFE2jGqzfz8WGFiUtRPgGoCNzlJ7O6zs_jG6iz_5Bb2E3raUyRoerTa-WJv27MFylFy3BZEcYwlFLTbhyYC3FzWCV1Bu4vkIxMVwrspReDodAo8Re7bBqcj1kR8KcojIU3wrTN_JJjfVJ-W8hYUW2EGpXalusC9I9uhwSm9oIqJ5WCBXCBhS5GRxwcu0PZOTkO5rCJlsXrZ0m9-ESRVOBS6hsPX4cNu6O1V5-zXaH_5cXTEOqPlj6QhsEYzxOu7MMj57jno7H5RrMxekewHpV65h6-O61coQ8E75Vm7nFeYKuwKIlQEujYN8nZDcpuadgJA7F0xuj-mJ2yPfc5gNaFV6qk1fZX87fec8vLcVuZZ72T8FrdU4AbXs-KhtQavhpiZa6SkRMgj6eiPtg2anDHA-Ok11gHgoT4Ef7KJsXngvlSsiS6Ff2XxOlVQL9_lec0yanTq-fWRQfCs6n15-BwGPyIjL4EuUyboDcSl3YzOUCAqcW5uYgn338Yz2rJucGpgmtqM9fve4d_3GAtaN9tnFV4vdKVgSn6gIeZiqlwQe4yzXszGwmGq10rMa0IkO5bhGmtN5FcQahRkgCuERHIu3F5P9x0B3vcAiuMjuYweC6OpN41DfVo0N1uF06junDZRvjf4zY0wpl6FFbkI-LrgT4xl4P3Ky2JWQSkRbkBGiEiRfE0sTNteL5wAoswSeKyYc8Pb4qlVfdEo3pHEJDbpaowXSF46DpFKVvGdOCBLMF5YrYXixlrrZxJBgxU49IRc1hOgmF4CT-lTSnvlbdhYzsx_le98n9vuZ5rbiPwsi1c7N5-IDcWzdOVZj3mQvuQHmnPaN_wXnHPmbT1WHTtgILqaYZvBRd4GmCIEsUH3GkyIZVAxN_lp4czoS0OQubj2qhuYw_pVhm6gjg6-Qd8KD1B8jwz8vgLVyFC1S99KeG2xwQxjm-3HUSx3gy-4Py6pZELBB2MshewyYGJy2haVLopL8YOArplb6Sgbzbw73huh9cnLX51gs4hZ9uS4NtwKFJikUCWRzjBwC2MSJazEHoPJRWBPBGPCjsfuhlNcNAyuLR0GwvRSwePVLx9SsKqNYqQLc51Ci7aohl9q6qXOI8vsf3n3QC8LUV2wRjYi_Ph2YQn0Obwuq0Oe1YAd85C85Cud7XLtP33gX2A6B0wKhEUsvzBSeHhmFqDWYBjc0VnB_Rp0ue0sBGWMMrkxqnEZX2ETdLVOgLPtFeiNbGFb2R6zTzk3HB05-Y8ZXRIgJbVCUyJKZJ-DXoJCE0WIlXnfsqwQgfNyEz4j6HZ5r1JcNMXneiYMJ9teh2qWYH_NEBUrocb9_W4rITejOh62VnZPXOyCDOPCR6WOwe7rupN6tMTU3MXSjsZkY-whIiQPbZmVvkJrf_ZV-Ny0a8SyuHCu1vD96hmC4Ecutfa0A0OOJTB-610Yp0mr5R-LN1h3NVpV09tGEUR_nmUAv3ECrwJ65GN5Z4MnwmjGU37i_-kH-0ZIfZUYfqJd05_HhH41_T5EwgEUX3lCMM9W5XL56yOi8hjwDKqNJc_mRixwv0_ggAsHqyTsHfd-ZpeIxpsa7QITFwZPh0i7kYYyd-_iTrZoRr_KIQ__dpNW09ecWRzWicBOr2quWXawINRyhyWJRDkDOwAbfb_V7Gr19mDrdN_nChgu6CQFN_e0t4D5GwFS82fKUQNfREAolKI2D4ZxSCS4H_pS-ga0BOi_prdI62vzxGGyo0Imw-mbG24D3aoFSsG3av3RQOdPWrn_V58AZCI9ZVLOlL9Faq1wZ49z5-Ub7ebzWo6xT7tcYBLJJw7HAwP4hRvCfai0Go0M50qNaUwlAEN9ajgk1c-6SV1ck4LZdY8zhIXERuclHWchl9qehk22g_kXb45xV8rQkS7mnSHPKv4K4IfcAYXpawvpTstzx0Vk_3Y1doiZRFtZmngfQmue2uIeA1YJetI3HkiyMzJECfMBe0cKdd5x2-iB6CDLnhBiVhbjG-z13l-8GASF2u7J94ExX3GrIJHs8JRzAIQDq1ASE8iKCvD9f7dDnkCmMQtOIHhbsjAWxNeryLJqZkbSZ7l-PrVQPFau_ta7WnOMCstmBlPrQ0YcJMed8ume4QofRBZ|regm",
            "waterfall_id": data.waterfall_id,
            "INTERNAL__latency_qpl_instance_id": 131635346000265.0,  # from password_creation_request
            "flow_info": '{"flow_name":"new_to_family_ig_default","flow_type":"ntf"}',
            "is_platform_login": 0,
            "INTERNAL__latency_qpl_marker_id": 36707139,  # from password_creation_request
            "reg_info": reg_info,
            "family_device_id": data.family_device_id,
            "offline_experiment_group": "caa_iteration_v3_perf_ig_4",
            "access_flow_version": "pre_mt_behavior",
            "is_from_logged_in_switcher": 0,
            "current_step": 6,
            "qe_device_id": data.device_id,
        },
    }

    return {
        "method": "post",
        "pretty": "false",
        "format": "json",
        "server_timestamps": "true",
        "locale": "user",
        "purpose": "fetch",
        "fb_api_req_friendly_name": "IGBloksAppRootQuery-com.bloks.www.bloks.caa.reg.birthday.async",
        "client_doc_id": "356548512614739681018024088968",
        "enable_canonical_naming": "true",
        "enable_canonical_variable_overrides": "true",
        "enable_canonical_naming_ambiguous_type_prefixing": "true",
        "variables": json.dumps(
            {
                "params": {
                    "params": json.dumps({"params": json.dumps(variables)})
                }
            }
        ),
    }


def get_birth_headers(data: RegistrationData):
    return {
        "Host": "b.i.instagram.com",
        "Accept-Language": "en-US",
        # 'Content-Length': '30274',
        "Content-Type": "application/x-www-form-urlencoded",
        "Priority": "u=3, i",
        "User-Agent": data.user_agent,
        "X-Bloks-Version-Id": data.bloks_version,
        "X-Client-Doc-Id": "356548512614739681018024088968",
        "X-Fb-Client-Ip": "True",
        "X-Fb-Friendly-Name": "IGBloksAppRootQuery-com.bloks.www.bloks.caa.reg.birthday.async",
        "X-Fb-Request-Analytics-Tags": '{"network_tags":{"product":"'
        + data.app_id
        + '","request_category":"graphql","purpose":"fetch","retry_attempt":"0"}}',
        "X-Fb-Server-Cluster": "True",
        "X-Ig-Android-Id": data.android_id,
        "X-Ig-App-Id": data.app_id,
        "X-Ig-Capabilities": "3brTv10=",
        "X-Ig-Device-Id": data.device_id,
        "X-Ig-Is-Foldable": "true",
        "X-Ig-Timezone-Offset": "7200",
        "X-Ig-Validate-Null-In-Legacy-Dict": "true",
        "X-Root-Field-Name": "bloks_action",
        "X-Tigon-Is-Retry": "False",
        "X-Zero-Eh": "IG0e09d776530888418ab70f3822fbb4e1",
        # 'Accept-Encoding': 'gzip, deflate, br',
        "X-Fb-Conn-Uuid-Client": "95b2bb513e6c590b7147b9e4bcf849d8",
        "X-Fb-Http-Engine": "Tigon/MNS/TCP",
        "X-Graphql-Client-Library": "pando",
        "X-Graphql-Request-Purpose": "fetch",
    }
