import json
import requests
import os
from src.utils import write_response
from src import BasicData
from src.flow import utils

headers = {
    "Host": "b.i.instagram.com",
    "Accept-Language": "en-US",
    # 'Content-Length': '27226',
    "Content-Type": "application/x-www-form-urlencoded",
    "Priority": "u=3, i",
    "User-Agent": "Instagram 410.1.0.63.71 Android (31/12; 420dpi; 1080x2274; Google/google; sdk_gphone64_arm64; emulator64_arm64; ranchu; en_US; 846519343)",
    "X-Bloks-Version-Id": "b7737193b91c3a2f4050bdfc9d9ae0f578a93b4181fd43efe549daacba5c7db9",
    "X-Client-Doc-Id": "253360298312778871684788706414",
    "X-Fb-Client-Ip": "True",
    "X-Fb-Friendly-Name": "IGBloksAppRootQuery-com.bloks.www.bloks.caa.reg.contactpoint_phone",
    "X-Fb-Request-Analytics-Tags": '{"network_tags":{"product":"567067343352427","request_category":"graphql","purpose":"fetch","retry_attempt":"0"}}',
    "X-Fb-Server-Cluster": "True",
    "X-Ig-Android-Id": "android-f35f126bc4795e76",
    "X-Ig-App-Id": "567067343352427",
    "X-Ig-Capabilities": "3brTv10=",
    "X-Ig-Device-Id": "c734a1c7-d663-4fad-af07-817b064e424b",
    "X-Ig-Is-Foldable": "true",
    "X-Ig-Timezone-Offset": "7200",
    "X-Ig-Validate-Null-In-Legacy-Dict": "true",
    "X-Root-Field-Name": "bloks_app",
    "X-Tigon-Is-Retry": "False",
    "X-Zero-Eh": "IG0e09d776530888418ab70f3822fbb4e1",
    "X-Fb-Conn-Uuid-Client": "b0d866e0c3142f00b867bac783116a7c",
    "X-Fb-Http-Engine": "Tigon/MNS/TCP",
    "X-Graphql-Client-Library": "pando",
    "X-Graphql-Request-Purpose": "fetch",
}

data = {
    "method": "post",
    "pretty": "false",
    "format": "json",
    "server_timestamps": "true",
    "locale": "user",
    "purpose": "fetch",
    "fb_api_req_friendly_name": "IGBloksAppRootQuery-com.bloks.www.bloks.caa.reg.contactpoint_phone",
    "client_doc_id": "253360298312778871684788706414",
    "enable_canonical_naming": "true",
    "enable_canonical_variable_overrides": "true",
    "enable_canonical_naming_ambiguous_type_prefixing": "true",
    "variables": '{"params":{"params":"{\\"params\\":\\"{\\\\\\"client_input_params\\\\\\":{\\\\\\"family_device_id\\\\\\":\\\\\\"dd5b9513-0be3-4263-9106-459e51268b46\\\\\\",\\\\\\"block_store_machine_id\\\\\\":\\\\\\"\\\\\\",\\\\\\"device_id\\\\\\":\\\\\\"android-f35f126bc4795e76\\\\\\",\\\\\\"lois_settings\\\\\\":{\\\\\\"lois_token\\\\\\":\\\\\\"\\\\\\"},\\\\\\"waterfall_id\\\\\\":\\\\\\"d6031628-57e9-4414-93ad-9911cf738e0b\\\\\\",\\\\\\"cloud_trust_token\\\\\\":null,\\\\\\"machine_id\\\\\\":\\\\\\"aXFTbgABAAHw1cpzzsgkxOLUNm6H\\\\\\",\\\\\\"qe_device_id\\\\\\":\\\\\\"c734a1c7-d663-4fad-af07-817b064e424b\\\\\\"},\\\\\\"server_params\\\\\\":{\\\\\\"is_from_logged_out\\\\\\":0,\\\\\\"layered_homepage_experiment_group\\\\\\":\\\\\\"ld_no_language_selector\\\\\\",\\\\\\"aac\\\\\\":\\\\\\"{\\\\\\\\\\\\\\"aac_init_timestamp\\\\\\\\\\\\\\":1769034606,\\\\\\\\\\\\\\"aacjid\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"d2c8ed10-f952-4a12-aa09-e83671b1bf71\\\\\\\\\\\\\\"}\\\\\\",\\\\\\"device_id\\\\\\":\\\\\\"android-f35f126bc4795e76\\\\\\",\\\\\\"reg_context\\\\\\":\\\\\\"AViY10bOxkMUzLp3WtkOICp-WRgJAmMNlDN3UvXM2bfKzozG6DwsEQGT4JmNeEONuPWrEoGSxlvhdmEK_sxXpjLqeBJ8B3Fm68zVpULGLuNCT0IqKoPVWQ-9N8BPmZGMSoLLzM7q8qiqtm2uYrZBgGIX_dbY7cnTfpm29Ha1MtlkUtK53JL4p8h-IG2NABBYmgJlv8CM9FqTSr5-HKuhY2HQS7M5o6A4D55ESx5vwDYaW7bBflN09ORFZ0JxbnStfrwAyfYIDiRg2Xp4NBACq1hEzJ1h2GJFq_h9KlKmHds7CKy9QULHnOC_XuxCnfxwvVB7XVBhxOqEJIQawaQf9HJs2bjCj-oPkAb7nm8Q8PiZIHjkVjJkSIjKc6dRfsAzBelUODrojy-LojmwvQEPQOyKVfEecuRsz-nmuRDsTs6HS_lZl3qs2PlwGwOfX-DyHBORDameVPVu9KOceCMBIZHluOSSI5dJ7mwxdL67589V7BHQYxWjyF8Q9NgyxJf-GOmb1F8LJlQpG0LEyvFsDeQlRoOoMXMFiwbA6nnoYRTTeLRYclczNSVQ4h55io1BPBUtGK4ystK33HpfIUpdq_Kys5ATTVaOA97wJCIurtdAwkGQfmzNK1QuQexHEYhBUC5XsheEH8ykItpLbHytWKh4RbdP-vnXh9krOowxInRJZ4LqTqDJ5s4x0erfJf1DyWTjZEP7L6R1WsQT-wqurpO_G8d_kIhRNDuiQULkef9VqjZoNHBv_lOowfL2_RhVhsF34_jUnAO31O-jSBot1GkHpBahpmH5GD0FW82bJWDOWjaf-FpJZob_6LWkkHqQePqpkfmKyvj_7DGeD7UdcptsxRRqCH7vUWO_PEu9TKF3yZEo7lM4rSMiqhIl8Yh6mYT1X2LBB1LaxcNBlwOwFW5M0PkMCqCncEM9lPsTVJRlPVCG_e_viifxvUtt3SN1HLGBTUPvyyvQZsldwtyxa0BGu8-2uLzEMSaJKKt8v1hdGiHB6ISmgt_s8BJcc5i06pCkHxrxAyzToRRbOeR8r5roqx1l5VRHWLxn7H0lv9fSXmGj0mgj3McWHaMYYHhw6Y_5H4HvXm8tlTEF6lQKeuvkz4z0wiINIzrwU1rpm5tp-Y20dwE9DYAPogwDNe0WEkSltcvi4zq-phINkCh9f2WLaBGwFwBG1Gh6RVmKfYGgUiv2zsWd3vwuOMLwzserkDteB-GD5jbtG-BumhhyI-L0QxL5OiSXkFBwGEA4xOfwf2IHHaU9K75iK6_LLEH-QufDGBt-wgLEdIRCwR-Vy_C2tpKH8ZkkiBiEVFWQTCdAjNkebmW6-eORowzLIqK85N3l-VPcOkE83FLci5DepMrQG4KY_7R2deeI1M38GCsNXAUAW-AFIgsc-myBdTZed0hiaHUHc-8SbSHZktEnAUwVZDtXIyohEqCppjkAf_hVe1IdhdXNO20brIaFZ9zefYuWNa47jZHlmERxkP9Vpl-shqFm5BSqzh97mFVQODINf3zJkBqYicCyMBsDGSAhk_rTTM8bK-JZU9thcKQdI56uOQwdIyXe27xKZpfkOvpf7oy0qUe-45_7U9Zzsj-3vEjPkTIBv23sZT_5lhKkhuYBc4iybc_a81QVbjewKsM-2rnZPRvz7fN4gV3OJu7D9xUAocuoGPvVC3HCLXSiM89iASum8kR8Ul_B1th_njwGTVtrwhO0MonNNVcNUQ32eKA_ZEYS_Db2ZiK163gUUckqiXVaudxCemMecaux0VHZderseB_NtOIr3Wc09MpZ9Bz71mGmff0fDCt4yBt8m_WC5G_HYVOwynFgZqlxR09phyTQU1ZylcnRwwKOWyFITOqBYmahRXtaiWRsuRI-ItJ4e4cB6Dky73Nq0kTJN3FojK6zXL2nmxA_KM1jEqLb-gg-9dGVPP1FHjdjA2PCu89lp1rFTpMw8e52ypyPtW8Mjcy1Uo3PTnYkgxIJiPMLq8PVb7sfkkGDLictX3_k3LrV7acxuHbZYrbhKtXhYBRngfUPjl03WAu73y--Bib4QNupQ2yZFX2cmuqq6MDPRwcs-668D6X4Grb3v6d4ElkDRSzquOvlJaXjmDvYAH9q31yEa9BSaJXvNsbnrfunDr3KwQmXDmczA787za3WtiHYDEIi3yXFdh6XzOH_Ng62maRSqc1tnCkq2mM_dweN-jduEp_bbScSJVzSB7JGrdvyzl4UBpzH6QY82spG-NtSa1gMT_0ACRQJucskrJ2GObvJ3TwG6cgE85UK4ILYKvCNxzadiiAyybtBytx5ZrxckkUOIvCkpkhxYJ3ymIAQDupJOk4GpJWlBTx0R420zC4OSQQUavPOtYfOI6WV2f0OZx-lKxdrwHVkVcU2xZy5AfSuVbLRIbhIIEeOBwV96X40ja6_QeLJe-BqxH21QqUeivyZp_Pt1JLnyoIlbXV2-Noen8Z4T8dPnVPSvrNPbPKeIj2Psdyc3nIt-OR6oTzzF38ooqS-df2D_rzMuDjL4GbmkGRlHHFIHaJwj4ueQqeiu5Ll5DTGXbtrrLPEQ843MFUUM3SVPoHX24ITVtFnPueWCmxTU9ODXm7AiivDYpwgFnXpvkJ46pd9ibtnFGWkjPdJPW6J-q0cMWYbhKJoqGvfxeysAb2JKhWC5yZSAmgksiJ21Dqb7mdAlXhD7njklDlNl9nXQ-4-hFN2oetzTpHNRcI0EzMgNasmSZSLUXnaFTQGXpQa1wINnwqKv7FwCq03N7p8zjLR1fGqgaH08wdPpJ3u5j4iqOuUwOTBOMf-fJHZFAFwCDNno9nEd40Uzj3thYQbODHZ2jRP9wSkk0Q-WM16J23FVZBdxovt8fSBPjun-HjdiTMunGBIr9RjKptvHSs_U0RwfoRbXyF-_tcTghdPFCPZ9HHjtAwR9VzOn-gC3i8K4X35yyJQVwh1NRCGNtNFLANihyaQfhCZf1-9KQcVykjNGQ-Rihk281orruaH5WR3pBXe794sKSLCRu0yCmmZ-uxfECapMfGA3LSzHgBOgw-7uHgZ_lH3GF8osjz-YsYe5PQAFxxTwVr2dErBmckIC3MNGctPqz7KX_TET3dspW1xy2wIa5f1kf38a-XHxvLfV2HLLKGoKYa_usvx9G3cGy7pd3C31nNpz_fB6mfewhcufzqbbYMaX4bDIV_8qObpjkJzaYEbiS3OaUzHLFcd6wx31i46JjjhaHDPmV7WYYFr21aA9dksvC7_GGHQKvy72CRCpBOrYBc2qot-uVENBTTzuy5Ora2pC6H_JxLjxnFhZy0cAKYE-rV9EDrkDABrMq87BG6fsbEEpa9CViC2ej3a3_mLGaNuY8NiajJsbkkPBcSzBqNqHgAJAfUMmOcfAQu9ACMj9Df1R7-vlQRRHlk8z0f0hpN0mtfZWa05gthZZbXjAfuOK4VRAfZZ7e6l3vdQBJOQCj_FGkZMY_vz0WYKzPOgMM1d6GE2v_fjy0mlEkyRr6-PjMB7X2CVAI6aoztCdjkgdFNn3PtzyyNQaqf7WuEd3d8kHc5nmHmy96i4flxfK8XIRgXc2r99kRZtfiezU0j7jKzLkpkk2_UThPqsKnXFqWVOm2u_4tmNHwOjWtQvj8jVn2-gyPk8wAm3ax9nw-qeNvJu1nWDLBDdHngUZJp_RXXtaUmJIQMKx_PrHipb2Dt86sMz31jHhKArQ9628vugDH8cnUVnCzANaLhhDSFAH9643l2br4W0Hiuh4pj1b9eACT9bm0aTrqkJjFG9mlUL8TkAkhthea7XyeMWREpVGlYGHYI3ar2vihiOlXsZo5CLzdiRDrA9jPlIqMvVDyuVCrzwrGIKcbrssVznCJWa9wuNjyh1cS59apms6h_IWbQr0IrEijCjDFqxrnYfu_9_q8RPqFS99Y18RwtQSNSoY1PRx9kbCXETofXLg_xLCKX-dy1LuWa3GZoxHfQ_2uHPpDmoVCs3lM5IxZBQGX-aTV8TNDXO3Ex5bkP3zaJeIA0N7rhjilL1Fa9IfjYP0D5k7rKSvt_FKAYFEh4bOdD7wAnKcWj8njkcjZhmOwfyQRZG7k5tCd_yF7HbHVhBfczbLee-tFuT01ri2v6Hc3q-2wmcl-zmZd5ZC285NbkBM-gRzRNgz7cb8TrY8Xtz4Ch9OQLoGT3G6tsdIwx26jgZoXndzIRNknYoPmyHXzQpLAoPs7mHgzrsfAypAwF1PjU4jcYMlGQCgg7Phz5Xvg03cgn3Ljwp3tPasLjHb5ftIe5LE8cQolxq2FWpgcoQkIMJ9PpWQ0NsoO499aN6mJNq1t54Lo3GzwhwsLtY7LsHY0qHI7AhEEFRvIgwtFT0NTGCEgIBW-OPEA5SV15fviVuzcqEbO9wU3OTQTZo1mx4iRMd54jb3htueNoAzOkeD0pLz2acnQsYqAtsvSV3THg52JMb_5VtP9K3qKwCWty5BTAhEbI0aSPVEAFaDtOXqxWV52b8P_02lZUMmmDXBk83rUqzsIM12eOQ02cm_pLzpj80MCAAN_eZk6YtBsnoBmA6ramgu5CvUrpnokduR35sKXjHNs4Vt3Yeg4NkmoocsJXGtF5KEhFj7eatix1JTR93YJebHxMHoKkcInEtre6P-GjcVH-L4A-21tv6H0n8lfz8mznLbEOzbpaiNqnyP_WtVsE3yc7LBQ-KZBoGs9YA9bs2D_7ruZcqhtdxAERVd5hfExr9B1KH9IaPHT_E0iCeC2EfotpMuutIOlULv1KwKVUppNXMUCrfeDSlF3umGFq7o58qpUUduYka898ANc4dIEq04R8oKmqKC9Bc8R9RElJNehLeWgU6rm_EacwH7Dlc5TzAIHUwjRh4KrGXIDzZs_ERaVx_2P-j1fhfvkOX63d18C_MFfYvyWxq6J5h1Us_EJZLNmbCe-QKa53FrAfar-AeYzmkLP2LuagrQz7VswWMKb-TAiNOXceTYPKKqGxnFdLyntuy2WUjzqJx3ITT1-k65wwoteWzJXz-qzY8aFK5ha-RYbtVfTTYH6d8cFLH8h-5E101cjCwcJBACQqoY4H_wktvb97T_r2rO88XVZ6clsrBgfRMah5tiUtxZJ8-m-PIsY0B1PteJY6Mw3qICIVdd6kjvl1yns3iM7lGkNoGYTJDgESDbanleppHRBs7TytDv3TU9XsBsqGQ5_KhKhAL0DoM5jaX0yAHRnBU7NLs7lI8DEQ_ZHQuMs5gQY6J4m1C0bi9GdiCOCBDj_lvAqRUJbsyfGooCjzfepG1Ogv4zeZW_UNTk6xRYqUx2Cn-zI6xBqRGnFHou9JaVlJ6R2SqIP928A5nyxzS2JZAyUVMuDM1omdm9n-PDBS7sM-jVEaq3rSbz32Iji70nc8OjWYjFVS-ElhF8oJoonypJqUSda3m_fOks3ODbGTVZGiQA_N-iU1YkUESwsKUn9xlGro3SwDsawuV0qLqDl9INlYMO7I6cR9I_dFhuqHRM5h-AWwEiCPDOMkjgRXdroUC3xeORiUqJ2Z-y5nbnrD21_udh68tcx1_uM1ho22mKcsXlL-YcTrBiCodU5esA7gjlGyi1u_TJAkC65a8CrcPYkbWMuOLOz4O9qLybYnZmQsH8_LMjTwRoWaShhuatDHmIOVEob79dHcJLM9duwc5VtiDHJe5NxfJLzuj1Q9Y97iwuuy-zUjOvupf1-MlfjhjyIkXXg6yugMd36CuzMJVFXwlon1KIE3-RVpvMOkFq3Epmnqk7aFmqM7pMGfAmKGAEVdswSLKUCcVLbh1AyjD3E4ZxXi4JsxD2KHPuF7pO9tnxeaPLj6MiuLXlE-ka4f0Sff_l3NUDg9CNyyKlirqoU3QF6U6xe3YHcZ_UhYQp4hNHT0hJ3ofBKb6wc_DRxS7BZDP0iHNZ-Yl3_NHN1mutFZ4d1UVmVkkrZnfR6h5MQyh7cPfOjCI4HLGHwFiXHw7K9wZEC_Nodb-AOgWZLGQsQOZYH796NTlM8zJWRIjZOG4-nsoNJkKVI-jftG-QGOuM8aZKtbJSWk6zXscQm0f750Mpi8g-8qvf-_A-37OUIOWyStKZMsmtt9_bxfHZF6VD6ZpW4PwSnLxFnf7AGbJyJ1sYU2OcRmF5T2tEBJV6L_7UHmM-Y7ZOclS9ZELlx9k5UncVdLUuODTwd6tMijRmWnTitbPDnKeJAA5N6NkFs_ouaIiv9nV_kXXeSGZv_uXdNzyrmmoRT3ew4A4d6DOg5iUw5ZjUHF3IRGVtrphgURp3LMU3ZGD9CKj2Ps4EAkzcBeHcO4bPFJYJ7QtzPgEOlvA0hSRWPf1aQNxemePWzrzMULNFIOx5AFg7nnF5TjEceFW9Kwzpj6S_e-WeO0Z_Fs-LRxh1HcRFPo62hCgUiF63n2qUgJljLqW-vycs09-UtocWin_kPPQPiYrrEemtdkDDrEA56ubKuzhuAJpbgYzxAwlGt1VLSHNltWnj9JHjLaKAhV3uwlIRPR-UbgidtnkfVYP0xorK1mrOMfTiOcNxnA4Odk_QsgmdXObfe-9vnvLQqR75TIPBtzeXk5Z002nRa2YjTTkpbV3YtZOPx7zivwC28QX2AO4j3IfmJzQ1AiPP4Tg8N99ym9uwMjLQfH7s4rtBvsashUdNw0sAHaUKBfjPWEasvH1YwYJLd1byehaEOD3Z7wssfWgkAz88MKElx7Yd2r70tRSMYAhA92CXskRU40YvKcC_aaLkdfS1QkcVgaibHF8INPDR3bqnTG44BsQ6DLQmzluxXJ-G6NSMn2_64hyjjmKNSyW_uMjfYlEa7eX6-l620uChGJo3gn-0MSDoWJfm595loMOc_b2Qb2DrHVL2wzbNQp90XY418XGLdRookV4pB5agWtSo9sjoTXIMKoPZUI3o8qd6XhE14QGMBMdTE9IoQ5hkKmtdri6r7YKIZMWiN46YroyWw78X5URc85c63_Y0AwUg_su4ByhEZf9cv7x9tGJx4nC4kKBeLybDxOhpsVlR5WSoIsYAT20_xe2c3jU18cwBypOF7t3XCxP8pB8tFrunWQeg9SoddorzuMRxV3qbDTFRgE2sC39_FM-I619SmAWGvQn65gNaw5WwoUjDgOtek5yTsUsVnB31armhxZnJMYsSLqfISzrM1TJRH5ugN1fXz4OQdODtVL2tydtoHcx7SKNsiyNUHVFI1whahTyU3GgJP4OOUT61z0P-uAuu_P1gaQcTgz5yDPZHvma5eekJMszhyJHBIHD6cYRSinfTTdWSAeqwYf7qT0oFTSuVWGeQdCkjce4UwCfOw4-MlY0kIRfA_mfQg5vcOUD4B4DLeSiDknItWkVEhCFhOpJ2hqjhP30pu5AYjHSRg8PjPDtbYJWFSo-9LNYx72YLoSz3xX446WtznXRjDWTEPxrJNMTge0oZ_lruKJr1XtVyhyroAe0zMwQ-x1Ibkzld6W3K27Nw4RkcmBdWpBYFGSoYFM2xKKhCPJcQeoOUcA697pluK5jMI3CXGGndwYqOhAwEO7C6YIEie3mcNq-rjcUygz_nphKz7g_dGAHKWxwVvRgF3-arxfy4_VbOVqqZi8fAd-0HXDQ4KMKTZN_Vck7QwRsliBF2XbbCKNilMFzlTdLDzmjG2pD84zDA-lOggX1R0_MsN8F23RcDk86knYrPt_U5HW_2HMJnrAhtwQApsPGotUU5qvOSmXT7fQferAiysI9e-LYDkHTLn86LybaO0ChwaXpsHD28wiAbDs4rADzWpkEx9CEpdd_w6ym305pcPioIKQ7gANdhAB5gVZZEgplED--hcYS-MQIiJl480E9dhMMvuwkMqA4ut7fuwD3mGaGG6Grubcejq3_nYkd2vf1gWWHS8A3AxCC6fpvLHGJ4nt5aZdORMQKvbGenJiICEn5crvzCVWEa9-JrBH4yR8Utehr9xOxgEckRXNwtLYX-zlw1lSBxvo5wAHv5ZLOBHoEQ5KwSnHldPoRhl0j8tIGpmyeaLHIJ8F8s8VUfEc1577EMsf9YPNyEAgljtrFn3WKbMSqIiWfcPxrRbzqwfHjET6jF7wcuN5eOG0Mdba17Nagb8Juf-3Urvz1UzuGyb_t4FxZaS74105uzJxTv3tMZreh5SjJx5fk3sqVuqAjYcQ-EZJhSogRTuyuP9mw0Xj7RolXrNcq5WFe4Lnj2v5Rj9VvB_m9U-S4cspEIowd-E64GktW-5Xr_rtVCmdWla3Rp88Ol59Mb04ka3QLT1gqOXs143pD9QuqemB9xLxgFxrkp_P6KG70W1Xh8MLSaO7bMOLve9OKpTDCtE7Is_R4pSih47jl9M3k16FfhiSDM2iBZ5FW6wPq9byarHMD6Zr-Fd8Ehdw8Z9R-J9mQQQYFSJfpMlG9YjeCbWgvnsWTpp-LaDp5Z39wvEeSPd6oJLyjXoTMgO67O2LqS3mboYWx4aptAFpCerBrNQzoFN-dDBgkEu_wRDEK6TBdeC91Bui9Ea4LGGoGCK-L1ehNfG47lfjCOupFq3q7t175opZpMT6uHZkrMpjvVR9VicEl8FNyysb4WGwED5D8VkqOAKuJ90w|regm\\\\\\",\\\\\\"waterfall_id\\\\\\":\\\\\\"d6031628-57e9-4414-93ad-9911cf738e0b\\\\\\",\\\\\\"flow_info\\\\\\":\\\\\\"{\\\\\\\\\\\\\\"flow_name\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"new_to_family_ig_default\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"flow_type\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"ntf\\\\\\\\\\\\\\"}\\\\\\",\\\\\\"is_platform_login\\\\\\":0,\\\\\\"reg_info\\\\\\":\\\\\\"{\\\\\\\\\\\\\\"first_name\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"last_name\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"full_name\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"contactpoint\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"ar_contactpoint\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"contactpoint_type\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"is_using_unified_cp\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"unified_cp_screen_variant\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"control\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"is_cp_auto_confirmed\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"is_cp_auto_confirmable\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"is_cp_claimed\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"confirmation_code\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"birthday\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"birthday_derived_from_age\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"age_range\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"did_use_age\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"os_shared_age_range\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"gender\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"use_custom_gender\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"custom_gender\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"encrypted_password\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"username\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"username_prefill\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"fb_conf_source\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"device_id\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"android-f35f126bc4795e76\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"ig4a_qe_device_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"family_device_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"user_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"safetynet_token\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"skip_slow_rel_check\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"safetynet_response\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"machine_id\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"h1NxaVnaYULGGzgpCn_hPfVP\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"profile_photo\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"profile_photo_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"profile_photo_upload_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"avatar\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"email_oauth_token_no_contact_perm\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"email_oauth_token\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"email_oauth_tokens\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"sign_in_with_google_email\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"should_skip_two_step_conf\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"openid_tokens_for_testing\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"encrypted_msisdn\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"encrypted_msisdn_for_safetynet\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"cached_headers_safetynet_info\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"should_skip_headers_safetynet\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"headers_last_infra_flow_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"headers_last_infra_flow_id_safetynet\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"headers_flow_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"was_headers_prefill_available\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"sso_enabled\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"existing_accounts\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"used_ig_birthday\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"create_new_to_app_account\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"skip_session_info\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"ck_error\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"ck_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"ck_nonce\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"should_save_password\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"fb_access_token\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"is_msplit_reg\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"is_spectra_reg\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"dema_account_consent_given\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"spectra_reg_token\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"spectra_reg_guardian_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"spectra_reg_guardian_logged_in_context\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"user_id_of_msplit_creator\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"msplit_creator_nonce\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"dma_data_combination_consent_given\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"xapp_accounts\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"fb_device_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"fb_machine_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"ig_device_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"ig_machine_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"should_skip_nta_upsell\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"big_blue_token\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"caa_reg_flow_source\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"login_home_native_integration_point\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"ig_authorization_token\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"full_sheet_flow\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"crypted_user_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"is_caa_perf_enabled\\\\\\\\\\\\\\":true,\\\\\\\\\\\\\\"is_preform\\\\\\\\\\\\\\":true,\\\\\\\\\\\\\\"should_show_rel_error\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"ignore_suma_check\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"dismissed_login_upsell_with_cna\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"ignore_existing_login\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"ignore_existing_login_from_suma\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"ignore_existing_login_after_errors\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"suggested_first_name\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"suggested_last_name\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"suggested_full_name\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"frl_authorization_token\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"post_form_errors\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"skip_step_without_errors\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"existing_account_exact_match_checked\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"existing_account_fuzzy_match_checked\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"email_oauth_exists\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"confirmation_code_send_error\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"is_too_young\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"source_account_type\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"whatsapp_installed_on_client\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"confirmation_medium\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"source_credentials_type\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"source_cuid\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"source_account_reg_info\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"soap_creation_source\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"source_account_type_to_reg_info\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"registration_flow_id\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"2bfd5926-c03f-48eb-8e17-a98ed947592c\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"should_skip_youth_tos\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"is_youth_regulation_flow_complete\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"is_on_cold_start\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"email_prefilled\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"cp_confirmed_by_auto_conf\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"in_sowa_experiment\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"youth_regulation_config\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"conf_allow_back_nav_after_change_cp\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"conf_bouncing_cliff_screen_type\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"conf_show_bouncing_cliff\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"eligible_to_flash_call_in_ig4a\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"eligible_to_mo_sms_in_ig4a\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"mo_sms_ent_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"flash_call_permissions_status\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"attestation_result\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"request_data_and_challenge_nonce_string\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"confirmed_cp_and_code\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"notification_callback_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"reg_suma_state\\\\\\\\\\\\\\":0,\\\\\\\\\\\\\\"is_msplit_neutral_choice\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"msg_previous_cp\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"ntp_import_source_info\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"youth_consent_decision_time\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"should_show_spi_before_conf\\\\\\\\\\\\\\":true,\\\\\\\\\\\\\\"google_oauth_account\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"is_reg_request_from_ig_suma\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"is_toa_reg\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"is_threads_public\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"spc_import_flow\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"caa_play_integrity_attestation_result\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"client_known_key_hash\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"flash_call_provider\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"spc_birthday_input\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"failed_birthday_year_count\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"user_presented_medium_source\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"user_opted_out_of_ntp\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"is_from_registration_reminder\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"show_youth_reg_in_ig_spc\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"fb_suma_is_high_confidence\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"screen_visited\\\\\\\\\\\\\\":[],\\\\\\\\\\\\\\"fb_email_login_upsell_skip_suma_post_tos\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"fb_suma_is_from_email_login_upsell\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"fb_suma_is_from_phone_login_upsell\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"should_prefill_cp_in_ar\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"ig_partially_created_account_user_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"ig_partially_created_account_nonce\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"ig_partially_created_account_nonce_expiry\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"force_sessionless_nux_experience\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"has_seen_suma_landing_page_pre_conf\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"has_seen_suma_candidate_page_pre_conf\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"suma_on_conf_threshold\\\\\\\\\\\\\\":-1,\\\\\\\\\\\\\\"move_suma_to_cp_variant\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"control\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"pp_to_nux_eligible\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"should_show_error_msg\\\\\\\\\\\\\\":true,\\\\\\\\\\\\\\"th_profile_photo_token\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"attempted_silent_auth_in_fb\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"attempted_silent_auth_in_ig\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"cp_suma_results_map\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"source_username\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"next_uri\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"should_use_next_uri\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"linking_entry_point\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"fb_encrypted_partial_new_account_properties\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"starter_pack_name\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"starter_pack_creator_user_ids\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"wa_data_bundle\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"bloks_controller_source\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"airwave_registration_code\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"is_sessionless_nux\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"login_contactpoint\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"login_contactpoint_type\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"is_nta_shortened\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"should_show_bday_after_name_suggestions\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"should_override_back_nav\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"ig_footer_variant\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"control\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"device_network_info\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"is_from_web_lite_reg_controller\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"login_form_siwg_email\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"account_setup_waterfall_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"is_wanted_suma_user\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"device_zero_balance_state\\\\\\\\\\\\\\":null}\\\\\\",\\\\\\"offline_experiment_group\\\\\\":\\\\\\"caa_iteration_v3_perf_ig_4\\\\\\",\\\\\\"INTERNAL_INFRA_screen_id\\\\\\":\\\\\\"CAA_REG_CONTACT_POINT_PHONE\\\\\\",\\\\\\"access_flow_version\\\\\\":\\\\\\"pre_mt_behavior\\\\\\",\\\\\\"qe_device_id\\\\\\":\\\\\\"c734a1c7-d663-4fad-af07-817b064e424b\\\\\\",\\\\\\"current_step\\\\\\":0}}\\"}","bloks_versioning_id":"b7737193b91c3a2f4050bdfc9d9ae0f578a93b4181fd43efe549daacba5c7db9","infra_params":{"device_id":"c734a1c7-d663-4fad-af07-817b064e424b"},"app_id":"com.bloks.www.bloks.caa.reg.contactpoint_phone"},"bk_context":{"is_flipper_enabled":false,"theme_params":[],"debug_tooling_metadata_token":null}}',
}

response = requests.post(
    "https://b.i.instagram.com/graphql_www",
    headers=headers,
    data=data,
    verify=False,
)

write_response(response, os.path.dirname(__file__))


def get_phone_request_body(data: BasicData) -> str:
    reg_info = {
        "first_name": None,
        "last_name": None,
        "full_name": None,
        "contactpoint": None,
        "ar_contactpoint": None,
        "contactpoint_type": None,
        "is_using_unified_cp": None,
        "unified_cp_screen_variant": "control",
        "is_cp_auto_confirmed": False,
        "is_cp_auto_confirmable": False,
        "is_cp_claimed": False,
        "confirmation_code": None,
        "birthday": None,
        "birthday_derived_from_age": None,
        "age_range": None,
        "did_use_age": None,
        "os_shared_age_range": None,
        "gender": None,
        "use_custom_gender": False,
        "custom_gender": None,
        "encrypted_password": None,
        "username": None,
        "username_prefill": None,
        "fb_conf_source": None,
        "device_id": data.android_id,
        "ig4a_qe_device_id": None,
        "family_device_id": None,
        "user_id": None,
        "safetynet_token": None,
        "skip_slow_rel_check": False,
        "safetynet_response": None,
        "machine_id": "h1NxaVnaYULGGzgpCn_hPfVP",
        "profile_photo": None,
        "profile_photo_id": None,
        "profile_photo_upload_id": None,
        "avatar": None,
        "email_oauth_token_no_contact_perm": None,
        "email_oauth_token": None,
        "email_oauth_tokens": None,
        "sign_in_with_google_email": None,
        "should_skip_two_step_conf": None,
        "openid_tokens_for_testing": None,
        "encrypted_msisdn": None,
        "encrypted_msisdn_for_safetynet": None,
        "cached_headers_safetynet_info": None,
        "should_skip_headers_safetynet": None,
        "headers_last_infra_flow_id": None,
        "headers_last_infra_flow_id_safetynet": None,
        "headers_flow_id": None,
        "was_headers_prefill_available": None,
        "sso_enabled": None,
        "existing_accounts": None,
        "used_ig_birthday": None,
        "create_new_to_app_account": None,
        "skip_session_info": None,
        "ck_error": None,
        "ck_id": None,
        "ck_nonce": None,
        "should_save_password": None,
        "fb_access_token": None,
        "is_msplit_reg": None,
        "is_spectra_reg": None,
        "dema_account_consent_given": None,
        "spectra_reg_token": None,
        "spectra_reg_guardian_id": None,
        "spectra_reg_guardian_logged_in_context": None,
        "user_id_of_msplit_creator": None,
        "msplit_creator_nonce": None,
        "dma_data_combination_consent_given": None,
        "xapp_accounts": None,
        "fb_device_id": None,
        "fb_machine_id": None,
        "ig_device_id": None,
        "ig_machine_id": None,
        "should_skip_nta_upsell": None,
        "big_blue_token": None,
        "caa_reg_flow_source": "login_home_native_integration_point",
        "ig_authorization_token": None,
        "full_sheet_flow": False,
        "crypted_user_id": None,
        "is_caa_perf_enabled": True,
        "is_preform": True,
        "should_show_rel_error": False,
        "ignore_suma_check": False,
        "dismissed_login_upsell_with_cna": False,
        "ignore_existing_login": False,
        "ignore_existing_login_from_suma": False,
        "ignore_existing_login_after_errors": False,
        "suggested_first_name": None,
        "suggested_last_name": None,
        "suggested_full_name": None,
        "frl_authorization_token": None,
        "post_form_errors": None,
        "skip_step_without_errors": False,
        "existing_account_exact_match_checked": False,
        "existing_account_fuzzy_match_checked": False,
        "email_oauth_exists": False,
        "confirmation_code_send_error": None,
        "is_too_young": False,
        "source_account_type": None,
        "whatsapp_installed_on_client": False,
        "confirmation_medium": None,
        "source_credentials_type": None,
        "source_cuid": None,
        "source_account_reg_info": None,
        "soap_creation_source": None,
        "source_account_type_to_reg_info": None,
        "registration_flow_id": "2bfd5926-c03f-48eb-8e17-a98ed947592c",  # get this from registration button click
        "should_skip_youth_tos": False,
        "is_youth_regulation_flow_complete": False,
        "is_on_cold_start": False,
        "email_prefilled": False,
        "cp_confirmed_by_auto_conf": False,
        "in_sowa_experiment": False,
        "youth_regulation_config": None,
        "conf_allow_back_nav_after_change_cp": None,
        "conf_bouncing_cliff_screen_type": None,
        "conf_show_bouncing_cliff": None,
        "eligible_to_flash_call_in_ig4a": False,
        "eligible_to_mo_sms_in_ig4a": False,
        "mo_sms_ent_id": None,
        "flash_call_permissions_status": None,
        "attestation_result": None,
        "request_data_and_challenge_nonce_string": None,
        "confirmed_cp_and_code": None,
        "notification_callback_id": None,
        "reg_suma_state": 0,
        "is_msplit_neutral_choice": False,
        "msg_previous_cp": None,
        "ntp_import_source_info": None,
        "youth_consent_decision_time": None,
        "should_show_spi_before_conf": True,
        "google_oauth_account": None,
        "is_reg_request_from_ig_suma": False,
        "is_toa_reg": False,
        "is_threads_public": False,
        "spc_import_flow": False,
        "caa_play_integrity_attestation_result": None,
        "client_known_key_hash": None,
        "flash_call_provider": None,
        "spc_birthday_input": False,
        "failed_birthday_year_count": None,
        "user_presented_medium_source": None,
        "user_opted_out_of_ntp": None,
        "is_from_registration_reminder": False,
        "show_youth_reg_in_ig_spc": False,
        "fb_suma_is_high_confidence": None,
        "screen_visited": [],
        "fb_email_login_upsell_skip_suma_post_tos": False,
        "fb_suma_is_from_email_login_upsell": False,
        "fb_suma_is_from_phone_login_upsell": False,
        "should_prefill_cp_in_ar": None,
        "ig_partially_created_account_user_id": None,
        "ig_partially_created_account_nonce": None,
        "ig_partially_created_account_nonce_expiry": None,
        "force_sessionless_nux_experience": False,
        "has_seen_suma_landing_page_pre_conf": False,
        "has_seen_suma_candidate_page_pre_conf": False,
        "suma_on_conf_threshold": -1,
        "move_suma_to_cp_variant": "control",
        "pp_to_nux_eligible": False,
        "should_show_error_msg": True,
        "th_profile_photo_token": None,
        "attempted_silent_auth_in_fb": False,
        "attempted_silent_auth_in_ig": False,
        "cp_suma_results_map": None,
        "source_username": None,
        "next_uri": None,
        "should_use_next_uri": None,
        "linking_entry_point": None,
        "fb_encrypted_partial_new_account_properties": None,
        "starter_pack_name": None,
        "starter_pack_creator_user_ids": None,
        "wa_data_bundle": None,
        "bloks_controller_source": None,
        "airwave_registration_code": None,
        "is_sessionless_nux": None,
        "login_contactpoint": None,
        "login_contactpoint_type": None,
        "is_nta_shortened": False,
        "should_show_bday_after_name_suggestions": None,
        "should_override_back_nav": False,
        "ig_footer_variant": "control",
        "device_network_info": None,
        "is_from_web_lite_reg_controller": None,
        "login_form_siwg_email": None,
        "account_setup_waterfall_id": None,
        "is_wanted_suma_user": False,
        "device_zero_balance_state": None,
    }
    variables = {
        "client_input_params": {
            "family_device_id": data.family_device_id,
            "block_store_machine_id": "",
            "device_id": data.android_id,
            "lois_settings": {"lois_token": ""},
            "waterfall_id": data.waterfall_id,
            "cloud_trust_token": "None",
            "machine_id": "aXFTbgABAAHw1cpzzsgkxOLUNm6H",
            "qe_device_id": data.device_id,
        },
        "server_params": {
            "is_from_logged_out": 0,
            "layered_homepage_experiment_group": "ld_no_language_selector",
            "aac": '{"aac_init_timestamp":'
            + utils.get_pigeon_raw_client_time().split(".")[0]
            + ',"aacjid":"'
            + data.aacjid
            + '"}',
            "device_id": data.android_id,
            "reg_context": "AViY10bOxkMUzLp3WtkOICp-WRgJAmMNlDN3UvXM2bfKzozG6DwsEQGT4JmNeEONuPWrEoGSxlvhdmEK_sxXpjLqeBJ8B3Fm68zVpULGLuNCT0IqKoPVWQ-9N8BPmZGMSoLLzM7q8qiqtm2uYrZBgGIX_dbY7cnTfpm29Ha1MtlkUtK53JL4p8h-IG2NABBYmgJlv8CM9FqTSr5-HKuhY2HQS7M5o6A4D55ESx5vwDYaW7bBflN09ORFZ0JxbnStfrwAyfYIDiRg2Xp4NBACq1hEzJ1h2GJFq_h9KlKmHds7CKy9QULHnOC_XuxCnfxwvVB7XVBhxOqEJIQawaQf9HJs2bjCj-oPkAb7nm8Q8PiZIHjkVjJkSIjKc6dRfsAzBelUODrojy-LojmwvQEPQOyKVfEecuRsz-nmuRDsTs6HS_lZl3qs2PlwGwOfX-DyHBORDameVPVu9KOceCMBIZHluOSSI5dJ7mwxdL67589V7BHQYxWjyF8Q9NgyxJf-GOmb1F8LJlQpG0LEyvFsDeQlRoOoMXMFiwbA6nnoYRTTeLRYclczNSVQ4h55io1BPBUtGK4ystK33HpfIUpdq_Kys5ATTVaOA97wJCIurtdAwkGQfmzNK1QuQexHEYhBUC5XsheEH8ykItpLbHytWKh4RbdP-vnXh9krOowxInRJZ4LqTqDJ5s4x0erfJf1DyWTjZEP7L6R1WsQT-wqurpO_G8d_kIhRNDuiQULkef9VqjZoNHBv_lOowfL2_RhVhsF34_jUnAO31O-jSBot1GkHpBahpmH5GD0FW82bJWDOWjaf-FpJZob_6LWkkHqQePqpkfmKyvj_7DGeD7UdcptsxRRqCH7vUWO_PEu9TKF3yZEo7lM4rSMiqhIl8Yh6mYT1X2LBB1LaxcNBlwOwFW5M0PkMCqCncEM9lPsTVJRlPVCG_e_viifxvUtt3SN1HLGBTUPvyyvQZsldwtyxa0BGu8-2uLzEMSaJKKt8v1hdGiHB6ISmgt_s8BJcc5i06pCkHxrxAyzToRRbOeR8r5roqx1l5VRHWLxn7H0lv9fSXmGj0mgj3McWHaMYYHhw6Y_5H4HvXm8tlTEF6lQKeuvkz4z0wiINIzrwU1rpm5tp-Y20dwE9DYAPogwDNe0WEkSltcvi4zq-phINkCh9f2WLaBGwFwBG1Gh6RVmKfYGgUiv2zsWd3vwuOMLwzserkDteB-GD5jbtG-BumhhyI-L0QxL5OiSXkFBwGEA4xOfwf2IHHaU9K75iK6_LLEH-QufDGBt-wgLEdIRCwR-Vy_C2tpKH8ZkkiBiEVFWQTCdAjNkebmW6-eORowzLIqK85N3l-VPcOkE83FLci5DepMrQG4KY_7R2deeI1M38GCsNXAUAW-AFIgsc-myBdTZed0hiaHUHc-8SbSHZktEnAUwVZDtXIyohEqCppjkAf_hVe1IdhdXNO20brIaFZ9zefYuWNa47jZHlmERxkP9Vpl-shqFm5BSqzh97mFVQODINf3zJkBqYicCyMBsDGSAhk_rTTM8bK-JZU9thcKQdI56uOQwdIyXe27xKZpfkOvpf7oy0qUe-45_7U9Zzsj-3vEjPkTIBv23sZT_5lhKkhuYBc4iybc_a81QVbjewKsM-2rnZPRvz7fN4gV3OJu7D9xUAocuoGPvVC3HCLXSiM89iASum8kR8Ul_B1th_njwGTVtrwhO0MonNNVcNUQ32eKA_ZEYS_Db2ZiK163gUUckqiXVaudxCemMecaux0VHZderseB_NtOIr3Wc09MpZ9Bz71mGmff0fDCt4yBt8m_WC5G_HYVOwynFgZqlxR09phyTQU1ZylcnRwwKOWyFITOqBYmahRXtaiWRsuRI-ItJ4e4cB6Dky73Nq0kTJN3FojK6zXL2nmxA_KM1jEqLb-gg-9dGVPP1FHjdjA2PCu89lp1rFTpMw8e52ypyPtW8Mjcy1Uo3PTnYkgxIJiPMLq8PVb7sfkkGDLictX3_k3LrV7acxuHbZYrbhKtXhYBRngfUPjl03WAu73y--Bib4QNupQ2yZFX2cmuqq6MDPRwcs-668D6X4Grb3v6d4ElkDRSzquOvlJaXjmDvYAH9q31yEa9BSaJXvNsbnrfunDr3KwQmXDmczA787za3WtiHYDEIi3yXFdh6XzOH_Ng62maRSqc1tnCkq2mM_dweN-jduEp_bbScSJVzSB7JGrdvyzl4UBpzH6QY82spG-NtSa1gMT_0ACRQJucskrJ2GObvJ3TwG6cgE85UK4ILYKvCNxzadiiAyybtBytx5ZrxckkUOIvCkpkhxYJ3ymIAQDupJOk4GpJWlBTx0R420zC4OSQQUavPOtYfOI6WV2f0OZx-lKxdrwHVkVcU2xZy5AfSuVbLRIbhIIEeOBwV96X40ja6_QeLJe-BqxH21QqUeivyZp_Pt1JLnyoIlbXV2-Noen8Z4T8dPnVPSvrNPbPKeIj2Psdyc3nIt-OR6oTzzF38ooqS-df2D_rzMuDjL4GbmkGRlHHFIHaJwj4ueQqeiu5Ll5DTGXbtrrLPEQ843MFUUM3SVPoHX24ITVtFnPueWCmxTU9ODXm7AiivDYpwgFnXpvkJ46pd9ibtnFGWkjPdJPW6J-q0cMWYbhKJoqGvfxeysAb2JKhWC5yZSAmgksiJ21Dqb7mdAlXhD7njklDlNl9nXQ-4-hFN2oetzTpHNRcI0EzMgNasmSZSLUXnaFTQGXpQa1wINnwqKv7FwCq03N7p8zjLR1fGqgaH08wdPpJ3u5j4iqOuUwOTBOMf-fJHZFAFwCDNno9nEd40Uzj3thYQbODHZ2jRP9wSkk0Q-WM16J23FVZBdxovt8fSBPjun-HjdiTMunGBIr9RjKptvHSs_U0RwfoRbXyF-_tcTghdPFCPZ9HHjtAwR9VzOn-gC3i8K4X35yyJQVwh1NRCGNtNFLANihyaQfhCZf1-9KQcVykjNGQ-Rihk281orruaH5WR3pBXe794sKSLCRu0yCmmZ-uxfECapMfGA3LSzHgBOgw-7uHgZ_lH3GF8osjz-YsYe5PQAFxxTwVr2dErBmckIC3MNGctPqz7KX_TET3dspW1xy2wIa5f1kf38a-XHxvLfV2HLLKGoKYa_usvx9G3cGy7pd3C31nNpz_fB6mfewhcufzqbbYMaX4bDIV_8qObpjkJzaYEbiS3OaUzHLFcd6wx31i46JjjhaHDPmV7WYYFr21aA9dksvC7_GGHQKvy72CRCpBOrYBc2qot-uVENBTTzuy5Ora2pC6H_JxLjxnFhZy0cAKYE-rV9EDrkDABrMq87BG6fsbEEpa9CViC2ej3a3_mLGaNuY8NiajJsbkkPBcSzBqNqHgAJAfUMmOcfAQu9ACMj9Df1R7-vlQRRHlk8z0f0hpN0mtfZWa05gthZZbXjAfuOK4VRAfZZ7e6l3vdQBJOQCj_FGkZMY_vz0WYKzPOgMM1d6GE2v_fjy0mlEkyRr6-PjMB7X2CVAI6aoztCdjkgdFNn3PtzyyNQaqf7WuEd3d8kHc5nmHmy96i4flxfK8XIRgXc2r99kRZtfiezU0j7jKzLkpkk2_UThPqsKnXFqWVOm2u_4tmNHwOjWtQvj8jVn2-gyPk8wAm3ax9nw-qeNvJu1nWDLBDdHngUZJp_RXXtaUmJIQMKx_PrHipb2Dt86sMz31jHhKArQ9628vugDH8cnUVnCzANaLhhDSFAH9643l2br4W0Hiuh4pj1b9eACT9bm0aTrqkJjFG9mlUL8TkAkhthea7XyeMWREpVGlYGHYI3ar2vihiOlXsZo5CLzdiRDrA9jPlIqMvVDyuVCrzwrGIKcbrssVznCJWa9wuNjyh1cS59apms6h_IWbQr0IrEijCjDFqxrnYfu_9_q8RPqFS99Y18RwtQSNSoY1PRx9kbCXETofXLg_xLCKX-dy1LuWa3GZoxHfQ_2uHPpDmoVCs3lM5IxZBQGX-aTV8TNDXO3Ex5bkP3zaJeIA0N7rhjilL1Fa9IfjYP0D5k7rKSvt_FKAYFEh4bOdD7wAnKcWj8njkcjZhmOwfyQRZG7k5tCd_yF7HbHVhBfczbLee-tFuT01ri2v6Hc3q-2wmcl-zmZd5ZC285NbkBM-gRzRNgz7cb8TrY8Xtz4Ch9OQLoGT3G6tsdIwx26jgZoXndzIRNknYoPmyHXzQpLAoPs7mHgzrsfAypAwF1PjU4jcYMlGQCgg7Phz5Xvg03cgn3Ljwp3tPasLjHb5ftIe5LE8cQolxq2FWpgcoQkIMJ9PpWQ0NsoO499aN6mJNq1t54Lo3GzwhwsLtY7LsHY0qHI7AhEEFRvIgwtFT0NTGCEgIBW-OPEA5SV15fviVuzcqEbO9wU3OTQTZo1mx4iRMd54jb3htueNoAzOkeD0pLz2acnQsYqAtsvSV3THg52JMb_5VtP9K3qKwCWty5BTAhEbI0aSPVEAFaDtOXqxWV52b8P_02lZUMmmDXBk83rUqzsIM12eOQ02cm_pLzpj80MCAAN_eZk6YtBsnoBmA6ramgu5CvUrpnokduR35sKXjHNs4Vt3Yeg4NkmoocsJXGtF5KEhFj7eatix1JTR93YJebHxMHoKkcInEtre6P-GjcVH-L4A-21tv6H0n8lfz8mznLbEOzbpaiNqnyP_WtVsE3yc7LBQ-KZBoGs9YA9bs2D_7ruZcqhtdxAERVd5hfExr9B1KH9IaPHT_E0iCeC2EfotpMuutIOlULv1KwKVUppNXMUCrfeDSlF3umGFq7o58qpUUduYka898ANc4dIEq04R8oKmqKC9Bc8R9RElJNehLeWgU6rm_EacwH7Dlc5TzAIHUwjRh4KrGXIDzZs_ERaVx_2P-j1fhfvkOX63d18C_MFfYvyWxq6J5h1Us_EJZLNmbCe-QKa53FrAfar-AeYzmkLP2LuagrQz7VswWMKb-TAiNOXceTYPKKqGxnFdLyntuy2WUjzqJx3ITT1-k65wwoteWzJXz-qzY8aFK5ha-RYbtVfTTYH6d8cFLH8h-5E101cjCwcJBACQqoY4H_wktvb97T_r2rO88XVZ6clsrBgfRMah5tiUtxZJ8-m-PIsY0B1PteJY6Mw3qICIVdd6kjvl1yns3iM7lGkNoGYTJDgESDbanleppHRBs7TytDv3TU9XsBsqGQ5_KhKhAL0DoM5jaX0yAHRnBU7NLs7lI8DEQ_ZHQuMs5gQY6J4m1C0bi9GdiCOCBDj_lvAqRUJbsyfGooCjzfepG1Ogv4zeZW_UNTk6xRYqUx2Cn-zI6xBqRGnFHou9JaVlJ6R2SqIP928A5nyxzS2JZAyUVMuDM1omdm9n-PDBS7sM-jVEaq3rSbz32Iji70nc8OjWYjFVS-ElhF8oJoonypJqUSda3m_fOks3ODbGTVZGiQA_N-iU1YkUESwsKUn9xlGro3SwDsawuV0qLqDl9INlYMO7I6cR9I_dFhuqHRM5h-AWwEiCPDOMkjgRXdroUC3xeORiUqJ2Z-y5nbnrD21_udh68tcx1_uM1ho22mKcsXlL-YcTrBiCodU5esA7gjlGyi1u_TJAkC65a8CrcPYkbWMuOLOz4O9qLybYnZmQsH8_LMjTwRoWaShhuatDHmIOVEob79dHcJLM9duwc5VtiDHJe5NxfJLzuj1Q9Y97iwuuy-zUjOvupf1-MlfjhjyIkXXg6yugMd36CuzMJVFXwlon1KIE3-RVpvMOkFq3Epmnqk7aFmqM7pMGfAmKGAEVdswSLKUCcVLbh1AyjD3E4ZxXi4JsxD2KHPuF7pO9tnxeaPLj6MiuLXlE-ka4f0Sff_l3NUDg9CNyyKlirqoU3QF6U6xe3YHcZ_UhYQp4hNHT0hJ3ofBKb6wc_DRxS7BZDP0iHNZ-Yl3_NHN1mutFZ4d1UVmVkkrZnfR6h5MQyh7cPfOjCI4HLGHwFiXHw7K9wZEC_Nodb-AOgWZLGQsQOZYH796NTlM8zJWRIjZOG4-nsoNJkKVI-jftG-QGOuM8aZKtbJSWk6zXscQm0f750Mpi8g-8qvf-_A-37OUIOWyStKZMsmtt9_bxfHZF6VD6ZpW4PwSnLxFnf7AGbJyJ1sYU2OcRmF5T2tEBJV6L_7UHmM-Y7ZOclS9ZELlx9k5UncVdLUuODTwd6tMijRmWnTitbPDnKeJAA5N6NkFs_ouaIiv9nV_kXXeSGZv_uXdNzyrmmoRT3ew4A4d6DOg5iUw5ZjUHF3IRGVtrphgURp3LMU3ZGD9CKj2Ps4EAkzcBeHcO4bPFJYJ7QtzPgEOlvA0hSRWPf1aQNxemePWzrzMULNFIOx5AFg7nnF5TjEceFW9Kwzpj6S_e-WeO0Z_Fs-LRxh1HcRFPo62hCgUiF63n2qUgJljLqW-vycs09-UtocWin_kPPQPiYrrEemtdkDDrEA56ubKuzhuAJpbgYzxAwlGt1VLSHNltWnj9JHjLaKAhV3uwlIRPR-UbgidtnkfVYP0xorK1mrOMfTiOcNxnA4Odk_QsgmdXObfe-9vnvLQqR75TIPBtzeXk5Z002nRa2YjTTkpbV3YtZOPx7zivwC28QX2AO4j3IfmJzQ1AiPP4Tg8N99ym9uwMjLQfH7s4rtBvsashUdNw0sAHaUKBfjPWEasvH1YwYJLd1byehaEOD3Z7wssfWgkAz88MKElx7Yd2r70tRSMYAhA92CXskRU40YvKcC_aaLkdfS1QkcVgaibHF8INPDR3bqnTG44BsQ6DLQmzluxXJ-G6NSMn2_64hyjjmKNSyW_uMjfYlEa7eX6-l620uChGJo3gn-0MSDoWJfm595loMOc_b2Qb2DrHVL2wzbNQp90XY418XGLdRookV4pB5agWtSo9sjoTXIMKoPZUI3o8qd6XhE14QGMBMdTE9IoQ5hkKmtdri6r7YKIZMWiN46YroyWw78X5URc85c63_Y0AwUg_su4ByhEZf9cv7x9tGJx4nC4kKBeLybDxOhpsVlR5WSoIsYAT20_xe2c3jU18cwBypOF7t3XCxP8pB8tFrunWQeg9SoddorzuMRxV3qbDTFRgE2sC39_FM-I619SmAWGvQn65gNaw5WwoUjDgOtek5yTsUsVnB31armhxZnJMYsSLqfISzrM1TJRH5ugN1fXz4OQdODtVL2tydtoHcx7SKNsiyNUHVFI1whahTyU3GgJP4OOUT61z0P-uAuu_P1gaQcTgz5yDPZHvma5eekJMszhyJHBIHD6cYRSinfTTdWSAeqwYf7qT0oFTSuVWGeQdCkjce4UwCfOw4-MlY0kIRfA_mfQg5vcOUD4B4DLeSiDknItWkVEhCFhOpJ2hqjhP30pu5AYjHSRg8PjPDtbYJWFSo-9LNYx72YLoSz3xX446WtznXRjDWTEPxrJNMTge0oZ_lruKJr1XtVyhyroAe0zMwQ-x1Ibkzld6W3K27Nw4RkcmBdWpBYFGSoYFM2xKKhCPJcQeoOUcA697pluK5jMI3CXGGndwYqOhAwEO7C6YIEie3mcNq-rjcUygz_nphKz7g_dGAHKWxwVvRgF3-arxfy4_VbOVqqZi8fAd-0HXDQ4KMKTZN_Vck7QwRsliBF2XbbCKNilMFzlTdLDzmjG2pD84zDA-lOggX1R0_MsN8F23RcDk86knYrPt_U5HW_2HMJnrAhtwQApsPGotUU5qvOSmXT7fQferAiysI9e-LYDkHTLn86LybaO0ChwaXpsHD28wiAbDs4rADzWpkEx9CEpdd_w6ym305pcPioIKQ7gANdhAB5gVZZEgplED--hcYS-MQIiJl480E9dhMMvuwkMqA4ut7fuwD3mGaGG6Grubcejq3_nYkd2vf1gWWHS8A3AxCC6fpvLHGJ4nt5aZdORMQKvbGenJiICEn5crvzCVWEa9-JrBH4yR8Utehr9xOxgEckRXNwtLYX-zlw1lSBxvo5wAHv5ZLOBHoEQ5KwSnHldPoRhl0j8tIGpmyeaLHIJ8F8s8VUfEc1577EMsf9YPNyEAgljtrFn3WKbMSqIiWfcPxrRbzqwfHjET6jF7wcuN5eOG0Mdba17Nagb8Juf-3Urvz1UzuGyb_t4FxZaS74105uzJxTv3tMZreh5SjJx5fk3sqVuqAjYcQ-EZJhSogRTuyuP9mw0Xj7RolXrNcq5WFe4Lnj2v5Rj9VvB_m9U-S4cspEIowd-E64GktW-5Xr_rtVCmdWla3Rp88Ol59Mb04ka3QLT1gqOXs143pD9QuqemB9xLxgFxrkp_P6KG70W1Xh8MLSaO7bMOLve9OKpTDCtE7Is_R4pSih47jl9M3k16FfhiSDM2iBZ5FW6wPq9byarHMD6Zr-Fd8Ehdw8Z9R-J9mQQQYFSJfpMlG9YjeCbWgvnsWTpp-LaDp5Z39wvEeSPd6oJLyjXoTMgO67O2LqS3mboYWx4aptAFpCerBrNQzoFN-dDBgkEu_wRDEK6TBdeC91Bui9Ea4LGGoGCK-L1ehNfG47lfjCOupFq3q7t175opZpMT6uHZkrMpjvVR9VicEl8FNyysb4WGwED5D8VkqOAKuJ90w|regm",
            "waterfall_id": data.waterfall_id,
            "flow_info": '{"flow_name":"new_to_family_ig_default","flow_type":"ntf"}',
            "is_platform_login": 0,
            "reg_info": reg_info,
            "offline_experiment_group": "caa_iteration_v3_perf_ig_4",
            "INTERNAL_INFRA_screen_id": "CAA_REG_CONTACT_POINT_PHONE",
            "access_flow_version": "pre_mt_behavior",
            "qe_device_id": data.device_id,
            "current_step": 0,
        },
    }

    return {
        "method": "post",
        "pretty": "false",
        "format": "json",
        "server_timestamps": "true",
        "locale": "user",
        "purpose": "fetch",
        "fb_api_req_friendly_name": "IGBloksAppRootQuery-com.bloks.www.bloks.caa.reg.contactpoint_phone",
        "client_doc_id": "253360298312778871684788706414",
        "enable_canonical_naming": "true",
        "enable_canonical_variable_overrides": "true",
        "enable_canonical_naming_ambiguous_type_prefixing": "true",
        "variables": json.dumps(
            {
                "params": {
                    "params": json.dumps({"params": json.dumps(variables)})
                }
            }
        ),
    }


def get_phone_request_headers(data: BasicData):
    return {
        "Host": "b.i.instagram.com",
        "Accept-Language": "en-US",
        # 'Content-Length': '27226',
        "Content-Type": "application/x-www-form-urlencoded",
        "Priority": "u=3, i",
        "User-Agent": data.user_agent,
        "X-Bloks-Version-Id": data.bloks_version,
        "X-Client-Doc-Id": "253360298312778871684788706414",
        "X-Fb-Client-Ip": "True",
        "X-Fb-Friendly-Name": "IGBloksAppRootQuery-com.bloks.www.bloks.caa.reg.contactpoint_phone",
        "X-Fb-Request-Analytics-Tags": '{"network_tags":{"product":"'
        + data.app_id
        + '","request_category":"graphql","purpose":"fetch","retry_attempt":"0"}}',
        "X-Fb-Server-Cluster": "True",
        "X-Ig-Android-Id": data.android_id,
        "X-Ig-App-Id": data.app_id,
        "X-Ig-Capabilities": "3brTv10=",
        "X-Ig-Device-Id": data.device_id,
        "X-Ig-Is-Foldable": "true",
        "X-Ig-Timezone-Offset": "7200",
        "X-Ig-Validate-Null-In-Legacy-Dict": "true",
        "X-Root-Field-Name": "bloks_app",
        "X-Tigon-Is-Retry": "False",
        "X-Zero-Eh": "IG0e09d776530888418ab70f3822fbb4e1",
        # 'Accept-Encoding': 'gzip, deflate, br',
        "X-Fb-Conn-Uuid-Client": "b0d866e0c3142f00b867bac783116a7c",
        "X-Fb-Http-Engine": "Tigon/MNS/TCP",
        "X-Graphql-Client-Library": "pando",
        "X-Graphql-Request-Purpose": "fetch",
    }
