import json
import os
from src.utils import write_response
from src import RegistrationData
from src.flow import utils


import requests

headers = {
    "Host": "b.i.instagram.com",
    "Accept-Language": "en-US",
    # 'Content-Length': '28336',
    "Content-Type": "application/x-www-form-urlencoded",
    "Priority": "u=3, i",
    "User-Agent": "Instagram 410.1.0.63.71 Android (31/12; 420dpi; 1080x2274; Google/google; sdk_gphone64_arm64; emulator64_arm64; ranchu; en_US; 846519343)",
    "X-Bloks-Version-Id": "b7737193b91c3a2f4050bdfc9d9ae0f578a93b4181fd43efe549daacba5c7db9",
    "X-Client-Doc-Id": "356548512614739681018024088968",
    "X-Fb-Client-Ip": "True",
    "X-Fb-Friendly-Name": "IGBloksAppRootQuery-com.bloks.www.bloks.caa.reg.confirmation.async",
    "X-Fb-Request-Analytics-Tags": '{"network_tags":{"product":"567067343352427","request_category":"graphql","purpose":"fetch","retry_attempt":"0"}}',
    "X-Fb-Server-Cluster": "True",
    "X-Ig-Android-Id": "android-f35f126bc4795e76",
    "X-Ig-App-Id": "567067343352427",
    "X-Ig-Capabilities": "3brTv10=",
    "X-Ig-Device-Id": "c734a1c7-d663-4fad-af07-817b064e424b",
    "X-Ig-Is-Foldable": "true",
    "X-Ig-Timezone-Offset": "7200",
    "X-Ig-Validate-Null-In-Legacy-Dict": "true",
    "X-Root-Field-Name": "bloks_action",
    "X-Tigon-Is-Retry": "False",
    "X-Zero-Eh": "IG0e09d776530888418ab70f3822fbb4e1",
    # 'Accept-Encoding': 'gzip, deflate, br',
    "X-Fb-Conn-Uuid-Client": "95b2bb513e6c590b7147b9e4bcf849d8",
    "X-Fb-Http-Engine": "Tigon/MNS/TCP",
    "X-Graphql-Client-Library": "pando",
    "X-Graphql-Request-Purpose": "fetch",
}

data = {
    "method": "post",
    "pretty": "false",
    "format": "json",
    "server_timestamps": "true",
    "locale": "user",
    "purpose": "fetch",
    "fb_api_req_friendly_name": "IGBloksAppRootQuery-com.bloks.www.bloks.caa.reg.confirmation.async",
    "client_doc_id": "356548512614739681018024088968",
    "enable_canonical_naming": "true",
    "enable_canonical_variable_overrides": "true",
    "enable_canonical_naming_ambiguous_type_prefixing": "true",
    "variables": '{"params":{"params":"{\\"params\\":\\"{\\\\\\"client_input_params\\\\\\":{\\\\\\"confirmed_cp_and_code\\\\\\":{},\\\\\\"aac\\\\\\":\\\\\\"{\\\\\\\\\\\\\\"aac_init_timestamp\\\\\\\\\\\\\\":1770893519,\\\\\\\\\\\\\\"aacjid\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"68ac986a-64e3-4549-a584-59d4563d06f7\\\\\\\\\\\\\\"}\\\\\\",\\\\\\"block_store_machine_id\\\\\\":\\\\\\"\\\\\\",\\\\\\"code\\\\\\":\\\\\\"468469\\\\\\",\\\\\\"fb_ig_device_id\\\\\\":[],\\\\\\"device_id\\\\\\":\\\\\\"android-0386765ee19c2211\\\\\\",\\\\\\"lois_settings\\\\\\":{\\\\\\"lois_token\\\\\\":\\\\\\"\\\\\\"},\\\\\\"cloud_trust_token\\\\\\":null,\\\\\\"network_bssid\\\\\\":null},\\\\\\"server_params\\\\\\":{\\\\\\"event_request_id\\\\\\":\\\\\\"24356277-4798-4e4b-b4c1-e1224b0aab0f\\\\\\",\\\\\\"is_from_logged_out\\\\\\":0,\\\\\\"text_input_id\\\\\\":74299438500143,\\\\\\"layered_homepage_experiment_group\\\\\\":\\\\\\"ld_no_language_selector\\\\\\",\\\\\\"device_id\\\\\\":\\\\\\"android-0386765ee19c2211\\\\\\",\\\\\\"reg_context\\\\\\":\\\\\\"AVjbF0WnZAfmNpqR5Z8kpxkZzDXW2cDtb5mFMLmKdAPtny6oLvA02WNMyBM7jT-Tp2dvqtqJn3XMp_IS2jSx4MIwnJvxAn1AkVpBp7-50OE4bbAYAbMKS7Qmpx3pxL3qklXslr6ffvq6fQXUYF94u1undrAVJCaEKCPzDWGhhrrGUP7OSxN5FdHXaTLqZhW55qo-7gqPlZx9iT4lwFFI_C6PHOrVmybTPvac91KWuRXw1XV85r7zm5-Azk3g-2xZYDQvgrx_UsQ2NjrqBjIKR1ww5JLLuLYSMfDdmcyDx3lbW9TeJhMrM8DXHfEfgiPZeguji13bzrpVLUwa8J-FRaHz3bDStpCA0uaGZMsT0G5X07_USyH3fhjlKQ3EKpw6XUuZO6rXwLB2k77txLzbhZrRvvCrgZYI9aQo6LB8xufbw26-Iq8H1bWlZ2pYHMLCusj19-BrKxvQgymSUHPg0RGGSM_Qbj5iRS43WfV38dTkFD03fPNydbaa0siOCnejYXuBre6ITTVPI3cIgi9duD9Eg0L0EDe_1LL3cdM6MKSVgelwaj1t87Fb4VrYKvOzj7NeRcU12D3QFKgYi5jO6kZANFeVt1_z6ud3hKKgbA_wwSYCRlcwIH4IM9G7Pt4JoAfLFK0bdq3_EPnOsQgbgjlegTwUzRDeByDGgB_ttm1sMrso223n599El1DCEdPgk6GDwGHhLi63pItFYwGfB_xHfou2_69v15vnRkMzGVGgnXbzipC7YtHH1ZIYQl1HSEtz_BHAHipHrOdpQeUV0A-vXEFVLZmO301Legv7uXNU8FzP9ZzhsMJ_m3UWKIMXAAqjsIazOLmbnU5Whc70iu1pNEZiP896AjIOebbT64Kk032v_Bir6qQPQEfLp_MR1Wn1si3Q9AmZ2t-v6wxbsEJ49q943Fbpj-vYAx39G6P2jFi4Pxn81VANLGqkzRyJMxz_T2IYseV27hCWodMAbMOO-r4QwCNbL29Ohq75iBRznimLVWlYZnHYJ4W8wXL7t9OG7-f152VShirrAuZ0EXGT2AOqIJYM7WU1l0lLP7cSzTkn3yx6EZp0Wg9NKQddW5dIeEPM-mtAPHREeMmg2AONLONlOL_Aws7lSANb2MH36l62htWU9Hm8PYLHtHPPaTiyjE5RA5xHIbIJddWjNz6HrvKD7bq6-yuwJjQ5YP_tK6LRDtIbq24z2BzhWaXt2m05aKLOLtyeNntRLZ6KJDHe00BK4schsLlrV-6gxfiEpoJjeLxJ7GowSLtjWiA-7NmPRict2Bt1WQ56Cv1SJ8G9zm0HiJilM159bpqIj8N4KB9T8yXKS6kyrPx1CympMpEfpNKSRbEtjsT2TdzuNzj_Lm2EcVT2xzbKwmYH89EzNNysHrsdjXOCCH3ZC6iXjy7pZLa_134C6aGWlTxbmz_SVTqvzShlWkb1MnhKBOmRweziPkMesMxr8LUC6WpQ_A99yHwC_5DzYBcmyt0Eh8NFoYKfXrkmqMnJjtUZurs0nw7EuxUmdzdVyTp_reuA91JYL8uQmrJOF0MCfA-fubciq817Ui2DRCsm2nfj762iYP99FqYMlr9IinYeCNSvlEplLuyhmlXLukLemr1OJ5ArmeK4KM8NJQhqzDRSkdxWCt7YgTQbS1isgMj621JUczWA_F1tsFnk4Irt-mlRC8-EvqTKW8PkgyDV07htsTadwa-V8191xxgRZjnVl8SnOIdmuMj-dCMBQQtcSo3Xg_d64u1TXgpLKJ07YSj5_PdFOnB41IruJYcJNf3eaHNHgI1MI9Q5OHzkJheyYJyMuM5tITjACIS0chf3Z_HXZWRHC4i4WSuRee6Aff1RgNEcAnkiM_A6SAgH1VaLRZB3e_VdAXcODcyj_sYd6nBuSpgL42H14wDxtEKWX0kenSetnCS9qlit_kJooz1ydo3RjFw8KEshk6dF6kRIqDLKiCP20NbnHyBbx90VBcmUicLF58zD3NaMZpjoZNP1182Zgw9_eMJ1ZBsmFI0JQHeUtQuxi2z-l50pVXEsVbZjbVlWP72zBbBrIGAcs3yGS3nfwOU0ChEVmwXuETNjSF2Q6_WSsojWMC-PFOhBSyaJ_P2KSBrJnOfwYKk32CY8NV_-qrPRbaCpxao7muSwtmOPaJtjy6JLyV1rFqBPO9dlSQJcZfyLL1SOyOjCzmNkbIY1wR9yb1GjSFb1aw1ygE2mihBue7x46QA3yGHh5SVoIrV5hCknWHA7rbhLphwaPu3I9HhGdeiSl0pHalw8xcF_7jAk0FGosLDV9QWjRs0TojywpW-QhydaJNd2HDvctLc1sB1-aIMh-NzpcKeTCfG0uCz9Ee4C5nlcJiZYaKnAobIU-k12qatsKVN9xIyk-ltlq9TpIgpLss71d5MkmO3EjplwbZwh5KijTtAZK11f9wy84qvd5F-iSabHGd9ZQsNbNKVxybl8BTUjTsjZKNNNF8DWW_TmZtH8WTwrZJwP0XjJdsTDq07u8M_616BYFp0znzmMT_SjFfKW5sqoSAvHSbfcoaJgmhlSpcXVsI7nqZdMQsJvuxwQxkmCKB7uK-FHrtuqR3S1YhIKjOWBIn7OGPYWnIx5ST9Kc4e8rbWOL8DtrDzn8GLl8f_DhJaaiUfEXFGACxRRs_Aj9lZSF2Ary-cXzgriXijFBcyk39aPIL5hj_wkMleixAtbZx4Q_wg5cd0A3c3Xtw6kxs57KgE_5v_pp9yu4Q7_R5P1eOexLWYAppAHkITOR1xrAOoEGxFmIDzql-svGdeZ4BqzaWzvsQHnDfInWdqpuxJ2BDz5Mf5NJf5jxsYTukrHD4apm4ff9tN7DOVvWm73_addU_uPZucsMW-EfNMPE4P8UbIHgJNzqKwV5qoLB8G6UTwqSQNjUirnAk9ZgR-J-uveMqvK2I8v_9aWvNYWJD_5gvU9h9oBgmB163F3W0UVJ8f4lU6_aGxWN7otYPH_mpA0E3vReWA7T-FBGBEvz93jRz-6NGTw8tQrHZMJ97xRhzIdtq5g9JOlkSYeJrQJtXQ4--cSHGVHyqDsZTEzjGA2xIj1x6bLts6qIGhJ1Z1Sg2xb99sdRAHyHjjK96YVszBGq_MvuvzfO4ppwn-kOBtL6Vi7JaO7U-1QyiARNFf6G8N9B4oYnqGq4TZ3jQTXVJRH02Tay7SQJV4zKz800KJwvWJuQ3B9UpFQpDRHbZR-V2xQbJWXGq7CW-kBt_AO742o4pNOzXOdHORHabrZxS_2POSPaUr279I_nT1zfOBJGqNkzKIkPma1kzXFo0vxthUcyv8TE0xwzh1gQKPuNkjsUaxVYfiI5cqUcBMO8zyRFleZQ2jVBMb63vDCPXq1itRKAvkPiDEVLsy1xcTBO-ONxMaZeY-Aj3QmVZkWkX3zuosIdc8TFc4DaVSeWo_foBG2GkVl8ThGNDB84NmR1OrK0rzezC-nqvi9IgV7FrZwnGmdP5ygoN62PBlYPAAbtyt3q0hq1WRQF69XGhb0UjEhZlTb7gaVqUHsogba2qQz-pynA3KHFkDJ3k92SszOMIRs7kU-o5X-h3pHiT6_oYyVDvHrh6LNhS4KOYhZrsHxo5f0Ycw4ewpZJDFjxyZO62WFJmQzQw37TmRftLgUBdZAdbrs_EVbyzHieVSLj3PwfiqPDNLDwyFmrfhqY20QaL9l6nZge_r8BckRfesNUl75-Pf48nh8xjRhI09CSpYqj_CRbdz1x9XVgkOyfvnSoerCqzyyrns_1c3W23gkoPzNEiOrVkjQwRfrEA2Z0MmLolhh79dANgSJNbqpVL31GqdNk_ISwqT_aUrei7aT1A5tftEfX_s8q-CB8E16SWeRi3zmEX0N4GBRYtIlETfe2mbfHZUuOhWECFHGjrObLDhgvHUMBeH9GEMe-yqJT6FwwpjCrxlhlzMDeXcN27kNDev-cucN3qbVW1AV9TmHqsoA4mNEhGYGd32Ns7ZYXCt0EMQc3Swi3HrsaEcU0UqixHq05EKTT4T0vqmA4fIOgMI0NR34YdYKRtJnCQYe2RhUOz5WiqU2qrmFB_ESMQrw0CV2BMhZseDjWLdcBDclxYg0EwBbIPwcgfhykyHO2nr0dRMCOMOanQ9X7zyu2xXYBU0acrKEl4eZ27sHTt7abFkI5A-KHxc2Sm9_ob3kjOeilBFkZ5LvSWZ8dJ6cJpyLc8YqEUJkQ-uI8c4_x1luPQwb6exClybtBOMHafin9l9NPHZ_ilXLLjhAgp_QrC6i4Sh0h8dNcsEeEHfnG5j999LYFBchDPXBywg_ZOPI1nu5jcNgr59rs4yUZrPFUGA4Mdnb2R0AqMATUjqOScfDrpQ9DivTAInxV_FbFB_5GmfG_pLIb5PVmyK6NtLG-9r0hQd3N__St-8HLO03Fj2Prbqjy8RxY3po_0McO2snRjnEAJPn5tMdiyKaJxMYPkDNyLsKIZkCkwAbV4lGhzEa1R5alx39vYWFmfSJfsJmjKVDQzT7BijZeB647U74R7ICEf5XWtC_9qqBrvs_3drv0vIsA7E5tZxMhDSBcaTiVDPBmOinlmKA4ZGfID77bYKSyW_yIleltWGatPJADthtq5o6SELBAVi0lt0CI6isqRoulEkeaqzBo8dck0HPZVcueN4cAPt4CQo5u9E7nvoKcr50pxsPVru8gwSuddr48IY2pt_Z3YemhvaO12hJVknvlVrOpuXF_eKMebdzzGlZKYXXkVG8R9-Y2rN2Gn7e6Q-nkmogn3FICA8qQmAcYOM5MzdyTpuRO6S2R42qDuftw2uxFlskGEN881rAhbhBpqE5XhKYfpxQKwV40QHEhd6OLSVFUl3oaIBvsTuYVgcClXWaDUmW3sf_FdbiEdRdYq3R-ejNOuzPIPlxZse7FwTqFqUJmTtTKDXoSd1Geqmhw2JRCLNclJnOsCIW2FglAt8S5IpoKcFgKAQnBm-4R4MDYCgDzdEOk4G4qFA3a6tOx3Wj_d3QWEfeIQx40YmRQtOop811RFdNrmIifp1NLr-APbC7xj0V3a7EVHvZqtsT7PhvIPFGqorL-RvPEEqjfFt0UONsgcSv-dZKLDInQytVhsqQabJnOA_ZDGNQRzDaTbypT3zh54M-nkp3rzVdAVnwyD4DiSD7mNZvQ78W59ZLiYMcpMu0cq9bVNUEfkpAEmfFbpc4RPn3AozGN_znA5SQ0qY9Kc0K6yBodur3TXk-QzdfPIhvVOClJeKNGulvhwSe7-8k_gp8mPIUuz9IlAIb8KPShYVyPdR0-XDe3xnnVbEOh-io9jjM91Q1-R1fER0hQ8g6a2v2Au845lcZcixQLnfBOEXZZqcGTLqgDm0iig_O5g_PYQaxIVmpLviuC8VUPbiKNOXedNauqPfLwFj799j7vF9wshhynro1HKkcOwE4mSDNr8ZpVcz_yWyTivK9vjKo50OysycZYTG-OMvjQ_4ojzYSi2aVohtdeLfI_oEHtmpRxJN1YiLMpqZOPuWEAvFluSzWADJUw4yV5mxD87VggUxy5tkdG2xvOWMp3HlqYnBZ199NjYVuNcMVRXsA1CMMqgwsgxN5gh78zsUXizb_mAY76rFWlaWuD1O1xKSQ48ewE1961c15O9ftwVSbiJ5ldOIr-OXUGHVmLHShBV9H4kADVltLJrCmVae1UfS49jHgYGjf5W1xyClgUU1iL9Cyk1lBxiVpPCxwmizX7WA57f3-QmwJ3J3VR8rVADmidhmCW1ByeBrWlJZvgWgE4wj1dq24reFiDGbytA5gZHvsFzPgYs6E29H6Ju1Rm6uEFypoYLBApV8YlX-jhPLIKbOdqlfFiON-Bf1WdtyjKRNrzJJCrUwqUEWtMIkKiKDVuhgNZn9sOwf2siFZOG5yLgOD2GTzrWkgnvcZ7_PYDCaIYzFVErc_ZMeE7P97Z07_Beq_4UfnGHr6vAIEOprDcqmPR0Yp89wEsmVGj60lh39ft-_vNxxD3n9MdFQ51W6DFMkMJQbvXaT_comkq30vXyTmuNrIC1SFA7-Vok1zIzVd25HTfXoAsMzrZXGa2GXUTw9OdnbvWq9RNexpRG2iku-355WS8ib_KMJcLuXMmwXtXZYEGmSh0eC4d9Ggq0oqqlBl4C8qmy7xfZDIV50UoFy5B0bCbSWfGblAxGAAAMgFebvWoNQt6K-Si7vETYpzYLUgw2eQt48G4MgzqcMTaXbGHYCah1p1c7L_qSbIQBxCkGsdtUvqAmkrT1Kead5YtrfVmTKc_iIXQjOaYoeGp1hrtxd6POIcESKWzhUwsOX2PupJsnfiBkrsGBvo-SZa3ayKn9GUNpJ28o5yPjo9gTI79nonhgfhnoB_JJgulpCEG6F4rwsQI15V8h6gx9cIE_257If5j3xDvSN1zd2AFVzZWkww_OJeuPTWyzgGKL2P6ArB3u7uMEtd6DXhj_sbzvIJMRoh9JDRECNDWg7amsdMdNYgCVdHLrKBNl4u0-e_8o4J5ffINRt0aY8jTpyeQcR5l-0FHSCm3Y3HT0MqyWL7nJ7CbH1ESY6vVJzFFN17XZ_EW1W0arXXS8SiRjx2WMn1FrgBLWjhbRDKpXisXgmFvegHYBGOWcMQfaCrrOTwna3uslEJVabu-QVZ7BlYUaHwP7epPkycofPmk1Cbt-2CfFOryfHrnc_G8-WtcuEEcbs-YYTu2YriB8XaFi0c0_Xnb7vN7k-E4YYTRgUtNGURQKenFF3rei1LZtX8ISTBnm8sVn0Wcd_go7GcZJSrxLtjRp48o9Kn-vW6x81d359gCCazYUYuvtsxLrbRAkNfoyCqzhUqPqrstL6wAZGGbBVgPExTuu6Qge5v1dqrTLzmA7LOfXSUUqwgwxAbpF-e36bvRtmgg5CIunQ7HtaJ19Ud9PSg6JzosrHC2Crey339DOGmj0zvbna44mY34Ma3qWbcFOI4DfvDXHAsnAbGyvLsEYwSPxMWGi7uW05L5SbO9Tx2gJ5KmE-VjzxLDPd9d_KQwtAbXRKijOvfAYS8xeDN6m2px6Yc3dLpheGHLNsaRvSIEqgofe8oHHl6L8Pl5YzyjXcWwQyEfDdOY9an27ksrWVHnuO0QRxfZ9IwLS9mZC8IUNGf14uio2QEZOc2EPqwlW_Re3pwRhruwwZ0NGG9Evc1DwchiUw9z6JPgA3vf9ZOAOqaLNPCDwDlWuxb3USx1axa2-BGSGnbEIi0Ti50Bj4can4XQrvvfp33eRGxAQuUuLIW7klFq-FSjPz2sAKghHISVLJ_rpXJt2-bdzJXyzF2-4fWiVC-vtWcbYu-HP4qOA4KDkl7r-ziMTahs61zGXWl20moRmZSkepkOz-rzQQCKjiYTG6WLI6EFmSrfcn-sFtLg0ZuGpVviejEUenC2q0tpspvZdbQHs5dY6mMDsYxuO7eOZQzPUGIpUTqcvcgntbLF7btgEGIrfl4fslj_gDURwzvNo3BlE5IT78AVSUZ0H2qbTMZ8rMs4OUQI7q7knKH-K302bEAHmPrvscw5TX3TYmyB2OXx2N_QKRg4NrPVp6QvuL2QiESo9dJWESeO3K9gZvXfUx9JK2BotQ6tDHSlQgArNBLVsRW4FV-sbHQcQ4-E7NdcoCjouUUmtq_TMgZH3hbc7dxHjJZVn_0bb9Fs4QJ_zpZMjBT0q1yVohsBW_se6_Zx2KmJV2NXzQ3MiSekz90VLolYMCYZ2W6iQNlxuGwv4l6TGT7qln3gtHyjwy9tVX6d5l3y-zcgBcOpKOxYm3RJIBowyssgrD15qu_ONru5eDEyhxTFHaK9wDA3utQSJB1dqU6M5YM_202sx4Hm43KLI5lWoAJ5Mq0YbkPmmZUKS9gUsI4Xz_vXD5g-NWiKpAwIqepiWniivuMjqkMiR5spv99ShAIBhFLmFZ-mCb2Ng2b7HnprKNk9nfKxbQEamrhH7R3kF1yp0Zi6dNyHUqJgguIBdj_afcWrYFpramlVtSa-vd9CWDz4rDht_AQhnxHnmO-8w5dUNxeKkghQYqJDVDy4jg99fI9H2h55yUAjMhdWzFIetObS8OvdPcJjbQLd0_CCIjXVe1axCObcY5yJldDhrt1nRomuEL5VFBbwOed1qdKcR7lkqIBjMbdY0rlxNaRLUVQwCjpC9w7zaKcx7mdp9IjVZ2UEYaOeKB3IYDLewlD8qxEBHx8FiDWtg77kTJBMfQuSPhkMjOJf9QLXmrne6qf1crakq9zo5168icYJuNYP6yHfoTpjAaRIq7tszDLmfbMDBuNSZFUYY1itbePNIcYaHGUNgi-0YCFrp3KUidO4cpfNbAvzk7QbonDFV9QVxbcTBCnrxheO2sI6Fsy-LVLLIbY0bzqO8cQEkcWCuygvNZN2NhBCR90aITJp6tIh2tpMe6x4XNUOYlGBNYe2acUJB_1CY0yXRowjMruDMuJvFvyGcr9DqpQpB-JWUBnN8HQlI4jz_P_XGko2k2eYZ2FAyytA5DE3A60OjLIAfGaKjYeDmvVjqHORAiViUyaoEwT6EpQAoFnEBlsRyy_MU3AbVc4ijfE7yXBfk4baw2T3RCHcAM7KS0CuKGVV2opSVGLtyZ0T8royiXTgcALNOo2Y39DBpGXvWGXow0QZfD-NGG__Ah7GLq6XU2iuttuUZ-ilKAVzhTt_Ow5wCgd3Udgh_cSNTNBAPl15VdQattMoyVbxy5o-hPPSpUNTDsdsHUwt-cMThoEUMB_rGwcCSlj6fAiqG54trkI-12Xb43fh3l0Ycyr92bCj6n3NovYMAKSNPFwMl5xHU7J1NNjrUsq-                          ",\\\\\\"waterfall_id\\\\\\":\\\\\\"dee2aa49-2355-4097-9f0f-eeaa9e4cc4e0\\\\\\",\\\\\\"wa_timer_id\\\\\\":\\\\\\"wa_retriever\\\\\\",\\\\\\"INTERNAL__latency_qpl_instance_id\\\\\\":7.429943850079E13,\\\\\\"flow_info\\\\\\":\\\\\\"{\\\\\\\\\\\\\\"flow_name\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"new_to_family_ig_default\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"flow_type\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"ntf\\\\\\\\\\\\\\"}\\\\\\",\\\\\\"is_platform_login\\\\\\":0,\\\\\\"sms_retriever_started_prior_step\\\\\\":0,\\\\\\"INTERNAL__latency_qpl_marker_id\\\\\\":36707139,\\\\\\"reg_info\\\\\\":\\\\\\"{\\\\\\\\\\\\\\"first_name\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"last_name\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"full_name\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"contactpoint\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"enserhriziomr2cc\\\\\\\\\\\\\\\\u0040outlook.com\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"ar_contactpoint\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"contactpoint_type\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"email\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"is_using_unified_cp\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"unified_cp_screen_variant\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"control\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"is_cp_auto_confirmed\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"is_cp_auto_confirmable\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"is_cp_claimed\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"confirmation_code\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"birthday\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"birthday_derived_from_age\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"age_range\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"did_use_age\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"os_shared_age_range\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"gender\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"use_custom_gender\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"custom_gender\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"encrypted_password\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"username\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"username_prefill\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"fb_conf_source\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"device_id\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"android-0386765ee19c2211\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"ig4a_qe_device_id\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"5b506631-5663-465c-835a-39432e917259\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"family_device_id\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"945ba9e9-b955-48a3-934b-72726bd49844\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"user_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"safetynet_token\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"skip_slow_rel_check\\\\\\\\\\\\\\":true,\\\\\\\\\\\\\\"safetynet_response\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"machine_id\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"z7CNaUmTlYWmnlThuoxypreE\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"profile_photo\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"profile_photo_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"profile_photo_upload_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"avatar\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"email_oauth_token_no_contact_perm\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"email_oauth_token\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"email_oauth_tokens\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"sign_in_with_google_email\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"should_skip_two_step_conf\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"openid_tokens_for_testing\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"encrypted_msisdn\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"encrypted_msisdn_for_safetynet\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"cached_headers_safetynet_info\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"should_skip_headers_safetynet\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"headers_last_infra_flow_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"headers_last_infra_flow_id_safetynet\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"headers_flow_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"was_headers_prefill_available\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"sso_enabled\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"existing_accounts\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"used_ig_birthday\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"create_new_to_app_account\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"skip_session_info\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"ck_error\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"ck_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"ck_nonce\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"should_save_password\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"fb_access_token\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"is_msplit_reg\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"is_spectra_reg\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"dema_account_consent_given\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"spectra_reg_token\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"spectra_reg_guardian_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"spectra_reg_guardian_logged_in_context\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"user_id_of_msplit_creator\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"msplit_creator_nonce\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"dma_data_combination_consent_given\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"xapp_accounts\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"fb_device_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"fb_machine_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"ig_device_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"ig_machine_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"should_skip_nta_upsell\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"big_blue_token\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"caa_reg_flow_source\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"lid_landing_screen\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"ig_authorization_token\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"full_sheet_flow\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"crypted_user_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"is_caa_perf_enabled\\\\\\\\\\\\\\":true,\\\\\\\\\\\\\\"is_preform\\\\\\\\\\\\\\":true,\\\\\\\\\\\\\\"should_show_rel_error\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"ignore_suma_check\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"dismissed_login_upsell_with_cna\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"ignore_existing_login\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"ignore_existing_login_from_suma\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"ignore_existing_login_after_errors\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"suggested_first_name\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"suggested_last_name\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"suggested_full_name\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"frl_authorization_token\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"post_form_errors\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"skip_step_without_errors\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"existing_account_exact_match_checked\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"existing_account_fuzzy_match_checked\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"email_oauth_exists\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"confirmation_code_send_error\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"is_too_young\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"source_account_type\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"whatsapp_installed_on_client\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"confirmation_medium\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"source_credentials_type\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"source_cuid\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"source_account_reg_info\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"soap_creation_source\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"source_account_type_to_reg_info\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"registration_flow_id\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"d7c268dd-e599-4a71-b587-efb6be445c56\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"should_skip_youth_tos\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"is_youth_regulation_flow_complete\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"is_on_cold_start\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"email_prefilled\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"cp_confirmed_by_auto_conf\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"in_sowa_experiment\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"youth_regulation_config\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"conf_allow_back_nav_after_change_cp\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"conf_bouncing_cliff_screen_type\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"conf_show_bouncing_cliff\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"eligible_to_flash_call_in_ig4a\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"eligible_to_mo_sms_in_ig4a\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"mo_sms_ent_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"flash_call_permissions_status\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"gms_incoming_call_retriever_eligibility\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"attestation_result\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"request_data_and_challenge_nonce_string\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"confirmed_cp_and_code\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"notification_callback_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"reg_suma_state\\\\\\\\\\\\\\":0,\\\\\\\\\\\\\\"is_msplit_neutral_choice\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"msg_previous_cp\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"ntp_import_source_info\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"youth_consent_decision_time\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"should_show_spi_before_conf\\\\\\\\\\\\\\":true,\\\\\\\\\\\\\\"google_oauth_account\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"is_reg_request_from_ig_suma\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"is_toa_reg\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"is_threads_public\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"spc_import_flow\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"caa_play_integrity_attestation_result\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"client_known_key_hash\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"flash_call_provider\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"spc_birthday_input\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"failed_birthday_year_count\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"user_presented_medium_source\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"user_opted_out_of_ntp\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"is_from_registration_reminder\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"show_youth_reg_in_ig_spc\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"fb_suma_is_high_confidence\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"screen_visited\\\\\\\\\\\\\\":[\\\\\\\\\\\\\\"CAA_REG_CONTACT_POINT_PHONE\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"CAA_REG_CONTACT_POINT_EMAIL\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"CAA_REG_CONFIRMATION_SCREEN\\\\\\\\\\\\\\"],\\\\\\\\\\\\\\"fb_email_login_upsell_skip_suma_post_tos\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"fb_suma_is_from_email_login_upsell\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"fb_suma_is_from_phone_login_upsell\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"should_prefill_cp_in_ar\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"ig_partially_created_account_user_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"ig_partially_created_account_nonce\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"ig_partially_created_account_nonce_expiry\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"force_sessionless_nux_experience\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"has_seen_suma_landing_page_pre_conf\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"has_seen_suma_candidate_page_pre_conf\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"has_seen_confirmation_screen\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"suma_on_conf_threshold\\\\\\\\\\\\\\":-1,\\\\\\\\\\\\\\"move_suma_to_cp_variant\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"control\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"pp_to_nux_eligible\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"should_show_error_msg\\\\\\\\\\\\\\":true,\\\\\\\\\\\\\\"th_profile_photo_token\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"attempted_silent_auth_in_fb\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"attempted_silent_auth_in_ig\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"cp_suma_results_map\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"source_username\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"next_uri\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"should_use_next_uri\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"linking_entry_point\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"fb_encrypted_partial_new_account_properties\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"starter_pack_name\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"starter_pack_creator_user_ids\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"wa_data_bundle\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"bloks_controller_source\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"airwave_registration_code\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"is_sessionless_nux\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"login_contactpoint\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"login_contactpoint_type\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"is_nta_shortened\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"should_show_bday_after_name_suggestions\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"should_override_back_nav\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"ig_footer_variant\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"control\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"device_network_info\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"is_from_web_lite_reg_controller\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"login_form_siwg_email\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"account_setup_waterfall_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"is_wanted_suma_user\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"device_zero_balance_state\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"is_in_nta_single_form\\\\\\\\\\\\\\":false}\\\\\\",\\\\\\"family_device_id\\\\\\":\\\\\\"945ba9e9-b955-48a3-934b-72726bd49844\\\\\\",\\\\\\"offline_experiment_group\\\\\\":\\\\\\"caa_iteration_v3_perf_ig_4\\\\\\",\\\\\\"access_flow_version\\\\\\":\\\\\\"pre_mt_behavior\\\\\\",\\\\\\"is_from_logged_in_switcher\\\\\\":0,\\\\\\"current_step\\\\\\":3,\\\\\\"qe_device_id\\\\\\":\\\\\\"5b506631-5663-465c-835a-39432e917259\\\\\\"}}\\"}","bloks_versioning_id":"b7737193b91c3a2f4050bdfc9d9ae0f578a93b4181fd43efe549daacba5c7db9","infra_params":{"device_id":"5b506631-5663-465c-835a-39432e917259"},"app_id":"com.bloks.www.bloks.caa.reg.confirmation.async"},"bk_context":{"is_flipper_enabled":false,"theme_params":[],"debug_tooling_metadata_token":null}}',
}

response = requests.post(
    "https://b.i.instagram.com/graphql_www",
    headers=headers,
    data=data,
    verify=False,
)

print(response.json())

# write_response(response, os.path.dirname(__file__))


# def get_confirmation_code_body(data: RegistrationData):
#     if not data.confirmation_code:
#         return "No confirmation code provided"

#     reg_info = {
#         "first_name": None,
#         "last_name": None,
#         "full_name": None,
#         "contactpoint": data.email,
#         "ar_contactpoint": None,
#         "contactpoint_type": "email",
#         "is_using_unified_cp": False,
#         "unified_cp_screen_variant": "control",
#         "is_cp_auto_confirmed": False,
#         "is_cp_auto_confirmable": False,
#         "is_cp_claimed": False,
#         "confirmation_code": None,
#         "birthday": None,
#         "birthday_derived_from_age": None,
#         "age_range": None,
#         "did_use_age": None,
#         "os_shared_age_range": None,
#         "gender": None,
#         "use_custom_gender": False,
#         "custom_gender": None,
#         "encrypted_password": None,
#         "username": None,
#         "username_prefill": None,
#         "fb_conf_source": None,
#         "device_id": data.android_id,
#         "ig4a_qe_device_id": data.device_id,
#         "family_device_id": data.family_device_id,
#         "user_id": None,
#         "safetynet_token": None,
#         "skip_slow_rel_check": True,
#         "safetynet_response": None,
#         "machine_id": "h1NxaVnaYULGGzgpCn_hPfVP",
#         "profile_photo": None,
#         "profile_photo_id": None,
#         "profile_photo_upload_id": None,
#         "avatar": None,
#         "email_oauth_token_no_contact_perm": None,
#         "email_oauth_token": None,
#         "email_oauth_tokens": None,
#         "sign_in_with_google_email": None,
#         "should_skip_two_step_conf": None,
#         "openid_tokens_for_testing": None,
#         "encrypted_msisdn": None,
#         "encrypted_msisdn_for_safetynet": None,
#         "cached_headers_safetynet_info": None,
#         "should_skip_headers_safetynet": None,
#         "headers_last_infra_flow_id": None,
#         "headers_last_infra_flow_id_safetynet": None,
#         "headers_flow_id": None,
#         "was_headers_prefill_available": None,
#         "sso_enabled": None,
#         "existing_accounts": None,
#         "used_ig_birthday": None,
#         "create_new_to_app_account": None,
#         "skip_session_info": None,
#         "ck_error": None,
#         "ck_id": None,
#         "ck_nonce": None,
#         "should_save_password": None,
#         "fb_access_token": None,
#         "is_msplit_reg": None,
#         "is_spectra_reg": None,
#         "dema_account_consent_given": None,
#         "spectra_reg_token": None,
#         "spectra_reg_guardian_id": None,
#         "spectra_reg_guardian_logged_in_context": None,
#         "user_id_of_msplit_creator": None,
#         "msplit_creator_nonce": None,
#         "dma_data_combination_consent_given": None,
#         "xapp_accounts": None,
#         "fb_device_id": None,
#         "fb_machine_id": None,
#         "ig_device_id": None,
#         "ig_machine_id": None,
#         "should_skip_nta_upsell": None,
#         "big_blue_token": None,
#         "caa_reg_flow_source": "login_home_native_integration_point",
#         "ig_authorization_token": None,
#         "full_sheet_flow": False,
#         "crypted_user_id": None,
#         "is_caa_perf_enabled": True,
#         "is_preform": True,
#         "should_show_rel_error": False,
#         "ignore_suma_check": False,
#         "dismissed_login_upsell_with_cna": False,
#         "ignore_existing_login": False,
#         "ignore_existing_login_from_suma": False,
#         "ignore_existing_login_after_errors": False,
#         "suggested_first_name": None,
#         "suggested_last_name": None,
#         "suggested_full_name": None,
#         "frl_authorization_token": None,
#         "post_form_errors": None,
#         "skip_step_without_errors": False,
#         "existing_account_exact_match_checked": False,
#         "existing_account_fuzzy_match_checked": False,
#         "email_oauth_exists": False,
#         "confirmation_code_send_error": None,
#         "is_too_young": False,
#         "source_account_type": None,
#         "whatsapp_installed_on_client": False,
#         "confirmation_medium": None,
#         "source_credentials_type": None,
#         "source_cuid": None,
#         "source_account_reg_info": None,
#         "soap_creation_source": None,
#         "source_account_type_to_reg_info": None,
#         "registration_flow_id": data.registration_flow_id,
#         "should_skip_youth_tos": False,
#         "is_youth_regulation_flow_complete": False,
#         "is_on_cold_start": False,
#         "email_prefilled": False,
#         "cp_confirmed_by_auto_conf": False,
#         "in_sowa_experiment": False,
#         "youth_regulation_config": None,
#         "conf_allow_back_nav_after_change_cp": None,
#         "conf_bouncing_cliff_screen_type": None,
#         "conf_show_bouncing_cliff": None,
#         "eligible_to_flash_call_in_ig4a": False,
#         "eligible_to_mo_sms_in_ig4a": False,
#         "mo_sms_ent_id": None,
#         "flash_call_permissions_status": None,
#         "attestation_result": None,
#         "request_data_and_challenge_nonce_string": None,
#         "confirmed_cp_and_code": None,
#         "notification_callback_id": None,
#         "reg_suma_state": 0,
#         "is_msplit_neutral_choice": False,
#         "msg_previous_cp": None,
#         "ntp_import_source_info": None,
#         "youth_consent_decision_time": None,
#         "should_show_spi_before_conf": True,
#         "google_oauth_account": None,
#         "is_reg_request_from_ig_suma": False,
#         "is_toa_reg": False,
#         "is_threads_public": False,
#         "spc_import_flow": False,
#         "caa_play_integrity_attestation_result": None,
#         "client_known_key_hash": None,
#         "flash_call_provider": None,
#         "spc_birthday_input": False,
#         "failed_birthday_year_count": None,
#         "user_presented_medium_source": None,
#         "user_opted_out_of_ntp": None,
#         "is_from_registration_reminder": False,
#         "show_youth_reg_in_ig_spc": False,
#         "fb_suma_is_high_confidence": None,
#         "screen_visited": [
#             "CAA_REG_CONTACT_POINT_PHONE",
#             "CAA_REG_CONTACT_POINT_EMAIL",
#             "CAA_REG_CONFIRMATION_SCREEN",
#         ],
#         "fb_email_login_upsell_skip_suma_post_tos": False,
#         "fb_suma_is_from_email_login_upsell": False,
#         "fb_suma_is_from_phone_login_upsell": False,
#         "should_prefill_cp_in_ar": None,
#         "ig_partially_created_account_user_id": None,
#         "ig_partially_created_account_nonce": None,
#         "ig_partially_created_account_nonce_expiry": None,
#         "force_sessionless_nux_experience": False,
#         "has_seen_suma_landing_page_pre_conf": False,
#         "has_seen_suma_candidate_page_pre_conf": False,
#         "suma_on_conf_threshold": -1,
#         "move_suma_to_cp_variant": "control",
#         "pp_to_nux_eligible": False,
#         "should_show_error_msg": True,
#         "th_profile_photo_token": None,
#         "attempted_silent_auth_in_fb": False,
#         "attempted_silent_auth_in_ig": False,
#         "cp_suma_results_map": None,
#         "source_username": None,
#         "next_uri": None,
#         "should_use_next_uri": None,
#         "linking_entry_point": None,
#         "fb_encrypted_partial_new_account_properties": None,
#         "starter_pack_name": None,
#         "starter_pack_creator_user_ids": None,
#         "wa_data_bundle": None,
#         "bloks_controller_source": None,
#         "airwave_registration_code": None,
#         "is_sessionless_nux": None,
#         "login_contactpoint": None,
#         "login_contactpoint_type": None,
#         "is_nta_shortened": False,
#         "should_show_bday_after_name_suggestions": None,
#         "should_override_back_nav": False,
#         "ig_footer_variant": "control",
#         "device_network_info": None,
#         "is_from_web_lite_reg_controller": None,
#         "login_form_siwg_email": None,
#         "account_setup_waterfall_id": None,
#         "is_wanted_suma_user": False,
#         "device_zero_balance_state": None,
#     }
#     variables = {
#         "client_input_params": {
#             "confirmed_cp_and_code": {},
#             "aac": '{"aac_init_timestamp":'
#             + utils.get_pigeon_raw_client_time().split(".")[0]
#             + ',"aacjid":"d2c8ed10-f952-4a12-aa09-e83671b1bf71"}',
#             "block_store_machine_id": "",
#             "code": data.confirmation_code,
#             "fb_ig_device_id": [],
#             "device_id": data.android_id,
#             "lois_settings": {"lois_token": ""},
#             "cloud_trust_token": None,
#             "network_bssid": None,
#         },
#         "server_params": {
#             "event_request_id": "a74f96c8-4c34-4f13-8dc4-a1e613af4b9a",  # get from "next button click request"
#             "is_from_logged_out": 0,
#             "text_input_id": 131241622200161,  # get from "next button click request"
#             "layered_homepage_experiment_group": "ld_no_language_selector",
#             "device_id": data.android_id,
#             ## below is "pre_mt_behavior"
#             "reg_context": "AVjTreZNHdqsQoQD0qc-hdeiACw_CV4EczuMK2VICTc3m0Uipao131ioUR_BraVWDaOYsu5wqcCewNHYtiUrEJKaIgMaLCcci0nmD0FoEAPPOuxbraP__gnOy2B4lnF0l85RDZLGBwM92GHXWokWmbGa_OoMn4fc_TYE_WeLYjAy9XQPaDUtE6Rfq6ELDTlNX7S0p4NeGgMZk9YFZyIpUWPd4wo4AsiWIgCvHoDXfy6Q2wxb9GV1mQ1gMl1JMg3FSwCZgO2IXEj7J5X3_YYOSKvtSNmhLUBqplJoxSdcLHZJ81m6kaL76ie_wP51VNAf6vRx4aL521qRzAa0UgyV63MScEpqcd_FaNlK8olLDFh8mc5eWoolhtdQl276p3xw1DQcuHgXW1ONEP87z20fQihroN7jTe2JZKT0tcKpcmVSHjP5TraYo-9nF3uphkX5c668ELfHqw3Btt2HeJMFdhL_Nfxh9bb5W_Rtx_e3R7_sWhusuSO_JdFjUkKbV-FXyXYQ2W1MiNwuSXoGJ1_iOHNhrV2wr1qy_R5J7gBpi-mStAMBH5MliZpDv7yAPldchKko82jBwzMIVJy-ZBsw8mQwTq8DkAtS2QCCM77y-jFVj0h7ydTh2P1BMnIcFFdJlUwny00WvzPlSyx9shks7CytA1MVNWNTuXIwBHBNuIOJbG8j8ct5WRxNg5jrQCjknR_v2YW0tZCWi6Zy6D2-Fscj09ziY8_w9rviwMQ-rYrVVOGvZs5N-6lRY-jE7Ab0fHDSQDkCuoMjL0QVnsCeRbJhn2OUd0-KpQ0P7lVxpfZd1AjNqgFPwBRm1W-pq7op3FgP2l7OAMrfnfFjQj7hg7gLMeaw9NIGCtllgnqLckHxPfNzL2osSYzGG7M-pS4PQuZbWMj7s2hsogrYfVkIRHowhNG929De8Oi21kV1BYSHNC3QzEaMi_UlJPzWWGD9FQb7-gX4_boCEe2d6ijKkPfg6qsju7RkhHDt_79GpsNjMqw3lSYOwRmf4MiWymu43Qi6FN97gFVSYJ6uAXt5zRDkjrh1Tb8Jbw7E7URR4Bu1rniY82kN7mkRKG7yq4L0nn8Ab3-j0YZbR_Shm0fRCgkVw0VWJy6UeXR_BzXL-mpRCRruRaBb442fibMUktrEbY5W64rro5WvyJaw64fLgwi_RLL_DC8XHZzS7wapNSVYlQVoxNA92tN3ztj2UbitnNyhUgDSIDmzZRKc_jWs7zB5wu_FO32UQ3mNdB6ExiN_L1A-G06uVpnSTy_qm5Ej7bt_xYvc06wstRF2IGOwq2jPFxPJ47B78_LeD5qE2ECvynzf32BP3O8PSaw1AqS53k1AxBSjTSg4YEw1TvMlB6dqWqtM-nKoi4WvpEt0JKDZBb6ZohKnORHxeTghs4zkhq9dcwkro95hh4YdxJgIYFxzUrOXOhymxH_Kf0jQXIw9IyXcAbA7s4zNk5cJ60_h-TBgYoPNQ_9_LmttZZnPQB4VyLma5NAqiEZ1LL6uOwMBoaJRax4c8bNdvPVjbXRPgWDgSvdIAHbP3moHvLJzv-hMpD3Bhcs4xJCRe7nSw8qySn3LWEgRUPBJG5Ih0mEwvnCWnRKdjlMIapFHvnen-WQQnu-k5lnE-T4doL4c40vK1DDJQAqCLpz3RjAPWa81lCl3wsxN7cxDPDbvSYcvX6VEnUFjbzQ5yxnjYuXdTUUrFknBaoWoqv9FxdkzXTzdt3i3ux0gy2FtICLxvmCi8TqciaL-Z70ScXEfC_Ri5BwT_eWNUFLhRXa0ynUaPqDso_H3vVEknAyKxCSXVVhp8OrgLmWO8Wjhs0BYoiSogMJ_V0A9T_Y9iu7WkUexRDoFa1Qqvs9sALId-ec1ml7uJlTIybpfgOYcaUahQsiq0tFl1AveP4zVw9KcTQwt8f8P-X8FoUg9AnSUaTONW4KKqBKnf5OovppIrJZEL5M10H4_68YuSWQL5hbtCUjvGLKkB5WpAUi8di4v9V5GGF-Lc2530a7HYd8PTUEQQtiZYqGWo8C7sdJpfz0TfiPGufCpUeKdYoTs5tNoexzbPPb2NStba_GbB4xeruVt7l2fjREBTKnNjScPo3H8UaSPcLpQNafzdr13yxOZPEjxG7ZyG8ZcvYgxzWmZ9QwjDyWbljEcHx6yMA0STvLiVNYKyVgz0ZvU4tnEgK__cju0yR3t6HkSnUScbHd9rBrLgKbv4i-8iZf1SwSggSo38RRzAZh9bSsjpyJflkDriQ09-a9cad8v06S7eq1JSv7k8eJQbQJJc5OYgA3F0DWex8mFhLOojz2ecHv-pPWWWauRFkFWle2f0lrArcsLeqKUBQFT27sM0PCxhXo2jLUK-yKsU5zbCoM2mcFaYh7LjN9IclCgN9qejp6LlD91_JCWhC8L7dVYJuepAJKO_d435bdWzb7iIfgvTw_0_4Fmfoo_RaCXZ7btdHHU8o9ULNE4Z8rDe1gkpqfdHt8fv0RrEto5gFOkYtlIh-GTKKqtYnMHHRSiwfhJ_cjZNR6MYtWvqTATOdAAsvw_oxmb-QQfhJjtBZ6ufT4StvRo9fvgKrKOy3eNINlCb3clfOuztKia8diF5fNNhjeBMSXjZ6-NsoB2VyNynKFCBqywEPPsQloomkpcZfgP92j9XEbAupFISAm3rd_0TVQV24jV2Bc9ssSJT1xvVc_K90N5yHMYjCwCNKrZEEydIyX62abuxlPjht4TlFTURMDbRmhgmj6G_6Dq2465OAt7IGLzaE1ko2ed8T3qomKVn8dnlixRLMblintP84IubP6qlX0F0ASI-P-mTnoRNEOKOxNTut-mGVENZWLMip3Tc459GJ26pCrx3LA03UlVtBehscnWUvu3WHzjXuxFcMx1-zeC4uwdJdRLcDhsM4WzavIHfNxwD5XDi771yxO53oyvpPRRj3v9rV-pphNKzgcvua80d_bYZxXpBy_8Ucv8P6Gv_ekRVpux4BaUo-BYzsDh1Sf18tD8ir9fmiBR390Lm06wjn27D4CiiY0TcAxAK32hZ0Lljgpk6yA1EhCvEg437vzJJKcTo1ifR0NRqXyqF7jft7z-FgK1REPVduE-YUWOGWG8gUfSaCk1E5QK1BNgD6eWAJBlSSSwgxR24FxZ4RnYBV7LUNx69wTM3buY2p6MlzD2HyyrNbt4BNanf2CE-yYvwP0QSJwBaVH3Bq55DLxJ3Yr0bZ9waCl2FGUsiKZM2q9buRKy_szurLAXcO6urRoSuRVI0R544Vy7utZr42EKMeXlLiWlxFyE0LDLCecrAY6yrrjaaJgO9TyzxClezdcd632LEfXUeXy9XeuDRiVqmSdXuU9tyrK1Cs9jh4yrn5F364pQy6sdT_QmCzdLOgXPqf2PWt-14n6FRLCmbtVOz-PK37wAINee7NdFoQKmhpG17ee9CeC_ho1ZJljlas26D8T5IqYfNPYI1OVZTWyfZsjOsY2k2HnyR6sA_QEOa2-7CS1Z2DoIauolj1Rpjd6QjJ_tO5adMN19C1gY6ra-50M8h5SOXv5TDnP3b9q_HsZ_0iGsCiUCXzsYdp_-BaKOviMNypwMU4FmImE-pGOWSvJmVDtmsBTD62dvLsitQoaUdYtNj4PRaMnsHb5hNAMdMTNEU0wGzXzF_2HNszkGSloyKnL1icSeT6cxa-YyavNhCf5Dqka0E_6FbH9CDL023WLvp8VRZCbpw4K6YJNEppAFnJWZHQj1dZP88I0jwvWycWycSDX4ofMrejV9KRFxssQpvTCxE6nJsOc_XDP7cnXx-E6wavipTgF3aYiz5upuf6pzKyaYlGsgtpDTtSK0E8JB9GDOGACL0rAbiGxoZbUI0JAZY61sm7GLYtEBcJZ20o0MyscJvLdRHeEuVJPjIDtJBjCQlzyKGZLeagPafYoqCKavkiNExEWhdAtZHpfgTNhMURuMUZYn36yF5vdXQLyeQXVmtVmhs3h8JcOMNwDjmm2dTD3-d5NTzFWNOPZy6Z0GRki_MuM3sMVDObf1sovxjcLljPNOXOyIaMTDCTRyLKHe--HdOBGi_t_-3p3ShCOKwyakvlOuAVrZ6rZO5lxTZaLcQQs_JFImSO9RVNhISFLRNSzGJX1F7Ij8ns1uQPXrZpsnOvD6afWHPI4Oz-2E2XSsdz1wJRhwR_aRrrtiOacq8fdY4DYK3wWHL3PznAvXqWiyzi9FVPt369NSe-SBw4TMQ_biDJkai1AJ0X_c517rkW0qsf8JSah6LuDwFyP3wRFJnT_RA9l0uq0HZUaYENMHKZYcU92reynRvefdrQhgFl93hbKHSGIig5noF5VxpEs6JxSZEiO-hG6Y_nUBcAdOXQv1peMe6j5WZ7b5yxqyOXnZf_-Jc1cbeOHwkM8pW7bBzB-K8hfU_USDCajj7PDAe47c26TBjeMwlMB2X64hQHzub3hVOz8TXh5kp1GMlTG8j9TPAFufy-SGfa38UWDLlZ1HFiF6FHy5XQ23TGUzTvw-0elY6UeTy4qzr0O2Bt15O1OExVAAg2kD6mw_nGbngXgo_UGbhAPA5WYQ8PyT5qR2jwF9U2mnCIrJR6NkQQTapboNt7bO1NyKziiDcMFPvtzmAuGu7YgNSZ4F_K2G1-vjIYsRAespB5gn2enL1Mh37ezjOVhD1OQk0up4kQSqIGTk2SiBwAT2e_ifnueWtla5ICHPhPAHSKdSbGcRPmv2334eHdsbHE4WzW57vkwHT0zmaFpZ4vo5uyKvPleXy9scQmvTseNcbk-54fqjIEENlDJAO1lRhP95VbLPTLUoQmiBbtfctHaOzI9Mez_Bes4w1l1NXEOXdZXnL0aZ76Logfa4B7zJP4R4MLd9lrvBAO-iKGoa_0Lso_VBtTpxEsrMDjG-9LxtGboGjx6Ng5ht-eoj17Mgjp6NpEaLVbE1wOnfyL_tFhv5wnS9stoy84SeA1pEIXWMeBVRf_h8Wo_nunbUNOJit7zLtjqb9_StZcTxy86eQED9V27iI7D04B626Vt5Ed-SlrXNlUZJmSzHGkIGtRY7AOtGeCy1-a6FyPaWjRg5lQytIf3ldq5lCngPMBwHCn2bkGwf2KPD2ug_LMH00KhtFTQCxUg_ib8g0asJmWAWY23Jx8QoekQfqUPErkI_3jwKOlKJEfr0an-MkN8lACKlHCecGWPILzNnvtthpCPDrPSXs2ssSPCJ3dg15eonvzNKtfffahqf_fhFs_tRLSLqdQWMnUwvTn1P_PF123xFC9O2aEiAZXm1cYuA2Vc0fURYecEuvxhBTs4iPT8uPejz-wkLQIUd8k61OKrYmdAHPJ_MeRGEj9_Q8aPjLDebqhik7pStNNOjuMYsiNkn5F9HZ18TimaW_RoG5i8ZDXVf6Bj9NfXBoGGZSMrd9sAn37SICkRXskfiQn8kTURFPIqSa4DhT6wEOenuLuS4gAw77pV7bFGMofZW8mHf8aZ9J9uj2XWYKZjqlFjT7PyoKEldsN65aUb33Mu_tHAk4yoZCtQ1K00am-gA2OhAgEsu4WIt55DNn-_nobBcdUFGvlBsRybRgvRT5mFbmhqFR248K8Wqh5szU2SBdbt3QCc_QcYj2dy1B1iilz34OGiZb-aj7dn8Cbn0-CRwW0YDm7B1_4DRMxU9uOSIo_IXgaR5eoWFfC5dsLLtmNiFniYRxEWQKfxgKnE3GliemcPRRe8my8LRVGmjGW713oaYtNoQQB6J20dutgP4PXhJh7fwD4-ZykkzAEeIuKwBCdGAxuuV-mU6u2RT_Ni8S_QyStRKwWyM2Esm-j7sf0CHKTQoBk9KuMkBUoynxZ4VZbxT8gnS8_OWoLIH0lPqOj4je6oIDt-ELeAV3lvwjMAHYjZ7sOrI2_mrLp9Tuq4uV1FNBWBMUWJsjzvu3ruKhS8H_-ank2xCNlBPRSKatlQzQ3HPS-dPLxGcsumC1DD9K6DjPzr9Gb3gVoiD-yvDVtfrzHu3baJtXnfo_zZcar6g4tCe_Dia2DhcvoX-qSQ_uKOKjG9JacDDhxsOBVwLKlJgQYLMFM3E_u7H_wRuePXnPwp1Y9eZooDmYyI4EFdefijyfh-GRLhG0XYqHoo1IN9bNsdCQDsDzD_wAceIqsxudJCRlqgc5xBIgaL-irO5I4IclOWQQE-JvyTsIVbBqWLTJr077XkpTuRguUytBBKzflafatvAOmpT2D0I6bOP4tBDXp4cGyJS0c3SKwKQYlBK1D5JpLz382erzf-Qybh5heGuf5IdhVkBo_UZDQWHOb3czWYWdK67DMPN3piUBptUJ2LMEO1UPdrtqbS_cRScPNWU1X302foqy6JRQ6mwK390BBc5a5FmFZGSTX8OuF1JyJpWroEp9cwPH8qP540US9kO6Zio1htSBKd1dSSxIMejhsZZizGNMx76nii2o4vE0pRoDaaX8t7qwNqzfvFM6-9Q1u3fxew8fSZgG8WlR1QriiXM0oO3udmN9ZW3A2JmM4oB5bhR0CY4qoA1Nsq_VnhL63FmT-ups72_KVasEuD82Eipf5J0IUrO64ZGyxu3qhvu6YSlItPsuKpSoU9vTyaH7ObodnngfzIzVqSjZmSlvm_a5fZf_uxD7kAvbWNyoxGZgaDy5rmSxe78rvhyr3_7Vt-VhOCtkfhIYtOwoqGAdWyLS9hrwLKAzxaurwLlcQNWdJPDRdXZ7P6nSI23RCac2B5t-TYsp9qcvX5YBpj5BScQP67tWmfweNnjVgIH4HhF2gZr2gXYT6dyXru7mXFjtadmgpfdSTzXMcfN-5j4QMmtURqH6gjuu4giivK_6M_lahLQ2qiifbGZ0qRTUs5f6so_Ud5vPdbk4Gm3r3kWVbeBAMWfAsd8fOoQxH0rAxVQU7Ne6x-FoGKtQg7Rt3atWcVKeVeCYnCVTxe-HEGaVsTOz93Entr6l5kLpiYBIDCMhjItb_gDcyc4QnwewJUE1VACGLpKrkrdHQ8aGp15Zj7Au0t7Y9M2FGYOnycmf6rNOA1fE5nG4oMkzCBIagYnAvILlOkbYujIe1t8mJJtd1zRDuzkVzYeskpBGeB3p5kR_AyIv004Y0Ac33bmmH6urQLW5FFGVL3vIIP1i4Mr3Yc0HaW4K1zJ0vHnbAHnEc2Qdsi99KYiQpB88W-8fj0-vytA4lQuy_PQwE2-0uEmseSvCr6M-QqbXVbPJYE0zdyeVdfQCW0dyU5dFU-rFec9H2yYUKctgrYyTgvnkkOyT3s63pSimmkJFtLVR4AJsUGiLB7vI0LLLonKAE87G6qlA_9qRF94cA7IVjGuxSa8zJihb6OsTiRWNtyB6P_b_lebn8S5uBRgWbsnUDsmu9o5liK5AAD89cMXVhxkBA9jgIXp4R_zLQfo561-BeXV63RGrqfpgZBKRoElSN2u_HkBuEvsumf18ghxWQOgZm2BZnj7klbUaWTJDnes6oyKp9FnPhm2PnkxCPI-vkOkHCYKFYAknA9SK5P3c5QnRs_7LA2Qe-TWeNVasGJM3qUIEKy1BGLGDnspgeu-2DIj4AHeP2qeKEWjGHQa7Cg2U4Kk71qYMUWLvWrgABbJnhmHiI7cwkpPe4LJYkTViXgr-_HCydIgnQ7TLalz5WEJEniLyQ_vgjUUty7v4X5jiAWvQFbSQ_bPQuZQ-vzaCaDKNNszsmUmieUsBzzKk5oh880h5HfdSGiTqoRyceCcTRcVserD16tGZzcXjYAQdSOHeysQ9nft3i6Gh5poGulgOflErlnkz6lkofZgIkmoHuHtH4lrLepb1jz-buGdfLVzR3RGg3jRZ601A89GlIso8c0RbxIgR_MACtgiNPh8pr7Jbe91IYptmw0fZr4zfpEROOuPXIX3zqrfNJsF7WzTi9Iow97gD9iKtP0Saiaq8j0nEE2PjQY7WmDau3LE3iok8oZafhy-6yS4TrNKgCeMw7k2jJGHUr81QEam_HMs_cMtAkkizGHColWei_cLBovJmedzmDPxx-8vs5y2N3rMNJkpjUAXIk9ihRHwYIkv69203ycIijWCX96F4rAB4Rn-egG74UYlUu9WCZDgrxDMlWXJ2e7jAYuzIbdg16HI9wBjjBuwrVa6uz-sUDFRgbD_zmmBQdeWs2Fi918Kz1cDpdrmoGTD7RyL1S2gpUunZMh499q8iK6X9nR-adiATRPwNDBhpsBQPyPaXj0RJ-gVZ-fXsuLMogO12kj9zmph-nxsTOCHm-c9XgfeRi8SC3ixx4jbBMKh8ydEpJzXF-Q1iERUz7vaHwrE_SToSD3snL50b2OTv5dUnCjOVUczoyyxcqbUEasvfajJkgDiTqlyLFpJ2s4_r_5SG0ldC449aZCHcPTWbLLOSY-cbdIgIBzT3GZ7rnQNjgCyzWBFteBHTV4-scgjGXLI6oZrk7qOGKkYgoPC37Jr1yAGnIFElnC2AusVkNwwNRd9AfFISKDBp-zA-Zp1gT4Zh6AlOjDD3VmlNOnat2l3hvHmW34dkDoL-MZ5-w4jeaDjA8IFbUU-e2eC-HS6nWarf5F_wjmTm87CcDyGZS3xQC0DLBiN1RbNpR73moR84evHZUv9Ogsh8nydqEajlbmYjIgmNiiL0-UclcxRN7MV2SrmlC8YHebKOYo_viLMRS6bwhpfK_4IV5Cf8EKqYUb4uZmNVkeRn-V85muBIb1wxSTzgdmytp7C55-ja_v35RyE1BBNi_hH02bn9ZAp6jl6Vx4B35sj4i0oxBJZKwnvsmUKaU1nnb5ay9lbjlgDrd3j99TMNh9dcDajMlP2DG1A7BbHOWeZvajLFakR7ulSx2Qo|regm",
#             "waterfall_id": data.waterfall_id,
#             "wa_timer_id": "wa_retriever",
#             "INTERNAL__latency_qpl_instance_id": 131241622200564.0,  # get from "next button click request"
#             "flow_info": '{"flow_name":"new_to_family_ig_default","flow_type":"ntf"}',
#             "is_platform_login": 0,
#             "sms_retriever_started_prior_step": 0,
#             "INTERNAL__latency_qpl_marker_id": 36707139,  # get from "next button click request"
#             "reg_info": json.dumps(reg_info),
#             "family_device_id": data.family_device_id,
#             "offline_experiment_group": "caa_iteration_v3_perf_ig_4",
#             "access_flow_version": "pre_mt_behavior",
#             "is_from_logged_in_switcher": 0,
#             "current_step": 3,
#             "qe_device_id": data.device_id,
#         },
#     }

#     return {
#         "method": "post",
#         "pretty": "false",
#         "format": "json",
#         "server_timestamps": "true",
#         "locale": "user",
#         "purpose": "fetch",
#         "fb_api_req_friendly_name": "IGBloksAppRootQuery-com.bloks.www.bloks.caa.reg.confirmation.async",
#         "client_doc_id": "356548512614739681018024088968",
#         "enable_canonical_naming": "true",
#         "enable_canonical_variable_overrides": "true",
#         "enable_canonical_naming_ambiguous_type_prefixing": "true",
#         "variables": json.dumps(
#             {
#                 "params": {
#                     "params": json.dumps({"params": json.dumps(variables)})
#                 }
#             }
#         ),
#     }


# def get_confirmation_request_headers(data: RegistrationData) -> dict:
#     return {
#         "Host": "b.i.instagram.com",
#         "Accept-Language": "en-US",
#         # 'Content-Length': '28336',
#         "Content-Type": "application/x-www-form-urlencoded",
#         "Priority": "u=3, i",
#         "User-Agent": data.user_agent,
#         "X-Bloks-Version-Id": data.bloks_version,
#         "X-Client-Doc-Id": "356548512614739681018024088968",
#         "X-Fb-Client-Ip": "True",
#         "X-Fb-Friendly-Name": "IGBloksAppRootQuery-com.bloks.www.bloks.caa.reg.confirmation.async",
#         "X-Fb-Request-Analytics-Tags": '{"network_tags":{"product":"'
#         + data.app_id
#         + '","request_category":"graphql","purpose":"fetch","retry_attempt":"0"}}',
#         "X-Fb-Server-Cluster": "True",
#         "X-Ig-Android-Id": data.android_id,
#         "X-Ig-App-Id": data.app_id,
#         "X-Ig-Capabilities": "3brTv10=",
#         "X-Ig-Device-Id": data.device_id,
#         "X-Ig-Is-Foldable": "true",
#         "X-Ig-Timezone-Offset": "7200",
#         "X-Ig-Validate-Null-In-Legacy-Dict": "true",
#         "X-Root-Field-Name": "bloks_action",
#         "X-Tigon-Is-Retry": "False",
#         "X-Zero-Eh": "IG0e09d776530888418ab70f3822fbb4e1",
#         # 'Accept-Encoding': 'gzip, deflate, br',
#         "X-Fb-Conn-Uuid-Client": "95b2bb513e6c590b7147b9e4bcf849d8",
#         "X-Fb-Http-Engine": "Tigon/MNS/TCP",
#         "X-Graphql-Client-Library": "pando",
#         "X-Graphql-Request-Purpose": "fetch",
#     }
