import os
from src.utils import write_response
import json
from src import RegistrationData
from src.flow import utils

import requests

headers = {
    "Host": "b.i.instagram.com",
    "Accept-Language": "en-US",
    # 'Content-Length': '30283',
    "Content-Type": "application/x-www-form-urlencoded",
    "Priority": "u=3, i",
    "User-Agent": "Instagram 410.1.0.63.71 Android (31/12; 420dpi; 1080x2274; Google/google; sdk_gphone64_arm64; emulator64_arm64; ranchu; en_US; 846519343)",
    "X-Bloks-Version-Id": "b7737193b91c3a2f4050bdfc9d9ae0f578a93b4181fd43efe549daacba5c7db9",
    "X-Client-Doc-Id": "356548512614739681018024088968",
    "X-Fb-Client-Ip": "True",
    "X-Fb-Friendly-Name": "IGBloksAppRootQuery-com.bloks.www.bloks.caa.reg.password.async",
    "X-Fb-Request-Analytics-Tags": '{"network_tags":{"product":"567067343352427","request_category":"graphql","purpose":"fetch","retry_attempt":"0"}}',
    "X-Fb-Server-Cluster": "True",
    "X-Ig-Android-Id": "android-f35f126bc4795e76",
    "X-Ig-App-Id": "567067343352427",
    "X-Ig-Capabilities": "3brTv10=",
    "X-Ig-Device-Id": "c734a1c7-d663-4fad-af07-817b064e424b",
    "X-Ig-Is-Foldable": "true",
    "X-Ig-Timezone-Offset": "7200",
    "X-Ig-Validate-Null-In-Legacy-Dict": "true",
    "X-Root-Field-Name": "bloks_action",
    "X-Tigon-Is-Retry": "False",
    "X-Zero-Eh": "IG0e09d776530888418ab70f3822fbb4e1",
    # 'Accept-Encoding': 'gzip, deflate, br',
    "X-Fb-Conn-Uuid-Client": "95b2bb513e6c590b7147b9e4bcf849d8",
    "X-Fb-Http-Engine": "Tigon/MNS/TCP",
    "X-Graphql-Client-Library": "pando",
    "X-Graphql-Request-Purpose": "fetch",
}

data = {
    "method": "post",
    "pretty": "false",
    "format": "json",
    "server_timestamps": "true",
    "locale": "user",
    "purpose": "fetch",
    "fb_api_req_friendly_name": "IGBloksAppRootQuery-com.bloks.www.bloks.caa.reg.password.async",
    "client_doc_id": "356548512614739681018024088968",
    "enable_canonical_naming": "true",
    "enable_canonical_variable_overrides": "true",
    "enable_canonical_naming_ambiguous_type_prefixing": "true",
    "variables": '{"params":{"params":"{\\"params\\":\\"{\\\\\\"client_input_params\\\\\\":{\\\\\\"spi_action\\\\\\":1,\\\\\\"safetynet_response\\\\\\":\\\\\\"API_ERROR: class com.google.android.gms.common.api.ApiException:7: \\\\\\",\\\\\\"caa_play_integrity_attestation_result\\\\\\":\\\\\\"\\\\\\",\\\\\\"aac\\\\\\":\\\\\\"{\\\\\\\\\\\\\\"aac_init_timestamp\\\\\\\\\\\\\\":1769034606,\\\\\\\\\\\\\\"aacjid\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"d2c8ed10-f952-4a12-aa09-e83671b1bf71\\\\\\\\\\\\\\"}\\\\\\",\\\\\\"safetynet_token\\\\\\":\\\\\\"ZTcwMzc1MzQ0QGdtYWlsLmNvbXwxNzY5MDM0OTM5fBWut2xb6bRZ8ZphWFhqT9knoNB2hgkyHg==\\\\\\",\\\\\\"whatsapp_installed_on_client\\\\\\":0,\\\\\\"zero_balance_state\\\\\\":\\\\\\"\\\\\\",\\\\\\"network_bssid\\\\\\":null,\\\\\\"machine_id\\\\\\":\\\\\\"aXFTbgABAAHw1cpzzsgkxOLUNm6H\\\\\\",\\\\\\"headers_last_infra_flow_id_safetynet\\\\\\":\\\\\\"\\\\\\",\\\\\\"system_permissions_status\\\\\\":{\\\\\\"READ_CONTACTS\\\\\\":\\\\\\"DENIED\\\\\\",\\\\\\"GET_ACCOUNTS\\\\\\":\\\\\\"DENIED\\\\\\",\\\\\\"READ_PHONE_STATE\\\\\\":\\\\\\"DENIED\\\\\\",\\\\\\"READ_PHONE_NUMBERS\\\\\\":\\\\\\"DENIED\\\\\\"},\\\\\\"email_oauth_token_map\\\\\\":{},\\\\\\"block_store_machine_id\\\\\\":\\\\\\"\\\\\\",\\\\\\"fb_ig_device_id\\\\\\":[],\\\\\\"encrypted_msisdn_for_safetynet\\\\\\":\\\\\\"\\\\\\",\\\\\\"lois_settings\\\\\\":{\\\\\\"lois_token\\\\\\":\\\\\\"\\\\\\"},\\\\\\"cloud_trust_token\\\\\\":null,\\\\\\"client_known_key_hash\\\\\\":\\\\\\"\\\\\\",\\\\\\"encrypted_password\\\\\\":\\\\\\"#PWD_INSTAGRAM:4:1769035008:AZ5ExDXjM1ZLdM2rMGUAAVPBP/IsjHJHTphEA/Iam7dV4U+CpYwbFzkSnyJ5xrOgk0pnBnN5Qd8FN2qviVQTSHUAIkcg2J2Zc0xFq7/lE+e4pDSze1c9WOk8rW2YpfIskC7yxjUw3dEYE2BGqJeNLzNYNs435LEIE4ar8t7iTwTS2oWb2UkZ/nWma7wCS0GwR+/S5HZtpcSvM6ZUxBKwu75OmUM/3wrCnWSQ0ZcJpbdTmbvE+sE+Yh+/ROr/Unte8z5rn9nGKU5Jx8pi6I7wpH0YlZJPAIVi7qqk/N18aLUGIwYCY8xTO49ogv+nRCoOSIu72A/IXdAc+A/druvNvDluMsgyLJAyyeo4L+QW/OrY5HOVRkeflqunwyNZMkPTfDOWgGtgA0LCvnFrEso=\\\\\\"},\\\\\\"server_params\\\\\\":{\\\\\\"event_request_id\\\\\\":\\\\\\"e6fb130e-2326-4b73-9729-ed9267147b04\\\\\\",\\\\\\"flow_modifier\\\\\\":\\\\\\"{\\\\\\\\\\\\\\"flow_name\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"new_to_family_ig_default\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"flow_type\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"ntf\\\\\\\\\\\\\\"}\\\\\\",\\\\\\"is_from_logged_out\\\\\\":0,\\\\\\"layered_homepage_experiment_group\\\\\\":\\\\\\"ld_no_language_selector\\\\\\",\\\\\\"device_id\\\\\\":\\\\\\"android-f35f126bc4795e76\\\\\\",\\\\\\"reg_context\\\\\\":\\\\\\"AVgIyhY2WWV7XdE4GTvwQv5PwpFJ53msUHytpcj6MvbKkZB7aJuuP8XiJCXVqjIuKxff3kEjTjgPApwOoSCsa-3xeFyzmFYxH4sk-NWQMaB_7X7Ws9yxr-htkYqS5ke5m5GjxJf-xbs70pBquF3QkJ-MpVWFPw3rjZfs5CFz51GuzEtioCHw_prciiOQOWxUClot6uDTkarl4NUdUBfAU7oPyrjQbkkUDcY5UnhGMH8kncpG0CsWl4As3Ss_O6DtVwXKXcM818QC6anCEVw75AsIeEuP-A5r74UWa9XuewJTwxrmWqAYy8m0DvssAHjzh7MtX343Hsd7GINSBdkQc-M8IVxcHosgHfY0qg2vDOXLZmxUOxyyipfxtzy8qG2KZvDGVM7kECgBKsOZ19McQIP6TWnjWJxYhp9ex5r1D2sWwoGCjJ_xzqd5O7WeIziwIybExbi4fIgV2c7w5v09I8buSZQ2_DxS3Di3EARwFyGBD6DpGdvite2NcNr4YHZA-pUTpWqeJNFpHnXUcDMbjxkPSEJ_XaBIZpqfRmtFSvkKjzeh3hf8BztUMUGqmJIPvWwYqzFlEUVer6-ijdki7ss4Z996iVAHGT46qd_tq6XFsyeLtJ-5b3MQeQS83qi8IvObHPl2jUVb4whkgVUmhFyjfPv8Z0UzVJ_V5j_LaJUW4jicKK-jaesG7LtqKskl54-79sLIKAIdIx58h1EKahB0YdtT6S27ksicBsAe4H6I2NQiZ5HS7tHNV1Pgn3tcpsK73oJV02Wjl3onarJj_cX-5OZflusDNhzfSglNiQkxxFjbvz4u1FD7jGnw7HZb9TEwZFaWCU-lqRzDHScS1BiARsxnrT3rSgaa4kf0gfkZm987CzXJvSOqE5pfny4Pnj1aekK8KHqpRIikEHSd_fdR_UmVzSGGzqah7ed8aZDOcCH_tDhqeVyGzli0rLcMJSElq_VqCfLeLlrzuRogIBZZxwUckSjxox6qAbyxYXeiaFQdD9zs2wlzGSpGxdETGKtqsHvvr3K8am89dtL2dZIC_Hg3uVD0s2MCw0sutDjo_jLMMj_mlokRe5y0Y7PPUs5LLtWfaGZS6FqooVAGCK9zDHm3M3fxBwnzGtlp6a2ZNZDICNVRkwc8NoeW0SdsdDKirvJPf9WkRS1UJdMxnW6un-bY_F25ZWEIVAAEBWbUWYwsUFriLhBueXyZ4lheRMsDV87_22j0irm-c9l9nW4e8YHlN1vM9dXSrzZJb8XM0ve7W634kCxgFe3opZY2B6FJkpj5EKxzsVHm9AEnfl3YGphHvFCOu1h-g55bK-jcQqJQZBJiZpFJ6mgz60nNgUDxYAgf3snDaG4wZG0-q8p6qoK32tQntXNharuZYGYYu3q2OV1garGeMBAO_TX6BDD85cRIunr4nQc1QlNMbvQEQJicmjqycyIVk4Lw11z4PfMDnjGcNH7up9ThJIQxwa0x6eMAIFph9NmxLU70-xOiZfk67yn0wuBXALHwY7iWSHNEQrv1RJ3lKugyepWMsWQBtwzlPd31xPNyTJJaCU2eqDi8E5CTfefIe30_hS8PYFInF7MeEJgzMCofdC70NW-2l_gDfqS7dUWItUpWRKB3p-UOrqxk1xIncyIVpE5FsA7WCbD7HNxC2hMrQcry4CU1IkiLo2Q4qdPvPp9M-AdbMS6ExflGSMaQT85yVlAiZpeWaY6hefJUtdOxl8gK3yYfzKvzbgu14jzeWWfZQvxYXZ80CsQ6huaJNwl2JNqfN4-w1_LFWrzzz4u-SwprRxBq_0JAMoPjwVYtOaI4wLV_YsZ4WNKOjcK5txLowbUrZY7uo526QqUpHVGm0HpPcq3Sdh7blAWeneJY8XPQhD4vF3D4Vd9tXGe3dqsjKNZObrjSTLcw6b8_Rc2KHJkAIeWKDJPyXnH9liwfJzJBwG8EC7bFbzUtvoQeXYi_FpPVqbSaXBxhAI-YbZO65AzxwV_1zREW7J4zz2QP7V1GMSFqYLytYag5CcPBtVX6uTgUxcU5PU0Jinz-P8zRIjZa6rSVyyy70Lq65a5qdK7yd5UTc9-MkgAH3r7s_Whi83UqLPsKz-VoaLxDW8coSHFwsv-Npizou01d7Z9PSScS1BRHeWZgved_R2GiwCevcvqNA5mUrkxtjVLO_ytMAXimaE3ZmeYwx5IQwLts38N-WXbtcbLNVJkb3HHq8ToUrT0uqryFZNn5keCnxVZ_hOp8SoEtsw4SffaZsNDg-m9mYMKLJkCfXIZKu0AJ_OWKLRRW7rZfwKwutyLp0gAjNA4_Pqn1mEnM_2cGDgBDBd-eefn8CLVB-QiEjWEw6wvic8r2ai4qDYKAHGu-wXAwRnPVY4Z-9cpSE71kANz1zDdK492J4A8rlrX-NLGtWo8YAv3grhfDH-7JX3Kgk5IAVVSxGu1xkQr1blm-FBlQhuovhLlpE_qWjHoEvYjW6LD0BsTEyLJToFiwOLPL_eaW1sjhQbRmhPP7dkfCuz-QZj4pkOJdQKcYItrNpN3uSaQaRZ_G0n4-N8CRxNFWi2JOPTiL9UT98ZkRVAU5c5LRc5FsVK_KjFVMRxhhedxZ50qMCi-3rw1KyVeNipBF7xPyO54CGJgzoKHl-DjSoCt1okRYksRjP9cgccqsl02ntKw53R9tiR7Z-hrHnGWDK5pUgmPePwI3Cjh2_S6NmdA_1ZbPTkBGytcSIdkIvrSc9ux4BXbuWtef_P_O_rYCNmVw5JJYsKRMxETOKvci3IY3hBUArMbHrEQAHSYlzPQutujQXXOxh2LmvuWSMH1cCA8oWFKNQOLOgy3I140qPlG9-8yi9DKOkQ7_Ve2v-Dgddzgz0Agi_87ydnDsh9SX1l8SKwBojAtpNz6bATQUzpd796z0ZRZa6Nf0RtXMsFqjBpJRbkh0Eqe3cPkntkHD6xXYXQ55keHtewerEA2k7HgSFqQeZYORc25sDBo87WHgAvmH3HeHc0P0K5CKbLOyHC-ghrmNglBjNkSbZUfSDH54_hWsIiXpz8POqJwpGEssur5RCNf6V7_4yQ161-5cwxwIA96saeoRb1HyZzBONM6VJaHBJkmmiOaCIkeClOco2toBwVYFagJuh_6eHK8alBfJP1cc--jW5N0cHqggjUnaLJageNKNZ9CJNbuZ4tOHmeGdZqp6ZfTzLi4BIU1GNz9UoeYR8aifsAMYAYjy_5IYy7Q28I7wIiOHkgxNKSLYjFu1trSf6maXz_zy7xpJbFRylvHqpxTBOULr49OXj5Q77VwE4_o1lKrkWO3Ck3EgfRCMTigszPDKUhofnYAdGCyNYrXjYjsRxO1Y6FKKt3kflLIntfJLiszcbXJhj4iU1OzcsU_Y9ztlShpfC56qic7cdYy4U8Huplq4dRr88iw87L2gi8BlrCrapBBwxXohNGAbznk0w-ka8Qk-HBo_1WsMBPk38LpieIWyfRHXm5N6b6H3Fp1-523kZHpMMVoVrT8TR0EAtsIEFJg6xIA6JaO8F36aTCMTg1tb5mDBDQF2yW00xiHY59oWJXyJW6UiN5xbqDBBiZCoRNhHG3_pXS_YWmpXQUmliG2zO9cLxb3PSauVSprCwNgVM10nH10BOWDovZ4IHcqJQC_WNmUt9VSSSs4m3OU_liF5k7614jEJMLP1PJmZkO2oi3aw_4rQ1ThojIcyLhqMb_rMGYHyBVsMTKkY7_cpESqXeTk2HYsKLEO-TlB8wrWsikShi8C9gpU4TJbFjCIajBum2Isa1x8fkGcDSP96slrtP_KcMzI2xPhxRWEVSoYZaNFwFuxlUFfrpI2ZWsN-105EOnHM-UVSzdPdKJzl_izzKSJQgz-W2Ep4-bjRgm9DBCoNx2-jACKLhnegKJlQVAV7PARAB7eAOVEKneGjV-bxC_R3_0QXD7NpTNKop4juQamYaIvNSMlPs1XK57JjIitze_YgdGIJB78_gq_spGxn7L7tEzhTOs-l80xZb8f77c4AhfFH8t5iQDIJJx3ZmBzS5ISieR3TcG8IGdd5kuG249Bx4vVOoWVRciyZtGJmMI2jOEhn-MawPEu1pG9V7fDt3Tp8RlLwv-ItOkOQeDbf_QaDfyF2XMXh56FgH4h4gYopjCDPF8BizUKywCrlejoh-nYmLt9dxP1eZ1KphfI0evoO3ePsQXsNqZQOBWxq5XH15eD_s_1g6iGUOQlk7Ul5hlKDD15QYyT-RlxvCdmunRMjlWSX-OsHm_sBJecgkxThWSlg6ftvukmJfwpsUW5-NVcuCytwwoCjsLuvCsuCrmxy99Em0LER_XjgMY59fZnMReKBu6PSBWu-mfCU0Q6FUqLPHu_boR9HnYt5Oo6WHo1hJkC-EOFLitn_A2MsH5axybMgUGtO8j15SxoDa1dyRSDFNmwqETrxJf_T85o-VpyTS1-GtCqzcF_irkvVVzxeucdy1CGXxs_k-tdmYXwn2F-NcrnOkeT8H5GvnyOLmzRlY4FuLxDJlVYNJ_ofcZWcusC9pSRoCe1DrHji_vhBQgzOmvaqcGNvq-Cgz6UQQF-UwX_Hq9rfv1ZPG7uVw6hohlDkae7dYJ2y4v6uVpxX91h2oTngewLfTGVI92Il5goWBuBe-DrTNU-fPOS1RYOhQHDOEuamyaBY3Es0YBcjfn3lZfZifWr7yOeOH4Jmb3XN_ckjmGx6BWIS4Wan2FY5Gl2rUSnoNJg1aNbLfz7Cf6yT2XAS-VtPF2z-IrlMPxNt4YFvYur2eoth84CRj5IhhVflpRWmN0ap648-KtYxXHMnG0kcI7hKpVHkZQuCWEDhVVkqyumY3r2Db3V0AKYRdmGDsAL0V5ciqkpNRw2PmHqbGn9vKO86cb8M2jKmc139qS2zNVDkPDeYhtQ2SUfK5ctLeyTOBSvymEyDOV2DAADY8U6EBghaSX5iU3xg3QXSTCrqHvZJXUMoWRjbUzXZ1rqUPVTQ6HgOnrEbM8XNsss2GZAxkw8LasuSY373QPylqVdWwnKkk57TWCnoVy8STL-jHdEjqH10RTo7are1GHq123je-c5xVwxHGKglcuNLhAvIZmugb4gtT-GmNMLW9Ea0S40I9kaTOvu8bI06-qCmqxbB8wcV2zNKkIrVhcsduZAUc66ozFyxHC_EjLo0jOXBkxH_pbg3aQZyqENbdr5yeMZYnfTvkCCT-Vy-_8RanjahXc36hqePUbXML7mwNomJcr7fnsuTl1eRdrIUwCuCtceZD4WFhDXsHScaCeF-9AIbvpPLdM2Xb5dxJbSsUl2BRZdvmpkAxwegiIJOkwGyUaZxLba_MWc0L3-8kvMudMTilmGH1to1k9r72ymWMvNZKpkGwTyezUMAPzM865tPbeau1KjqlYPn5jTsM1jZe6TP_ktBuqs0q4qwanIGq7IqOGyQzc5E3rEK6QG7BpiLiCQQ_xtY9x55xh887RPDbRP51p0LlXhiiVZK_rELD9e18x0LTNLuoUcc2mrtUagbjvb_HM3i3qsIs2X6XDpnqjGXqpRLnzln28EZx_h3odK843Js_ORYUmCYwV7lX6CZfRHb_m2R0B2V6-iLTxeCAjSEpM-LvNHH6yzruROR82yU8HGTjhFk6q2eFRelQuTfhp-dG1SDXVvopgQ-X8M-fnuh3y0k_d3hyotzXi1PYZg-458Tqvi3nOszDEuq_h7u1j86B610RDDCd8cl35l14YpfsVT0bI6RBTfosHJvzJeFHmJ3hOPhSwLD-2Or7K2_5cDC29OUkW33-G4_GjgWFUHXkG0ezAtkIyGBgI9mFyjQVloDGeBwvHhA4AmPDefskftqrP0sCXWhQ1wNfgslaMQ-uIqDKYo-Vqp5-iKxA8TkFZpkgYP75w4t2OhLo2ThWSNLRpf2bExnmeW828AIBKZ5UgOaLqa1omJAyOcCMtXMzPnMHhg_gI3Lbb1KZFp9VNVo1M-_vu6XKDXX5cmEOUAycmRbh9QNAfnIh90fUaGvAgf1s2Ze6wAzgDlJ6k4ntcnCLOBI5AlKNpr728TDNgFB_uh5Lm9tq7p7tsilslbf0g7PjIQq_f7OsooaaGEOjFdp5Ntv2tbkIMm3gn6T60OLjpD-LMHzCuGgjauPYUy0XqvxP9HwUA_56Py0dokSVqlO2NQm1WdM2t_ITY66PWzflDlKnaILQH2MS1Uk2KJSD2LA3ETPTigU55VuBJxaNQjlMfgsH1DvWQ3nYckj5iCqb99cHT0ZIPy2Equj5FBXAQx3zjFsOLidGbOC-CaeJiWIvRYhQm9yvEKBLLiTnfVDiP84DjLNpb7Ii3BgcwsQSfEuyrITR5-yF6pNPvSXKhVFsLZed_7lNHceTKTIGRqmnMSxT9f3fEuG8rH51h4dBuSsfeHt6xViOA3IsgUBEciqobomRwk1_TXRP02GxJXIhfgwP14e9lesNz8HyJ3SM4-IxcZq4KcrqzFz6Uk9Aqfj1dyFFmlUFSj9x1shlhx-HnoER2fwhshcIco6yQ2BQUsa8o4ie5OeKiUsXON7jsoRgzqFfcY6JY6bxHk39GIET_YTDHnNYo1Zue7Xo6YT4nLbiT3Bsk-CJB1WgKhvsLu2hQSHydu_QW0m4xPNkaFW1EhwixkFdcL2Hi8r6_2GWTUv3VAIKDahNUjpMiQCYdIkwdMShDcIslNPXuQIfTmDUmZtA3tzcEmFBfo3PNuP6eCufa4c6QHkhykfFvN-aLpQsvsitFC2S2UqQ58Kd6u8M9tmCi_EsBav2VTwVUWcSiq9gir1CaiHFF6vaeGGl2oBoXn6A0Zf1tiPPTnnciVVksCSQRzEfWqi56FClghfozXJ9FIgyEUNCHiUCOKRc7M_3vwI-unYXiBdbCsjzs69QnVF6KtD8SsT91tt8ocAiEjsW65KCWaks1OovM5rf_5XhqiRrcWp0Jw46Q7sHo5QQMszbYmdABiHOYmIrhw8VJEol5JPvRGlsLyUdlTS7bz5tOL5BxmFdn_I9-wwOus-TPP45hVdkkOV3PRpLyqo6bwJXZQ_1zD97pq_1PN8qbmftqwsk-5-vHqBZJojrqnZLp2W3p-r8DbXPMMb_pn9rsRukpWw4nZVYo1bo9W_YBNx_yFifdYDspKVMgfi4fxCNBJAN22crOzIxGnykcs6sNVz350nY8pSHIJ-uZeQe571chyb0hrtFZxn6V-6x0gh4vjFGOAjpDq8iRfvVgVfTNLVng6tLfi7B0DVTnrMJ0xSgmqmRKYrJHx5zk67bgZKwvrI4QtQ4rihl8DuCk8oirpeDpwDYrIEqXeuAHJJkM0JFLoCprtHnJai2xOb0uuY6vPU-2Le5a2W4KoDDGTSKkg4_qIYc1JjiF9nYOIjhPRxQgrHQRFqhsu22ApUvIk_d9PnebFB-JNtlWLbYy3VilpBrt72WGf6V41fI_W7UK2g8OnhsDCUWfmVB0b_EE03kVPEPRC9NLzG1OjXUl0mez0-t8IxF8_8mLANMCM_UO949bLqP9FXHUrfqP0lvGnDKS5Pidy0_iiz6-R3-G5VppHJpUpo3wIug2l2PrEunmrXqnN0uzPZM0osII8gaW8ja31AubAHB9LiYBSjlgCIj00hBggYp7t3hxvde54c_Ua89G-zHOGIf4rgdYNddQK0pjBtY575X_5JcQEwduuwUg5nkJKB5XNVqZhtkK9qTeUYW61vyPKPJ-NzavnGwDlxK81JRAmxiYKhFREqk7rBfoyFkxZvbEUWj3mBZV4kX69_QV_4zRXt3bNeGBMZEbY-gOBq5R9ohvSMqh0ZmnYiU3C4Yg5Bo_AfvfgMSHPSbTRuQ93WeuoStnd7pqz-PIQ3ZC3gV3klIsIXeC0X_248yEpXtwK8XVs77QxGD1HZs1acE-Z5ROzZlSeAxo95hZVtm0LwbpJhZ8isla2zWTwIgIKSFriPonIsWD3jFfj3j85X2o210vZY8BPUD7NbW2Q1h5GxmanYAgqddyIxs_VNX_BoEbh0eZaM0NN2Jg0rhDW4FGkhKI6b44rr28HLL9cUd9TrGkTqNz1gy2AHVi0s1CuBipK0HJv99P9zlH6uLdd9Zu9fPUlVyB4qMUSn3J2Rzb2sAJ1YhK4sMGaF-npOGZ85vX6YDKscFIkUGYCJaRhSIB0FtlexZcuXyLcLklO9yaFatNEIYsvqftYzzaVCKAGcmeAKYN6D4xteZ9V9o1dr1JA53q3WxTrBKO9sFyJASXvzeoW9gYZB7P7dU8tqFr3V8QwcLrUbUPOxFiKgMA6GBD4mzZS8joNOSJ3LOC_u3ZvRw48ebxyIPpTuHzhONTfY4yJlkf278L5X0RkVKmt25UisFX20XpveYjlhokCV6q52VNYmtHQazNrMcjJPHuhGKrfhY6NeZOI_s5b28hj4b5etGAhoDatCvcjX5FIMEPm6lHdfrd3CTSlm9RCX74ok8n_sLcs466DfpvqnJ-qAi2vYAw0XiYVehHGh4P9JGy_UN-r0Wh0gdSry48hT0K0gH_vHenZMOgQ3riP-TFptALAIvtlZaJnOPmpaELZiVfuvLI7Kyno1Y7oBMl-5IRRCOmhEfcKovUCXXlsjIAF1q4Qo9zqmrkhSxo_jQTXwHoAhtAF5v3Ceeivk-spn_RM7na1nWyKDVaU9MQJJCLzkAMv6QXfpJHQrrHQH902ao0uzMwInJmpk801-e8RNgvHAHhSt_WC7IiEeA-wQoV5VjHQqD7hn3ckiinb5wPNIEhAbP-jvs9Dy4pppsCOT8RILJMTa36jf7KSKyR4mi_RNuF4sn43_blb2ar8UxSl9rM_fiKlGizLfEbqYiJ16pcu7_kb2vRo_16rzu0GF6qeLfwhHp22LRWIbDx0KeAOKC-FayYcd|regm\\\\\\",\\\\\\"waterfall_id\\\\\\":\\\\\\"d6031628-57e9-4414-93ad-9911cf738e0b\\\\\\",\\\\\\"INTERNAL__latency_qpl_instance_id\\\\\\":1.3137432550011E14,\\\\\\"flow_info\\\\\\":\\\\\\"{\\\\\\\\\\\\\\"flow_name\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"new_to_family_ig_default\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"flow_type\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"ntf\\\\\\\\\\\\\\"}\\\\\\",\\\\\\"is_platform_login\\\\\\":0,\\\\\\"INTERNAL__latency_qpl_marker_id\\\\\\":36707139,\\\\\\"reg_info\\\\\\":\\\\\\"{\\\\\\\\\\\\\\"first_name\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"last_name\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"full_name\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"contactpoint\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"e70375344\\\\\\\\\\\\\\\\u0040gmail.com\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"ar_contactpoint\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"contactpoint_type\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"email\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"is_using_unified_cp\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"unified_cp_screen_variant\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"control\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"is_cp_auto_confirmed\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"is_cp_auto_confirmable\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"is_cp_claimed\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"confirmation_code\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"HLhN6nli\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"birthday\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"birthday_derived_from_age\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"age_range\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"did_use_age\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"os_shared_age_range\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"gender\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"use_custom_gender\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"custom_gender\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"encrypted_password\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"username\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"username_prefill\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"fb_conf_source\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"device_id\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"android-f35f126bc4795e76\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"ig4a_qe_device_id\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"c734a1c7-d663-4fad-af07-817b064e424b\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"family_device_id\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"dd5b9513-0be3-4263-9106-459e51268b46\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"user_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"safetynet_token\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"skip_slow_rel_check\\\\\\\\\\\\\\":true,\\\\\\\\\\\\\\"safetynet_response\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"machine_id\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"h1NxaVnaYULGGzgpCn_hPfVP\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"profile_photo\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"profile_photo_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"profile_photo_upload_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"avatar\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"email_oauth_token_no_contact_perm\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"email_oauth_token\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"email_oauth_tokens\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"sign_in_with_google_email\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"should_skip_two_step_conf\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"openid_tokens_for_testing\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"encrypted_msisdn\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"encrypted_msisdn_for_safetynet\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"cached_headers_safetynet_info\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"should_skip_headers_safetynet\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"headers_last_infra_flow_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"headers_last_infra_flow_id_safetynet\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"headers_flow_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"was_headers_prefill_available\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"sso_enabled\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"existing_accounts\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"used_ig_birthday\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"create_new_to_app_account\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"skip_session_info\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"ck_error\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"ck_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"ck_nonce\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"should_save_password\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"fb_access_token\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"is_msplit_reg\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"is_spectra_reg\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"dema_account_consent_given\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"spectra_reg_token\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"spectra_reg_guardian_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"spectra_reg_guardian_logged_in_context\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"user_id_of_msplit_creator\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"msplit_creator_nonce\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"dma_data_combination_consent_given\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"xapp_accounts\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"fb_device_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"fb_machine_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"ig_device_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"ig_machine_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"should_skip_nta_upsell\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"big_blue_token\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"caa_reg_flow_source\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"login_home_native_integration_point\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"ig_authorization_token\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"full_sheet_flow\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"crypted_user_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"is_caa_perf_enabled\\\\\\\\\\\\\\":true,\\\\\\\\\\\\\\"is_preform\\\\\\\\\\\\\\":true,\\\\\\\\\\\\\\"should_show_rel_error\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"ignore_suma_check\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"dismissed_login_upsell_with_cna\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"ignore_existing_login\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"ignore_existing_login_from_suma\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"ignore_existing_login_after_errors\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"suggested_first_name\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"suggested_last_name\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"suggested_full_name\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"frl_authorization_token\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"post_form_errors\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"skip_step_without_errors\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"existing_account_exact_match_checked\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"existing_account_fuzzy_match_checked\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"email_oauth_exists\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"confirmation_code_send_error\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"is_too_young\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"source_account_type\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"whatsapp_installed_on_client\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"confirmation_medium\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"source_credentials_type\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"source_cuid\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"source_account_reg_info\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"soap_creation_source\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"source_account_type_to_reg_info\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"registration_flow_id\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"2bfd5926-c03f-48eb-8e17-a98ed947592c\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"should_skip_youth_tos\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"is_youth_regulation_flow_complete\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"is_on_cold_start\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"email_prefilled\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"cp_confirmed_by_auto_conf\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"in_sowa_experiment\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"youth_regulation_config\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"conf_allow_back_nav_after_change_cp\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"conf_bouncing_cliff_screen_type\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"conf_show_bouncing_cliff\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"eligible_to_flash_call_in_ig4a\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"eligible_to_mo_sms_in_ig4a\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"mo_sms_ent_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"flash_call_permissions_status\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"attestation_result\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"request_data_and_challenge_nonce_string\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"confirmed_cp_and_code\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"notification_callback_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"reg_suma_state\\\\\\\\\\\\\\":0,\\\\\\\\\\\\\\"is_msplit_neutral_choice\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"msg_previous_cp\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"ntp_import_source_info\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"youth_consent_decision_time\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"should_show_spi_before_conf\\\\\\\\\\\\\\":true,\\\\\\\\\\\\\\"google_oauth_account\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"is_reg_request_from_ig_suma\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"is_toa_reg\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"is_threads_public\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"spc_import_flow\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"caa_play_integrity_attestation_result\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"client_known_key_hash\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"flash_call_provider\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"spc_birthday_input\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"failed_birthday_year_count\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"user_presented_medium_source\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"user_opted_out_of_ntp\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"is_from_registration_reminder\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"show_youth_reg_in_ig_spc\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"fb_suma_is_high_confidence\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"screen_visited\\\\\\\\\\\\\\":[\\\\\\\\\\\\\\"CAA_REG_CONTACT_POINT_PHONE\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"CAA_REG_CONTACT_POINT_EMAIL\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"CAA_REG_CONFIRMATION_SCREEN\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"CAA_REG_PASSWORD\\\\\\\\\\\\\\"],\\\\\\\\\\\\\\"fb_email_login_upsell_skip_suma_post_tos\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"fb_suma_is_from_email_login_upsell\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"fb_suma_is_from_phone_login_upsell\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"should_prefill_cp_in_ar\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"ig_partially_created_account_user_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"ig_partially_created_account_nonce\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"ig_partially_created_account_nonce_expiry\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"force_sessionless_nux_experience\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"has_seen_suma_landing_page_pre_conf\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"has_seen_suma_candidate_page_pre_conf\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"suma_on_conf_threshold\\\\\\\\\\\\\\":-1,\\\\\\\\\\\\\\"move_suma_to_cp_variant\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"control\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"pp_to_nux_eligible\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"should_show_error_msg\\\\\\\\\\\\\\":true,\\\\\\\\\\\\\\"th_profile_photo_token\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"attempted_silent_auth_in_fb\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"attempted_silent_auth_in_ig\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"cp_suma_results_map\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"source_username\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"next_uri\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"should_use_next_uri\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"linking_entry_point\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"fb_encrypted_partial_new_account_properties\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"starter_pack_name\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"starter_pack_creator_user_ids\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"wa_data_bundle\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"bloks_controller_source\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"airwave_registration_code\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"is_sessionless_nux\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"login_contactpoint\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"login_contactpoint_type\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"is_nta_shortened\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"should_show_bday_after_name_suggestions\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"should_override_back_nav\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"ig_footer_variant\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"control\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"device_network_info\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"is_from_web_lite_reg_controller\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"login_form_siwg_email\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"account_setup_waterfall_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"is_wanted_suma_user\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"device_zero_balance_state\\\\\\\\\\\\\\":null}\\\\\\",\\\\\\"family_device_id\\\\\\":\\\\\\"dd5b9513-0be3-4263-9106-459e51268b46\\\\\\",\\\\\\"offline_experiment_group\\\\\\":\\\\\\"caa_iteration_v3_perf_ig_4\\\\\\",\\\\\\"access_flow_version\\\\\\":\\\\\\"pre_mt_behavior\\\\\\",\\\\\\"is_from_logged_in_switcher\\\\\\":0,\\\\\\"current_step\\\\\\":4,\\\\\\"qe_device_id\\\\\\":\\\\\\"c734a1c7-d663-4fad-af07-817b064e424b\\\\\\"}}\\"}","bloks_versioning_id":"b7737193b91c3a2f4050bdfc9d9ae0f578a93b4181fd43efe549daacba5c7db9","infra_params":{"device_id":"c734a1c7-d663-4fad-af07-817b064e424b"},"app_id":"com.bloks.www.bloks.caa.reg.password.async"},"bk_context":{"is_flipper_enabled":false,"theme_params":[],"debug_tooling_metadata_token":null}}',
}

response = requests.post(
    "https://b.i.instagram.com/graphql_www",
    headers=headers,
    data=data,
    verify=False,
)

write_response(response, os.path.dirname(__file__))


def get_password_create_body(data: RegistrationData):
    reg_info = {
        "first_name": None,
        "last_name": None,
        "full_name": None,
        "contactpoint": data.email,
        "ar_contactpoint": None,
        "contactpoint_type": "email",
        "is_using_unified_cp": False,
        "unified_cp_screen_variant": "control",
        "is_cp_auto_confirmed": False,
        "is_cp_auto_confirmable": False,
        "is_cp_claimed": False,
        "confirmation_code": "HLhN6nli",
        "birthday": None,
        "birthday_derived_from_age": None,
        "age_range": None,
        "did_use_age": None,
        "os_shared_age_range": None,
        "gender": None,
        "use_custom_gender": False,
        "custom_gender": None,
        "encrypted_password": None,
        "username": None,
        "username_prefill": None,
        "fb_conf_source": None,
        "device_id": data.android_id,
        "ig4a_qe_device_id": data.device_id,
        "family_device_id": data.family_device_id,
        "user_id": None,
        "safetynet_token": None,
        "skip_slow_rel_check": True,
        "safetynet_response": None,
        "machine_id": "h1NxaVnaYULGGzgpCn_hPfVP",
        "profile_photo": None,
        "profile_photo_id": None,
        "profile_photo_upload_id": None,
        "avatar": None,
        "email_oauth_token_no_contact_perm": None,
        "email_oauth_token": None,
        "email_oauth_tokens": None,
        "sign_in_with_google_email": None,
        "should_skip_two_step_conf": None,
        "openid_tokens_for_testing": None,
        "encrypted_msisdn": None,
        "encrypted_msisdn_for_safetynet": None,
        "cached_headers_safetynet_info": None,
        "should_skip_headers_safetynet": None,
        "headers_last_infra_flow_id": None,
        "headers_last_infra_flow_id_safetynet": None,
        "headers_flow_id": None,
        "was_headers_prefill_available": None,
        "sso_enabled": None,
        "existing_accounts": None,
        "used_ig_birthday": None,
        "create_new_to_app_account": None,
        "skip_session_info": None,
        "ck_error": None,
        "ck_id": None,
        "ck_nonce": None,
        "should_save_password": None,
        "fb_access_token": None,
        "is_msplit_reg": None,
        "is_spectra_reg": None,
        "dema_account_consent_given": None,
        "spectra_reg_token": None,
        "spectra_reg_guardian_id": None,
        "spectra_reg_guardian_logged_in_context": None,
        "user_id_of_msplit_creator": None,
        "msplit_creator_nonce": None,
        "dma_data_combination_consent_given": None,
        "xapp_accounts": None,
        "fb_device_id": None,
        "fb_machine_id": None,
        "ig_device_id": None,
        "ig_machine_id": None,
        "should_skip_nta_upsell": None,
        "big_blue_token": None,
        "caa_reg_flow_source": "login_home_native_integration_point",
        "ig_authorization_token": None,
        "full_sheet_flow": False,
        "crypted_user_id": None,
        "is_caa_perf_enabled": True,
        "is_preform": True,
        "should_show_rel_error": False,
        "ignore_suma_check": False,
        "dismissed_login_upsell_with_cna": False,
        "ignore_existing_login": False,
        "ignore_existing_login_from_suma": False,
        "ignore_existing_login_after_errors": False,
        "suggested_first_name": None,
        "suggested_last_name": None,
        "suggested_full_name": None,
        "frl_authorization_token": None,
        "post_form_errors": None,
        "skip_step_without_errors": False,
        "existing_account_exact_match_checked": False,
        "existing_account_fuzzy_match_checked": False,
        "email_oauth_exists": False,
        "confirmation_code_send_error": None,
        "is_too_young": False,
        "source_account_type": None,
        "whatsapp_installed_on_client": False,
        "confirmation_medium": None,
        "source_credentials_type": None,
        "source_cuid": None,
        "source_account_reg_info": None,
        "soap_creation_source": None,
        "source_account_type_to_reg_info": None,
        "registration_flow_id": data.registration_flow_id,
        "should_skip_youth_tos": False,
        "is_youth_regulation_flow_complete": False,
        "is_on_cold_start": False,
        "email_prefilled": False,
        "cp_confirmed_by_auto_conf": False,
        "in_sowa_experiment": False,
        "youth_regulation_config": None,
        "conf_allow_back_nav_after_change_cp": None,
        "conf_bouncing_cliff_screen_type": None,
        "conf_show_bouncing_cliff": None,
        "eligible_to_flash_call_in_ig4a": False,
        "eligible_to_mo_sms_in_ig4a": False,
        "mo_sms_ent_id": None,
        "flash_call_permissions_status": None,
        "attestation_result": None,
        "request_data_and_challenge_nonce_string": None,
        "confirmed_cp_and_code": None,
        "notification_callback_id": None,
        "reg_suma_state": 0,
        "is_msplit_neutral_choice": False,
        "msg_previous_cp": None,
        "ntp_import_source_info": None,
        "youth_consent_decision_time": None,
        "should_show_spi_before_conf": True,
        "google_oauth_account": None,
        "is_reg_request_from_ig_suma": False,
        "is_toa_reg": False,
        "is_threads_public": False,
        "spc_import_flow": False,
        "caa_play_integrity_attestation_result": None,
        "client_known_key_hash": None,
        "flash_call_provider": None,
        "spc_birthday_input": False,
        "failed_birthday_year_count": None,
        "user_presented_medium_source": None,
        "user_opted_out_of_ntp": None,
        "is_from_registration_reminder": False,
        "show_youth_reg_in_ig_spc": False,
        "fb_suma_is_high_confidence": None,
        "screen_visited": [
            "CAA_REG_CONTACT_POINT_PHONE",
            "CAA_REG_CONTACT_POINT_EMAIL",
            "CAA_REG_CONFIRMATION_SCREEN",
            "CAA_REG_PASSWORD",
        ],
        "fb_email_login_upsell_skip_suma_post_tos": False,
        "fb_suma_is_from_email_login_upsell": False,
        "fb_suma_is_from_phone_login_upsell": False,
        "should_prefill_cp_in_ar": None,
        "ig_partially_created_account_user_id": None,
        "ig_partially_created_account_nonce": None,
        "ig_partially_created_account_nonce_expiry": None,
        "force_sessionless_nux_experience": False,
        "has_seen_suma_landing_page_pre_conf": False,
        "has_seen_suma_candidate_page_pre_conf": False,
        "suma_on_conf_threshold": -1,
        "move_suma_to_cp_variant": "control",
        "pp_to_nux_eligible": False,
        "should_show_error_msg": True,
        "th_profile_photo_token": None,
        "attempted_silent_auth_in_fb": False,
        "attempted_silent_auth_in_ig": False,
        "cp_suma_results_map": None,
        "source_username": None,
        "next_uri": None,
        "should_use_next_uri": None,
        "linking_entry_point": None,
        "fb_encrypted_partial_new_account_properties": None,
        "starter_pack_name": None,
        "starter_pack_creator_user_ids": None,
        "wa_data_bundle": None,
        "bloks_controller_source": None,
        "airwave_registration_code": None,
        "is_sessionless_nux": None,
        "login_contactpoint": None,
        "login_contactpoint_type": None,
        "is_nta_shortened": False,
        "should_show_bday_after_name_suggestions": None,
        "should_override_back_nav": False,
        "ig_footer_variant": "control",
        "device_network_info": None,
        "is_from_web_lite_reg_controller": None,
        "login_form_siwg_email": None,
        "account_setup_waterfall_id": None,
        "is_wanted_suma_user": False,
        "device_zero_balance_state": None,
    }
    variables = {
        "client_input_params": {
            "spi_action": 1,
            "safetynet_response": "API_ERROR: class com.google.android.gms.common.api.ApiException:7: ",  #### important note here
            "caa_play_integrity_attestation_result": "",
            "aac": '{"aac_init_timestamp":1769034606,"aacjid":"d2c8ed10-f952-4a12-aa09-e83671b1bf71"}',
            "safetynet_token": "ZTcwMzc1MzQ0QGdtYWlsLmNvbXwxNzY5MDM0OTM5fBWut2xb6bRZ8ZphWFhqT9knoNB2hgkyHg==",
            "whatsapp_installed_on_client": 0,
            "zero_balance_state": "",
            "network_bssid": "None",
            "machine_id": "aXFTbgABAAHw1cpzzsgkxOLUNm6H",
            "headers_last_infra_flow_id_safetynet": "",
            "system_permissions_status": {
                "READ_CONTACTS": "DENIED",
                "GET_ACCOUNTS": "DENIED",
                "READ_PHONE_STATE": "DENIED",
                "READ_PHONE_NUMBERS": "DENIED",
            },
            "email_oauth_token_map": {},
            "block_store_machine_id": "",
            "fb_ig_device_id": [],
            "encrypted_msisdn_for_safetynet": "",
            "lois_settings": {"lois_token": ""},
            "cloud_trust_token": "None",
            "client_known_key_hash": "",
            "encrypted_password": utils.encrypt_password(
                utils.get_pigeon_raw_client_time(),
                data.data_encryption_key_id,
                data.data_encryption_key,
                data.password,
            ),
        },
        "server_params": {
            "event_request_id": "e6fb130e-2326-4b73-9729-ed9267147b04",  # from confirmation code request
            "flow_modifier": '{"flow_name":"new_to_family_ig_default","flow_type":"ntf"}',
            "is_from_logged_out": 0,
            "layered_homepage_experiment_group": "ld_no_language_selector",
            "device_id": data.android_id,
            # from confirmation code request
            "reg_context": "AVgIyhY2WWV7XdE4GTvwQv5PwpFJ53msUHytpcj6MvbKkZB7aJuuP8XiJCXVqjIuKxff3kEjTjgPApwOoSCsa-3xeFyzmFYxH4sk-NWQMaB_7X7Ws9yxr-htkYqS5ke5m5GjxJf-xbs70pBquF3QkJ-MpVWFPw3rjZfs5CFz51GuzEtioCHw_prciiOQOWxUClot6uDTkarl4NUdUBfAU7oPyrjQbkkUDcY5UnhGMH8kncpG0CsWl4As3Ss_O6DtVwXKXcM818QC6anCEVw75AsIeEuP-A5r74UWa9XuewJTwxrmWqAYy8m0DvssAHjzh7MtX343Hsd7GINSBdkQc-M8IVxcHosgHfY0qg2vDOXLZmxUOxyyipfxtzy8qG2KZvDGVM7kECgBKsOZ19McQIP6TWnjWJxYhp9ex5r1D2sWwoGCjJ_xzqd5O7WeIziwIybExbi4fIgV2c7w5v09I8buSZQ2_DxS3Di3EARwFyGBD6DpGdvite2NcNr4YHZA-pUTpWqeJNFpHnXUcDMbjxkPSEJ_XaBIZpqfRmtFSvkKjzeh3hf8BztUMUGqmJIPvWwYqzFlEUVer6-ijdki7ss4Z996iVAHGT46qd_tq6XFsyeLtJ-5b3MQeQS83qi8IvObHPl2jUVb4whkgVUmhFyjfPv8Z0UzVJ_V5j_LaJUW4jicKK-jaesG7LtqKskl54-79sLIKAIdIx58h1EKahB0YdtT6S27ksicBsAe4H6I2NQiZ5HS7tHNV1Pgn3tcpsK73oJV02Wjl3onarJj_cX-5OZflusDNhzfSglNiQkxxFjbvz4u1FD7jGnw7HZb9TEwZFaWCU-lqRzDHScS1BiARsxnrT3rSgaa4kf0gfkZm987CzXJvSOqE5pfny4Pnj1aekK8KHqpRIikEHSd_fdR_UmVzSGGzqah7ed8aZDOcCH_tDhqeVyGzli0rLcMJSElq_VqCfLeLlrzuRogIBZZxwUckSjxox6qAbyxYXeiaFQdD9zs2wlzGSpGxdETGKtqsHvvr3K8am89dtL2dZIC_Hg3uVD0s2MCw0sutDjo_jLMMj_mlokRe5y0Y7PPUs5LLtWfaGZS6FqooVAGCK9zDHm3M3fxBwnzGtlp6a2ZNZDICNVRkwc8NoeW0SdsdDKirvJPf9WkRS1UJdMxnW6un-bY_F25ZWEIVAAEBWbUWYwsUFriLhBueXyZ4lheRMsDV87_22j0irm-c9l9nW4e8YHlN1vM9dXSrzZJb8XM0ve7W634kCxgFe3opZY2B6FJkpj5EKxzsVHm9AEnfl3YGphHvFCOu1h-g55bK-jcQqJQZBJiZpFJ6mgz60nNgUDxYAgf3snDaG4wZG0-q8p6qoK32tQntXNharuZYGYYu3q2OV1garGeMBAO_TX6BDD85cRIunr4nQc1QlNMbvQEQJicmjqycyIVk4Lw11z4PfMDnjGcNH7up9ThJIQxwa0x6eMAIFph9NmxLU70-xOiZfk67yn0wuBXALHwY7iWSHNEQrv1RJ3lKugyepWMsWQBtwzlPd31xPNyTJJaCU2eqDi8E5CTfefIe30_hS8PYFInF7MeEJgzMCofdC70NW-2l_gDfqS7dUWItUpWRKB3p-UOrqxk1xIncyIVpE5FsA7WCbD7HNxC2hMrQcry4CU1IkiLo2Q4qdPvPp9M-AdbMS6ExflGSMaQT85yVlAiZpeWaY6hefJUtdOxl8gK3yYfzKvzbgu14jzeWWfZQvxYXZ80CsQ6huaJNwl2JNqfN4-w1_LFWrzzz4u-SwprRxBq_0JAMoPjwVYtOaI4wLV_YsZ4WNKOjcK5txLowbUrZY7uo526QqUpHVGm0HpPcq3Sdh7blAWeneJY8XPQhD4vF3D4Vd9tXGe3dqsjKNZObrjSTLcw6b8_Rc2KHJkAIeWKDJPyXnH9liwfJzJBwG8EC7bFbzUtvoQeXYi_FpPVqbSaXBxhAI-YbZO65AzxwV_1zREW7J4zz2QP7V1GMSFqYLytYag5CcPBtVX6uTgUxcU5PU0Jinz-P8zRIjZa6rSVyyy70Lq65a5qdK7yd5UTc9-MkgAH3r7s_Whi83UqLPsKz-VoaLxDW8coSHFwsv-Npizou01d7Z9PSScS1BRHeWZgved_R2GiwCevcvqNA5mUrkxtjVLO_ytMAXimaE3ZmeYwx5IQwLts38N-WXbtcbLNVJkb3HHq8ToUrT0uqryFZNn5keCnxVZ_hOp8SoEtsw4SffaZsNDg-m9mYMKLJkCfXIZKu0AJ_OWKLRRW7rZfwKwutyLp0gAjNA4_Pqn1mEnM_2cGDgBDBd-eefn8CLVB-QiEjWEw6wvic8r2ai4qDYKAHGu-wXAwRnPVY4Z-9cpSE71kANz1zDdK492J4A8rlrX-NLGtWo8YAv3grhfDH-7JX3Kgk5IAVVSxGu1xkQr1blm-FBlQhuovhLlpE_qWjHoEvYjW6LD0BsTEyLJToFiwOLPL_eaW1sjhQbRmhPP7dkfCuz-QZj4pkOJdQKcYItrNpN3uSaQaRZ_G0n4-N8CRxNFWi2JOPTiL9UT98ZkRVAU5c5LRc5FsVK_KjFVMRxhhedxZ50qMCi-3rw1KyVeNipBF7xPyO54CGJgzoKHl-DjSoCt1okRYksRjP9cgccqsl02ntKw53R9tiR7Z-hrHnGWDK5pUgmPePwI3Cjh2_S6NmdA_1ZbPTkBGytcSIdkIvrSc9ux4BXbuWtef_P_O_rYCNmVw5JJYsKRMxETOKvci3IY3hBUArMbHrEQAHSYlzPQutujQXXOxh2LmvuWSMH1cCA8oWFKNQOLOgy3I140qPlG9-8yi9DKOkQ7_Ve2v-Dgddzgz0Agi_87ydnDsh9SX1l8SKwBojAtpNz6bATQUzpd796z0ZRZa6Nf0RtXMsFqjBpJRbkh0Eqe3cPkntkHD6xXYXQ55keHtewerEA2k7HgSFqQeZYORc25sDBo87WHgAvmH3HeHc0P0K5CKbLOyHC-ghrmNglBjNkSbZUfSDH54_hWsIiXpz8POqJwpGEssur5RCNf6V7_4yQ161-5cwxwIA96saeoRb1HyZzBONM6VJaHBJkmmiOaCIkeClOco2toBwVYFagJuh_6eHK8alBfJP1cc--jW5N0cHqggjUnaLJageNKNZ9CJNbuZ4tOHmeGdZqp6ZfTzLi4BIU1GNz9UoeYR8aifsAMYAYjy_5IYy7Q28I7wIiOHkgxNKSLYjFu1trSf6maXz_zy7xpJbFRylvHqpxTBOULr49OXj5Q77VwE4_o1lKrkWO3Ck3EgfRCMTigszPDKUhofnYAdGCyNYrXjYjsRxO1Y6FKKt3kflLIntfJLiszcbXJhj4iU1OzcsU_Y9ztlShpfC56qic7cdYy4U8Huplq4dRr88iw87L2gi8BlrCrapBBwxXohNGAbznk0w-ka8Qk-HBo_1WsMBPk38LpieIWyfRHXm5N6b6H3Fp1-523kZHpMMVoVrT8TR0EAtsIEFJg6xIA6JaO8F36aTCMTg1tb5mDBDQF2yW00xiHY59oWJXyJW6UiN5xbqDBBiZCoRNhHG3_pXS_YWmpXQUmliG2zO9cLxb3PSauVSprCwNgVM10nH10BOWDovZ4IHcqJQC_WNmUt9VSSSs4m3OU_liF5k7614jEJMLP1PJmZkO2oi3aw_4rQ1ThojIcyLhqMb_rMGYHyBVsMTKkY7_cpESqXeTk2HYsKLEO-TlB8wrWsikShi8C9gpU4TJbFjCIajBum2Isa1x8fkGcDSP96slrtP_KcMzI2xPhxRWEVSoYZaNFwFuxlUFfrpI2ZWsN-105EOnHM-UVSzdPdKJzl_izzKSJQgz-W2Ep4-bjRgm9DBCoNx2-jACKLhnegKJlQVAV7PARAB7eAOVEKneGjV-bxC_R3_0QXD7NpTNKop4juQamYaIvNSMlPs1XK57JjIitze_YgdGIJB78_gq_spGxn7L7tEzhTOs-l80xZb8f77c4AhfFH8t5iQDIJJx3ZmBzS5ISieR3TcG8IGdd5kuG249Bx4vVOoWVRciyZtGJmMI2jOEhn-MawPEu1pG9V7fDt3Tp8RlLwv-ItOkOQeDbf_QaDfyF2XMXh56FgH4h4gYopjCDPF8BizUKywCrlejoh-nYmLt9dxP1eZ1KphfI0evoO3ePsQXsNqZQOBWxq5XH15eD_s_1g6iGUOQlk7Ul5hlKDD15QYyT-RlxvCdmunRMjlWSX-OsHm_sBJecgkxThWSlg6ftvukmJfwpsUW5-NVcuCytwwoCjsLuvCsuCrmxy99Em0LER_XjgMY59fZnMReKBu6PSBWu-mfCU0Q6FUqLPHu_boR9HnYt5Oo6WHo1hJkC-EOFLitn_A2MsH5axybMgUGtO8j15SxoDa1dyRSDFNmwqETrxJf_T85o-VpyTS1-GtCqzcF_irkvVVzxeucdy1CGXxs_k-tdmYXwn2F-NcrnOkeT8H5GvnyOLmzRlY4FuLxDJlVYNJ_ofcZWcusC9pSRoCe1DrHji_vhBQgzOmvaqcGNvq-Cgz6UQQF-UwX_Hq9rfv1ZPG7uVw6hohlDkae7dYJ2y4v6uVpxX91h2oTngewLfTGVI92Il5goWBuBe-DrTNU-fPOS1RYOhQHDOEuamyaBY3Es0YBcjfn3lZfZifWr7yOeOH4Jmb3XN_ckjmGx6BWIS4Wan2FY5Gl2rUSnoNJg1aNbLfz7Cf6yT2XAS-VtPF2z-IrlMPxNt4YFvYur2eoth84CRj5IhhVflpRWmN0ap648-KtYxXHMnG0kcI7hKpVHkZQuCWEDhVVkqyumY3r2Db3V0AKYRdmGDsAL0V5ciqkpNRw2PmHqbGn9vKO86cb8M2jKmc139qS2zNVDkPDeYhtQ2SUfK5ctLeyTOBSvymEyDOV2DAADY8U6EBghaSX5iU3xg3QXSTCrqHvZJXUMoWRjbUzXZ1rqUPVTQ6HgOnrEbM8XNsss2GZAxkw8LasuSY373QPylqVdWwnKkk57TWCnoVy8STL-jHdEjqH10RTo7are1GHq123je-c5xVwxHGKglcuNLhAvIZmugb4gtT-GmNMLW9Ea0S40I9kaTOvu8bI06-qCmqxbB8wcV2zNKkIrVhcsduZAUc66ozFyxHC_EjLo0jOXBkxH_pbg3aQZyqENbdr5yeMZYnfTvkCCT-Vy-_8RanjahXc36hqePUbXML7mwNomJcr7fnsuTl1eRdrIUwCuCtceZD4WFhDXsHScaCeF-9AIbvpPLdM2Xb5dxJbSsUl2BRZdvmpkAxwegiIJOkwGyUaZxLba_MWc0L3-8kvMudMTilmGH1to1k9r72ymWMvNZKpkGwTyezUMAPzM865tPbeau1KjqlYPn5jTsM1jZe6TP_ktBuqs0q4qwanIGq7IqOGyQzc5E3rEK6QG7BpiLiCQQ_xtY9x55xh887RPDbRP51p0LlXhiiVZK_rELD9e18x0LTNLuoUcc2mrtUagbjvb_HM3i3qsIs2X6XDpnqjGXqpRLnzln28EZx_h3odK843Js_ORYUmCYwV7lX6CZfRHb_m2R0B2V6-iLTxeCAjSEpM-LvNHH6yzruROR82yU8HGTjhFk6q2eFRelQuTfhp-dG1SDXVvopgQ-X8M-fnuh3y0k_d3hyotzXi1PYZg-458Tqvi3nOszDEuq_h7u1j86B610RDDCd8cl35l14YpfsVT0bI6RBTfosHJvzJeFHmJ3hOPhSwLD-2Or7K2_5cDC29OUkW33-G4_GjgWFUHXkG0ezAtkIyGBgI9mFyjQVloDGeBwvHhA4AmPDefskftqrP0sCXWhQ1wNfgslaMQ-uIqDKYo-Vqp5-iKxA8TkFZpkgYP75w4t2OhLo2ThWSNLRpf2bExnmeW828AIBKZ5UgOaLqa1omJAyOcCMtXMzPnMHhg_gI3Lbb1KZFp9VNVo1M-_vu6XKDXX5cmEOUAycmRbh9QNAfnIh90fUaGvAgf1s2Ze6wAzgDlJ6k4ntcnCLOBI5AlKNpr728TDNgFB_uh5Lm9tq7p7tsilslbf0g7PjIQq_f7OsooaaGEOjFdp5Ntv2tbkIMm3gn6T60OLjpD-LMHzCuGgjauPYUy0XqvxP9HwUA_56Py0dokSVqlO2NQm1WdM2t_ITY66PWzflDlKnaILQH2MS1Uk2KJSD2LA3ETPTigU55VuBJxaNQjlMfgsH1DvWQ3nYckj5iCqb99cHT0ZIPy2Equj5FBXAQx3zjFsOLidGbOC-CaeJiWIvRYhQm9yvEKBLLiTnfVDiP84DjLNpb7Ii3BgcwsQSfEuyrITR5-yF6pNPvSXKhVFsLZed_7lNHceTKTIGRqmnMSxT9f3fEuG8rH51h4dBuSsfeHt6xViOA3IsgUBEciqobomRwk1_TXRP02GxJXIhfgwP14e9lesNz8HyJ3SM4-IxcZq4KcrqzFz6Uk9Aqfj1dyFFmlUFSj9x1shlhx-HnoER2fwhshcIco6yQ2BQUsa8o4ie5OeKiUsXON7jsoRgzqFfcY6JY6bxHk39GIET_YTDHnNYo1Zue7Xo6YT4nLbiT3Bsk-CJB1WgKhvsLu2hQSHydu_QW0m4xPNkaFW1EhwixkFdcL2Hi8r6_2GWTUv3VAIKDahNUjpMiQCYdIkwdMShDcIslNPXuQIfTmDUmZtA3tzcEmFBfo3PNuP6eCufa4c6QHkhykfFvN-aLpQsvsitFC2S2UqQ58Kd6u8M9tmCi_EsBav2VTwVUWcSiq9gir1CaiHFF6vaeGGl2oBoXn6A0Zf1tiPPTnnciVVksCSQRzEfWqi56FClghfozXJ9FIgyEUNCHiUCOKRc7M_3vwI-unYXiBdbCsjzs69QnVF6KtD8SsT91tt8ocAiEjsW65KCWaks1OovM5rf_5XhqiRrcWp0Jw46Q7sHo5QQMszbYmdABiHOYmIrhw8VJEol5JPvRGlsLyUdlTS7bz5tOL5BxmFdn_I9-wwOus-TPP45hVdkkOV3PRpLyqo6bwJXZQ_1zD97pq_1PN8qbmftqwsk-5-vHqBZJojrqnZLp2W3p-r8DbXPMMb_pn9rsRukpWw4nZVYo1bo9W_YBNx_yFifdYDspKVMgfi4fxCNBJAN22crOzIxGnykcs6sNVz350nY8pSHIJ-uZeQe571chyb0hrtFZxn6V-6x0gh4vjFGOAjpDq8iRfvVgVfTNLVng6tLfi7B0DVTnrMJ0xSgmqmRKYrJHx5zk67bgZKwvrI4QtQ4rihl8DuCk8oirpeDpwDYrIEqXeuAHJJkM0JFLoCprtHnJai2xOb0uuY6vPU-2Le5a2W4KoDDGTSKkg4_qIYc1JjiF9nYOIjhPRxQgrHQRFqhsu22ApUvIk_d9PnebFB-JNtlWLbYy3VilpBrt72WGf6V41fI_W7UK2g8OnhsDCUWfmVB0b_EE03kVPEPRC9NLzG1OjXUl0mez0-t8IxF8_8mLANMCM_UO949bLqP9FXHUrfqP0lvGnDKS5Pidy0_iiz6-R3-G5VppHJpUpo3wIug2l2PrEunmrXqnN0uzPZM0osII8gaW8ja31AubAHB9LiYBSjlgCIj00hBggYp7t3hxvde54c_Ua89G-zHOGIf4rgdYNddQK0pjBtY575X_5JcQEwduuwUg5nkJKB5XNVqZhtkK9qTeUYW61vyPKPJ-NzavnGwDlxK81JRAmxiYKhFREqk7rBfoyFkxZvbEUWj3mBZV4kX69_QV_4zRXt3bNeGBMZEbY-gOBq5R9ohvSMqh0ZmnYiU3C4Yg5Bo_AfvfgMSHPSbTRuQ93WeuoStnd7pqz-PIQ3ZC3gV3klIsIXeC0X_248yEpXtwK8XVs77QxGD1HZs1acE-Z5ROzZlSeAxo95hZVtm0LwbpJhZ8isla2zWTwIgIKSFriPonIsWD3jFfj3j85X2o210vZY8BPUD7NbW2Q1h5GxmanYAgqddyIxs_VNX_BoEbh0eZaM0NN2Jg0rhDW4FGkhKI6b44rr28HLL9cUd9TrGkTqNz1gy2AHVi0s1CuBipK0HJv99P9zlH6uLdd9Zu9fPUlVyB4qMUSn3J2Rzb2sAJ1YhK4sMGaF-npOGZ85vX6YDKscFIkUGYCJaRhSIB0FtlexZcuXyLcLklO9yaFatNEIYsvqftYzzaVCKAGcmeAKYN6D4xteZ9V9o1dr1JA53q3WxTrBKO9sFyJASXvzeoW9gYZB7P7dU8tqFr3V8QwcLrUbUPOxFiKgMA6GBD4mzZS8joNOSJ3LOC_u3ZvRw48ebxyIPpTuHzhONTfY4yJlkf278L5X0RkVKmt25UisFX20XpveYjlhokCV6q52VNYmtHQazNrMcjJPHuhGKrfhY6NeZOI_s5b28hj4b5etGAhoDatCvcjX5FIMEPm6lHdfrd3CTSlm9RCX74ok8n_sLcs466DfpvqnJ-qAi2vYAw0XiYVehHGh4P9JGy_UN-r0Wh0gdSry48hT0K0gH_vHenZMOgQ3riP-TFptALAIvtlZaJnOPmpaELZiVfuvLI7Kyno1Y7oBMl-5IRRCOmhEfcKovUCXXlsjIAF1q4Qo9zqmrkhSxo_jQTXwHoAhtAF5v3Ceeivk-spn_RM7na1nWyKDVaU9MQJJCLzkAMv6QXfpJHQrrHQH902ao0uzMwInJmpk801-e8RNgvHAHhSt_WC7IiEeA-wQoV5VjHQqD7hn3ckiinb5wPNIEhAbP-jvs9Dy4pppsCOT8RILJMTa36jf7KSKyR4mi_RNuF4sn43_blb2ar8UxSl9rM_fiKlGizLfEbqYiJ16pcu7_kb2vRo_16rzu0GF6qeLfwhHp22LRWIbDx0KeAOKC-FayYcd|regm",
            "waterfall_id": data.waterfall_id,
            "INTERNAL__latency_qpl_instance_id": data.qpl_instance_id,  # from previous code request
            "flow_info": '{"flow_name":"new_to_family_ig_default","flow_type":"ntf"}',
            "is_platform_login": 0,
            "INTERNAL__latency_qpl_marker_id": data.qpl_marker_id,  # from confirmation code request
            "reg_info": json.dumps(reg_info),
            "family_device_id": data.family_device_id,
            "offline_experiment_group": data.experiment_group,
            "access_flow_version": "pre_mt_behavior",
            "is_from_logged_in_switcher": 0,
            "current_step": 4,
            "qe_device_id": data.device_id,
        },
    }

    return {
        "method": "post",
        "pretty": "false",
        "format": "json",
        "server_timestamps": "true",
        "locale": "user",
        "purpose": "fetch",
        "fb_api_req_friendly_name": "IGBloksAppRootQuery-com.bloks.www.bloks.caa.reg.password.async",
        "client_doc_id": "356548512614739681018024088968",
        "enable_canonical_naming": "true",
        "enable_canonical_variable_overrides": "true",
        "enable_canonical_naming_ambiguous_type_prefixing": "true",
        "variables": json.dumps(
            {
                "params": {
                    "params": json.dumps({"params": json.dumps(variables)})
                }
            }
        ),
    }


def get_password_create_headers(data: RegistrationData):
    return {
        "Host": "b.i.instagram.com",
        "Accept-Language": "en-US",
        # 'Content-Length': '30283',
        "Content-Type": "application/x-www-form-urlencoded",
        "Priority": "u=3, i",
        "User-Agent": data.user_agent,
        "X-Bloks-Version-Id": data.bloks_version,
        "X-Client-Doc-Id": "356548512614739681018024088968",
        "X-Fb-Client-Ip": "True",
        "X-Fb-Friendly-Name": "IGBloksAppRootQuery-com.bloks.www.bloks.caa.reg.password.async",
        "X-Fb-Request-Analytics-Tags": '{"network_tags":{"product":"'
        + data.app_id
        + '","request_category":"graphql","purpose":"fetch","retry_attempt":"0"}}',
        "X-Fb-Server-Cluster": "True",
        "X-Ig-Android-Id": data.android_id,
        "X-Ig-App-Id": data.app_id,
        "X-Ig-Capabilities": "3brTv10=",
        "X-Ig-Device-Id": data.device_id,
        "X-Ig-Is-Foldable": "true",
        "X-Ig-Timezone-Offset": "7200",
        "X-Ig-Validate-Null-In-Legacy-Dict": "true",
        "X-Root-Field-Name": "bloks_action",
        "X-Tigon-Is-Retry": "False",
        "X-Zero-Eh": "IG0e09d776530888418ab70f3822fbb4e1",
        # 'Accept-Encoding': 'gzip, deflate, br',
        "X-Fb-Conn-Uuid-Client": "95b2bb513e6c590b7147b9e4bcf849d8",
        "X-Fb-Http-Engine": "Tigon/MNS/TCP",
        "X-Graphql-Client-Library": "pando",
        "X-Graphql-Request-Purpose": "fetch",
    }
