import json
import os
from src.utils import write_response
from src.flow import utils

import requests

headers = {
    "Host": "b.i.instagram.com",
    "Accept-Language": "en-US",
    # 'Content-Length': '19799',
    "Content-Type": "application/x-www-form-urlencoded",
    "Priority": "u=3, i",
    "User-Agent": "Instagram 410.1.0.63.71 Android (31/12; 420dpi; 1080x2274; Google/google; sdk_gphone64_arm64; emulator64_arm64; ranchu; en_US; 846519343)",
    "X-Bloks-Version-Id": "b7737193b91c3a2f4050bdfc9d9ae0f578a93b4181fd43efe549daacba5c7db9",
    "X-Client-Doc-Id": "356548512614739681018024088968",
    "X-Fb-Client-Ip": "True",
    "X-Fb-Friendly-Name": "IGBloksAppRootQuery-com.bloks.www.bloks.caa.reg.async.contactpoint_email.async",
    "X-Fb-Request-Analytics-Tags": '{"network_tags":{"product":"567067343352427","request_category":"graphql","purpose":"fetch","retry_attempt":"0"}}',
    "X-Fb-Server-Cluster": "True",
    "X-Ig-Android-Id": "android-f35f126bc4795e76",
    "X-Ig-App-Id": "567067343352427",
    "X-Ig-Capabilities": "3brTv10=",
    "X-Ig-Device-Id": "c734a1c7-d663-4fad-af07-817b064e424b",
    "X-Ig-Is-Foldable": "true",
    "X-Ig-Timezone-Offset": "7200",
    "X-Ig-Validate-Null-In-Legacy-Dict": "true",
    "X-Root-Field-Name": "bloks_action",
    "X-Tigon-Is-Retry": "False",
    "X-Zero-Eh": "IG0e09d776530888418ab70f3822fbb4e1",
    # 'Accept-Encoding': 'gzip, deflate, br',
    "X-Fb-Conn-Uuid-Client": "95b2bb513e6c590b7147b9e4bcf849d8",
    "X-Fb-Http-Engine": "Tigon/MNS/TCP",
    "X-Graphql-Client-Library": "pando",
    "X-Graphql-Request-Purpose": "fetch",
}


data = {
    "method": "post",
    "pretty": "False",
    "format": "json",
    "server_timestamps": "true",
    "locale": "user",
    "purpose": "fetch",
    "fb_api_req_friendly_name": "IGBloksAppRootQuery-com.bloks.www.bloks.caa.reg.async.contactpoint_email.async",
    "client_doc_id": "356548512614739681018024088968",
    "enable_canonical_naming": "true",
    "enable_canonical_variable_overrides": "true",
    "enable_canonical_naming_ambiguous_type_prefixing": "true",
    "variables": '{"params":{"params":"{\\"params\\":\\"{\\\\\\"client_input_params\\\\\\":{\\\\\\"aac\\\\\\":\\\\\\"{\\\\\\\\\\\\\\"aac_init_timestamp\\\\\\\\\\\\\\":1769034606,\\\\\\\\\\\\\\"aacjid\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"d2c8ed10-f952-4a12-aa09-e83671b1bf71\\\\\\\\\\\\\\"}\\\\\\",\\\\\\"device_id\\\\\\":\\\\\\"android-f35f126bc4795e76\\\\\\",\\\\\\"zero_balance_state\\\\\\":\\\\\\"\\\\\\",\\\\\\"network_bssid\\\\\\":null,\\\\\\"msg_previous_cp\\\\\\":\\\\\\"\\\\\\",\\\\\\"email_token\\\\\\":\\\\\\"\\\\\\",\\\\\\"switch_cp_first_time_loading\\\\\\":1,\\\\\\"accounts_list\\\\\\":[],\\\\\\"email_prefilled\\\\\\":0,\\\\\\"confirmed_cp_and_code\\\\\\":{},\\\\\\"family_device_id\\\\\\":\\\\\\"dd5b9513-0be3-4263-9106-459e51268b46\\\\\\",\\\\\\"block_store_machine_id\\\\\\":\\\\\\"\\\\\\",\\\\\\"fb_ig_device_id\\\\\\":[],\\\\\\"lois_settings\\\\\\":{\\\\\\"lois_token\\\\\\":\\\\\\"\\\\\\"},\\\\\\"cloud_trust_token\\\\\\":null,\\\\\\"is_from_device_emails\\\\\\":0,\\\\\\"email\\\\\\":\\\\\\"e70375344@gmail.com\\\\\\",\\\\\\"switch_cp_have_seen_suma\\\\\\":0},\\\\\\"server_params\\\\\\":{\\\\\\"event_request_id\\\\\\":\\\\\\"d9b4df62-a454-477c-ae9c-f6208305c56b\\\\\\",\\\\\\"is_from_logged_out\\\\\\":0,\\\\\\"text_input_id\\\\\\":130881677700070,\\\\\\"layered_homepage_experiment_group\\\\\\":\\\\\\"ld_no_language_selector\\\\\\",\\\\\\"device_id\\\\\\":\\\\\\"android-f35f126bc4795e76\\\\\\",\\\\\\"waterfall_id\\\\\\":\\\\\\"d6031628-57e9-4414-93ad-9911cf738e0b\\\\\\",\\\\\\"INTERNAL__latency_qpl_instance_id\\\\\\":1.30881677700106E14,\\\\\\"flow_info\\\\\\":\\\\\\"{\\\\\\\\\\\\\\"flow_name\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"new_to_family_ig_default\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"flow_type\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"ntf\\\\\\\\\\\\\\"}\\\\\\",\\\\\\"is_platform_login\\\\\\":0,\\\\\\"INTERNAL__latency_qpl_marker_id\\\\\\":36707139,\\\\\\"reg_info\\\\\\":\\\\\\"{\\\\\\\\\\\\\\"first_name\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"last_name\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"full_name\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"contactpoint\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"ar_contactpoint\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"contactpoint_type\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"is_using_unified_cp\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"unified_cp_screen_variant\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"control\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"is_cp_auto_confirmed\\\\\\\\\\\\\\":False,\\\\\\\\\\\\\\"is_cp_auto_confirmable\\\\\\\\\\\\\\":False,\\\\\\\\\\\\\\"is_cp_claimed\\\\\\\\\\\\\\":False,\\\\\\\\\\\\\\"confirmation_code\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"birthday\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"birthday_derived_from_age\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"age_range\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"did_use_age\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"os_shared_age_range\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"gender\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"use_custom_gender\\\\\\\\\\\\\\":False,\\\\\\\\\\\\\\"custom_gender\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"encrypted_password\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"username\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"username_prefill\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"fb_conf_source\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"device_id\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"android-f35f126bc4795e76\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"ig4a_qe_device_id\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"c734a1c7-d663-4fad-af07-817b064e424b\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"family_device_id\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"dd5b9513-0be3-4263-9106-459e51268b46\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"user_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"safetynet_token\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"skip_slow_rel_check\\\\\\\\\\\\\\":False,\\\\\\\\\\\\\\"safetynet_response\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"machine_id\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"h1NxaVnaYULGGzgpCn_hPfVP\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"profile_photo\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"profile_photo_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"profile_photo_upload_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"avatar\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"email_oauth_token_no_contact_perm\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"email_oauth_token\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"email_oauth_tokens\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"sign_in_with_google_email\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"should_skip_two_step_conf\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"openid_tokens_for_testing\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"encrypted_msisdn\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"encrypted_msisdn_for_safetynet\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"cached_headers_safetynet_info\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"should_skip_headers_safetynet\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"headers_last_infra_flow_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"headers_last_infra_flow_id_safetynet\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"headers_flow_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"was_headers_prefill_available\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"sso_enabled\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"existing_accounts\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"used_ig_birthday\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"create_new_to_app_account\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"skip_session_info\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"ck_error\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"ck_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"ck_nonce\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"should_save_password\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"fb_access_token\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"is_msplit_reg\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"is_spectra_reg\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"dema_account_consent_given\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"spectra_reg_token\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"spectra_reg_guardian_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"spectra_reg_guardian_logged_in_context\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"user_id_of_msplit_creator\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"msplit_creator_nonce\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"dma_data_combination_consent_given\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"xapp_accounts\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"fb_device_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"fb_machine_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"ig_device_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"ig_machine_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"should_skip_nta_upsell\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"big_blue_token\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"caa_reg_flow_source\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"login_home_native_integration_point\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"ig_authorization_token\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"full_sheet_flow\\\\\\\\\\\\\\":False,\\\\\\\\\\\\\\"crypted_user_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"is_caa_perf_enabled\\\\\\\\\\\\\\":true,\\\\\\\\\\\\\\"is_preform\\\\\\\\\\\\\\":true,\\\\\\\\\\\\\\"should_show_rel_error\\\\\\\\\\\\\\":False,\\\\\\\\\\\\\\"ignore_suma_check\\\\\\\\\\\\\\":False,\\\\\\\\\\\\\\"dismissed_login_upsell_with_cna\\\\\\\\\\\\\\":False,\\\\\\\\\\\\\\"ignore_existing_login\\\\\\\\\\\\\\":False,\\\\\\\\\\\\\\"ignore_existing_login_from_suma\\\\\\\\\\\\\\":False,\\\\\\\\\\\\\\"ignore_existing_login_after_errors\\\\\\\\\\\\\\":False,\\\\\\\\\\\\\\"suggested_first_name\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"suggested_last_name\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"suggested_full_name\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"frl_authorization_token\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"post_form_errors\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"skip_step_without_errors\\\\\\\\\\\\\\":False,\\\\\\\\\\\\\\"existing_account_exact_match_checked\\\\\\\\\\\\\\":False,\\\\\\\\\\\\\\"existing_account_fuzzy_match_checked\\\\\\\\\\\\\\":False,\\\\\\\\\\\\\\"email_oauth_exists\\\\\\\\\\\\\\":False,\\\\\\\\\\\\\\"confirmation_code_send_error\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"is_too_young\\\\\\\\\\\\\\":False,\\\\\\\\\\\\\\"source_account_type\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"whatsapp_installed_on_client\\\\\\\\\\\\\\":False,\\\\\\\\\\\\\\"confirmation_medium\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"source_credentials_type\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"source_cuid\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"source_account_reg_info\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"soap_creation_source\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"source_account_type_to_reg_info\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"registration_flow_id\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"2bfd5926-c03f-48eb-8e17-a98ed947592c\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"should_skip_youth_tos\\\\\\\\\\\\\\":False,\\\\\\\\\\\\\\"is_youth_regulation_flow_complete\\\\\\\\\\\\\\":False,\\\\\\\\\\\\\\"is_on_cold_start\\\\\\\\\\\\\\":False,\\\\\\\\\\\\\\"email_prefilled\\\\\\\\\\\\\\":False,\\\\\\\\\\\\\\"cp_confirmed_by_auto_conf\\\\\\\\\\\\\\":False,\\\\\\\\\\\\\\"in_sowa_experiment\\\\\\\\\\\\\\":False,\\\\\\\\\\\\\\"youth_regulation_config\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"conf_allow_back_nav_after_change_cp\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"conf_bouncing_cliff_screen_type\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"conf_show_bouncing_cliff\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"eligible_to_flash_call_in_ig4a\\\\\\\\\\\\\\":False,\\\\\\\\\\\\\\"eligible_to_mo_sms_in_ig4a\\\\\\\\\\\\\\":False,\\\\\\\\\\\\\\"mo_sms_ent_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"flash_call_permissions_status\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"attestation_result\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"request_data_and_challenge_nonce_string\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"confirmed_cp_and_code\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"notification_callback_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"reg_suma_state\\\\\\\\\\\\\\":0,\\\\\\\\\\\\\\"is_msplit_neutral_choice\\\\\\\\\\\\\\":False,\\\\\\\\\\\\\\"msg_previous_cp\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"ntp_import_source_info\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"youth_consent_decision_time\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"should_show_spi_before_conf\\\\\\\\\\\\\\":true,\\\\\\\\\\\\\\"google_oauth_account\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"is_reg_request_from_ig_suma\\\\\\\\\\\\\\":False,\\\\\\\\\\\\\\"is_toa_reg\\\\\\\\\\\\\\":False,\\\\\\\\\\\\\\"is_threads_public\\\\\\\\\\\\\\":False,\\\\\\\\\\\\\\"spc_import_flow\\\\\\\\\\\\\\":False,\\\\\\\\\\\\\\"caa_play_integrity_attestation_result\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"client_known_key_hash\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"flash_call_provider\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"spc_birthday_input\\\\\\\\\\\\\\":False,\\\\\\\\\\\\\\"failed_birthday_year_count\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"user_presented_medium_source\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"user_opted_out_of_ntp\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"is_from_registration_reminder\\\\\\\\\\\\\\":False,\\\\\\\\\\\\\\"show_youth_reg_in_ig_spc\\\\\\\\\\\\\\":False,\\\\\\\\\\\\\\"fb_suma_is_high_confidence\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"screen_visited\\\\\\\\\\\\\\":[\\\\\\\\\\\\\\"CAA_REG_CONTACT_POINT_PHONE\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"CAA_REG_CONTACT_POINT_EMAIL\\\\\\\\\\\\\\"],\\\\\\\\\\\\\\"fb_email_login_upsell_skip_suma_post_tos\\\\\\\\\\\\\\":False,\\\\\\\\\\\\\\"fb_suma_is_from_email_login_upsell\\\\\\\\\\\\\\":False,\\\\\\\\\\\\\\"fb_suma_is_from_phone_login_upsell\\\\\\\\\\\\\\":False,\\\\\\\\\\\\\\"should_prefill_cp_in_ar\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"ig_partially_created_account_user_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"ig_partially_created_account_nonce\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"ig_partially_created_account_nonce_expiry\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"force_sessionless_nux_experience\\\\\\\\\\\\\\":False,\\\\\\\\\\\\\\"has_seen_suma_landing_page_pre_conf\\\\\\\\\\\\\\":False,\\\\\\\\\\\\\\"has_seen_suma_candidate_page_pre_conf\\\\\\\\\\\\\\":False,\\\\\\\\\\\\\\"suma_on_conf_threshold\\\\\\\\\\\\\\":-1,\\\\\\\\\\\\\\"move_suma_to_cp_variant\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"control\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"pp_to_nux_eligible\\\\\\\\\\\\\\":False,\\\\\\\\\\\\\\"should_show_error_msg\\\\\\\\\\\\\\":true,\\\\\\\\\\\\\\"th_profile_photo_token\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"attempted_silent_auth_in_fb\\\\\\\\\\\\\\":False,\\\\\\\\\\\\\\"attempted_silent_auth_in_ig\\\\\\\\\\\\\\":False,\\\\\\\\\\\\\\"cp_suma_results_map\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"source_username\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"next_uri\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"should_use_next_uri\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"linking_entry_point\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"fb_encrypted_partial_new_account_properties\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"starter_pack_name\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"starter_pack_creator_user_ids\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"wa_data_bundle\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"bloks_controller_source\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"airwave_registration_code\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"is_sessionless_nux\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"login_contactpoint\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"login_contactpoint_type\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"is_nta_shortened\\\\\\\\\\\\\\":False,\\\\\\\\\\\\\\"should_show_bday_after_name_suggestions\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"should_override_back_nav\\\\\\\\\\\\\\":False,\\\\\\\\\\\\\\"ig_footer_variant\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"control\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"device_network_info\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"is_from_web_lite_reg_controller\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"login_form_siwg_email\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"account_setup_waterfall_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"is_wanted_suma_user\\\\\\\\\\\\\\":False,\\\\\\\\\\\\\\"device_zero_balance_state\\\\\\\\\\\\\\":null}\\\\\\",\\\\\\"family_device_id\\\\\\":\\\\\\"dd5b9513-0be3-4263-9106-459e51268b46\\\\\\",\\\\\\"offline_experiment_group\\\\\\":\\\\\\"caa_iteration_v3_perf_ig_4\\\\\\",\\\\\\"cp_funnel\\\\\\":0,\\\\\\"cp_source\\\\\\":0,\\\\\\"access_flow_version\\\\\\":\\\\\\"pre_mt_behavior\\\\\\",\\\\\\"is_from_logged_in_switcher\\\\\\":0,\\\\\\"current_step\\\\\\":0,\\\\\\"qe_device_id\\\\\\":\\\\\\"c734a1c7-d663-4fad-af07-817b064e424b\\\\\\"}}\\"}","bloks_versioning_id":"b7737193b91c3a2f4050bdfc9d9ae0f578a93b4181fd43efe549daacba5c7db9","infra_params":{"device_id":"c734a1c7-d663-4fad-af07-817b064e424b"},"app_id":"com.bloks.www.bloks.caa.reg.async.contactpoint_email.async"},"bk_context":{"is_flipper_enabled":False,"theme_params":[],"debug_tooling_metadata_token":null}}',
}

response = requests.post(
    "https://b.i.instagram.com/graphql_www",
    headers=headers,
    data=data,
    verify=False,
)

write_response(response, os.path.dirname(__file__))


# def get_submit_body(data: RegistrationData) -> dict:
#     reg_info = {
#         "first_name": "None",
#         "last_name": "None",
#         "full_name": "None",
#         "contactpoint": "None",
#         "ar_contactpoint": "None",
#         "contactpoint_type": "None",
#         "is_using_unified_cp": "None",
#         "unified_cp_screen_variant": "control",
#         "is_cp_auto_confirmed": False,
#         "is_cp_auto_confirmable": False,
#         "is_cp_claimed": False,
#         "confirmation_code": "None",
#         "birthday": "None",
#         "birthday_derived_from_age": "None",
#         "age_range": "None",
#         "did_use_age": "None",
#         "os_shared_age_range": "None",
#         "gender": "None",
#         "use_custom_gender": False,
#         "custom_gender": "None",
#         "encrypted_password": "None",
#         "username": "None",
#         "username_prefill": "None",
#         "fb_conf_source": "None",
#         "device_id": data.android_id,
#         "ig4a_qe_device_id": data.device_id,
#         "family_device_id": data.family_device_id,
#         "user_id": "None",
#         "safetynet_token": "None",
#         "skip_slow_rel_check": False,
#         "safetynet_response": "None",
#         "machine_id": "h1NxaVnaYULGGzgpCn_hPfVP",
#         "profile_photo": "None",
#         "profile_photo_id": "None",
#         "profile_photo_upload_id": "None",
#         "avatar": "None",
#         "email_oauth_token_no_contact_perm": "None",
#         "email_oauth_token": "None",
#         "email_oauth_tokens": "None",
#         "sign_in_with_google_email": "None",
#         "should_skip_two_step_conf": "None",
#         "openid_tokens_for_testing": "None",
#         "encrypted_msisdn": "None",
#         "encrypted_msisdn_for_safetynet": "None",
#         "cached_headers_safetynet_info": "None",
#         "should_skip_headers_safetynet": "None",
#         "headers_last_infra_flow_id": "None",
#         "headers_last_infra_flow_id_safetynet": "None",
#         "headers_flow_id": "None",
#         "was_headers_prefill_available": "None",
#         "sso_enabled": "None",
#         "existing_accounts": "None",
#         "used_ig_birthday": "None",
#         "create_new_to_app_account": "None",
#         "skip_session_info": "None",
#         "ck_error": "None",
#         "ck_id": "None",
#         "ck_nonce": "None",
#         "should_save_password": "None",
#         "fb_access_token": "None",
#         "is_msplit_reg": "None",
#         "is_spectra_reg": "None",
#         "dema_account_consent_given": "None",
#         "spectra_reg_token": "None",
#         "spectra_reg_guardian_id": "None",
#         "spectra_reg_guardian_logged_in_context": "None",
#         "user_id_of_msplit_creator": "None",
#         "msplit_creator_nonce": "None",
#         "dma_data_combination_consent_given": "None",
#         "xapp_accounts": "None",
#         "fb_device_id": "None",
#         "fb_machine_id": "None",
#         "ig_device_id": "None",
#         "ig_machine_id": "None",
#         "should_skip_nta_upsell": "None",
#         "big_blue_token": "None",
#         "caa_reg_flow_source": "login_home_native_integration_point",
#         "ig_authorization_token": "None",
#         "full_sheet_flow": False,
#         "crypted_user_id": "None",
#         "is_caa_perf_enabled": True,
#         "is_preform": True,
#         "should_show_rel_error": False,
#         "ignore_suma_check": False,
#         "dismissed_login_upsell_with_cna": False,
#         "ignore_existing_login": False,
#         "ignore_existing_login_from_suma": False,
#         "ignore_existing_login_after_errors": False,
#         "suggested_first_name": "None",
#         "suggested_last_name": "None",
#         "suggested_full_name": "None",
#         "frl_authorization_token": "None",
#         "post_form_errors": "None",
#         "skip_step_without_errors": False,
#         "existing_account_exact_match_checked": False,
#         "existing_account_fuzzy_match_checked": False,
#         "email_oauth_exists": False,
#         "confirmation_code_send_error": "None",
#         "is_too_young": False,
#         "source_account_type": "None",
#         "whatsapp_installed_on_client": False,
#         "confirmation_medium": "None",
#         "source_credentials_type": "None",
#         "source_cuid": "None",
#         "source_account_reg_info": "None",
#         "soap_creation_source": "None",
#         "source_account_type_to_reg_info": "None",
#         "registration_flow_id": data.registration_flow_id,
#         "should_skip_youth_tos": False,
#         "is_youth_regulation_flow_complete": False,
#         "is_on_cold_start": False,
#         "email_prefilled": False,
#         "cp_confirmed_by_auto_conf": False,
#         "in_sowa_experiment": False,
#         "youth_regulation_config": "None",
#         "conf_allow_back_nav_after_change_cp": "None",
#         "conf_bouncing_cliff_screen_type": "None",
#         "conf_show_bouncing_cliff": "None",
#         "eligible_to_flash_call_in_ig4a": False,
#         "eligible_to_mo_sms_in_ig4a": False,
#         "mo_sms_ent_id": "None",
#         "flash_call_permissions_status": "None",
#         "attestation_result": "None",
#         "request_data_and_challenge_nonce_string": "None",
#         "confirmed_cp_and_code": "None",
#         "notification_callback_id": "None",
#         "reg_suma_state": 0,
#         "is_msplit_neutral_choice": False,
#         "msg_previous_cp": "None",
#         "ntp_import_source_info": "None",
#         "youth_consent_decision_time": "None",
#         "should_show_spi_before_conf": True,
#         "google_oauth_account": "None",
#         "is_reg_request_from_ig_suma": False,
#         "is_toa_reg": False,
#         "is_threads_public": False,
#         "spc_import_flow": False,
#         "caa_play_integrity_attestation_result": "None",
#         "client_known_key_hash": "None",
#         "flash_call_provider": "None",
#         "spc_birthday_input": False,
#         "failed_birthday_year_count": "None",
#         "user_presented_medium_source": "None",
#         "user_opted_out_of_ntp": "None",
#         "is_from_registration_reminder": False,
#         "show_youth_reg_in_ig_spc": False,
#         "fb_suma_is_high_confidence": "None",
#         "screen_visited": [
#             "CAA_REG_CONTACT_POINT_PHONE",
#             "CAA_REG_CONTACT_POINT_EMAIL",
#         ],
#         "fb_email_login_upsell_skip_suma_post_tos": False,
#         "fb_suma_is_from_email_login_upsell": False,
#         "fb_suma_is_from_phone_login_upsell": False,
#         "should_prefill_cp_in_ar": "None",
#         "ig_partially_created_account_user_id": "None",
#         "ig_partially_created_account_nonce": "None",
#         "ig_partially_created_account_nonce_expiry": "None",
#         "force_sessionless_nux_experience": False,
#         "has_seen_suma_landing_page_pre_conf": False,
#         "has_seen_suma_candidate_page_pre_conf": False,
#         "suma_on_conf_threshold": -1,
#         "move_suma_to_cp_variant": "control",
#         "pp_to_nux_eligible": False,
#         "should_show_error_msg": True,
#         "th_profile_photo_token": "None",
#         "attempted_silent_auth_in_fb": False,
#         "attempted_silent_auth_in_ig": False,
#         "cp_suma_results_map": "None",
#         "source_username": "None",
#         "next_uri": "None",
#         "should_use_next_uri": "None",
#         "linking_entry_point": "None",
#         "fb_encrypted_partial_new_account_properties": "None",
#         "starter_pack_name": "None",
#         "starter_pack_creator_user_ids": "None",
#         "wa_data_bundle": "None",
#         "bloks_controller_source": "None",
#         "airwave_registration_code": "None",
#         "is_sessionless_nux": "None",
#         "login_contactpoint": "None",
#         "login_contactpoint_type": "None",
#         "is_nta_shortened": False,
#         "should_show_bday_after_name_suggestions": "None",
#         "should_override_back_nav": False,
#         "ig_footer_variant": "control",
#         "device_network_info": "None",
#         "is_from_web_lite_reg_controller": "None",
#         "login_form_siwg_email": "None",
#         "account_setup_waterfall_id": "None",
#         "is_wanted_suma_user": False,
#         "device_zero_balance_state": "None",
#     }
#     variables = {
#         "client_input_params": {
#             "aac": '{"aac_init_timestamp":'
#             + utils.get_pigeon_raw_client_time().split(".")[0]
#             + ',"aacjid":"'
#             + data.aacjid
#             + '"}',
#             "device_id": data.android_id,
#             "zero_balance_state": "",
#             "network_bssid": "None",
#             "msg_previous_cp": "",
#             "email_token": "",
#             "switch_cp_first_time_loading": 1,
#             "accounts_list": [],
#             "email_prefilled": 0,
#             "confirmed_cp_and_code": {},
#             "family_device_id": data.family_device_id,
#             "block_store_machine_id": "",
#             "fb_ig_device_id": [],
#             "lois_settings": {"lois_token": ""},
#             "cloud_trust_token": "None",
#             "is_from_device_emails": 0,
#             "email": data.email,
#             "switch_cp_have_seen_suma": 0,
#         },
#         "server_params": {
#             "event_request_id": "d9b4df62-a454-477c-ae9c-f6208305c56b",  # get this value from "email registration button click" request
#             "is_from_logged_out": 0,
#             "text_input_id": 130881677700070,  # get this value from "email registration button click" request
#             "layered_homepage_experiment_group": "ld_no_language_selector",
#             "device_id": data.android_id,
#             "waterfall_id": data.waterfall_id,
#             "INTERNAL__latency_qpl_instance_id": data.qpl_instance_id,  # get this value from "email registration button click" request
#             "flow_info": '{"flow_name":"new_to_family_ig_default","flow_type":"ntf"}',
#             "is_platform_login": 0,
#             "INTERNAL__latency_qpl_marker_id": data.qpl_marker_id,  # get this value from "email registration button click" request
#             "reg_info": json.dumps(reg_info),
#             "family_device_id": data.family_device_id,
#             "offline_experiment_group": "caa_iteration_v3_perf_ig_4",
#             "cp_funnel": 0,
#             "cp_source": 0,
#             "access_flow_version": "pre_mt_behavior",
#             "is_from_logged_in_switcher": 0,
#             "current_step": 0,
#             "qe_device_id": data.device_id,
#         },
#     }

#     return {
#         "method": "post",
#         "pretty": "False",
#         "format": "json",
#         "server_timestamps": "true",
#         "locale": "user",
#         "purpose": "fetch",
#         "fb_api_req_friendly_name": "IGBloksAppRootQuery-com.bloks.www.bloks.caa.reg.async.contactpoint_email.async",
#         "client_doc_id": "356548512614739681018024088968",
#         "enable_canonical_naming": "true",
#         "enable_canonical_variable_overrides": "true",
#         "enable_canonical_naming_ambiguous_type_prefixing": "true",
#         "variables": json.dumps(
#             {
#                 "params": {
#                     "params": json.dumps({"params": json.dumps(variables)})
#                 }
#             }
#         ),
#     }


# def get_submit_headers(
#     user_agent: str,
#     bloks_version: str,
#     app_id: str,
#     android_id: str,
#     device_id: str,
# ) -> dict:
#     return {
#         "Host": "b.i.instagram.com",
#         "Accept-Language": "en-US",
#         # 'Content-Length': '19799',
#         "Content-Type": "application/x-www-form-urlencoded",
#         "Priority": "u=3, i",
#         "User-Agent": user_agent,
#         "X-Bloks-Version-Id": bloks_version,
#         "X-Client-Doc-Id": "356548512614739681018024088968",
#         "X-Fb-Client-Ip": "True",
#         "X-Fb-Friendly-Name": "IGBloksAppRootQuery-com.bloks.www.bloks.caa.reg.async.contactpoint_email.async",
#         "X-Fb-Request-Analytics-Tags": '{"network_tags":{"product":"'
#         + app_id
#         + '","request_category":"graphql","purpose":"fetch","retry_attempt":"0"}}',
#         "X-Fb-Server-Cluster": "True",
#         "X-Ig-Android-Id": android_id,
#         "X-Ig-App-Id": app_id,
#         "X-Ig-Capabilities": "3brTv10=",
#         "X-Ig-Device-Id": device_id,
#         "X-Ig-Is-Foldable": "true",
#         "X-Ig-Timezone-Offset": "7200",
#         "X-Ig-Validate-Null-In-Legacy-Dict": "true",
#         "X-Root-Field-Name": "bloks_action",
#         "X-Tigon-Is-Retry": "False",
#         "X-Zero-Eh": "IG0e09d776530888418ab70f3822fbb4e1",
#         # 'Accept-Encoding': 'gzip, deflate, br',
#         "X-Fb-Conn-Uuid-Client": "95b2bb513e6c590b7147b9e4bcf849d8",
#         "X-Fb-Http-Engine": "Tigon/MNS/TCP",
#         "X-Graphql-Client-Library": "pando",
#         "X-Graphql-Request-Purpose": "fetch",
#     }
