import os
from src.utils import write_response

import requests

headers = {
    "Host": "b.i.instagram.com",
    "Accept-Language": "en-US",
    # 'Content-Length': '30216',
    "Content-Type": "application/x-www-form-urlencoded",
    "Priority": "u=3, i",
    "User-Agent": "Instagram 410.1.0.63.71 Android (31/12; 420dpi; 1080x2274; Google/google; sdk_gphone64_arm64; emulator64_arm64; ranchu; en_US; 846519343)",
    "X-Bloks-Version-Id": "b7737193b91c3a2f4050bdfc9d9ae0f578a93b4181fd43efe549daacba5c7db9",
    "X-Client-Doc-Id": "356548512614739681018024088968",
    "X-Fb-Client-Ip": "True",
    "X-Fb-Friendly-Name": "IGBloksAppRootQuery-com.bloks.www.bloks.caa.reg.name_ig_and_soap.async",
    "X-Fb-Request-Analytics-Tags": '{"network_tags":{"product":"567067343352427","request_category":"graphql","purpose":"fetch","retry_attempt":"0"}}',
    "X-Fb-Server-Cluster": "True",
    "X-Ig-Android-Id": "android-f35f126bc4795e76",
    "X-Ig-App-Id": "567067343352427",
    "X-Ig-Capabilities": "3brTv10=",
    "X-Ig-Device-Id": "c734a1c7-d663-4fad-af07-817b064e424b",
    "X-Ig-Is-Foldable": "true",
    "X-Ig-Timezone-Offset": "7200",
    "X-Ig-Validate-Null-In-Legacy-Dict": "true",
    "X-Root-Field-Name": "bloks_action",
    "X-Tigon-Is-Retry": "False",
    "X-Zero-Eh": "IG0e09d776530888418ab70f3822fbb4e1",
    # 'Accept-Encoding': 'gzip, deflate, br',
    "X-Fb-Conn-Uuid-Client": "95b2bb513e6c590b7147b9e4bcf849d8",
    "X-Fb-Http-Engine": "Tigon/MNS/TCP",
    "X-Graphql-Client-Library": "pando",
    "X-Graphql-Request-Purpose": "fetch",
}

data = {
    "method": "post",
    "pretty": "false",
    "format": "json",
    "server_timestamps": "true",
    "locale": "user",
    "purpose": "fetch",
    "fb_api_req_friendly_name": "IGBloksAppRootQuery-com.bloks.www.bloks.caa.reg.name_ig_and_soap.async",
    "client_doc_id": "356548512614739681018024088968",
    "enable_canonical_naming": "true",
    "enable_canonical_variable_overrides": "true",
    "enable_canonical_naming_ambiguous_type_prefixing": "true",
    "variables": '{"params":{"params":"{\\"params\\":\\"{\\\\\\"client_input_params\\\\\\":{\\\\\\"accounts_list\\\\\\":[],\\\\\\"aac\\\\\\":\\\\\\"{\\\\\\\\\\\\\\"aac_init_timestamp\\\\\\\\\\\\\\":1769034606,\\\\\\\\\\\\\\"aacjid\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"d2c8ed10-f952-4a12-aa09-e83671b1bf71\\\\\\\\\\\\\\"}\\\\\\",\\\\\\"lois_settings\\\\\\":{\\\\\\"lois_token\\\\\\":\\\\\\"\\\\\\"},\\\\\\"zero_balance_state\\\\\\":\\\\\\"\\\\\\",\\\\\\"network_bssid\\\\\\":null,\\\\\\"name\\\\\\":\\\\\\"Eugene\\\\\\"},\\\\\\"server_params\\\\\\":{\\\\\\"is_from_logged_out\\\\\\":0,\\\\\\"layered_homepage_experiment_group\\\\\\":\\\\\\"ld_no_language_selector\\\\\\",\\\\\\"device_id\\\\\\":\\\\\\"android-f35f126bc4795e76\\\\\\",\\\\\\"reg_context\\\\\\":\\\\\\"AVjkEY9lF0jTGN38_b5Qcnx_av7U0H_e9rUw9Du9AreI6CGmt25YpMosqErTHexqLnrSibtG70GxK49-LaBQk2LmpYNXIfVrra6MNCo70T7tEOZAAfS16-LhZikJNq1az3hIpcJNbL0gVYowTKT-sXJ7AHHglbZOYf3ESBCHNqrf8CK4FMp6_YISU4gHQqPMQ6r14d_h-bAQikBH3EGEXfcFIOxBvXDHFN1vFX1TgrHl2Isdk7CMxAiDEdIzeVv_IGrFuj9s37CY1zN_G0PdBjh5rX8hULfTNttu7l4awtcHwvnpXphwt_DEPfNJ3_rYswQuECP9j9y-tE4KHGtav0FYwVbe0GH_hCjJDbbNGM3NjibUSbV6pg_dlx6dZqfmMMM6oEVu-fRszxupOxJ-SVTCxO3ptC3CQmXdDUwy5J2eP7d1_qAbpB-R8_R1mdEHGjE1JZZHFYr9w9n_kQ_jhRBazGWLeLAwCFicRz97HrreaK95leTWB1FyUieMK2JUhtmpOP0VZaSQh-Tww7GGVhO-DFVwUCjdKPJUwTNOVs-WvlBeDaSsgHG9zsGlewRzuQlcIj1q9FwXVpTeGATGai5_Bbq-e2v3ltJiMHT6A2NsNUPFY7R0Fh8w9qsd4I7ebYKl2IItH1zCwmOso1YpvtYrsxLpux3zY4DwOZKZ6MY7NQz80XabfGITysprRkF0gyfsRjBnPQUGBksiXKfAZm1Og6znhOualco1lWkglzfPOipTWHPzHC0IemjAxejatprVsFoqOi0Rs83hXRhpUJjD38gqAwvnlu2C6o-4w6O18ZxCInlSPJp50-IAWBrkzmMvLTTwKPaBBqSnWEZMBgLYl-cagcl8DxRgv6AXGutV01G8zBBy2E6uNJeZfnsQ2hLLROarWZ5nScx14892G3aKUXfk3HJCxJV4is7nx65Tp4S8KxmChnGL96acsUel4TM-qg_x13ZLxe7rc2iGaWzsX7HAsOrAKBd5ppUeLV8b-_WUwo0k9EWMeLTLCNHsZc9DeOGmKjJ13GTfL9gfqI4G6QKN-ICZfeYkfp_c5TKvSdBuheCFp8rzI70zkgUrQ0nisZOLIieVUggK7xtcsDD5aevWgEYoqIKh0X7CbOqbtKpZldNXoDUbrkvvgtIFCTd7VXaKYNExwzQPOtjXvVOIGQX55-DFSgEvjL9bU2J0ZKfnvzKmGphtHURz6GvFSIDd6_t2O1LcWGm6BtXMT-aaZ2AdsO4uPUepTadxhDwEon-bzTiH_kxM0RlaA7H132e-vQO6WaQBKwqM5fpQHlqj5_YXj_jEwg43tP7_VDWQZNTJBnQ_mlIKc2MQiDVRvshhg4Zgh87BkW53JuRPK-ZNJI_gWOxleeam5AT8VnYzIo9SAeSQaHIsPzKB_wjp3meGyIBrPQeDPOG6zsbHy5-1ZHuBmi6uRGXMemJrFxgkhBqjwNtunVq9XORwomcSuAUnJ7eECJSxDXx-oiPbspUQetVUwi5V4pcsmUyWNo-CzC5IGCme85jEYbcTlaZiBC81460TT5LqholQIlUAJrBGMdhMzWbZ7U_8Buy58_l_APyrBtKiQ6foJO-rQLeqryxytBqNwDtGhKAtp7Pt3D40pR23_Z_9oKaxHkuy0xKvBFWjxyi4R8LTdQGgaoz-CMi_5-IdfpI-TF4CP1YvSkI_lFYjaVJ5PZB8Yg2ulfnJN5rjCdH_d_nB_l3OgR9Po8vSzWW5mhDke7jBUbsCSXuKLwrGLgVyumeOsoCbl1vUBguCFhWWgcVLt8LE1NrTSQcwL9Fq4b1gTc4zMfBxLhkzlx1yMM10Ij78fVp5S-nhWpUesWzwDv3zezz7aD_tDRFaEQb8iyC-LMzZ1oF2ODjSB0vf6-7HHvsHL8H9r-Der76RjnihJtSEXi-UsR5-QW2tyWhb39-_sCuevdDkF1BOqoMysliDzsiImNkXiUgHuWyxb_idqNPdOAv1uqn7hdc4eAlDZKgxhiwGQ5LsXGvF5e12Iw9NXXcNT45khxTPMlfDlFVXSS66xIAruQyCCE7wXKjPP2RwXWv68qWoU6RY2ga2fzt0gTCtFxueqZl5XrSmV5syIVwLV7DB-4zAuwtk-Vz5s_wKowBxab1NJ3utplS6ckVlDUyDcKC5OSdd50qgKilpjcH_Mx1ecPpEO1v0w_NkPKNaY0sP1Z-ztLE68C2Nm_JLACKcwi763b0YnHE9CIgZAp7gYZ5Y2AobBGBfXtAeCVYBG_KL_o-zWVvWEuSz8DScOxVO79D15FzEdZb4Ercl3RWR77WU2pVMPgiC8q4lhiJoRvFhMS_PAvJ69dS3qqiPVZ0btIXiMU8myOYPx6Ni9ZcZXOmErudL6zNTMH8Re714_Qtyvu3SLNCggHGG-GFNKgCJBfKgURuFVtCCcTJsrKQqw83oOg8_bpMrGSXoUmFVFLoFk4BHYW8IT_I5jA6RkqdPU5UxpM7yfo3tFTjG3nrfAf3eyPLgexNmxQz7uNDb6zJGVzPSo0FS8YegGSbUuqrZrGxUoxTMjJ404m_2kE7vav72lPUAoYpUARZcOUUf_wIbaQ6Zuf954w2lyGMHAP5eqyYd5sEN5aMoveUhGl4l-AsVsu5L64TpsGS1xGVpnOd0_d7mFZl_3LEW1xsVoSkQ0LZM7HN4Z1-OL6cJ0xBt5ybQ-bzM1iqCkkwe3kpILH_NT2JW5nsnQSWGBlmrZrMpcaVs956WE9bHinhGSvuTjOQlV1ksm4WhI8XTNXHEx8wzhxe3t3KYEQndm53vxdNzTj3as7hfZkbmjybmOGIbeMa75RukkfcDvQIt_8SFzwXi9mQH6RCUcGVzk-f1fM-oYu_Y4ajN0TYFRp6cltI5jRVQVrB9-ES5MYItu_0LAr0B0Yyo7vjjkntzWGpydCbGH8XS_txbWM5Z8G27XT2f7G3MF4vJG2aV0WzrfBka1tAV7tbeKVnvk9FJob7TsWuXmzlVYHX2WARDnOQ8E2IvJe86BWJkyBj1UiFOegX8-4ukZdx4ucQanL0ln381r-GIhspqLQjuLp5IWNvCOvLpjoy_JptwLEGvTG4F3biMsJVSNXIJA3KcuZHvAnHlUWRmN_Qpa0_UGz0u3Mx_5AmRkja_eA0Im9Cddufb1vPQGz6vFWE6IAGJzCi3BdPIHuUMTcAgt7hHq4gSYUna-caC-NRe6AtAUFwLtgni7Xp8ZgD_gSGpjus9g9T3oL-WP2zGVTmrolLqHJrWZegBc3IzYkpsG9EjXfIRxQFTg91imivOEiG9BqB6CzOP-ZSvk997SXtxZB6-cWJ2vZhtBIT1tyScrqd4u8MssryPLgueZMex0H6EKfArAjCMTkyy0oQegJpBR_28TagT3PCLEUxYjQXuu7H49vYvw-OiMWPcHknSdfbzCAXSAq21_hgqxqH_R13TxIQhBKDloU9EThOmlh1vU4ww-kE-oh-pKT_kHDzKeADtDw0bUSlEAESaRJ68qpC-xlPmROwwRJlVq439zUDL4gGP7otbdSd5RRicp4rnRXwjzMIf7WG9ajEszXdLODcxChNy14uO7fiCfpH5IfjcCgILmD6nEzcp-JTIb39IeEmhVnNbolVKFQ3jRY0a0CKrjGsd0oKG1ynsPVb8FUSMDfy36gfSAQzLoKIEXbvce-V6InTg-h9MHX2y3OhIf5i8IfnjzFrOJaZ6UzM0Rdgce7QJ4rKiyid5QbVQQBxQiR2DQz85EVbkFAffqm0gBHLkQnSX403NMgg_zogMHvrIbnPOcDr71qGu0KtiuSvuk0dU1fR56WEQKpL_2Td4_X6hoL3nwa4JEAtXIhIdjRTIfaXXpkBcqZ_Po3MIfAM5_IBqZq6dpe6yTb0-pmCxlBR9w98BKK81zr1gPoX2h02rb8eqlqmfffjAnW7moGc1pA4xtTlv7SJPHNcRYyshjwuQifFKSENSk_fOJpQrD2gG5BihhIHnrboktLSyhUsj3NjL8PMQPbQpT4je7gO2xmriJpeFv99mtiOKtwJd8ooq4AflTQd6BVlWPAnXHqRDwBLWRpbTgh6rcgj4RbN5z5Zu4zhEz8X2RPmSpgThZ7TXj8Ndf6E8ZzE6WhtuhuP5Vby9ihERkJbxCXyOLZZMKPmLxyITVeuz3WDP6JEGPht5ptMHwHsANhKICCYbn9dvNwngpOhwn4VnfMt5-1xhmy2GqqxoXBHm6QofIHwbuGed0W4FdtkeXQL4P14wSH1CKSLoxHFU-Xhhbmi1Ir9m71R1sfwLw-qsiHOgW2RUjPi5FBdVprXiLOaEopj1DnI_pk5U8_8Q0hTcUOq7-Gx-kdbd8cjzovP9jz5_HQ632-clKXHHmStWW0jIMCYCOEE1RZt_qz4X1DCc3MYnCdLys0wkHsFHBDs4Ief-cS5TwVpITbNbqs-X_R3ewVAz5hSO9GLDTymG1jI8OJqAluF1dht6aWGWcomFkI0mVFQAv1cN-3Sli7n7RY7YkwELwrnMDompuTlqYAEMFO44lu1oJ4uX5EPf973KzFyv9YwlMiBQ41TkPa-U-ZE3EQqI4klYOzNCoTEXHEmw4DTMuvBTh8b3UlJdCZ0LuuYP2Mk7TuHHfFshOyi-ZnA_VBoS3ylZ-UK41JkXt_lEiVXOYCk6J5IOwcR4_0ySKoz-SDIf3MVMpI2RDK6hyw3EO4MmVdPUfV833nOD82XtQnHMkFyHgJ5UrtK8DCmqMfgXzbHJtHMb2dQ-VugAoL84cr3-dvKfm74NF8tlWtCVaNCPdQGeVtExb8Mw_pRprTaCOM-OxqRRP3M90FIC60WHjMBcSvlmkeS-tda8mlVzDOAan_vk4FAEaz3XYTeaU9sdaEm--1j2q-7zsvm14cZmz2mSK3rTiLli0j0ASYBWmO0U3rsNqZImHttZq3k1Q4tq58MaqxNIYeE9H3a-LOoXZ7KHdJmUgFZ7Z6gYZrvwLXHrMomRG--J3tuayYqW5hWxdcFIUdPfqA4NinhjhOcHJEWUzh6duD-HZDbulITNz7Xi5RVcp08VQ241hkosDBXCWFd4XEGi0kFkS4opK2SSy55RoA9jnYFFJchKiRPHp4hmCN8m9kcbG0IE3j-qLUv9LaNQD6IGY6T18IJYap_Ez_UArNUevH1AA-lP4YNkbAhZkYYdK2ZJn3ykpBp7-4o67EzI2-7G7-H9NfXWcW1H6ae6he2SkXY8Y1A0lCC6FdVw-6IBes3xaGAlh16CFLuZ5RBoai03B66kraxjiy8vCp_4HJIFER8oR03rLZH3U-i806bzv5hALizXCRQTamimMSdJxtp3gHYB3g0hGpzKUwBl-__Qfx2A7G-E0MzPaA9pOA1nx_VMU4rM3ShqMuwz3pE3Qkgkfs52t9b8f-FGlgUKNxSFpMU8cq3vtmCs22TbNspsajUFkjWfJvUoC1WFxTahFno_LqSibiJ6FQVLCqx7Ax5hAfUJYVcVmZL4FHVe1PMRYYwtRVpe0HMDJW3u3PBh_YM8qJyOwUvrc2_aPp9_w1HFAnZs3B1P96IeWaoco7DX6WLWgYihpbEYCaFg_QKPxY7PVyzCRNzylZPY2YrzQZ6cxGKfMYIkYiGR7jTI_IjUTAqreSm5abofv4jgCqwCs6HBvCB73ZUx4zPCzUqh6ldbmbOuaxYla7rDn1B8jFNYmXoXAA4T9QVItJJKYmNFagMo8McTtfTfKCudRn_n0SdYD0kGOVv6CibSZL646CjKPrmOQPELErqmiHfZuLH8z58SZNDEVxXJPpCnIykagB52TTZmXmXIDPrq4aNsQ-6EWk4H4K89q8j97iiZg9c6Y9xNOl328QNe6RWOSRgODG-6zOF_9BNAq8hAG3QBSDG_hRLwj0bZ_wre1LiVZ9KySeNF90KA7EZS0Tvv-iO43h-mTTEVkIFQGxRObiP7_8yUjO55brF9zVZPBBQU8C8oDIWkFbwP1lUljfiDGKy49JBNQ4rT6W9OrzxnJisshDc_F6rOea3Y4YljjHJASrWvmrY0onK597vAq03HknRKuZwP6If1uPUKNs77PnasQlSOmpMf7hHV1vFPks_5LvE3HGzWVABM6BxXgj5cmlsDSpuNqyuAplrCbpThcmGf-p3sSSHkQs336tGWfbjjcTm5DbqWaGYtYS_mA8i1xfB_BIOTh1tVYm6c1qbbBQgXfwtz9A2nxxXgRCFNjj3fFMRb99a0Tov37JIIELkIsgn5jb0vtAwdQP6RXhJQ84a8iVQw_3DVZBWOTGy-8uhE3lHbGFrpUaiiMdvscIqI5W2dgM9KfftnGDLqCiRIORKsJFnzGIxRh_pEfCejuBfahNBJyCaSoz61t-pe7cmdbSB6D4dCCbCgLH5GYt-gwLC7IeMksJWh2VsIaT91AMuBV3Iew9ehGB_c6H_Tia_1YcU7Gfy497Z5KTeQykpbkagvyi-5HLEuRyC2nZFjQ4B149SHKFFgRkw_ZTAmQvQ_tnlKhj6P038UMGBOrttTny7RKtd-gh_7zmEbA18r6VYWMDw1mCi0OIZ_GW8nrQby7IqKSatWkXGxeFsNB6d5xM_EtR0KED2s4ImeEQtAI2uguImd-NyDygg7lHsqANECtH8WuHO4IqEPFV_Rr--swGNdkKZYq_AXPg_I47mRr9kBd-c2tY43JmTT9nlrrZBBHIGQg7FipPnPBMAwp4iKLNFtTE0nnd4p55aSunZljXlF2dS3TDZflXbf03XEP5lubhE8LT3QhXgn8-m3ooEUlozpXTfF65Ky7dAF_rpgfI1LzcXWz0XEffZV_-iFQk6WTfgSrnreCHm7YX-n2IyOhmAYTHYRTLS15Ml13CKkalfj6c326BY7thdlGeasx6UNwI8VkWpzMHPJFwmaUBPD6KegEwJT1vTHnI4JUkftCNEjaY123xl_1ja3PaEm57pMvdR_3JyCQj6m_Ym17FFO3-IAIpZ0MTU1HUCGw8qHPfk9jL4SnnFY3a7zYFeXIoXzO4sGrO_YfAEhCmsiu8OYJ-vhogPu-KOg7GnQNgH2FLOJIiVf7FJqWYTdxQop1J1d3dI18egjTXMuVXOR7tV39n1vTOHwnMQXq_AGBsV1CrFM8PvNLMZzZvHa2KrmJqIj0I1q8zmkqXtaUHahQqUW0B1S1EQhiB9t2iZIlNM-8B4GbXIn6chXbYKY-jNPFvLKRKhpnXFLWyDjkxxWc-z7R-ToiPVGGhYTkdMGmIfG6rfteJOhnRtSJ9a92pzCwlhXNDGNOi-aKsXhhjfFzdfb7LOjKYNSqIQN_BoRscrXGmsMrZp6drUnfGkTksuEUJyBgRx5T5RdQEfQS1p4X7DTD01H1fDP9IxptVo6HJLzntADAJ-LQRmG1DO4lX1-l6zZCPW7Io6XYnh4p_n6TRCLzgT_XUkEKmsctA7jD1KFPSajAVXAOpvZ-OyzSm3RyxTkAyV4uR3p0QWUObFQAxkQIYprgkOq8RnAJ4aLqVZIzIagH3kcEeiDzKUgewbDp7y2yXa6YGgVS2PkqOfYTkitqB0JzmsLhqnMr-w51YbuhehcAL82RS0n9tulqpo7Rew4XMA5c6quQ9EinFeFek_AVO1htKwbBFP6VZHBfRtm4_SGBYZqjHVocbxfnQT3SfYBzn0yrkdTvgID4QRZG78_jC_Du1PwQRj4iI5SnUFKspIp-oWggzpHWRFvinTE2wVlXenlHT-mBJbc7FDRqWs6PsQb6JZOeDGnma6Rlv5xLOTSNqkC-3w-RgrzOmFJOIbTYYEqGpPDoTE4zrNCu3Z1_3dPRp88y1Qh9wT1b2nc_5hG6mSnWFX7w7hE5Y0f3dJn8HXXXoVHCF9HsokLpDY5a3c0Af9eXbJQewhzlLesIZ8qo_CLL9Us8HMn3iD8kND_WgNV3Ph08H97a4LMX2DuDXxC2ZTDCVIvJRG8QinxJWTyfjXkGCQY5qspTWB3mdp7PgTsqRungOlmcmhlLjEUTeA9we4s43uC32nIG0eB6SmEt4SG9z0yJ6XAZngdZ2WncoE0we-PSD0shbHFAW7Wg_lbEgie1rfugIRHnjMHNW1UnADpWrvQ4mjxtv5RonT-ZDZ6Lr_gXOWMq9Pd22z_Pf2lOlOfEmsnK_CercmGqJMwKNe6fyEbkmCeI5oL_oXzH_-uf2AF4UJZk242oMmWUoycaeltHu7CIsDw5u4jh7xl1tBogploqKQKxaxk0zrFcCN9mvMGJTEYbnaJhXDb2ZdaahgwmCnb_IqNgZSmu9sjoOrO7iq3cZdgtal9PhFHXR6YgmBpbuwBHp7mu8u3N2XXWUG_dRRSKZjbEuSUYFXIcEwiXEJOqWJWCg-z4Tyvo1Nu3hR3Dbo8XnUkO2wy_AmaZJR1fNNHw7owq1PYoD7SXmhomTtkQcf2ue4WZ3GuUxOJwwDCR77lsqe62GnHd4PbdnLMbEeoKXnRZuFtweBWS_n4CRbHNtvjgo5vO_5-c5m8qDCK18dLrdUrHqZO429eOuH0-WTV5eS5w6pTYjChbSRhVOVJAU1b2EMZ43-aHT5-UTnf33JLfK-PVW9Xy3gSB5RydgQAK0TEWdKQsBUWKV-GX7Yu81FXgNGQLgSZXT-0zVOdFm1x95MxTYZP6PxBkHHthgeBmCjI-mTNfGUd9-TUZamtrnzV20GiXFLRRQsJIx4_W5QctW2gThxdYAV9okAk11NCmN144Z5SNaNlY4SAQLIwGUQx0e9KP6oQ5_Pix-GSbipC4vgyTt7V_qsroP9G5nqjGskNKsr8En61F_eGiXGxEp8DPb4YYpyKnN_DjTWt9CwON_oz9n3VzH7nShQmYbsl6tcXHdPIie_qpbCSS52QK3wXBHz28UBgv3xY67zKutfstVbtkXlfFlcSE6MJXa3yqvui5Ixzf6Qj3xgBgoLrjoXlgR2Dv_yfmY2_KgT62j4oOsbmIF1V_x7N82NsUzCqQDBYyRARUK4KGwZ1_6KcwQEH2kIaHXouD6sqbecotjzMWK6f9HiVd1Z-UIO15G6UYbWMQ6NRc-prNlqOIZYXXNFIa4Ake9ixxExUklB_loVbJdZkUnK-Gg9dqIsQIcJ0NJzqpCSTufoc-8laNpso5hPkBKQvda9LxiBDr4JUG-poKCzigGuFE_I8IZYKqkZ-a0ltGe5UbIvq6OfJNnqKKTvuEpoWIzDgqmNV83IudqntqMFWAtjfN0uMqa36GadZ2BuTKgeTkoCPUqjLX7Ob4-kvb95K9qENCxKGab2kbaqlJRjt0_CRU63EiVJBUpueM60VCGPBeXJeHox38cFGAI0QnV5zBO0_2iZyFbDk9zCNxFNmyN4o2n9nGJymxUzgYipuUkpwT1ESKRvQIfk7iPH-azkgqRBvAR2jT-fS1KGYwLQ_NjwhhtiIhsnUk2nz3afDDH-0yZgh1PRoaEbcPQ0Bo-OAkeIVIRglLKVQYU4hZrWFAyXYWZZlaPiwI97r_J6o2mFI8HtpmX4Rt0aZkKjgIQ8qvOCViKwAk2-rbqb6QIrh7lusVUMQWYQbu0iwraNjjM4vaF1LuQ6ShmRelp3AYEtokLJ0DMgP6SfDY8SlGH1m0wZ00RZhK1WdmMwoM5wvrkWu-uF7EPIkXJi3ONOdpoO27MxLoAfU3-kPoa78W4ESHJ3nvkwa3fNRneeYa4AYjmcvyDWaHkoNG-sMYsRXuhNTRGGSYlGnLZggsna8QXBic4sGk7JIlYIm-rBQU9CM4WrRQTrxx06WGC1NPiQkh7OUC1gQz02qrB8LDRjIbFY|regm\\\\\\",\\\\\\"waterfall_id\\\\\\":\\\\\\"d6031628-57e9-4414-93ad-9911cf738e0b\\\\\\",\\\\\\"INTERNAL__latency_qpl_instance_id\\\\\\":1.31847373200033E14,\\\\\\"flow_info\\\\\\":\\\\\\"{\\\\\\\\\\\\\\"flow_name\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"new_to_family_ig_default\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"flow_type\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"ntf\\\\\\\\\\\\\\"}\\\\\\",\\\\\\"is_platform_login\\\\\\":0,\\\\\\"INTERNAL__latency_qpl_marker_id\\\\\\":36707139,\\\\\\"reg_info\\\\\\":\\\\\\"{\\\\\\\\\\\\\\"first_name\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"last_name\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"full_name\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"contactpoint\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"e70375344\\\\\\\\\\\\\\\\u0040gmail.com\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"ar_contactpoint\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"contactpoint_type\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"email\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"is_using_unified_cp\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"unified_cp_screen_variant\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"control\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"is_cp_auto_confirmed\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"is_cp_auto_confirmable\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"is_cp_claimed\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"confirmation_code\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"HLhN6nli\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"birthday\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"22-01-1993\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"birthday_derived_from_age\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"age_range\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"o18\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"did_use_age\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"os_shared_age_range\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"gender\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"use_custom_gender\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"custom_gender\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"encrypted_password\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"#PWD_INSTAGRAM:4:1769035008:AZ5ExDXjM1ZLdM2rMGUAAVPBP\\\\\\\\\\\\\\\\/IsjHJHTphEA\\\\\\\\\\\\\\\\/Iam7dV4U+CpYwbFzkSnyJ5xrOgk0pnBnN5Qd8FN2qviVQTSHUAIkcg2J2Zc0xFq7\\\\\\\\\\\\\\\\/lE+e4pDSze1c9WOk8rW2YpfIskC7yxjUw3dEYE2BGqJeNLzNYNs435LEIE4ar8t7iTwTS2oWb2UkZ\\\\\\\\\\\\\\\\/nWma7wCS0GwR+\\\\\\\\\\\\\\\\/S5HZtpcSvM6ZUxBKwu75OmUM\\\\\\\\\\\\\\\\/3wrCnWSQ0ZcJpbdTmbvE+sE+Yh+\\\\\\\\\\\\\\\\/ROr\\\\\\\\\\\\\\\\/Unte8z5rn9nGKU5Jx8pi6I7wpH0YlZJPAIVi7qqk\\\\\\\\\\\\\\\\/N18aLUGIwYCY8xTO49ogv+nRCoOSIu72A\\\\\\\\\\\\\\\\/IXdAc+A\\\\\\\\\\\\\\\\/druvNvDluMsgyLJAyyeo4L+QW\\\\\\\\\\\\\\\\/OrY5HOVRkeflqunwyNZMkPTfDOWgGtgA0LCvnFrEso=\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"username\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"username_prefill\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"fb_conf_source\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"device_id\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"android-f35f126bc4795e76\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"ig4a_qe_device_id\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"c734a1c7-d663-4fad-af07-817b064e424b\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"family_device_id\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"dd5b9513-0be3-4263-9106-459e51268b46\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"user_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"safetynet_token\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"ZTcwMzc1MzQ0QGdtYWlsLmNvbXwxNzY5MDM0OTM5fBWut2xb6bRZ8ZphWFhqT9knoNB2hgkyHg==\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"skip_slow_rel_check\\\\\\\\\\\\\\":true,\\\\\\\\\\\\\\"safetynet_response\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"API_ERROR: class com.google.android.gms.common.api.ApiException:7: \\\\\\\\\\\\\\",\\\\\\\\\\\\\\"machine_id\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"h1NxaVnaYULGGzgpCn_hPfVP\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"profile_photo\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"profile_photo_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"profile_photo_upload_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"avatar\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"email_oauth_token_no_contact_perm\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"email_oauth_token\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"email_oauth_tokens\\\\\\\\\\\\\\":[],\\\\\\\\\\\\\\"sign_in_with_google_email\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"should_skip_two_step_conf\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"openid_tokens_for_testing\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"encrypted_msisdn\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"encrypted_msisdn_for_safetynet\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"cached_headers_safetynet_info\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"should_skip_headers_safetynet\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"headers_last_infra_flow_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"headers_last_infra_flow_id_safetynet\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"headers_flow_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"was_headers_prefill_available\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"sso_enabled\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"existing_accounts\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"used_ig_birthday\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"create_new_to_app_account\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"skip_session_info\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"ck_error\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"ck_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"ck_nonce\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"should_save_password\\\\\\\\\\\\\\":true,\\\\\\\\\\\\\\"fb_access_token\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"is_msplit_reg\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"is_spectra_reg\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"dema_account_consent_given\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"spectra_reg_token\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"spectra_reg_guardian_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"spectra_reg_guardian_logged_in_context\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"user_id_of_msplit_creator\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"msplit_creator_nonce\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"dma_data_combination_consent_given\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"xapp_accounts\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"fb_device_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"fb_machine_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"ig_device_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"ig_machine_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"should_skip_nta_upsell\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"big_blue_token\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"caa_reg_flow_source\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"login_home_native_integration_point\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"ig_authorization_token\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"full_sheet_flow\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"crypted_user_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"is_caa_perf_enabled\\\\\\\\\\\\\\":true,\\\\\\\\\\\\\\"is_preform\\\\\\\\\\\\\\":true,\\\\\\\\\\\\\\"should_show_rel_error\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"ignore_suma_check\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"dismissed_login_upsell_with_cna\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"ignore_existing_login\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"ignore_existing_login_from_suma\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"ignore_existing_login_after_errors\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"suggested_first_name\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"suggested_last_name\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"suggested_full_name\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"frl_authorization_token\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"post_form_errors\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"skip_step_without_errors\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"existing_account_exact_match_checked\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"existing_account_fuzzy_match_checked\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"email_oauth_exists\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"confirmation_code_send_error\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"is_too_young\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"source_account_type\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"whatsapp_installed_on_client\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"confirmation_medium\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"source_credentials_type\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"source_cuid\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"source_account_reg_info\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"soap_creation_source\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"source_account_type_to_reg_info\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"registration_flow_id\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"2bfd5926-c03f-48eb-8e17-a98ed947592c\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"should_skip_youth_tos\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"is_youth_regulation_flow_complete\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"is_on_cold_start\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"email_prefilled\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"cp_confirmed_by_auto_conf\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"in_sowa_experiment\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"youth_regulation_config\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"conf_allow_back_nav_after_change_cp\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"conf_bouncing_cliff_screen_type\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"conf_show_bouncing_cliff\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"eligible_to_flash_call_in_ig4a\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"eligible_to_mo_sms_in_ig4a\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"mo_sms_ent_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"flash_call_permissions_status\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"attestation_result\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"request_data_and_challenge_nonce_string\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"confirmed_cp_and_code\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"notification_callback_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"reg_suma_state\\\\\\\\\\\\\\":0,\\\\\\\\\\\\\\"is_msplit_neutral_choice\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"msg_previous_cp\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"ntp_import_source_info\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"youth_consent_decision_time\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"should_show_spi_before_conf\\\\\\\\\\\\\\":true,\\\\\\\\\\\\\\"google_oauth_account\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"is_reg_request_from_ig_suma\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"is_toa_reg\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"is_threads_public\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"spc_import_flow\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"caa_play_integrity_attestation_result\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"client_known_key_hash\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"flash_call_provider\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"spc_birthday_input\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"failed_birthday_year_count\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"user_presented_medium_source\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"user_opted_out_of_ntp\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"is_from_registration_reminder\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"show_youth_reg_in_ig_spc\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"fb_suma_is_high_confidence\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"screen_visited\\\\\\\\\\\\\\":[\\\\\\\\\\\\\\"CAA_REG_CONTACT_POINT_PHONE\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"CAA_REG_CONTACT_POINT_EMAIL\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"CAA_REG_CONFIRMATION_SCREEN\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"CAA_REG_PASSWORD\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"bloks.caa.reg.birthday\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"CAA_REG_IG_NAME_SCREEN\\\\\\\\\\\\\\"],\\\\\\\\\\\\\\"fb_email_login_upsell_skip_suma_post_tos\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"fb_suma_is_from_email_login_upsell\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"fb_suma_is_from_phone_login_upsell\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"should_prefill_cp_in_ar\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"ig_partially_created_account_user_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"ig_partially_created_account_nonce\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"ig_partially_created_account_nonce_expiry\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"force_sessionless_nux_experience\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"has_seen_suma_landing_page_pre_conf\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"has_seen_suma_candidate_page_pre_conf\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"suma_on_conf_threshold\\\\\\\\\\\\\\":-1,\\\\\\\\\\\\\\"move_suma_to_cp_variant\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"control\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"pp_to_nux_eligible\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"should_show_error_msg\\\\\\\\\\\\\\":true,\\\\\\\\\\\\\\"th_profile_photo_token\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"attempted_silent_auth_in_fb\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"attempted_silent_auth_in_ig\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"cp_suma_results_map\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"source_username\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"next_uri\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"should_use_next_uri\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"linking_entry_point\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"fb_encrypted_partial_new_account_properties\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"starter_pack_name\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"starter_pack_creator_user_ids\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"wa_data_bundle\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"bloks_controller_source\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"airwave_registration_code\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"is_sessionless_nux\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"login_contactpoint\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"login_contactpoint_type\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"is_nta_shortened\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"should_show_bday_after_name_suggestions\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"should_override_back_nav\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"ig_footer_variant\\\\\\\\\\\\\\":\\\\\\\\\\\\\\"control\\\\\\\\\\\\\\",\\\\\\\\\\\\\\"device_network_info\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"is_from_web_lite_reg_controller\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"login_form_siwg_email\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"account_setup_waterfall_id\\\\\\\\\\\\\\":null,\\\\\\\\\\\\\\"is_wanted_suma_user\\\\\\\\\\\\\\":false,\\\\\\\\\\\\\\"device_zero_balance_state\\\\\\\\\\\\\\":null}\\\\\\",\\\\\\"family_device_id\\\\\\":\\\\\\"dd5b9513-0be3-4263-9106-459e51268b46\\\\\\",\\\\\\"offline_experiment_group\\\\\\":\\\\\\"caa_iteration_v3_perf_ig_4\\\\\\",\\\\\\"access_flow_version\\\\\\":\\\\\\"pre_mt_behavior\\\\\\",\\\\\\"is_from_logged_in_switcher\\\\\\":0,\\\\\\"current_step\\\\\\":7,\\\\\\"qe_device_id\\\\\\":\\\\\\"c734a1c7-d663-4fad-af07-817b064e424b\\\\\\"}}\\"}","bloks_versioning_id":"b7737193b91c3a2f4050bdfc9d9ae0f578a93b4181fd43efe549daacba5c7db9","infra_params":{"device_id":"c734a1c7-d663-4fad-af07-817b064e424b"},"app_id":"com.bloks.www.bloks.caa.reg.name_ig_and_soap.async"},"bk_context":{"is_flipper_enabled":false,"theme_params":[],"debug_tooling_metadata_token":null}}',
}

response = requests.post(
    "https://b.i.instagram.com/graphql_www",
    headers=headers,
    data=data,
    verify=False,
)

write_response(response, os.path.dirname(__file__))

from src.flow import utils
from src import RegistrationData
import json


def get_name_body(data: RegistrationData) -> dict:
    reg_info = {
        "first_name": None,
        "last_name": None,
        "full_name": None,
        "contactpoint": data.email,
        "ar_contactpoint": None,
        "contactpoint_type": "email",
        "is_using_unified_cp": False,
        "unified_cp_screen_variant": "control",
        "is_cp_auto_confirmed": False,
        "is_cp_auto_confirmable": False,
        "is_cp_claimed": False,
        "confirmation_code": "HLhN6nli",
        "birthday": data.birth_date,
        "birthday_derived_from_age": None,
        "age_range": "o18",  ### check for this also
        "did_use_age": False,
        "os_shared_age_range": None,
        "gender": None,
        "use_custom_gender": False,
        "custom_gender": None,
        "encrypted_password": data.encrypted_password,
        "username": None,
        "username_prefill": None,
        "fb_conf_source": None,
        "device_id": data.android_id,
        "ig4a_qe_device_id": data.device_id,
        "family_device_id": data.family_device_id,
        "user_id": None,
        "safetynet_token": "ZTcwMzc1MzQ0QGdtYWlsLmNvbXwxNzY5MDM0OTM5fBWut2xb6bRZ8ZphWFhqT9knoNB2hgkyHg==",
        "skip_slow_rel_check": True,
        "safetynet_response": "API_ERROR: class com.google.android.gms.common.api.ApiException:7: ",
        "machine_id": "h1NxaVnaYULGGzgpCn_hPfVP",
        "profile_photo": None,
        "profile_photo_id": None,
        "profile_photo_upload_id": None,
        "avatar": None,
        "email_oauth_token_no_contact_perm": None,
        "email_oauth_token": None,
        "email_oauth_tokens": [],
        "sign_in_with_google_email": None,
        "should_skip_two_step_conf": None,
        "openid_tokens_for_testing": None,
        "encrypted_msisdn": None,
        "encrypted_msisdn_for_safetynet": None,
        "cached_headers_safetynet_info": None,
        "should_skip_headers_safetynet": None,
        "headers_last_infra_flow_id": None,
        "headers_last_infra_flow_id_safetynet": None,
        "headers_flow_id": None,
        "was_headers_prefill_available": None,
        "sso_enabled": None,
        "existing_accounts": None,
        "used_ig_birthday": None,
        "create_new_to_app_account": None,
        "skip_session_info": None,
        "ck_error": None,
        "ck_id": None,
        "ck_nonce": None,
        "should_save_password": True,
        "fb_access_token": None,
        "is_msplit_reg": None,
        "is_spectra_reg": None,
        "dema_account_consent_given": None,
        "spectra_reg_token": None,
        "spectra_reg_guardian_id": None,
        "spectra_reg_guardian_logged_in_context": None,
        "user_id_of_msplit_creator": None,
        "msplit_creator_nonce": None,
        "dma_data_combination_consent_given": None,
        "xapp_accounts": None,
        "fb_device_id": None,
        "fb_machine_id": None,
        "ig_device_id": None,
        "ig_machine_id": None,
        "should_skip_nta_upsell": None,
        "big_blue_token": None,
        "caa_reg_flow_source": "login_home_native_integration_point",
        "ig_authorization_token": None,
        "full_sheet_flow": False,
        "crypted_user_id": None,
        "is_caa_perf_enabled": True,
        "is_preform": True,
        "should_show_rel_error": False,
        "ignore_suma_check": False,
        "dismissed_login_upsell_with_cna": False,
        "ignore_existing_login": False,
        "ignore_existing_login_from_suma": False,
        "ignore_existing_login_after_errors": False,
        "suggested_first_name": None,
        "suggested_last_name": None,
        "suggested_full_name": None,
        "frl_authorization_token": None,
        "post_form_errors": None,
        "skip_step_without_errors": False,
        "existing_account_exact_match_checked": False,
        "existing_account_fuzzy_match_checked": False,
        "email_oauth_exists": False,
        "confirmation_code_send_error": None,
        "is_too_young": False,
        "source_account_type": None,
        "whatsapp_installed_on_client": False,
        "confirmation_medium": None,
        "source_credentials_type": None,
        "source_cuid": None,
        "source_account_reg_info": None,
        "soap_creation_source": None,
        "source_account_type_to_reg_info": None,
        "registration_flow_id": data.registration_flow_id,
        "should_skip_youth_tos": False,
        "is_youth_regulation_flow_complete": False,
        "is_on_cold_start": False,
        "email_prefilled": False,
        "cp_confirmed_by_auto_conf": False,
        "in_sowa_experiment": False,
        "youth_regulation_config": None,
        "conf_allow_back_nav_after_change_cp": None,
        "conf_bouncing_cliff_screen_type": None,
        "conf_show_bouncing_cliff": None,
        "eligible_to_flash_call_in_ig4a": False,
        "eligible_to_mo_sms_in_ig4a": False,
        "mo_sms_ent_id": None,
        "flash_call_permissions_status": None,
        "attestation_result": None,
        "request_data_and_challenge_nonce_string": None,
        "confirmed_cp_and_code": None,
        "notification_callback_id": None,
        "reg_suma_state": 0,
        "is_msplit_neutral_choice": False,
        "msg_previous_cp": None,
        "ntp_import_source_info": None,
        "youth_consent_decision_time": None,
        "should_show_spi_before_conf": True,
        "google_oauth_account": None,
        "is_reg_request_from_ig_suma": False,
        "is_toa_reg": False,
        "is_threads_public": False,
        "spc_import_flow": False,
        "caa_play_integrity_attestation_result": None,
        "client_known_key_hash": None,
        "flash_call_provider": None,
        "spc_birthday_input": False,
        "failed_birthday_year_count": None,
        "user_presented_medium_source": None,
        "user_opted_out_of_ntp": None,
        "is_from_registration_reminder": False,
        "show_youth_reg_in_ig_spc": False,
        "fb_suma_is_high_confidence": None,
        "screen_visited": [
            "CAA_REG_CONTACT_POINT_PHONE",
            "CAA_REG_CONTACT_POINT_EMAIL",
            "CAA_REG_CONFIRMATION_SCREEN",
            "CAA_REG_PASSWORD",
            "bloks.caa.reg.birthday",
            "CAA_REG_IG_NAME_SCREEN",
        ],
        "fb_email_login_upsell_skip_suma_post_tos": False,
        "fb_suma_is_from_email_login_upsell": False,
        "fb_suma_is_from_phone_login_upsell": False,
        "should_prefill_cp_in_ar": None,
        "ig_partially_created_account_user_id": None,
        "ig_partially_created_account_nonce": None,
        "ig_partially_created_account_nonce_expiry": None,
        "force_sessionless_nux_experience": False,
        "has_seen_suma_landing_page_pre_conf": False,
        "has_seen_suma_candidate_page_pre_conf": False,
        "suma_on_conf_threshold": -1,
        "move_suma_to_cp_variant": "control",
        "pp_to_nux_eligible": False,
        "should_show_error_msg": True,
        "th_profile_photo_token": None,
        "attempted_silent_auth_in_fb": False,
        "attempted_silent_auth_in_ig": False,
        "cp_suma_results_map": None,
        "source_username": None,
        "next_uri": None,
        "should_use_next_uri": None,
        "linking_entry_point": None,
        "fb_encrypted_partial_new_account_properties": None,
        "starter_pack_name": None,
        "starter_pack_creator_user_ids": None,
        "wa_data_bundle": None,
        "bloks_controller_source": None,
        "airwave_registration_code": None,
        "is_sessionless_nux": None,
        "login_contactpoint": None,
        "login_contactpoint_type": None,
        "is_nta_shortened": False,
        "should_show_bday_after_name_suggestions": None,
        "should_override_back_nav": False,
        "ig_footer_variant": "control",
        "device_network_info": None,
        "is_from_web_lite_reg_controller": None,
        "login_form_siwg_email": None,
        "account_setup_waterfall_id": None,
        "is_wanted_suma_user": False,
        "device_zero_balance_state": None,
    }
    variables = {
        "client_input_params": {
            "accounts_list": [],
            "aac": '{"aac_init_timestamp":'
            + utils.get_pigeon_raw_client_time().split(".")[0]
            + ',"aacjid":"'
            + data.aacjid
            + '"}',
            "lois_settings": {"lois_token": ""},
            "zero_balance_state": "",
            "network_bssid": None,
            "name": "Eugene",
        },
        "server_params": {
            "is_from_logged_out": 0,
            "layered_homepage_experiment_group": "ld_no_language_selector",
            "device_id": data.android_id,
            # check from birthday request
            "reg_context": "AVjkEY9lF0jTGN38_b5Qcnx_av7U0H_e9rUw9Du9AreI6CGmt25YpMosqErTHexqLnrSibtG70GxK49-LaBQk2LmpYNXIfVrra6MNCo70T7tEOZAAfS16-LhZikJNq1az3hIpcJNbL0gVYowTKT-sXJ7AHHglbZOYf3ESBCHNqrf8CK4FMp6_YISU4gHQqPMQ6r14d_h-bAQikBH3EGEXfcFIOxBvXDHFN1vFX1TgrHl2Isdk7CMxAiDEdIzeVv_IGrFuj9s37CY1zN_G0PdBjh5rX8hULfTNttu7l4awtcHwvnpXphwt_DEPfNJ3_rYswQuECP9j9y-tE4KHGtav0FYwVbe0GH_hCjJDbbNGM3NjibUSbV6pg_dlx6dZqfmMMM6oEVu-fRszxupOxJ-SVTCxO3ptC3CQmXdDUwy5J2eP7d1_qAbpB-R8_R1mdEHGjE1JZZHFYr9w9n_kQ_jhRBazGWLeLAwCFicRz97HrreaK95leTWB1FyUieMK2JUhtmpOP0VZaSQh-Tww7GGVhO-DFVwUCjdKPJUwTNOVs-WvlBeDaSsgHG9zsGlewRzuQlcIj1q9FwXVpTeGATGai5_Bbq-e2v3ltJiMHT6A2NsNUPFY7R0Fh8w9qsd4I7ebYKl2IItH1zCwmOso1YpvtYrsxLpux3zY4DwOZKZ6MY7NQz80XabfGITysprRkF0gyfsRjBnPQUGBksiXKfAZm1Og6znhOualco1lWkglzfPOipTWHPzHC0IemjAxejatprVsFoqOi0Rs83hXRhpUJjD38gqAwvnlu2C6o-4w6O18ZxCInlSPJp50-IAWBrkzmMvLTTwKPaBBqSnWEZMBgLYl-cagcl8DxRgv6AXGutV01G8zBBy2E6uNJeZfnsQ2hLLROarWZ5nScx14892G3aKUXfk3HJCxJV4is7nx65Tp4S8KxmChnGL96acsUel4TM-qg_x13ZLxe7rc2iGaWzsX7HAsOrAKBd5ppUeLV8b-_WUwo0k9EWMeLTLCNHsZc9DeOGmKjJ13GTfL9gfqI4G6QKN-ICZfeYkfp_c5TKvSdBuheCFp8rzI70zkgUrQ0nisZOLIieVUggK7xtcsDD5aevWgEYoqIKh0X7CbOqbtKpZldNXoDUbrkvvgtIFCTd7VXaKYNExwzQPOtjXvVOIGQX55-DFSgEvjL9bU2J0ZKfnvzKmGphtHURz6GvFSIDd6_t2O1LcWGm6BtXMT-aaZ2AdsO4uPUepTadxhDwEon-bzTiH_kxM0RlaA7H132e-vQO6WaQBKwqM5fpQHlqj5_YXj_jEwg43tP7_VDWQZNTJBnQ_mlIKc2MQiDVRvshhg4Zgh87BkW53JuRPK-ZNJI_gWOxleeam5AT8VnYzIo9SAeSQaHIsPzKB_wjp3meGyIBrPQeDPOG6zsbHy5-1ZHuBmi6uRGXMemJrFxgkhBqjwNtunVq9XORwomcSuAUnJ7eECJSxDXx-oiPbspUQetVUwi5V4pcsmUyWNo-CzC5IGCme85jEYbcTlaZiBC81460TT5LqholQIlUAJrBGMdhMzWbZ7U_8Buy58_l_APyrBtKiQ6foJO-rQLeqryxytBqNwDtGhKAtp7Pt3D40pR23_Z_9oKaxHkuy0xKvBFWjxyi4R8LTdQGgaoz-CMi_5-IdfpI-TF4CP1YvSkI_lFYjaVJ5PZB8Yg2ulfnJN5rjCdH_d_nB_l3OgR9Po8vSzWW5mhDke7jBUbsCSXuKLwrGLgVyumeOsoCbl1vUBguCFhWWgcVLt8LE1NrTSQcwL9Fq4b1gTc4zMfBxLhkzlx1yMM10Ij78fVp5S-nhWpUesWzwDv3zezz7aD_tDRFaEQb8iyC-LMzZ1oF2ODjSB0vf6-7HHvsHL8H9r-Der76RjnihJtSEXi-UsR5-QW2tyWhb39-_sCuevdDkF1BOqoMysliDzsiImNkXiUgHuWyxb_idqNPdOAv1uqn7hdc4eAlDZKgxhiwGQ5LsXGvF5e12Iw9NXXcNT45khxTPMlfDlFVXSS66xIAruQyCCE7wXKjPP2RwXWv68qWoU6RY2ga2fzt0gTCtFxueqZl5XrSmV5syIVwLV7DB-4zAuwtk-Vz5s_wKowBxab1NJ3utplS6ckVlDUyDcKC5OSdd50qgKilpjcH_Mx1ecPpEO1v0w_NkPKNaY0sP1Z-ztLE68C2Nm_JLACKcwi763b0YnHE9CIgZAp7gYZ5Y2AobBGBfXtAeCVYBG_KL_o-zWVvWEuSz8DScOxVO79D15FzEdZb4Ercl3RWR77WU2pVMPgiC8q4lhiJoRvFhMS_PAvJ69dS3qqiPVZ0btIXiMU8myOYPx6Ni9ZcZXOmErudL6zNTMH8Re714_Qtyvu3SLNCggHGG-GFNKgCJBfKgURuFVtCCcTJsrKQqw83oOg8_bpMrGSXoUmFVFLoFk4BHYW8IT_I5jA6RkqdPU5UxpM7yfo3tFTjG3nrfAf3eyPLgexNmxQz7uNDb6zJGVzPSo0FS8YegGSbUuqrZrGxUoxTMjJ404m_2kE7vav72lPUAoYpUARZcOUUf_wIbaQ6Zuf954w2lyGMHAP5eqyYd5sEN5aMoveUhGl4l-AsVsu5L64TpsGS1xGVpnOd0_d7mFZl_3LEW1xsVoSkQ0LZM7HN4Z1-OL6cJ0xBt5ybQ-bzM1iqCkkwe3kpILH_NT2JW5nsnQSWGBlmrZrMpcaVs956WE9bHinhGSvuTjOQlV1ksm4WhI8XTNXHEx8wzhxe3t3KYEQndm53vxdNzTj3as7hfZkbmjybmOGIbeMa75RukkfcDvQIt_8SFzwXi9mQH6RCUcGVzk-f1fM-oYu_Y4ajN0TYFRp6cltI5jRVQVrB9-ES5MYItu_0LAr0B0Yyo7vjjkntzWGpydCbGH8XS_txbWM5Z8G27XT2f7G3MF4vJG2aV0WzrfBka1tAV7tbeKVnvk9FJob7TsWuXmzlVYHX2WARDnOQ8E2IvJe86BWJkyBj1UiFOegX8-4ukZdx4ucQanL0ln381r-GIhspqLQjuLp5IWNvCOvLpjoy_JptwLEGvTG4F3biMsJVSNXIJA3KcuZHvAnHlUWRmN_Qpa0_UGz0u3Mx_5AmRkja_eA0Im9Cddufb1vPQGz6vFWE6IAGJzCi3BdPIHuUMTcAgt7hHq4gSYUna-caC-NRe6AtAUFwLtgni7Xp8ZgD_gSGpjus9g9T3oL-WP2zGVTmrolLqHJrWZegBc3IzYkpsG9EjXfIRxQFTg91imivOEiG9BqB6CzOP-ZSvk997SXtxZB6-cWJ2vZhtBIT1tyScrqd4u8MssryPLgueZMex0H6EKfArAjCMTkyy0oQegJpBR_28TagT3PCLEUxYjQXuu7H49vYvw-OiMWPcHknSdfbzCAXSAq21_hgqxqH_R13TxIQhBKDloU9EThOmlh1vU4ww-kE-oh-pKT_kHDzKeADtDw0bUSlEAESaRJ68qpC-xlPmROwwRJlVq439zUDL4gGP7otbdSd5RRicp4rnRXwjzMIf7WG9ajEszXdLODcxChNy14uO7fiCfpH5IfjcCgILmD6nEzcp-JTIb39IeEmhVnNbolVKFQ3jRY0a0CKrjGsd0oKG1ynsPVb8FUSMDfy36gfSAQzLoKIEXbvce-V6InTg-h9MHX2y3OhIf5i8IfnjzFrOJaZ6UzM0Rdgce7QJ4rKiyid5QbVQQBxQiR2DQz85EVbkFAffqm0gBHLkQnSX403NMgg_zogMHvrIbnPOcDr71qGu0KtiuSvuk0dU1fR56WEQKpL_2Td4_X6hoL3nwa4JEAtXIhIdjRTIfaXXpkBcqZ_Po3MIfAM5_IBqZq6dpe6yTb0-pmCxlBR9w98BKK81zr1gPoX2h02rb8eqlqmfffjAnW7moGc1pA4xtTlv7SJPHNcRYyshjwuQifFKSENSk_fOJpQrD2gG5BihhIHnrboktLSyhUsj3NjL8PMQPbQpT4je7gO2xmriJpeFv99mtiOKtwJd8ooq4AflTQd6BVlWPAnXHqRDwBLWRpbTgh6rcgj4RbN5z5Zu4zhEz8X2RPmSpgThZ7TXj8Ndf6E8ZzE6WhtuhuP5Vby9ihERkJbxCXyOLZZMKPmLxyITVeuz3WDP6JEGPht5ptMHwHsANhKICCYbn9dvNwngpOhwn4VnfMt5-1xhmy2GqqxoXBHm6QofIHwbuGed0W4FdtkeXQL4P14wSH1CKSLoxHFU-Xhhbmi1Ir9m71R1sfwLw-qsiHOgW2RUjPi5FBdVprXiLOaEopj1DnI_pk5U8_8Q0hTcUOq7-Gx-kdbd8cjzovP9jz5_HQ632-clKXHHmStWW0jIMCYCOEE1RZt_qz4X1DCc3MYnCdLys0wkHsFHBDs4Ief-cS5TwVpITbNbqs-X_R3ewVAz5hSO9GLDTymG1jI8OJqAluF1dht6aWGWcomFkI0mVFQAv1cN-3Sli7n7RY7YkwELwrnMDompuTlqYAEMFO44lu1oJ4uX5EPf973KzFyv9YwlMiBQ41TkPa-U-ZE3EQqI4klYOzNCoTEXHEmw4DTMuvBTh8b3UlJdCZ0LuuYP2Mk7TuHHfFshOyi-ZnA_VBoS3ylZ-UK41JkXt_lEiVXOYCk6J5IOwcR4_0ySKoz-SDIf3MVMpI2RDK6hyw3EO4MmVdPUfV833nOD82XtQnHMkFyHgJ5UrtK8DCmqMfgXzbHJtHMb2dQ-VugAoL84cr3-dvKfm74NF8tlWtCVaNCPdQGeVtExb8Mw_pRprTaCOM-OxqRRP3M90FIC60WHjMBcSvlmkeS-tda8mlVzDOAan_vk4FAEaz3XYTeaU9sdaEm--1j2q-7zsvm14cZmz2mSK3rTiLli0j0ASYBWmO0U3rsNqZImHttZq3k1Q4tq58MaqxNIYeE9H3a-LOoXZ7KHdJmUgFZ7Z6gYZrvwLXHrMomRG--J3tuayYqW5hWxdcFIUdPfqA4NinhjhOcHJEWUzh6duD-HZDbulITNz7Xi5RVcp08VQ241hkosDBXCWFd4XEGi0kFkS4opK2SSy55RoA9jnYFFJchKiRPHp4hmCN8m9kcbG0IE3j-qLUv9LaNQD6IGY6T18IJYap_Ez_UArNUevH1AA-lP4YNkbAhZkYYdK2ZJn3ykpBp7-4o67EzI2-7G7-H9NfXWcW1H6ae6he2SkXY8Y1A0lCC6FdVw-6IBes3xaGAlh16CFLuZ5RBoai03B66kraxjiy8vCp_4HJIFER8oR03rLZH3U-i806bzv5hALizXCRQTamimMSdJxtp3gHYB3g0hGpzKUwBl-__Qfx2A7G-E0MzPaA9pOA1nx_VMU4rM3ShqMuwz3pE3Qkgkfs52t9b8f-FGlgUKNxSFpMU8cq3vtmCs22TbNspsajUFkjWfJvUoC1WFxTahFno_LqSibiJ6FQVLCqx7Ax5hAfUJYVcVmZL4FHVe1PMRYYwtRVpe0HMDJW3u3PBh_YM8qJyOwUvrc2_aPp9_w1HFAnZs3B1P96IeWaoco7DX6WLWgYihpbEYCaFg_QKPxY7PVyzCRNzylZPY2YrzQZ6cxGKfMYIkYiGR7jTI_IjUTAqreSm5abofv4jgCqwCs6HBvCB73ZUx4zPCzUqh6ldbmbOuaxYla7rDn1B8jFNYmXoXAA4T9QVItJJKYmNFagMo8McTtfTfKCudRn_n0SdYD0kGOVv6CibSZL646CjKPrmOQPELErqmiHfZuLH8z58SZNDEVxXJPpCnIykagB52TTZmXmXIDPrq4aNsQ-6EWk4H4K89q8j97iiZg9c6Y9xNOl328QNe6RWOSRgODG-6zOF_9BNAq8hAG3QBSDG_hRLwj0bZ_wre1LiVZ9KySeNF90KA7EZS0Tvv-iO43h-mTTEVkIFQGxRObiP7_8yUjO55brF9zVZPBBQU8C8oDIWkFbwP1lUljfiDGKy49JBNQ4rT6W9OrzxnJisshDc_F6rOea3Y4YljjHJASrWvmrY0onK597vAq03HknRKuZwP6If1uPUKNs77PnasQlSOmpMf7hHV1vFPks_5LvE3HGzWVABM6BxXgj5cmlsDSpuNqyuAplrCbpThcmGf-p3sSSHkQs336tGWfbjjcTm5DbqWaGYtYS_mA8i1xfB_BIOTh1tVYm6c1qbbBQgXfwtz9A2nxxXgRCFNjj3fFMRb99a0Tov37JIIELkIsgn5jb0vtAwdQP6RXhJQ84a8iVQw_3DVZBWOTGy-8uhE3lHbGFrpUaiiMdvscIqI5W2dgM9KfftnGDLqCiRIORKsJFnzGIxRh_pEfCejuBfahNBJyCaSoz61t-pe7cmdbSB6D4dCCbCgLH5GYt-gwLC7IeMksJWh2VsIaT91AMuBV3Iew9ehGB_c6H_Tia_1YcU7Gfy497Z5KTeQykpbkagvyi-5HLEuRyC2nZFjQ4B149SHKFFgRkw_ZTAmQvQ_tnlKhj6P038UMGBOrttTny7RKtd-gh_7zmEbA18r6VYWMDw1mCi0OIZ_GW8nrQby7IqKSatWkXGxeFsNB6d5xM_EtR0KED2s4ImeEQtAI2uguImd-NyDygg7lHsqANECtH8WuHO4IqEPFV_Rr--swGNdkKZYq_AXPg_I47mRr9kBd-c2tY43JmTT9nlrrZBBHIGQg7FipPnPBMAwp4iKLNFtTE0nnd4p55aSunZljXlF2dS3TDZflXbf03XEP5lubhE8LT3QhXgn8-m3ooEUlozpXTfF65Ky7dAF_rpgfI1LzcXWz0XEffZV_-iFQk6WTfgSrnreCHm7YX-n2IyOhmAYTHYRTLS15Ml13CKkalfj6c326BY7thdlGeasx6UNwI8VkWpzMHPJFwmaUBPD6KegEwJT1vTHnI4JUkftCNEjaY123xl_1ja3PaEm57pMvdR_3JyCQj6m_Ym17FFO3-IAIpZ0MTU1HUCGw8qHPfk9jL4SnnFY3a7zYFeXIoXzO4sGrO_YfAEhCmsiu8OYJ-vhogPu-KOg7GnQNgH2FLOJIiVf7FJqWYTdxQop1J1d3dI18egjTXMuVXOR7tV39n1vTOHwnMQXq_AGBsV1CrFM8PvNLMZzZvHa2KrmJqIj0I1q8zmkqXtaUHahQqUW0B1S1EQhiB9t2iZIlNM-8B4GbXIn6chXbYKY-jNPFvLKRKhpnXFLWyDjkxxWc-z7R-ToiPVGGhYTkdMGmIfG6rfteJOhnRtSJ9a92pzCwlhXNDGNOi-aKsXhhjfFzdfb7LOjKYNSqIQN_BoRscrXGmsMrZp6drUnfGkTksuEUJyBgRx5T5RdQEfQS1p4X7DTD01H1fDP9IxptVo6HJLzntADAJ-LQRmG1DO4lX1-l6zZCPW7Io6XYnh4p_n6TRCLzgT_XUkEKmsctA7jD1KFPSajAVXAOpvZ-OyzSm3RyxTkAyV4uR3p0QWUObFQAxkQIYprgkOq8RnAJ4aLqVZIzIagH3kcEeiDzKUgewbDp7y2yXa6YGgVS2PkqOfYTkitqB0JzmsLhqnMr-w51YbuhehcAL82RS0n9tulqpo7Rew4XMA5c6quQ9EinFeFek_AVO1htKwbBFP6VZHBfRtm4_SGBYZqjHVocbxfnQT3SfYBzn0yrkdTvgID4QRZG78_jC_Du1PwQRj4iI5SnUFKspIp-oWggzpHWRFvinTE2wVlXenlHT-mBJbc7FDRqWs6PsQb6JZOeDGnma6Rlv5xLOTSNqkC-3w-RgrzOmFJOIbTYYEqGpPDoTE4zrNCu3Z1_3dPRp88y1Qh9wT1b2nc_5hG6mSnWFX7w7hE5Y0f3dJn8HXXXoVHCF9HsokLpDY5a3c0Af9eXbJQewhzlLesIZ8qo_CLL9Us8HMn3iD8kND_WgNV3Ph08H97a4LMX2DuDXxC2ZTDCVIvJRG8QinxJWTyfjXkGCQY5qspTWB3mdp7PgTsqRungOlmcmhlLjEUTeA9we4s43uC32nIG0eB6SmEt4SG9z0yJ6XAZngdZ2WncoE0we-PSD0shbHFAW7Wg_lbEgie1rfugIRHnjMHNW1UnADpWrvQ4mjxtv5RonT-ZDZ6Lr_gXOWMq9Pd22z_Pf2lOlOfEmsnK_CercmGqJMwKNe6fyEbkmCeI5oL_oXzH_-uf2AF4UJZk242oMmWUoycaeltHu7CIsDw5u4jh7xl1tBogploqKQKxaxk0zrFcCN9mvMGJTEYbnaJhXDb2ZdaahgwmCnb_IqNgZSmu9sjoOrO7iq3cZdgtal9PhFHXR6YgmBpbuwBHp7mu8u3N2XXWUG_dRRSKZjbEuSUYFXIcEwiXEJOqWJWCg-z4Tyvo1Nu3hR3Dbo8XnUkO2wy_AmaZJR1fNNHw7owq1PYoD7SXmhomTtkQcf2ue4WZ3GuUxOJwwDCR77lsqe62GnHd4PbdnLMbEeoKXnRZuFtweBWS_n4CRbHNtvjgo5vO_5-c5m8qDCK18dLrdUrHqZO429eOuH0-WTV5eS5w6pTYjChbSRhVOVJAU1b2EMZ43-aHT5-UTnf33JLfK-PVW9Xy3gSB5RydgQAK0TEWdKQsBUWKV-GX7Yu81FXgNGQLgSZXT-0zVOdFm1x95MxTYZP6PxBkHHthgeBmCjI-mTNfGUd9-TUZamtrnzV20GiXFLRRQsJIx4_W5QctW2gThxdYAV9okAk11NCmN144Z5SNaNlY4SAQLIwGUQx0e9KP6oQ5_Pix-GSbipC4vgyTt7V_qsroP9G5nqjGskNKsr8En61F_eGiXGxEp8DPb4YYpyKnN_DjTWt9CwON_oz9n3VzH7nShQmYbsl6tcXHdPIie_qpbCSS52QK3wXBHz28UBgv3xY67zKutfstVbtkXlfFlcSE6MJXa3yqvui5Ixzf6Qj3xgBgoLrjoXlgR2Dv_yfmY2_KgT62j4oOsbmIF1V_x7N82NsUzCqQDBYyRARUK4KGwZ1_6KcwQEH2kIaHXouD6sqbecotjzMWK6f9HiVd1Z-UIO15G6UYbWMQ6NRc-prNlqOIZYXXNFIa4Ake9ixxExUklB_loVbJdZkUnK-Gg9dqIsQIcJ0NJzqpCSTufoc-8laNpso5hPkBKQvda9LxiBDr4JUG-poKCzigGuFE_I8IZYKqkZ-a0ltGe5UbIvq6OfJNnqKKTvuEpoWIzDgqmNV83IudqntqMFWAtjfN0uMqa36GadZ2BuTKgeTkoCPUqjLX7Ob4-kvb95K9qENCxKGab2kbaqlJRjt0_CRU63EiVJBUpueM60VCGPBeXJeHox38cFGAI0QnV5zBO0_2iZyFbDk9zCNxFNmyN4o2n9nGJymxUzgYipuUkpwT1ESKRvQIfk7iPH-azkgqRBvAR2jT-fS1KGYwLQ_NjwhhtiIhsnUk2nz3afDDH-0yZgh1PRoaEbcPQ0Bo-OAkeIVIRglLKVQYU4hZrWFAyXYWZZlaPiwI97r_J6o2mFI8HtpmX4Rt0aZkKjgIQ8qvOCViKwAk2-rbqb6QIrh7lusVUMQWYQbu0iwraNjjM4vaF1LuQ6ShmRelp3AYEtokLJ0DMgP6SfDY8SlGH1m0wZ00RZhK1WdmMwoM5wvrkWu-uF7EPIkXJi3ONOdpoO27MxLoAfU3-kPoa78W4ESHJ3nvkwa3fNRneeYa4AYjmcvyDWaHkoNG-sMYsRXuhNTRGGSYlGnLZggsna8QXBic4sGk7JIlYIm-rBQU9CM4WrRQTrxx06WGC1NPiQkh7OUC1gQz02qrB8LDRjIbFY|regm",
            "waterfall_id": data.waterfall_id,
            "INTERNAL__latency_qpl_instance_id": 131847373200033.0,  # check from birthday request
            "flow_info": '{"flow_name":"new_to_family_ig_default","flow_type":"ntf"}',
            "is_platform_login": 0,
            "INTERNAL__latency_qpl_marker_id": 36707139,  # check from birthday request
            "reg_info": json.dumps(reg_info),
            "family_device_id": data.family_device_id,
            "offline_experiment_group": "caa_iteration_v3_perf_ig_4",
            "access_flow_version": "pre_mt_behavior",
            "is_from_logged_in_switcher": 0,
            "current_step": 7,
            "qe_device_id": data.device_id,
        },
    }

    return {
        "method": "post",
        "pretty": "false",
        "format": "json",
        "server_timestamps": "true",
        "locale": "user",
        "purpose": "fetch",
        "fb_api_req_friendly_name": "IGBloksAppRootQuery-com.bloks.www.bloks.caa.reg.name_ig_and_soap.async",
        "client_doc_id": "356548512614739681018024088968",
        "enable_canonical_naming": "true",
        "enable_canonical_variable_overrides": "true",
        "enable_canonical_naming_ambiguous_type_prefixing": "true",
        "variables": json.dumps(
            {
                "params": {
                    "params": json.dumps({"params": json.dumps(variables)})
                }
            }
        ),
    }


def get_name_headers(data: RegistrationData) -> dict:
    return {
        "Host": "b.i.instagram.com",
        "Accept-Language": "en-US",
        # 'Content-Length': '30216',
        "Content-Type": "application/x-www-form-urlencoded",
        "Priority": "u=3, i",
        "User-Agent": data.user_agent,
        "X-Bloks-Version-Id": data.bloks_version,
        "X-Client-Doc-Id": "356548512614739681018024088968",
        "X-Fb-Client-Ip": "True",
        "X-Fb-Friendly-Name": "IGBloksAppRootQuery-com.bloks.www.bloks.caa.reg.name_ig_and_soap.async",
        "X-Fb-Request-Analytics-Tags": '{"network_tags":{"product":"'
        + data.app_id
        + '","request_category":"graphql","purpose":"fetch","retry_attempt":"0"}}',
        "X-Fb-Server-Cluster": "True",
        "X-Ig-Android-Id": data.android_id,
        "X-Ig-App-Id": data.app_id,
        "X-Ig-Capabilities": "3brTv10=",
        "X-Ig-Device-Id": data.device_id,
        "X-Ig-Is-Foldable": "true",
        "X-Ig-Timezone-Offset": "7200",
        "X-Ig-Validate-Null-In-Legacy-Dict": "true",
        "X-Root-Field-Name": "bloks_action",
        "X-Tigon-Is-Retry": "False",
        "X-Zero-Eh": "IG0e09d776530888418ab70f3822fbb4e1",
        # 'Accept-Encoding': 'gzip, deflate, br',
        "X-Fb-Conn-Uuid-Client": "95b2bb513e6c590b7147b9e4bcf849d8",
        "X-Fb-Http-Engine": "Tigon/MNS/TCP",
        "X-Graphql-Client-Library": "pando",
        "X-Graphql-Request-Purpose": "fetch",
    }
